// 2026-10-04 연결된 이야기 속 회화 미션 — 순수 데이터(import/DOM 없음).
// 하나의 이야기(영국 학교로 전학 온 "나"가 Jamie·Mia·Paul 선생님·Cookie와 방과 후 축제를 준비)를
// 10화 × 새 목표 표현 10개 = 100개로 나눈다. 1~10화 전부 채웠다(전체 개요는 별도 개요 문서).
// 7화의 가수는 실존 인물이 아닌 "우리가 좋아하는 가수" — 보내지 않는 가상 초대장 연습이며 답하거나 등장하지 않는다.
// 시간표: 1화 9일 월요일 → 2화 화 → 3화 수(축제 공지: 다음 주 금요일 20일 3시 반, 운동장) → 4화 목
// → 5화 금 방과 후 → 6화 둘째 주 월 → 7화 수 → 8화 목(장소를 강당으로) → 9·10화 20일 금요일.
//
// 스키마
// - STORY_EPISODES: { n, id: 'epNN', titleKo, summaryKo, nextHookKo, keySentence? }
//     keySentence(선택, 현재 2화만): { itemId, en, ko, goalKo, watch:{situationKo}, introIds:[회상 전 짧은 대화 문항 id], recall:{situationKo,roleKo,partner}, transfer:{situationKo,roleKo,partner,reply} }
//     — 기억할 한 문장 흐름 전용. transfer는 STORY_ITEMS에 넣지 않는다
// - STORY_ITEMS: { id: 'sEE-OO', episode, order, situationKo, roleKo, en, ko,
//     reply: { speaker: 'Jamie'|'Mia'|'Paul'|'Cookie'|'Shopkeeper'|'Guest', en, ko }
//       (Cookie는 'Woof!' 같은 소리·행동으로만 답한다. Shopkeeper=가게 주인, Guest=축제 손님),
//     alternatives(교사용 허용 표현, 학생 화면 비표시),
//     level(1=3~5단어, 2=6~8단어, 3=9단어 이상 또는 두 절), func, kind: 'new'|'review',
//     reviewOf(review면 기존 표현 id 또는 sEE-OO, new면 null), reuseIn(이 표현을 다시 쓰는 뒤 문항 id) }
// - 배열 순서 = 이야기 순서. order 1~10은 새 표현(kind 'new'), 11·12는 복습(kind 'review')이며
//   복습은 이야기 흐름상 해당 화 중간(바로 앞 문항 뒤)에 끼워 둔다.
//
// 세는 규칙: 100개 목표 = kind 'new'만 센다. 대소문자 무시·문장부호 제거 후 en이 전 문항에서 유일해야 하고,
// 기존 SITUATION_EXPRESSIONS 5개 문장을 새 표현으로 쓰지 않는다(복습으로만 재사용).
//
// situationKo/roleKo 규칙(정적 검사 예정): 각 60자 이하, 영어 글자 0, 자기 목표의 한국어 뜻이나 답을
// 알려 주는 어간(인사·안녕·반가·미안·사과·고마·감사·도와·도움·부탁·다시 말해 등) 금지.
// 무엇을 말하라가 아니라 무슨 일이 있었고 무엇을 이루고 싶은지만 쓴다.

export const STORY_EPISODES = [
  {
    n: 1,
    id: 'ep01',
    titleKo: '첫날의 빈자리',
    summaryKo: '9일 월요일, 영국 학교로 전학 온 첫날이에요. 폴 선생님과 반 친구들을 만나고 제이미 옆 빈자리에 앉아요. 앞자리 미아는 목소리가 아주 작아요.',
    nextHookKo: '내일 첫 시간은 미술이에요. 준비물을 묻자 제이미가 연필을 꼭 챙기라고 해요. 그런데 정작 제이미는…?',
  },
  {
    n: 2,
    id: 'ep02',
    titleKo: '숟가락이 든 필통',
    summaryKo: '미술 시간, 제이미의 필통에서 연필 대신 숟가락이 나와요. 칠판에는 처음 보는 단어가 적혀 있고, 점심시간에는 제이미의 도시락 통에서 수상한 소리가 나요.',
    nextHookKo: '하교 전, 교실 문에 종이로 가린 포스터가 붙었어요. 내일 큰 소식이 있대요.',
    // 오늘 기억할 한 문장(QA 전용 KeySentenceFlow). 이 흐름은 Paul(나)과 미아 두 사람만 나오는 시범 장면이다(212차 이후 운영자 정정 —
    // 오른쪽 상대는 승인된 여성 캐릭터 = 미아로 통일, 제이미 없음). watch/recall/transfer 텍스트는 공개 전 화면에 보이므로 영어·"빌려/빌리"·답 어간 금지
    keySentence: {
      itemId: 's02-03',
      en: 'Can I borrow a pencil?', ko: '연필 좀 빌려도 돼?',
      goalKo: '연필을 빌리는 말',
      watch: { situationKo: '미술 시간, 내 필통을 열었더니 연필 대신 숟가락이 나왔어요! 앞자리 미아는 연필이 많아요.' },
      introIds: ['s02-11'],
      recall: {
        situationKo: '그림을 그리다 연필심이 뚝 부러졌어요. 미아 필통에는 아직 연필이 여러 자루 있어요.',
        roleKo: '미아에게 연필 하나를 더 써도 되는지 물어봐요.',
        partner: 'Mia',
      },
      transfer: {
        situationKo: '다음 날 아침, 이번엔 필통을 통째로 집에 두고 왔어요. 옆자리에 미아가 있어요.',
        roleKo: '미아에게 연필 하나를 써도 되는지 물어봐요.',
        partner: 'Mia',
        reply: { speaker: 'Mia', en: 'Of course! Take this one.', ko: '물론이지! 이거 써.' },
      },
    },
  },
  {
    n: 3,
    id: 'ep03',
    titleKo: '축제 팀을 만들자',
    summaryKo: '포스터가 공개됐어요. 다음 주 금요일(20일) 3시 반, 운동장에서 학교 축제가 열려요. 셋이 한 팀이 되어 공연과 간식 가게를 정하고 역할을 나눠요.',
    nextHookKo: '리더가 된 미아가 내일 방과 후 음악실에서 첫 연습을 하자고 해요. 그런데 셋 다 춤은 처음이에요.',
  },
  {
    n: 4,
    id: 'ep04',
    titleKo: '첫 연습은 엉망진창',
    summaryKo: '음악실 첫 연습. 왼쪽 오른쪽이 뒤죽박죽이고 제이미는 커튼 속으로 돌아 들어가요. 천천히 다시 맞추고 서로 칭찬하며 차례로 곡을 골라요.',
    nextHookKo: '폴 선생님이 20파운드를 주며, 내일 방과 후 셋이 학교 앞 가게에 다녀와도 된다고 허락해요.',
  },
  {
    n: 5,
    id: 'ep05',
    titleKo: '필요한 것을 사러 가자',
    summaryKo: '금요일 방과 후, 셋이 학교 앞 가게에서 20파운드로 공연용 리본과 간식 재료를 골라요. 비싼 건 내려놓고 개수를 맞춰요.',
    nextHookKo: '미아가 주말 동안 봉지를 맡았다가 월요일 아침 교실 탁자에 올려 두기로 해요. 폴 선생님은 다음 주에 특별한 친구를 데려온대요.',
  },
  {
    n: 6,
    id: 'ep06',
    titleKo: 'Cookie가 가져간 것',
    summaryKo: '월요일 아침, 봉지 속 금색 리본이 하나 모자라요. 폴 선생님의 강아지 쿠키가 물고 달아났어요. 리본을 되찾다가 팝콘까지 쏟고 말아요.',
    nextHookKo: '수요일, 교실 라디오에서 우리가 좋아하는 가수의 노래가 흘러나와요. 미아가 눈을 반짝이며 상상을 시작해요.',
  },
  {
    n: 7,
    id: 'ep07',
    titleKo: '우리가 좋아하는 가수에게',
    summaryKo: '진짜로 보내지는 않는 가상의 초대장 쓰기 연습이에요. 우리가 좋아하는 가수에게 소개, 초대, 날짜, 시간, 장소를 차례로 적어요.',
    nextHookKo: '초대장은 교실 벽에만 붙였어요. 다음 날(목요일) 아침, 제이미의 목소리가 이상하고 날씨 예보에는 금요일 비 표시가 떠요.',
  },
  {
    n: 8,
    id: 'ep08',
    titleKo: '축제 전날의 문제',
    summaryKo: '축제 전날, 제이미는 목이 아파 노래를 못 하고 금요일에는 비가 온대요. 역할을 바꾸고 장소를 강당으로 옮겨요.',
    nextHookKo: '금요일 오후 3시 반, 밖에는 비가 내리고 강당 문이 열려요. 첫 손님이 들어와요.',
  },
  {
    n: 9,
    id: 'ep09',
    titleKo: '드디어 축제 시작',
    summaryKo: '강당에서 축제가 시작됐어요. 손님을 맞고, 주문을 받고, 간식을 건네고, 길을 안내해요. 그런데 과자가 다 떨어졌다는 말에 쿠키가 짖어요.',
    nextHookKo: '무대 뒤에서 미아와 금색 리본을 묶었어요. 남은 리본 하나는 쿠키 목에 달아 줬죠. 음악이 시작되고…',
  },
  {
    n: 10,
    id: 'ep10',
    titleKo: '완벽하지 않아도 성공',
    summaryKo: '공연 도중 음악이 멈춰요. 떨리지만 내가 노래를 이어 부르고 미아와 내가 끝까지 춰요. 강당을 정리하며 서로의 마음과 다음 약속을 나눠요.',
    nextHookKo: '이야기 끝 — 목에 금색 리본을 단 쿠키가 꼬리를 흔들어요.',
  },
]

export const STORY_ITEMS = [
  // ── 1화 첫날의 빈자리 ──
  {
    id: 's01-01', episode: 1, order: 1,
    situationKo: '전학 온 첫날 아침, 교실 문을 열자 칠판 앞의 폴 선생님이 고개를 들었어요.',
    roleKo: '처음 보는 선생님께 먼저 말을 걸고 내가 누구인지 알려요.',
    en: "Good morning! I'm the new student.", ko: '안녕하세요! 저는 새로 온 학생이에요.',
    reply: { speaker: 'Paul', en: 'Ah, welcome! Come in.', ko: '아, 어서 와! 들어오렴.' },
    alternatives: ["Hello! I'm new here.", 'Good morning, Mr Paul.', "Hi! I'm the new student."],
    level: 2, func: 'greeting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's01-02', episode: 1, order: 2,
    situationKo: '선생님이 친구들 앞에 나를 세웠어요. 친구들은 내 고향이 어디인지 궁금해해요.',
    roleKo: '전학생으로서 반 친구들에게 내 고향 나라를 알려요.',
    en: "I'm from Korea.", ko: '저는 한국에서 왔어요.',
    reply: { speaker: 'Paul', en: 'Korea? Wonderful! Welcome to 7B.', ko: '한국? 멋지구나! 7B반에 온 걸 환영해.' },
    alternatives: ['I come from Korea.', "I'm from South Korea.", "I'm Korean."],
    level: 1, func: 'introducing', kind: 'new', reviewOf: null, reuseIn: ['s07-11'],
  },
  {
    id: 's01-03', episode: 1, order: 3,
    situationKo: '선생님이 영국에는 언제 왔는지 물었어요. 짐을 푼 지 겨우 일주일 됐어요.',
    roleKo: '영국 생활을 시작한 지 얼마 안 됐다는 걸 선생님께 알려요.',
    en: 'I just moved here last week.', ko: '지난주에 막 이사 왔어요.',
    reply: { speaker: 'Paul', en: 'Lovely. I hope you like it here.', ko: '좋구나. 여기가 마음에 들면 좋겠다.' },
    alternatives: ['I moved here last week.', 'I came here last week.', 'I arrived last week.', 'I came to the UK last week.', "I've only been here a week."],
    level: 2, func: 'introducing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's01-04', episode: 1, order: 4,
    situationKo: '교실을 둘러보니 제이미 옆 의자에만 아무도 없어요. 주인이 있는지 모르겠어요.',
    roleKo: '그 의자에 앉을 사람이 있는지 제이미에게 확인해요.',
    en: 'Is this seat free?', ko: '이 자리 비어 있어?',
    reply: { speaker: 'Jamie', en: 'Yes! Sit here.', ko: '응! 여기 앉아.' },
    alternatives: ['Is anyone sitting here?', 'Can I sit here?', 'Is this seat taken?'],
    level: 1, func: 'seat', kind: 'new', reviewOf: null, reuseIn: ['s09-12'],
  },
  {
    id: 's01-05', episode: 1, order: 5,
    situationKo: '앉으려는데 의자 등받이에 파란 옷이 걸려 있어요. 제이미 것 같아요.',
    roleKo: '의자 위 옷의 주인이 제이미인지 확인해요.',
    en: 'Is this your coat?', ko: '이거 네 코트야?',
    reply: { speaker: 'Jamie', en: "Oops! Yes, it's mine.", ko: '앗! 응, 내 거야.' },
    alternatives: ['Is this coat yours?', 'Whose coat is this?', 'Is this yours?'],
    level: 1, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 제이미가 코트를 치운 직후
  {
    id: 's01-12', episode: 1, order: 12,
    situationKo: '제이미가 의자에 걸린 옷을 얼른 치우고 자리를 내줬어요.',
    roleKo: '자리를 내준 제이미에게 내 마음을 전해요.',
    en: 'Thank you so much!', ko: '정말 고마워!',
    reply: { speaker: 'Jamie', en: 'No problem!', ko: '괜찮아!' },
    alternatives: ['Thank you!', 'Thanks a lot!', 'Thanks, Jamie!'],
    level: 1, func: 'thanking', kind: 'review', reviewOf: 'thanks', reuseIn: [],
  },
  {
    id: 's01-06', episode: 1, order: 6,
    situationKo: '드디어 자리에 앉았어요. 옆의 짝을 뭐라고 불러야 할지 아직 몰라요.',
    roleKo: '짝을 이름으로 부르고 싶어요. 직접 물어봐요.',
    en: "What's your name?", ko: '너는 이름이 뭐야?',
    reply: { speaker: 'Jamie', en: "I'm Jamie!", ko: '나는 제이미야!' },
    alternatives: ['What is your name?', "Hi, what's your name?", 'What do I call you?', "Sorry, what's your name?"],
    level: 1, func: 'asking-name', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's01-07', episode: 1, order: 7,
    situationKo: '제이미가 이름을 너무 빨리 말해서 잘 못 알아들었어요.',
    roleKo: '짝의 이름을 제대로 알아듣고 싶어요.',
    en: 'Sorry, can you say that again?', ko: '미안, 다시 말해 줄래?',
    reply: { speaker: 'Jamie', en: 'Just call me Jamie!', ko: '그냥 제이미라고 불러!' },
    alternatives: ['Pardon?', 'Can you say it again, please?', 'Sorry, what was that?', 'Could you say it more slowly?', 'Sorry?'],
    level: 2, func: 'repeat', kind: 'new', reviewOf: null, reuseIn: ['s02-12'],
  },
  {
    id: 's01-08', episode: 1, order: 8,
    situationKo: '수업 중에 앞자리 미아가 돌아보며 속삭였어요. 소리가 너무 작아서 안 들려요.',
    roleKo: '미아가 한 말을 제대로 들을 수 있게 요청해요.',
    en: 'Could you speak a bit louder?', ko: '조금 더 크게 말해 줄래?',
    reply: { speaker: 'Mia', en: "I said, I'm Mia!", ko: '나 미아라고 했어!' },
    alternatives: ['Can you speak up, please?', "Sorry, I can't hear you.", 'A bit louder, please?'],
    level: 2, func: 'repeat', kind: 'new', reviewOf: null, reuseIn: ['s03-11'],
  },
  // 복습: 미아가 이름을 알려 준 직후
  {
    id: 's01-11', episode: 1, order: 11,
    situationKo: '미아가 자기 이름을 알려 주며 활짝 웃었어요. 오늘 처음 본 친구예요.',
    roleKo: '처음 본 미아에게 다정하게 첫마디를 건네요.',
    en: 'Hello! Nice to meet you.', ko: '안녕! 만나서 반가워.',
    reply: { speaker: 'Mia', en: 'Nice to meet you too!', ko: '나도 만나서 반가워!' },
    alternatives: ['Nice to meet you, Mia!', 'Hi, Mia! Nice to meet you.', "Hi! I'm happy to meet you."],
    level: 1, func: 'greeting', kind: 'review', reviewOf: 'hello', reuseIn: [],
  },
  {
    id: 's01-09', episode: 1, order: 9,
    situationKo: '쉬는 시간이 끝났어요. 내 가방이 책상 옆 통로를 막고 있어요.',
    roleKo: '통로가 막히지 않게 가방 둘 곳을 제이미에게 물어봐요.',
    en: 'Where do I put my bag?', ko: '내 가방은 어디에 둬?',
    reply: { speaker: 'Jamie', en: 'Under your desk.', ko: '책상 밑에 둬.' },
    alternatives: ['Where can I put my bag?', 'Where does my bag go?', 'Where should I put this?', 'Where should I put my bag?'],
    level: 2, func: 'asking-place', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's01-10', episode: 1, order: 10,
    situationKo: '하교 종이 울렸어요. 내일 첫 시간이 미술인데 무엇을 챙겨야 할지 몰라요.',
    roleKo: '내일 수업 준비물을 제이미에게 확인해요.',
    en: 'What do I need for tomorrow?', ko: '내일 뭐가 필요해?',
    reply: { speaker: 'Jamie', en: 'Bring a pencil!', ko: '연필 가져와!' },
    alternatives: ['What should I bring tomorrow?', 'What do we need tomorrow?', 'Do I need anything for tomorrow?', 'What do I need to bring tomorrow?'],
    level: 2, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 2화 숟가락이 든 필통 (화요일) ──
  {
    id: 's02-01', episode: 2, order: 1,
    situationKo: '미술 시간, 제이미가 필통을 열자 연필 대신 숟가락이 굴러 나왔어요.',
    roleKo: '이상한 물건이 왜 거기 있는지 제이미에게 물어봐요.',
    en: 'Why is there a spoon in your pencil case?', ko: '왜 네 필통에 숟가락이 있어?',
    reply: { speaker: 'Jamie', en: 'I packed in the dark!', ko: '깜깜할 때 가방을 쌌거든!' },
    alternatives: ['Why have you got a spoon?', 'Is that a spoon?', 'Why is your spoon in there?'],
    level: 3, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-02', episode: 2, order: 2,
    situationKo: '제이미는 숟가락만 들고 멍하니 있어요. 내 필통에는 연필이 딱 한 자루 있어요.',
    roleKo: '그릴 도구가 없는 제이미에게 내 것을 내밀어요.',
    en: 'You can use my pencil.', ko: '내 연필 써도 돼.',
    reply: { speaker: 'Jamie', en: "Really? You're the best!", ko: '정말? 네가 최고야!' },
    alternatives: ['Here, take my pencil.', 'You can have this one.', 'Use my pencil.'],
    level: 1, func: 'offering', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-03', episode: 2, order: 3,
    situationKo: '내 연필은 제이미에게 줬어요. 이제 그릴 도구가 없는데 앞자리 미아 필통에는 연필이 여러 자루 있어요.',
    roleKo: '미아에게 하나 써도 되는지 물어봐요.',
    en: 'Can I borrow a pencil?', ko: '연필 좀 빌려도 돼?',
    reply: { speaker: 'Mia', en: 'Sure! Here you are.', ko: '그럼! 여기 있어.' },
    alternatives: ['Could I borrow a pencil?', 'Can I use one of your pencils?', 'Have you got a spare pencil?'],
    level: 1, func: 'borrowing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-04', episode: 2, order: 4,
    situationKo: '선을 잘못 그었는데 지울 것이 없어요. 앞자리 미아의 책상 위에는 지우개가 두 개 있어요.',
    roleKo: '미아의 물건을 잠깐 써도 되는지 허락을 받아요.',
    en: 'Can I borrow your rubber?', ko: '지우개 좀 빌려도 돼?',
    reply: { speaker: 'Mia', en: 'Sure. Here you go.', ko: '그럼. 여기 있어.' },
    alternatives: ['Can I use your rubber?', 'Could I borrow your eraser?', 'May I borrow your rubber?'],
    level: 1, func: 'borrowing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 미아가 지우개를 건넨 직후
  {
    id: 's02-11', episode: 2, order: 11,
    situationKo: '미아가 지우개 하나를 내 책상 위에 살짝 올려 줬어요.',
    roleKo: '지우개를 내준 미아에게 내 마음을 전해요.',
    en: 'Thank you so much!', ko: '정말 고마워!',
    reply: { speaker: 'Mia', en: "You're welcome!", ko: '천만에!' },
    alternatives: ['Thank you!', 'Thanks a lot!', 'Thanks, Mia!'],
    level: 1, func: 'thanking', kind: 'review', reviewOf: 'thanks', reuseIn: [],
  },
  {
    id: 's02-05', episode: 2, order: 5,
    situationKo: '그림을 다 그렸는데 남은 시간이 많아요. 먼저 끝낸 미아가 칠판 쪽을 보고 있어요.',
    roleKo: '미아에게 내 상황을 알리고 다음에 무엇을 할지 알아봐요.',
    en: "I've finished. What should I do now?", ko: '다 했어. 이제 뭐 하면 돼?',
    reply: { speaker: 'Mia', en: 'Me too! Look at the board.', ko: '나도! 칠판을 봐.' },
    alternatives: ["I'm done. What can I do now?", "Finished! What's next?", "I've finished. Can I do something else?"],
    level: 3, func: 'asking-task', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-06', episode: 2, order: 6,
    situationKo: '칠판에 처음 보는 영어 단어가 있어요. 미아는 아까 선생님 설명을 들었어요.',
    roleKo: '처음 보는 단어를 이해하고 싶어서 미아에게 물어요.',
    en: 'What does this word mean?', ko: '이 단어는 무슨 뜻이야?',
    reply: { speaker: 'Mia', en: "I heard it's a day of music, food and fun!", ko: '음악, 음식, 재미가 있는 날이래!' },
    alternatives: ['What does it mean?', "What's the meaning of this word?", 'What does that word mean?'],
    level: 1, func: 'meaning', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-07', episode: 2, order: 7,
    situationKo: '미아 설명을 들으니 친구들이 모여 신나게 즐기는 날 같아요. 짐작이 맞는지 궁금해요.',
    roleKo: '미아 설명이 내가 아는 어떤 행사 얘기인지 확인해요.',
    en: 'Is it like a party?', ko: '그거 파티 같은 거야?',
    reply: { speaker: 'Mia', en: 'Yes! A big school party.', ko: '맞아! 학교 전체가 여는 큰 파티래.' },
    alternatives: ['Is it a party?', 'Like a big party?', "So it's a kind of party?"],
    level: 1, func: 'checking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-08', episode: 2, order: 8,
    situationKo: '어느새 칠판이 지워졌어요. 공책에 그 단어를 옮겨 적어야 하는데 막혔어요.',
    roleKo: '글자를 하나씩 알고 싶어서 꼼꼼한 미아에게 물어요.',
    en: 'How do you spell it?', ko: '그거 철자가 어떻게 돼?',
    reply: { speaker: 'Mia', en: 'F-E-S-T-I-V-A-L.', ko: '에프, 이, 에스, 티, 아이, 브이, 에이, 엘.' },
    alternatives: ['How do you spell that?', 'Can you spell it for me?', 'How is it spelt?'],
    level: 1, func: 'spelling', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 미아가 글자를 너무 빨리 불렀을 때
  {
    id: 's02-12', episode: 2, order: 12,
    situationKo: '미아가 글자를 너무 빨리 줄줄 불러서 중간부터 놓쳤어요.',
    roleKo: '미아가 불러 준 글자를 처음부터 제대로 받아 적고 싶어요.',
    en: 'Sorry, can you say that again?', ko: '미안, 다시 말해 줄래?',
    reply: { speaker: 'Mia', en: 'Sure! F-E-S-T... I-V-A-L.', ko: '그래! 에프, 이, 에스, 티… 아이, 브이, 에이, 엘.' },
    alternatives: ['Pardon?', 'Sorry, can you say it slowly?', 'Can you spell it again, please?'],
    level: 2, func: 'repeat', kind: 'review', reviewOf: 's01-07', reuseIn: [],
  },
  {
    id: 's02-09', episode: 2, order: 9,
    situationKo: '점심시간, 제이미가 도시락 통을 흔들자 안에서 덜그럭 소리가 났어요.',
    roleKo: '통 안에서 무슨 일이 생긴 건지 제이미에게 확인해요.',
    en: "Jamie, what's in your lunch box?", ko: '제이미, 네 도시락 통에 뭐가 들었어?',
    reply: { speaker: 'Jamie', en: 'Sandwiches. And... yoghurt?', ko: '샌드위치. 그리고… 요구르트?' },
    alternatives: ["What's in there, Jamie?", "What's in your lunchbox?", "Jamie, what's that noise?"],
    level: 2, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's02-10', episode: 2, order: 10,
    situationKo: '제이미는 아침에 분명히 챙겼다고 우겨요. 필통엔 숟가락이 있었죠. 짐작 가는 곳이 있어요.',
    roleKo: '아침에 사라진 물건이 어디 있을지 내 생각을 말해요.',
    en: 'Maybe your pencil is in your lunch box.', ko: '네 연필은 도시락 통에 있을지도 몰라.',
    reply: { speaker: 'Jamie', en: "Let me look... You're right!", ko: '어디 보자… 네 말이 맞아!' },
    alternatives: ['I think your pencil is in there.', "Maybe it's in your lunch box.", 'Check your lunch box!'],
    level: 2, func: 'guessing', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 3화 축제 팀을 만들자 (수요일) ──
  {
    id: 's03-01', episode: 3, order: 1,
    situationKo: '포스터가 공개됐어요. 다음 주 금요일에 학교 축제가 열려요! 셋이 팀을 짜기로 했어요.',
    roleKo: '팀 아이디어를 얻으려고 미아의 취미를 알아봐요.',
    en: 'What do you like doing after school?', ko: '너는 방과 후에 뭐 하는 걸 좋아해?',
    reply: { speaker: 'Mia', en: 'I love dancing!', ko: '나는 춤추는 걸 정말 좋아해!' },
    alternatives: ['What are your hobbies?', 'What do you do after school?', 'What do you like to do?'],
    level: 2, func: 'interests', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-02', episode: 3, order: 2,
    situationKo: '미아가 나에게도 똑같이 물었어요. 혼자 흥얼거리는 건 좋은데 사람들 앞에서는 떨려요.',
    roleKo: '내가 좋아하는 것과 걱정되는 점을 함께 알려요.',
    en: "I like singing, but I'm a bit shy.", ko: '나는 노래하는 걸 좋아하는데, 좀 부끄러워.',
    reply: { speaker: 'Mia', en: "Don't worry. We can sing together!", ko: '걱정 마. 같이 부르면 돼!' },
    alternatives: ["I love singing, but I get shy.", "I like singing, but I'm shy.", "I enjoy singing, but I'm a little shy."],
    level: 3, func: 'hobbies', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-03', episode: 3, order: 3,
    situationKo: '제이미가 이어폰을 끼고 고개를 까딱이고 있어요. 공연에 쓸 곡을 골라야 해요.',
    roleKo: '공연 곡을 정하려고 제이미의 취향을 알아봐요.',
    en: 'What kind of music do you like?', ko: '너는 어떤 음악을 좋아해?',
    reply: { speaker: 'Jamie', en: 'Pop music! And you?', ko: '팝 음악! 너는?' },
    alternatives: ['What music do you like?', 'What are you listening to?', 'What kind of songs do you like?'],
    level: 2, func: 'music', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-04', episode: 3, order: 4,
    situationKo: '제이미가 나에게도 똑같이 물었어요. 내 휴대폰 목록은 한국 가수들 곡으로 가득해요.',
    roleKo: '내가 즐겨 듣는 음악과 얼마나 자주 듣는지 알려요.',
    en: 'I listen to K-pop every day.', ko: '나는 매일 케이팝을 들어.',
    reply: { speaker: 'Jamie', en: 'Cool! Play me one!', ko: '멋지다! 하나 들려줘!' },
    alternatives: ['I love K-pop.', 'I listen to K-pop a lot.', 'I like Korean pop music.'],
    level: 2, func: 'music', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-05', episode: 3, order: 5,
    situationKo: '미아는 춤을, 제이미는 신나는 곡을 좋아해요. 우리 팀 공연을 정해야 해요.',
    roleKo: '두 친구가 좋아하는 것을 합친 공연을 제안해요.',
    en: "Why don't we do a dance?", ko: '우리 춤을 추는 게 어때?',
    reply: { speaker: 'Mia', en: "Yes! I'll make up the moves.", ko: '좋아! 동작은 내가 짤게.' },
    alternatives: ["Let's do a dance!", 'How about a dance?', 'Shall we do a dance?'],
    level: 2, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-06', episode: 3, order: 6,
    situationKo: '미아가 춤 중간에 나랑 제이미가 노래를 조금 부르면 어떠냐고 했어요. 멋질 것 같아요.',
    roleKo: '미아의 제안에 기쁘게 찬성해요.',
    en: "That's a great idea!", ko: '그거 좋은 생각이다!',
    reply: { speaker: 'Mia', en: "Great! Let's do it.", ko: '좋아! 그렇게 하자.' },
    alternatives: ['Good idea!', 'Sounds great!', 'I love that idea!'],
    level: 1, func: 'agreeing', kind: 'new', reviewOf: null, reuseIn: ['s05-11', 's08-11'],
  },
  {
    id: 's03-07', episode: 3, order: 7,
    situationKo: '포스터 아래에 작게 적혀 있어요. 원하는 팀은 먹을거리 가게도 열 수 있대요.',
    roleKo: '공연 말고 가게도 하나 열자고 친구들에게 제안해요.',
    en: 'Shall we sell snacks too?', ko: '우리 간식도 팔까?',
    reply: { speaker: 'Jamie', en: 'Yes! I love snacks!', ko: '좋아! 나 간식 엄청 좋아해!' },
    alternatives: ["Let's sell snacks too.", 'How about a snack stall?', "Why don't we sell snacks?"],
    level: 1, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-08', episode: 3, order: 8,
    situationKo: '축제를 알리려면 복도에 붙일 큰 그림 종이가 필요해요. 나는 그림 그리기를 잘해요.',
    roleKo: '내가 맡을 수 있는 일을 친구들에게 알려요.',
    en: 'I can make the posters.', ko: '포스터는 내가 만들 수 있어.',
    reply: { speaker: 'Mia', en: 'Perfect! Thanks!', ko: '딱이야! 고마워!' },
    alternatives: ["I'll make the posters.", 'I can draw the posters.', 'Can I do the posters?'],
    level: 1, func: 'roles', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-09', episode: 3, order: 9,
    situationKo: '할 일이 많아졌어요. 전체를 챙기며 계획을 세울 사람이 한 명 필요해요.',
    roleKo: '팀을 이끌 사람을 정하려고 둘에게 물어요.',
    en: 'Who wants to be the leader?', ko: '누가 리더 할래?',
    reply: { speaker: 'Jamie', en: 'Not me! I lose things.', ko: '난 빼 줘! 나는 물건을 잃어버리잖아.' },
    alternatives: ['Who will be the leader?', 'Who wants to lead?', 'Who should be our leader?'],
    level: 2, func: 'roles', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's03-10', episode: 3, order: 10,
    situationKo: '미아가 리더를 맡았어요. 신청서 맨 위에 우리 팀을 부를 칸이 아직 비어 있어요.',
    roleKo: '신청서 첫 칸을 채우려고 친구들의 생각을 물어요.',
    en: 'What shall we call our team?', ko: '우리 팀 이름을 뭐라고 할까?',
    reply: { speaker: 'Jamie', en: 'The Spoon Stars!', ko: '스푼 스타즈!' },
    alternatives: ["What's our team name?", 'What should we call our team?', "Let's think of a team name!"],
    level: 2, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 시끄러운 쉬는 시간에 미아가 연습 계획을 말할 때
  {
    id: 's03-11', episode: 3, order: 11,
    situationKo: '쉬는 시간이라 교실이 시끌시끌해요. 미아가 연습 계획을 말하는데 잘 안 들려요.',
    roleKo: '미아의 계획을 제대로 들을 수 있게 요청해요.',
    en: 'Could you speak a bit louder?', ko: '조금 더 크게 말해 줄래?',
    reply: { speaker: 'Mia', en: 'Practice tomorrow! Music room!', ko: '내일 연습! 음악실에서!' },
    alternatives: ['Can you speak up, please?', "Sorry, I can't hear you.", 'Louder, please!'],
    level: 2, func: 'repeat', kind: 'review', reviewOf: 's01-08', reuseIn: [],
  },

  // ── 4화 첫 연습은 엉망진창 (목요일 방과 후, 음악실) ──
  {
    id: 's04-01', episode: 4, order: 1,
    situationKo: '방과 후 음악실, 거울 앞에 셋이 섰어요. 심장이 쿵쿵 뛰고 손에 땀이 나요.',
    roleKo: '지금 내 기분을 친구들에게 솔직하게 털어놔요.',
    en: "I'm so nervous.", ko: '나 너무 떨려.',
    reply: { speaker: 'Mia', en: "Me too! It's OK.", ko: '나도 그래! 괜찮아.' },
    alternatives: ["I'm really nervous.", "I'm a bit nervous.", "I'm so scared."],
    level: 1, func: 'feelings', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-02', episode: 4, order: 2,
    situationKo: '첫 동작은 빙글 도는 거예요. 그런데 미아가 방향은 알려 주지 않았어요.',
    roleKo: '셋이 똑같이 움직일 수 있게 미아에게 확인해요.',
    en: 'Which way do we turn?', ko: '어느 쪽으로 돌아?',
    reply: { speaker: 'Mia', en: 'Left first, then right.', ko: '먼저 왼쪽, 그다음 오른쪽.' },
    alternatives: ['Do we turn left or right?', 'Which way?', 'Which side do we turn to?'],
    level: 1, func: 'directions', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-03', episode: 4, order: 3,
    situationKo: '음악이 시작되자 나만 반대로 돌아서 미아와 얼굴을 마주 봤어요.',
    roleKo: '내가 실수했다는 걸 웃으며 인정해요.',
    en: 'Oops, I went the wrong way.', ko: '앗, 나 반대로 갔어.',
    reply: { speaker: 'Jamie', en: "Me too! I'm in the curtain!", ko: '나도! 난 커튼 속에 있어!' },
    alternatives: ['Oops, wrong way!', 'Oh no, I turned the wrong way.', 'Oops, I went left!'],
    level: 2, func: 'mistake', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 반대로 돌다가 미아의 발을 밟았을 때
  {
    id: 's04-11', episode: 4, order: 11,
    situationKo: '반대로 돌다가 미아의 발을 살짝 밟았어요. 미아가 발을 감싸 쥐었어요.',
    roleKo: '발을 밟힌 미아에게 내 잘못을 인정해요.',
    en: "I'm sorry.", ko: '미안해.',
    reply: { speaker: 'Mia', en: "It's OK. I'm fine.", ko: '괜찮아. 안 다쳤어.' },
    alternatives: ['Sorry!', "I'm so sorry.", 'Oops, sorry, Mia!'],
    level: 1, func: 'apologising', kind: 'review', reviewOf: 'sorry', reuseIn: [],
  },
  {
    id: 's04-04', episode: 4, order: 4,
    situationKo: '셋 다 엉망인 채로 음악이 끝났어요. 이번에는 제대로 맞춰 보고 싶어요.',
    roleKo: '처음부터 맞춰 보자고 친구들에게 제안해요.',
    en: 'Can we do it again?', ko: '우리 다시 해 볼까?',
    reply: { speaker: 'Mia', en: 'Sure! Ready?', ko: '좋아! 준비됐지?' },
    alternatives: ['Can we try again?', "Let's do it again.", 'One more time?', "Let's start from the beginning."],
    level: 1, func: 'again', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-05', episode: 4, order: 5,
    situationKo: '미아의 발동작이 너무 빨라서 눈으로 따라갈 수가 없어요.',
    roleKo: '동작을 제대로 익히려고 미아에게 요청해요.',
    en: 'Could you show me again, slowly?', ko: '천천히 한 번 더 보여 줄래?',
    reply: { speaker: 'Mia', en: 'OK. Step, step, clap.', ko: '알았어. 스텝, 스텝, 박수.' },
    alternatives: ['Can you do it slowly?', 'Could you do it more slowly?', 'Slower, please?'],
    level: 2, func: 'slowly', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-06', episode: 4, order: 6,
    situationKo: '점프까지는 외웠어요. 그런데 거기서 매번 멈춰 버려요.',
    roleKo: '순서를 끝까지 외우려고 미아에게 물어요.',
    en: 'What comes after the jump?', ko: '점프 다음엔 뭐야?',
    reply: { speaker: 'Mia', en: 'A spin and a clap!', ko: '한 바퀴 돌고 박수!' },
    alternatives: ['What do we do after the jump?', "What's next after the jump?", 'And after the jump?'],
    level: 1, func: 'order', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-07', episode: 4, order: 7,
    situationKo: '한 시간째 연습 중이에요. 다리가 후들거리고 목이 말라요.',
    roleKo: '지친 몸을 추스를 수 있게 리더 미아에게 제안해요.',
    en: 'Can we take a short break?', ko: '우리 잠깐 쉬어도 돼?',
    reply: { speaker: 'Mia', en: 'Good idea. Five minutes!', ko: '좋아. 5분만!' },
    alternatives: ['Can we have a break?', "Let's take a break.", 'Can we rest for a minute?'],
    level: 2, func: 'break', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-08', episode: 4, order: 8,
    situationKo: '쉬는 동안 미아가 혼자 동작을 보여 줬어요. 아주 매끄럽고 멋져요.',
    roleKo: '미아의 춤 실력을 진심으로 치켜세워요.',
    en: "You're really good at this!", ko: '너 이거 진짜 잘한다!',
    reply: { speaker: 'Mia', en: 'Aw, thanks! You too!', ko: '와, 고마워! 너도야!' },
    alternatives: ["You're a great dancer!", "Wow, you're so good!", "You're really good!"],
    level: 1, func: 'praise', kind: 'new', reviewOf: null, reuseIn: ['s10-12'],
  },
  {
    id: 's04-09', episode: 4, order: 9,
    situationKo: '셋이 번갈아 연습곡을 틀기로 했어요. 방금 곡이 끝났는데 이번엔 누군지 헷갈려요.',
    roleKo: '다음 곡을 고를 사람이 누구인지 확인해요.',
    en: 'Whose turn is it to choose the music?', ko: '음악 고를 차례가 누구야?',
    reply: { speaker: 'Jamie', en: "Mine! Here's a fast one.", ko: '내 차례! 빠른 곡 간다.' },
    alternatives: ['Whose turn is it?', "Who's choosing the next song?", 'Is it my turn to pick?'],
    level: 2, func: 'turns', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's04-10', episode: 4, order: 10,
    situationKo: '폴 선생님이 들러서 준비가 어떤지 물어요. 공연 옷도, 가게에서 팔 것도 아직 없어요.',
    roleKo: '아직 마련하지 못한 것들을 선생님께 알려요.',
    en: 'We still need costumes and snacks.', ko: '아직 의상이랑 간식이 필요해요.',
    reply: { speaker: 'Paul', en: "Here's twenty pounds. Spend it wisely!", ko: '여기 20파운드야. 잘 써야 한다!' },
    alternatives: ['We need costumes and snacks.', "We haven't got costumes or snacks yet.", "We don't have costumes or snacks."],
    level: 2, func: 'planning', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 5화 필요한 것을 사러 가자 (금요일 방과 후, 학교 앞 가게 — 폴 선생님 허락, 셋이서) ──
  {
    id: 's05-01', episode: 5, order: 1,
    situationKo: '방과 후, 셋이 학교 앞 가게에 왔어요. 지갑을 든 미아에게 남은 돈이 정확히 얼마인지 모르겠어요.',
    roleKo: '물건을 고르기 전에 우리 예산부터 확인해요.',
    en: 'How much money do we have?', ko: '우리 돈 얼마 있어?',
    reply: { speaker: 'Mia', en: 'Twenty pounds.', ko: '20파운드.' },
    alternatives: ['How much have we got?', 'How much money is there?', "What's our budget?"],
    level: 2, func: 'budget', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-02', episode: 5, order: 2,
    situationKo: '진열대에 빨강, 파랑, 금색 리본이 걸려 있어요. 공연 옷은 리더 미아가 정하기로 했어요.',
    roleKo: '리본을 고르려고 미아의 마음에 드는 것을 물어요.',
    en: 'Which colour do you like?', ko: '어떤 색이 좋아?',
    reply: { speaker: 'Mia', en: "Gold! It's shiny.", ko: '금색! 반짝거리잖아.' },
    alternatives: ['What colour do you want?', 'Which one do you like?', 'Which colour shall we get?'],
    level: 1, func: 'colour', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-03', episode: 5, order: 3,
    situationKo: '반짝이는 리본 묶음을 집었어요. 붙어 있던 가격표가 떨어져서 보이지 않아요.',
    roleKo: '계산대의 가게 주인에게 이 물건의 값을 확인해요.',
    en: 'How much is this?', ko: '이거 얼마예요?',
    reply: { speaker: 'Shopkeeper', en: "That one's fifteen pounds.", ko: '그건 15파운드란다.' },
    alternatives: ['How much is it?', 'Excuse me, how much is this?', 'How much does this cost?'],
    level: 1, func: 'price', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-04', episode: 5, order: 4,
    situationKo: '리본 하나에 예산 대부분을 써 버리게 생겼어요. 간식 재료도 사야 하는데요.',
    roleKo: '이 값으로는 살 수 없다고 친구들에게 말해요.',
    en: "That's too expensive.", ko: '그건 너무 비싸.',
    reply: { speaker: 'Jamie', en: 'Yeah. Put it back!', ko: '맞아. 다시 내려놔!' },
    alternatives: ["It's too expensive.", "That's a lot of money.", "We can't buy that."],
    level: 1, func: 'price', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-05', episode: 5, order: 5,
    situationKo: '그래도 공연에는 반짝이는 리본이 꼭 필요해요. 다른 상품이 있을지도 몰라요.',
    roleKo: '예산에 맞는 다른 리본이 있는지 가게 주인에게 물어요.',
    en: 'Is there a cheaper one?', ko: '더 싼 거 있어요?',
    reply: { speaker: 'Shopkeeper', en: 'Yes. These are two pounds each.', ko: '그럼. 이건 하나에 2파운드야.' },
    alternatives: ['Do you have a cheaper one?', 'Have you got anything cheaper?', 'Is there anything cheaper?'],
    level: 1, func: 'choosing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-06', episode: 5, order: 6,
    situationKo: '값이 싼 리본에도 미아가 고른 그 색이 있어요. 이제 결정만 하면 돼요.',
    roleKo: '어떤 리본을 살지 결정해서 친구들에게 말해요.',
    en: "Let's get the gold ones.", ko: '금색으로 사자.',
    reply: { speaker: 'Mia', en: "Yes! They're perfect.", ko: '좋아! 딱이야.' },
    alternatives: ["Let's buy the gold ones.", "Let's take the gold ribbons.", 'The gold ones, please.'],
    level: 1, func: 'choosing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-07', episode: 5, order: 7,
    situationKo: '제이미가 리본을 한 아름 집어 들었어요. 정말 그만큼 필요할지 모르겠어요.',
    roleKo: '꼭 필요한 만큼만 사려고 친구들과 확인해요.',
    en: 'How many do we need?', ko: '몇 개 필요해?',
    reply: { speaker: 'Mia', en: 'One for each of us.', ko: '한 사람에 하나씩.' },
    alternatives: ['How many ribbons do we need?', 'How many shall we get?', 'How many?'],
    level: 1, func: 'quantity', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-08', episode: 5, order: 8,
    situationKo: '미아 말대로 한 사람에 하나씩이면 돼요. 그런데 제이미 손에는 리본이 열 개나 있어요.',
    roleKo: '사야 할 정확한 개수를 제이미에게 알려 줘요.',
    en: 'We need three ribbons.', ko: '리본은 세 개 필요해.',
    reply: { speaker: 'Jamie', en: "Oops! I'll put seven back.", ko: '앗! 일곱 개 내려놓을게.' },
    alternatives: ['Just three ribbons.', 'We only need three.', 'Three is enough.'],
    level: 1, func: 'quantity', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 제이미가 간식 재료를 제안했을 때
  {
    id: 's05-11', episode: 5, order: 11,
    situationKo: '제이미가 팝콘과 레모네이드 재료를 사서 가게에서 팔자고 했어요. 축제에 딱 좋겠어요.',
    roleKo: '제이미의 제안에 기쁘게 찬성해요.',
    en: "That's a great idea!", ko: '그거 좋은 생각이다!',
    reply: { speaker: 'Jamie', en: 'Yes! Popcorn party!', ko: '좋았어! 팝콘 파티!' },
    alternatives: ['Good idea!', 'Sounds great!', 'Great idea, Jamie!'],
    level: 1, func: 'agreeing', kind: 'review', reviewOf: 's03-06', reuseIn: [],
  },
  {
    id: 's05-09', episode: 5, order: 9,
    situationKo: '바구니에 리본 세 개, 팝콘, 레모네이드 재료를 담고 계산대 앞에 섰어요.',
    roleKo: '이 물건들의 값을 치르겠다고 가게 주인에게 말해요.',
    en: 'Can we pay for these, please?', ko: '이거 계산할게요.',
    reply: { speaker: 'Shopkeeper', en: "That's twelve pounds, please.", ko: '12파운드란다.' },
    alternatives: ['Can I pay for these, please?', 'Can we pay, please?', 'How much is it all?'],
    level: 2, func: 'paying', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's05-10', episode: 5, order: 10,
    situationKo: '값을 치르고도 돈이 조금 남았어요. 계산대 옆에 맛있어 보이는 과자 상자가 있어요.',
    roleKo: '남은 돈으로 과자도 사도 되는지 리더 미아에게 물어봐요.',
    en: 'Can we get some cookies too?', ko: '쿠키도 좀 사도 돼?',
    reply: { speaker: 'Mia', en: "Yes! We've got eight pounds left.", ko: '응! 8파운드 남았어.' },
    alternatives: ['Can we buy some cookies?', 'Shall we get cookies too?', 'Can we have some cookies as well?', 'Can we get some biscuits too?'],
    level: 2, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 6화 쿠키가 가져간 것 (둘째 주 월요일 16일 — 쿠키 첫 등장) ──
  {
    id: 's06-01', episode: 6, order: 1,
    situationKo: '월요일 아침, 미아가 탁자에 둔 봉지를 열었어요. 반짝이는 리본이 두 개뿐이에요.',
    roleKo: '없어진 하나의 행방을 친구들에게 물어요.',
    en: "Where's the gold ribbon?", ko: '금색 리본 어디 있어?',
    reply: { speaker: 'Mia', en: "I don't know! It was here.", ko: '몰라! 여기 있었는데.' },
    alternatives: ['Where is the gold ribbon?', "Where's the other ribbon?", 'Where did the ribbon go?'],
    level: 1, func: 'location', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-02', episode: 6, order: 2,
    situationKo: '제이미는 물건을 잘 잃어버려요. 마침 아침 내내 봉지 바로 옆에 서 있었어요.',
    roleKo: '범인이 제이미인지 조심스럽게 확인해요.',
    en: 'Jamie, did you take it?', ko: '제이미, 네가 가져갔어?',
    reply: { speaker: 'Jamie', en: 'No! Look, Cookie!', ko: '아니야! 저기 봐, 쿠키야!' },
    alternatives: ['Did you take it, Jamie?', 'Jamie, have you got it?', 'Jamie, is it in your bag?'],
    level: 1, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-03', episode: 6, order: 3,
    situationKo: '폴 선생님의 강아지 쿠키가 무언가를 물고 문밖으로 달아났어요. 마침 선생님이 들어와요.',
    roleKo: '강아지가 간 곳을 알아내려고 선생님께 물어요.',
    en: 'Have you seen Cookie?', ko: '쿠키 보셨어요?',
    reply: { speaker: 'Paul', en: 'She went that way!', ko: '저쪽으로 갔어!' },
    alternatives: ['Where did Cookie go?', 'Did you see Cookie?', 'Where is Cookie?'],
    level: 1, func: 'finding', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-04', episode: 6, order: 4,
    situationKo: '복도로 나가 보니 긴 나무 의자 쪽에서 꼬리가 살랑거려요. 리본도 반짝여요.',
    roleKo: '쿠키를 찾았다고 친구들에게 있는 곳과 함께 알려요.',
    en: "Look! Cookie's under the bench.", ko: '봐! 쿠키가 벤치 밑에 있어.',
    reply: { speaker: 'Jamie', en: 'Quick! Before she runs!', ko: '빨리! 도망가기 전에!' },
    alternatives: ["Cookie's under the bench!", "Look, there's Cookie!", "She's under the bench!"],
    level: 1, func: 'location', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 쿠키가 의자 밑 깊숙이 들어갔을 때
  {
    id: 's06-11', episode: 6, order: 11,
    situationKo: '쿠키가 의자 밑 깊숙이 들어가 버렸어요. 내 팔이 끝까지 닿지 않아요.',
    roleKo: '혼자서는 안 돼요. 옆에 있는 제이미에게 함께해 달라고 해요.',
    en: 'Can you help me, please?', ko: '나 좀 도와줄래?',
    reply: { speaker: 'Jamie', en: 'Sure! Cookie, come here!', ko: '그럼! 쿠키, 이리 와!' },
    alternatives: ['Can you help me?', 'Jamie, help me, please!', 'Could you help me, please?'],
    level: 1, func: 'asking-help', kind: 'review', reviewOf: 'help', reuseIn: [],
  },
  {
    id: 's06-05', episode: 6, order: 5,
    situationKo: '쿠키가 리본을 꽉 물고 꼬리를 흔들어요. 장난치는 줄 아나 봐요.',
    roleKo: '리본을 돌려받으려고 쿠키에게 단호하게 말해요.',
    en: 'Cookie, drop it!', ko: '쿠키, 그거 놔!',
    reply: { speaker: 'Cookie', en: 'Woof!', ko: '멍!' },
    alternatives: ['Drop it, Cookie!', 'Cookie, give it back!', 'Cookie, no!'],
    level: 1, func: 'command', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-06', episode: 6, order: 6,
    situationKo: '리본을 들고 교실로 돌아와 돌아서다 팔꿈치로 팝콘 봉지를 쳤어요. 바닥이 엉망이에요.',
    roleKo: '방금 벌어진 일에 깜짝 놀라 소리쳐요.',
    en: "Oh no, I've knocked the popcorn over!", ko: '아 이런, 팝콘을 엎었어!',
    reply: { speaker: 'Mia', en: 'Oh no! Cookie, stay!', ko: '안 돼! 쿠키, 가만있어!' },
    alternatives: ["Oh no, I've spilled the popcorn!", 'Oops, the popcorn!', 'Oh no, I knocked it over!'],
    level: 2, func: 'mistake', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-07', episode: 6, order: 7,
    situationKo: '쿠키가 바닥의 팝콘을 먹으려고 해요. 청소 도구는 복도 끝 창고에 있어요.',
    roleKo: '친구들은 쿠키를 지키게 하고, 나는 창고로 가겠다고 알려요.',
    en: "Wait here. I'll get the broom.", ko: '여기서 기다려. 내가 빗자루 가져올게.',
    reply: { speaker: 'Jamie', en: 'OK! Hurry!', ko: '알았어! 빨리 와!' },
    alternatives: ["Stay here. I'll get the broom.", "Wait here, I'll be back.", "Hold on. I'll get a broom."],
    level: 2, func: 'waiting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-08', episode: 6, order: 8,
    situationKo: '빗자루를 들고 오니 폴 선생님이 바닥을 보고 놀란 얼굴로 서 있어요.',
    roleKo: '교실을 어지럽힌 건 내 탓이라고 선생님께 말해요.',
    en: "I'm really sorry about the mess.", ko: '어질러서 정말 죄송해요.',
    reply: { speaker: 'Paul', en: "It's OK. Accidents happen.", ko: '괜찮아. 그럴 수도 있지.' },
    alternatives: ["I'm so sorry about this.", "Sorry, it's my fault.", 'Sorry about the mess, Mr Paul.'],
    level: 2, func: 'apologising', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-09', episode: 6, order: 9,
    situationKo: '선생님이 쿠키를 붙잡았어요. 팝콘은 아직 교실 바닥 여기저기에 흩어져 있어요.',
    roleKo: '빨리 끝낼 수 있게 친구들에게 제안해요.',
    en: "Let's clean this up together.", ko: '우리 같이 치우자.',
    reply: { speaker: 'Mia', en: "OK! I'll get the bin.", ko: '좋아! 내가 쓰레기통 가져올게.' },
    alternatives: ["Let's clean up together.", "Let's tidy this up.", 'Can we all clean up?'],
    level: 1, func: 'cleaning', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's06-10', episode: 6, order: 10,
    situationKo: '바닥이 깨끗해졌어요. 리본을 봉지에 다시 넣기 전에 혹시 몰라 확인하고 싶어요.',
    roleKo: '공연에 쓸 것이 하나도 빠지지 않았는지 미아에게 확인해요.',
    en: 'Are all three ribbons here?', ko: '리본 세 개 다 있어?',
    reply: { speaker: 'Mia', en: 'One, two, three. Yes!', ko: '하나, 둘, 셋. 응!' },
    alternatives: ['Have we got all three ribbons?', 'Are the three ribbons here?', 'Do we have all the ribbons?'],
    level: 1, func: 'checking', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 7화 우리가 좋아하는 가수에게 (수요일 18일 — 보내지 않는 가상 초대장 연습) ──
  {
    id: 's07-01', episode: 7, order: 1,
    situationKo: '라디오에서 우리가 좋아하는 가수의 노래가 나와요. 진짜로 올 리는 없지만 상상은 자유예요.',
    roleKo: '진짜로 보내지는 않는 상상 놀이를 친구들에게 제안해요.',
    en: "Let's pretend to invite our favourite singer!", ko: '우리가 좋아하는 가수를 초대하는 척해 보자!',
    reply: { speaker: 'Mia', en: 'Yes! Just for practice.', ko: '좋아! 연습으로만.' },
    alternatives: ["Let's pretend to invite them!", 'What if we invited our favourite singer?', "Let's imagine inviting our favourite singer!"],
    level: 2, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-02', episode: 7, order: 2,
    situationKo: '폴 선생님이 좋대요. 보내지는 않는 가상의 초대장이니 영어 쓰기 연습이 된대요.',
    roleKo: '셋이 쓸 준비를 하려고 필기구를 찾아요.',
    en: 'Has anyone got a pen?', ko: '펜 있는 사람?',
    reply: { speaker: 'Jamie', en: 'Me! A gold pen!', ko: '나! 금색 펜!' },
    alternatives: ['Does anyone have a pen?', 'Can I borrow a pen?', 'Who has a pen?'],
    level: 1, func: 'asking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-03', episode: 7, order: 3,
    situationKo: '가상의 초대장 첫 줄이에요. 가수는 우리를 전혀 모르니 누군지부터 밝혀야 해요.',
    roleKo: '초대장 첫 줄에 들어갈 우리 소개를 소리 내어 말해요.',
    en: "We're students from Class 7B.", ko: '저희는 7B반 학생들이에요.',
    reply: { speaker: 'Mia', en: 'Good start!', ko: '좋은 시작이야!' },
    alternatives: ["We're from Class 7B.", 'We are students in 7B.', "We're three students from 7B."],
    level: 1, func: 'self-introduction', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 가상의 초대장에 내 소개를 한 줄 넣을 때
  {
    id: 's07-11', episode: 7, order: 11,
    situationKo: '미아가 가상의 초대장에 내 소개도 한 줄 넣재요. 초대장이 더 특별해질 것 같대요.',
    roleKo: '초대장에 넣을 내 고향 소개 한 줄을 말해요.',
    en: "I'm from Korea.", ko: '저는 한국에서 왔어요.',
    reply: { speaker: 'Mia', en: 'Nice! Put that in.', ko: '좋아! 그것도 넣자.' },
    alternatives: ['I come from Korea.', "I'm from South Korea.", "I'm Korean."],
    level: 1, func: 'introducing', kind: 'review', reviewOf: 's01-02', reuseIn: [],
  },
  {
    id: 's07-04', episode: 7, order: 4,
    situationKo: '이제 왜 편지를 쓰는지 밝힐 차례예요. 이번 주 금요일에 큰 행사가 있죠.',
    roleKo: '가상의 초대장에 우리 학교 행사를 소개해요.',
    en: "We're having a school festival.", ko: '저희 학교에서 축제를 열어요.',
    reply: { speaker: 'Jamie', en: 'Got it. Writing it now.', ko: '알았어. 지금 쓸게.' },
    alternatives: ["We're having a festival.", 'Our school is having a festival.', "There's a festival at our school.", 'We have a school festival.'],
    level: 1, func: 'event', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-05', episode: 7, order: 5,
    situationKo: '행사 소개를 썼어요. 이제 상상 속 가수에게 가장 하고 싶은 말을 쓸 차례예요.',
    roleKo: '가상의 초대장 속 가수에게 정중하게 마음을 물어요.',
    en: 'Would you like to come?', ko: '오시겠어요?',
    reply: { speaker: 'Mia', en: 'Polite. I like it!', ko: '정중하네. 마음에 들어!' },
    alternatives: ['Can you come?', 'Do you want to come?', 'Please come to our festival!'],
    level: 1, func: 'inviting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-06', episode: 7, order: 6,
    situationKo: '초대를 받으면 누구나 날짜부터 궁금하겠죠. 달력에 축제 날이 동그라미 쳐져 있어요.',
    roleKo: '가상의 초대장에 축제 날짜를 넣어요.',
    en: "It's on Friday the twentieth.", ko: '20일 금요일이에요.',
    reply: { speaker: 'Jamie', en: 'Done! What next?', ko: '다 썼어! 다음은?' },
    alternatives: ["It's on the twentieth.", "It's on Friday, the twentieth.", 'The festival is on Friday the twentieth.'],
    level: 1, func: 'date', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-07', episode: 7, order: 7,
    situationKo: '날짜 다음은 시간이에요. 포스터를 보니 수업이 끝나고 삼십 분 뒤예요.',
    roleKo: '가상의 초대장에 행사가 몇 시부터인지 넣어요.',
    en: 'It starts at half past three.', ko: '세 시 반에 시작해요.',
    reply: { speaker: 'Mia', en: 'Perfect. Now the place.', ko: '완벽해. 이제 장소.' },
    alternatives: ['It begins at half past three.', 'It starts at three thirty.', 'At half past three.'],
    level: 2, func: 'time', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-08', episode: 7, order: 8,
    situationKo: '이제 장소를 쓸 차례예요. 포스터에는 학교 건물 앞 넓은 마당 그림이 있어요.',
    roleKo: '가상의 초대장에 축제가 열리는 곳을 넣어요.',
    en: "It's on the school playground.", ko: '학교 운동장에서 해요.',
    reply: { speaker: 'Jamie', en: "Outside! I hope it's sunny.", ko: '밖이네! 날씨가 맑으면 좋겠다.' },
    alternatives: ["It's at our school playground.", "It's on the playground.", "It's outside, on the playground."],
    level: 1, func: 'place', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-09', episode: 7, order: 9,
    situationKo: '가상의 초대장 마지막 줄이에요. 다정하게 마무리하고 싶어요.',
    roleKo: '편지를 기분 좋게 끝맺을 마지막 문장을 말해요.',
    en: 'We hope to see you there!', ko: '그날 뵙기를 바라요!',
    reply: { speaker: 'Mia', en: "Lovely! Now let's sign it.", ko: '멋져! 이제 이름 쓰자.' },
    alternatives: ['Hope to see you there!', 'We hope you can come!', 'See you there!'],
    level: 2, func: 'closing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's07-10', episode: 7, order: 10,
    situationKo: '가상의 초대장이 완성됐어요. 글자만 빽빽해서 조금 심심해 보여요. 나는 포스터 담당이죠.',
    roleKo: '초대장을 더 꾸미자고 친구들에게 제안해요.',
    en: 'Shall we add a picture?', ko: '그림도 넣을까?',
    reply: { speaker: 'Jamie', en: 'Yes! Draw Cookie!', ko: '좋아! 쿠키 그려!' },
    alternatives: ['Can we add a picture?', "Let's draw a picture too.", 'Shall I draw something?'],
    level: 1, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 8화 축제 전날의 문제 (목요일 19일) ──
  {
    id: 's08-01', episode: 8, order: 1,
    situationKo: '목요일 아침, 제이미가 쉰 목소리로 겨우 속삭여요. 얼굴도 조금 창백해요.',
    roleKo: '제이미의 몸 상태가 마음에 걸려서 먼저 물어봐요.',
    en: 'Are you OK, Jamie?', ko: '제이미, 괜찮아?',
    reply: { speaker: 'Jamie', en: 'Not really...', ko: '별로…' },
    alternatives: ['Jamie, are you all right?', 'Are you feeling OK?', "What's wrong, Jamie?"],
    level: 1, func: 'feelings', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-02', episode: 8, order: 2,
    situationKo: '제이미가 목을 손으로 감싸고 침을 삼킬 때마다 얼굴을 찡그려요.',
    roleKo: '어디가 불편한지 제이미에게 확인해요.',
    en: 'Does your throat hurt?', ko: '목 아파?',
    reply: { speaker: 'Jamie', en: "Yes. I can't sing.", ko: '응. 노래를 못 하겠어.' },
    alternatives: ['Is your throat sore?', 'Have you got a sore throat?', 'Does it hurt?'],
    level: 1, func: 'feelings', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-03', episode: 8, order: 3,
    situationKo: '내 가방에 아직 따지 않은 물병이 하나 있어요. 제이미는 계속 콜록거려요.',
    roleKo: '목이 아픈 제이미에게 내 물병을 내밀어요.',
    en: 'Here, have some water.', ko: '자, 물 좀 마셔.',
    reply: { speaker: 'Jamie', en: "Thanks. That's better.", ko: '고마워. 좀 낫다.' },
    alternatives: ['Here, drink some water.', 'Do you want some water?', 'Have my water.'],
    level: 1, func: 'offering', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-04', episode: 8, order: 4,
    situationKo: '제이미가 내일 공연을 망칠까 봐 고개를 푹 숙였어요.',
    roleKo: '풀이 죽은 제이미에게 내 손이 필요한지 물어요.',
    en: 'Is there anything I can do?', ko: '내가 해 줄 수 있는 게 있을까?',
    reply: { speaker: 'Jamie', en: 'Can you sing my part?', ko: '내 파트 불러 줄 수 있어?' },
    alternatives: ['Can I do anything?', 'What can I do for you?', 'How can I help?'],
    level: 2, func: 'offering-help', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-05', episode: 8, order: 5,
    situationKo: '사람들 앞에서 노래하는 건 아직 떨려요. 그래도 제이미를 위해 용기를 내기로 했어요.',
    roleKo: '제이미를 안심시키고 그 일을 내가 맡겠다고 해요.',
    en: "Don't worry. I can sing your part.", ko: '걱정 마. 네 파트는 내가 부를 수 있어.',
    reply: { speaker: 'Jamie', en: "Really? You're a star!", ko: '정말? 너 진짜 멋지다!' },
    alternatives: ["Don't worry, I'll sing it.", 'I can sing your part.', "It's OK. I'll do your part."],
    level: 3, func: 'offering-help', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-06', episode: 8, order: 6,
    situationKo: '미아가 휴대폰 날씨를 보여 줘요. 내일 오후에 비구름이 떠 있어요. 축제는 운동장에서 해요.',
    roleKo: '날씨 때문에 마음이 놓이지 않는다고 친구들에게 털어놔요.',
    en: "I'm worried about the rain.", ko: '비가 걱정돼.',
    reply: { speaker: 'Mia', en: 'Me too. What can we do?', ko: '나도. 어떻게 하지?' },
    alternatives: ["I'm worried it'll rain.", 'What if it rains?', 'Oh no, rain!'],
    level: 1, func: 'worry', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-07', episode: 8, order: 7,
    situationKo: '운동장에는 비를 피할 곳이 없어요. 학교 강당은 내일 오후에 비어 있대요.',
    roleKo: '비를 피할 다른 장소를 친구들에게 제안해요.',
    en: 'How about using the hall instead?', ko: '대신 강당을 쓰는 건 어때?',
    reply: { speaker: 'Mia', en: 'Good thinking!', ko: '좋은 생각이야!' },
    alternatives: ['Why not use the hall?', 'What about the hall?', 'Can we use the hall instead?'],
    level: 2, func: 'alternatives', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-08', episode: 8, order: 8,
    situationKo: '장소를 바꾸려면 허락이 필요해요. 마침 폴 선생님이 교무실로 걸어가고 있어요.',
    roleKo: '허락해 줄 수 있는 사람에게 가 보자고 친구들에게 말해요.',
    en: "Let's ask Mr Paul.", ko: '폴 선생님께 여쭤보자.',
    reply: { speaker: 'Mia', en: 'Yes. Quick!', ko: '응. 빨리!' },
    alternatives: ["Let's ask the teacher.", 'Shall we ask Mr Paul?', 'We should ask Mr Paul.'],
    level: 1, func: 'suggesting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's08-09', episode: 8, order: 9,
    situationKo: '선생님이 강당을 써도 된대요. 그런데 장소도, 노래할 사람도 처음 정한 것과 달라졌어요.',
    roleKo: '새로 정할 것이 생겼다고 친구들에게 말해요.',
    en: 'So we need to change the plan.', ko: '그럼 우리 계획을 바꿔야 해.',
    reply: { speaker: 'Mia', en: "OK. Let's make a new list.", ko: '좋아. 새 목록을 만들자.' },
    alternatives: ['We need a new plan.', 'So we have to change our plan.', "Let's change the plan."],
    level: 2, func: 'changing-plans', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 미아가 간식 가게를 강당 문 옆에 두자고 할 때
  {
    id: 's08-11', episode: 8, order: 11,
    situationKo: '미아가 간식 가게를 강당 문 바로 옆에 두재요. 손님들이 들어오자마자 볼 수 있대요.',
    roleKo: '미아의 제안에 기쁘게 찬성해요.',
    en: "That's a great idea!", ko: '그거 좋은 생각이다!',
    reply: { speaker: 'Mia', en: 'Then everyone will see it!', ko: '그럼 다들 보겠지!' },
    alternatives: ['Good idea!', 'Sounds great!', 'Great idea, Mia!'],
    level: 1, func: 'agreeing', kind: 'review', reviewOf: 's03-06', reuseIn: [],
  },
  {
    id: 's08-10', episode: 8, order: 10,
    situationKo: '목이 아픈 제이미는 노래도 하고 가게도 보기로 했었어요. 너무 무리예요.',
    roleKo: '제이미가 한 가지 일에만 집중하도록 역할을 다시 정해 줘요.',
    en: 'Jamie, you can just do the snacks.', ko: '제이미, 너는 간식만 맡으면 돼.',
    reply: { speaker: 'Jamie', en: 'Deal! Snacks are my thing.', ko: '좋아! 간식은 내 전문이야.' },
    alternatives: ['Jamie, you can do the snacks.', 'You just sell the snacks, Jamie.', 'Jamie, just do the snack stall.'],
    level: 2, func: 'roles', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 9화 드디어 축제 시작 (금요일 20일 오후, 강당) ──
  {
    id: 's09-01', episode: 9, order: 1,
    situationKo: '금요일 오후, 비를 피해 손님들이 강당으로 들어와요. 나는 문 앞을 맡았어요.',
    roleKo: '처음 들어온 손님들을 기분 좋게 맞아요.',
    en: 'Welcome to our festival!', ko: '저희 축제에 오신 걸 환영해요!',
    reply: { speaker: 'Guest', en: 'Thank you! It looks great.', ko: '고마워요! 멋지네요.' },
    alternatives: ['Welcome!', 'Welcome to the festival!', 'Hello! Come on in!'],
    level: 1, func: 'welcoming', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 폴 선생님이 처음 보는 손님을 모시고 왔을 때
  {
    id: 's09-11', episode: 9, order: 11,
    situationKo: '폴 선생님이 다른 학교 선생님을 모시고 왔어요. 나는 처음 보는 분이에요.',
    roleKo: '처음 보는 손님에게 다정하게 첫마디를 건네요.',
    en: 'Hello! Nice to meet you.', ko: '안녕하세요! 만나서 반가워요.',
    reply: { speaker: 'Guest', en: 'Nice to meet you too!', ko: '나도 반갑구나!' },
    alternatives: ['Hi! Nice to meet you.', "Hello! I'm happy to meet you."],
    level: 1, func: 'greeting', kind: 'review', reviewOf: 'hello', reuseIn: [],
  },
  {
    id: 's09-02', episode: 9, order: 2,
    situationKo: '간식 가게 앞에 첫 손님이 섰어요. 차림표를 한참 들여다보고 있어요.',
    roleKo: '손님이 고를 수 있게 주문을 받아요.',
    en: 'What would you like?', ko: '뭐 드릴까요?',
    reply: { speaker: 'Guest', en: 'A lemonade, please.', ko: '레모네이드 하나 주세요.' },
    alternatives: ['What can I get you?', 'Would you like a snack?'],
    level: 1, func: 'ordering', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-03', episode: 9, order: 3,
    situationKo: '손님이 함께 온 아이들 몫까지 레모네이드를 사겠대요. 컵을 꺼내야 해요.',
    roleKo: '컵을 꺼내기 전에 손님께 확인해요.',
    en: 'How many would you like?', ko: '몇 잔 드릴까요?',
    reply: { speaker: 'Guest', en: 'Three, please.', ko: '세 잔 주세요.' },
    alternatives: ['How many do you want?', 'How many lemonades?', 'How many cups?'],
    level: 1, func: 'ordering', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-04', episode: 9, order: 4,
    situationKo: '폴 선생님이 가게 앞을 기웃거려요. 우리 팀이 준비한 팝콘이 아직 많이 남았어요.',
    roleKo: '선생님께 우리 간식을 권해요.',
    en: 'Would you like some popcorn?', ko: '팝콘 좀 드실래요?',
    reply: { speaker: 'Paul', en: 'Yes, please! A small bag.', ko: '응, 좋지! 작은 봉지로.' },
    alternatives: ['Do you want some popcorn?', 'How about some popcorn?', 'Popcorn, Mr Paul?'],
    level: 1, func: 'offering-food', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-05', episode: 9, order: 5,
    situationKo: '손님이 간식 값을 물어요. 가격표가 젖어서 글씨가 번졌어요.',
    roleKo: '번진 가격표 대신 값을 직접 알려 드려요.',
    en: "It's one pound each.", ko: '하나에 1파운드예요.',
    reply: { speaker: 'Guest', en: "Great. Here's three pounds.", ko: '좋아요. 여기 3파운드요.' },
    alternatives: ['One pound each.', "They're one pound each.", "It's a pound each."],
    level: 1, func: 'price', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-06', episode: 9, order: 6,
    situationKo: '레모네이드 세 잔을 쟁반에 담았어요. 손님이 손을 내밀어요.',
    roleKo: '간식을 건네며 기분 좋은 한마디를 덧붙여요.',
    en: 'Here you are. Enjoy!', ko: '여기 있어요. 맛있게 드세요!',
    reply: { speaker: 'Guest', en: 'Thanks! Mmm, lovely.', ko: '고마워요! 음, 맛있네요.' },
    alternatives: ['Here you go!', 'Here you are.', 'Enjoy your snack!'],
    level: 1, func: 'giving', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-07', episode: 9, order: 7,
    situationKo: '한 손님이 급하게 화장실을 찾아요. 아침에 봤어요 — 강당 밖 긴 복도, 왼편 벽 쪽 문이었어요.',
    roleKo: '급한 손님에게 길을 정확하게 알려 드려요.',
    en: 'The toilets are down the corridor on the left.', ko: '화장실은 복도 따라가면 왼쪽에 있어요.',
    reply: { speaker: 'Guest', en: 'Thanks! Back soon.', ko: '고마워요! 금방 올게요.' },
    alternatives: ["They're down the corridor, on the left.", "Go down the corridor. They're on the left.", "It's on the left, down the corridor."],
    level: 3, func: 'directions', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-08', episode: 9, order: 8,
    situationKo: '가게 앞에 손님들이 한꺼번에 몰려와 뒤죽박죽이에요. 바닥에 노란 선이 그어져 있어요.',
    roleKo: '손님들이 차례로 기다리도록 안내해요.',
    en: 'Please queue here.', ko: '여기 줄 서 주세요.',
    reply: { speaker: 'Guest', en: 'Oh, sorry! OK.', ko: '아, 미안해요! 알겠어요.' },
    alternatives: ['Please wait in line here.', 'Can you queue here, please?', 'Line up here, please.'],
    level: 1, func: 'waiting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's09-09', episode: 9, order: 9,
    situationKo: '한 아이가 과자를 달라는데, 지난주 가게에서 산 과자 상자가 텅 비었어요.',
    roleKo: '실망할 아이에게 사정을 솔직하게 알려요.',
    en: "Sorry, we've run out of cookies.", ko: '미안, 쿠키는 다 떨어졌어.',
    reply: { speaker: 'Cookie', en: 'Woof! Woof!', ko: '멍! 멍!' },
    alternatives: ['Sorry, no more cookies.', 'Sorry, the cookies are all gone.', "Sorry, we haven't got any cookies left."],
    level: 2, func: 'informing', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 공연 직전 폴 선생님 옆 의자를 찾을 때
  {
    id: 's09-12', episode: 9, order: 12,
    situationKo: '공연 전에 잠깐 숨을 고르려는데, 폴 선생님 옆 의자에 아무도 없어요.',
    roleKo: '그 의자에 앉을 사람이 있는지 선생님께 확인해요.',
    en: 'Is this seat free?', ko: '이 자리 비어 있어요?',
    reply: { speaker: 'Paul', en: 'Yes! Sit down. Breathe.', ko: '그럼! 앉으렴. 숨 쉬고.' },
    alternatives: ['Is anyone sitting here?', 'Can I sit here?', 'Is this seat taken?'],
    level: 1, func: 'seat', kind: 'review', reviewOf: 's01-04', reuseIn: [],
  },
  {
    id: 's09-10', episode: 9, order: 10,
    situationKo: '무대 담당 선배가 손가락 다섯 개를 펴 보였어요. 미아는 아직 가게에서 팝콘을 담고 있어요.',
    roleKo: '공연 시간이 다가왔다고 미아에게 급히 알려요.',
    en: "We're on in five minutes!", ko: '우리 5분 뒤에 무대야!',
    reply: { speaker: 'Mia', en: "Oh no! Let's go!", ko: '어머! 가자!' },
    alternatives: ['Five minutes to go!', "We're on soon!", 'The show starts in five minutes!'],
    level: 1, func: 'preparing', kind: 'new', reviewOf: null, reuseIn: [],
  },

  // ── 10화 완벽하지 않아도 성공 (금요일 20일, 무대 → 정리) ──
  {
    id: 's10-01', episode: 10, order: 1,
    situationKo: '춤이 한창인데 스피커가 뚝 조용해졌어요. 관객들이 웅성거려요.',
    roleKo: '갑자기 벌어진 일에 놀라 미아에게 소리쳐요.',
    en: 'Oh no, the music stopped!', ko: '아 이런, 음악이 멈췄어!',
    reply: { speaker: 'Mia', en: 'What do we do?!', ko: '어떡해?!' },
    alternatives: ['The music stopped!', "Oh no, there's no music!", 'Oh no, the speaker!'],
    level: 1, func: 'reacting', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-02', episode: 10, order: 2,
    situationKo: '사람들 앞에서 노래하는 건 아직 떨려요. 하지만 지금 우리 곡을 끝까지 아는 사람은 나예요.',
    roleKo: '떨리는 마음을 누르고 내가 나서겠다고 친구들에게 외쳐요.',
    en: "I'll keep singing!", ko: '내가 계속 노래할게!',
    reply: { speaker: 'Mia', en: "Yes! We'll dance!", ko: '좋아! 우린 춤출게!' },
    alternatives: ["I'll sing it!", "Keep going, I'll sing!"],
    level: 1, func: 'encouragement', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-03', episode: 10, order: 3,
    situationKo: '내가 노래를 시작했는데 미아가 멈칫하고 서 있어요. 관객들이 지켜보고 있어요.',
    roleKo: '멈칫한 미아가 다시 움직이도록 응원해요.',
    en: "Come on, Mia! Don't stop!", ko: '힘내, 미아! 멈추지 마!',
    reply: { speaker: 'Mia', en: 'OK! Five, six, seven, eight!', ko: '좋아! 다섯, 여섯, 일곱, 여덟!' },
    alternatives: ['Keep dancing, Mia!', "Don't stop!", "Let's keep going!"],
    level: 1, func: 'encouragement', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-04', episode: 10, order: 4,
    situationKo: '마지막 동작이 끝나자 음악이 다시 나오고 관객들이 박수를 쳐요.',
    roleKo: '끝까지 마친 기쁨을 미아와 함께 외쳐요.',
    en: 'We did it!', ko: '우리가 해냈어!',
    reply: { speaker: 'Mia', en: 'Yes! We really did!', ko: '응! 정말 해냈어!' },
    alternatives: ['We did it, Mia!', 'Yes! We did it!', 'We made it!'],
    level: 1, func: 'celebrating', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-05', episode: 10, order: 5,
    situationKo: '무대에서 내려왔어요. 제이미가 쉰 목소리로 기분이 어땠냐고 물어요.',
    roleKo: '공연을 마친 소감을 제이미에게 들려줘요.',
    en: 'That was so much fun.', ko: '정말 재미있었어.',
    reply: { speaker: 'Jamie', en: 'You were amazing!', ko: '너 정말 멋졌어!' },
    alternatives: ['That was really fun!', 'It was so much fun!', 'That was great!'],
    level: 1, func: 'impressions', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-06', episode: 10, order: 6,
    situationKo: '제이미가 어느 장면이 마음에 남냐고 물어요. 음악이 다시 나오며 미아와 손을 맞잡은 순간이 떠올라요.',
    roleKo: '공연에서 마음에 남은 장면을 제이미에게 알려 줘요.',
    en: 'My favourite part was the ending.', ko: '내가 제일 좋았던 부분은 마지막이야.',
    reply: { speaker: 'Jamie', en: 'Mine too!', ko: '나도 그래!' },
    alternatives: ['I liked the ending best.', 'The ending was the best part.', 'My favourite part was the end.'],
    level: 2, func: 'impressions', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 미아의 마지막 즉흥 동작에 관객이 환호했을 때
  {
    id: 's10-12', episode: 10, order: 12,
    situationKo: '미아가 마지막에 즉흥으로 새 동작을 넣었는데 관객들이 환호했어요.',
    roleKo: '리더 미아의 춤 실력을 진심으로 치켜세워요.',
    en: "You're really good at this!", ko: '너 이거 진짜 잘한다!',
    reply: { speaker: 'Mia', en: 'Thanks! You were brilliant too.', ko: '고마워! 너도 정말 멋졌어.' },
    alternatives: ["You're a great dancer!", "Wow, you're so good!", "You're really good!"],
    level: 1, func: 'praise', kind: 'review', reviewOf: 's04-08', reuseIn: [],
  },
  {
    id: 's10-07', episode: 10, order: 7,
    situationKo: '축제가 끝났어요. 바닥엔 팝콘 부스러기가, 강당엔 펼쳐진 의자가 가득해요.',
    roleKo: '정리할 일을 나눠 맡으려고 내가 할 일을 알려요.',
    en: "I'll fold the chairs.", ko: '의자는 내가 접을게.',
    reply: { speaker: 'Jamie', en: "I'll get the broom!", ko: '빗자루는 내가 가져올게!' },
    alternatives: ["I'll put the chairs away.", 'I can fold the chairs.', 'Let me fold the chairs.'],
    level: 1, func: 'tidying', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-08', episode: 10, order: 8,
    situationKo: '접은 의자는 벽에 세웠어요. 리본과 남은 컵이 든 상자가 하나 남았는데 제자리를 몰라요.',
    roleKo: '상자를 정리하려고 폴 선생님께 물어요.',
    en: 'Where does this box go?', ko: '이 상자는 어디에 둬요?',
    reply: { speaker: 'Paul', en: 'In the cupboard, please.', ko: '창고에 넣어 주렴.' },
    alternatives: ['Where do I put this box?', 'Where should this box go?', 'Where does this go?'],
    level: 1, func: 'tidying', kind: 'new', reviewOf: null, reuseIn: [],
  },
  // 복습: 강당 열쇠를 들고 온 폴 선생님께
  {
    id: 's10-11', episode: 10, order: 11,
    situationKo: '폴 선생님이 강당 열쇠를 들고 왔어요. 돈도, 장소도 선생님이 마련해 주셨죠.',
    roleKo: '축제를 위해 애써 주신 선생님께 내 마음을 전해요.',
    en: 'Thank you so much!', ko: '정말 고맙습니다!',
    reply: { speaker: 'Paul', en: "You're welcome. I'm proud of you.", ko: '천만에. 너희가 자랑스럽구나.' },
    alternatives: ['Thank you, Mr Paul!', 'Thanks a lot!', 'Thank you for everything!'],
    level: 1, func: 'thanking', kind: 'review', reviewOf: 'thanks', reuseIn: [],
  },
  {
    id: 's10-09', episode: 10, order: 9,
    situationKo: '정리를 마치고 셋이 강당 계단에 앉았어요. 전학 첫날 빈자리에서 만난 두 친구예요.',
    roleKo: '그날부터 곁에 있어 준 두 친구에게 내 마음을 전해요.',
    en: 'Thanks for being such good friends.', ko: '이렇게 좋은 친구가 되어 줘서 고마워.',
    reply: { speaker: 'Jamie', en: 'Aww. Group hug!', ko: '아이고. 다 같이 안아!' },
    alternatives: ['Thank you for being my friends.', "Thanks, you're the best friends.", "You're great friends. Thank you!"],
    level: 2, func: 'thanking', kind: 'new', reviewOf: null, reuseIn: [],
  },
  {
    id: 's10-10', episode: 10, order: 10,
    situationKo: '미아가 오늘이 끝이라 아쉽대요. 목에 금색 리본을 단 쿠키가 꼬리를 흔들어요.',
    roleKo: '다음 축제에도 이 팀으로 함께하자고 약속해요.',
    en: "Let's do it again next year!", ko: '내년에 또 하자!',
    reply: { speaker: 'Mia', en: 'Yes! Spoon Stars forever!', ko: '좋아! 스푼 스타즈 영원히!' },
    alternatives: ["Let's do this again next year!", "Let's be a team again next year!", 'Same team next year!'],
    level: 2, func: 'promise', kind: 'new', reviewOf: null, reuseIn: [],
  },
]
