// scripts/testLegacyRewardServer.mjs
//
// Reward System V1 — 레거시 클라이언트 6종 별 지급 경로(2026-09-06) 서버
// 흡수 검증. scripts/testRewardServerHardeningBehavior.mjs / testTownShopServer.mjs
// 와 같은 하네스 패턴을 그대로 재사용한다: esbuild로 api/grant-xp.js를
// 번들하되 @supabase/supabase-js와 ./_pinAuth.js만 인메모리 가짜로 치환한다.
// 핸들러 코드 자체는 한 글자도 바꾸지 않고 그대로 실행된다("테스트를 위해
// production 코드를 고치지 않는다"는 원칙, 위 두 파일과 동일).
//
// 검증 대상(운영자 지정, 이 세션 범위):
//   pronunciation / mission-clear / daily-mission-bonus / spelling-combo /
//   sticker-duplicate / matchgame — 6종 각각의 정상 지급, 중복 재생,
//   금액 위조 무시, invalid sourceId 거부, 일일 상한, 그리고 기존
//   word-session-complete(V1 앵커)/XP 경로 무회귀.
//
// 산출물: scripts/.tmp/(gitignore) — fakeSupabaseForLegacyReward.mjs /
// fakePinAuthLegacy.mjs / grantXp.legacy.bundle.mjs (다른 하네스가 쓰는
// 파일명과 충돌하지 않는 이 파일 전용 이름).
//
// 등록: tests/harness/registry.mjs에 올리는 작업은 이 세션 책임 밖(다른
// 에이전트/사람이 소유) — 여기서는 직접 실행만.
//   node scripts/testLegacyRewardServer.mjs
//
// 네트워크 0, production 요청 0, DB 무접촉.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

// ── 가짜 Supabase — testRewardServerHardeningBehavior.mjs와 동일한 체이닝
// 구현(파일명만 이 테스트 전용으로 분리) ──────────────────────────────────
const fakePath = path.join(TMP, 'fakeSupabaseForLegacyReward.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testLegacyRewardServer.mjs
export const __db = { students: [], entrance_test_results: [], reward_ledger: [], xp_ledger: [] }
export const __fail = { students: null, entrance_test_results: null, reward_ledger: null }
export const __failOp = { maybeSingle: null, count: null }
export const __calls = []
export function __reset() {
  __db.students = []; __db.entrance_test_results = []; __db.reward_ledger = []; __db.xp_ledger = []
  __fail.students = null; __fail.entrance_test_results = null; __fail.reward_ledger = null
  __failOp.maybeSingle = null; __failOp.count = null
  __calls.length = 0
}
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    match(rows) {
      return rows.filter(r => filters.every(([c, v]) => {
        if (c.startsWith('__gte__')) return String(r[c.slice(7)]) >= String(v)
        return String(r[c]) === String(v)
      }))
    },
    maybeSingle() {
      __calls.push({ table, op: 'maybeSingle', filters: [...filters] })
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      if (table === 'reward_ledger' && __failOp.maybeSingle) return Promise.resolve({ data: null, error: __failOp.maybeSingle })
      const hit = q.match(__db[table] || [])
      return Promise.resolve({ data: hit[0] || null, error: null })
    },
    then(resolve) {
      __calls.push({ table, op: headCount ? 'count' : 'select', filters: [...filters] })
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      if (table === 'reward_ledger' && headCount && __failOp.count) return resolve({ data: null, count: null, error: __failOp.count })
      const hit = q.match(__db[table] || [])
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}
export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          __calls.push({ table, op: 'insert', row })
          if (__fail[table]) return Promise.resolve({ error: __fail[table] })
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some(r => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const outfile = path.join(TMP, 'grantXp.legacy.bundle.mjs')
const fakePinAuthPath = path.join(TMP, 'fakePinAuthLegacy.mjs')
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')

await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-legacy',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: pathToFileURL(fakePinAuthPath).href, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default
const {
  REWARD_STARS, REWARD_DAILY_CAP, rewardIdempotencyKey,
} = await import('../src/utils/rewardEngine.js')

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

process.env.SESSION_SECRET = 'legacy-reward-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

const STUDENT = '11111111-2222-4333-8444-555555555555'
const today = new Date().toDateString()

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
const tokenFor = (sid) => signSessionToken(sid)
const post = (body) => {
  const withAuth = (body && body.ledger === 'reward' && body.token === undefined && body.studentId)
    ? { ...body, token: tokenFor(body.studentId) }
    : body
  const r = res(); return handler({ method: 'POST', body: withAuth, headers: {} }, r).then(() => r)
}
function seed() {
  fake.__reset()
  fake.__db.students.push({ id: STUDENT })
}
const ledger = () => fake.__db.reward_ledger

// ── 1) 6종 각각 정상 지급 + idempotency_key 형식 + 재생(duplicate) ────────
console.log('\n1. 레거시 6종 — 정상 지급 + 서버 조립 idempotency_key + 재생')
{
  const cases = [
    {
      label: 'pronunciation', rewardType: 'pronunciation', sourceType: 'pronunciation',
      sourceId: `word-a1:${today}`, expectedStars: 1,
    },
    {
      label: 'mission-clear', rewardType: 'mission-clear', sourceType: 'mission',
      sourceId: 'word-b2', expectedStars: 3,
    },
    {
      label: 'daily-mission-bonus', rewardType: 'daily-mission-bonus', sourceType: 'daily-round',
      sourceId: `${today}:worda,wordb,wordc`, expectedStars: 10,
    },
    {
      label: 'spelling-combo(5)', rewardType: 'spelling-combo', sourceType: 'spelling-combo',
      sourceId: `word-c3:5:${today}`, expectedStars: 2,
    },
    {
      label: 'sticker-duplicate(milestone)', rewardType: 'sticker-duplicate', sourceType: 'gift',
      sourceId: `sticker-owl:milestone:7`, expectedStars: 20,
    },
    {
      label: 'matchgame', rewardType: 'matchgame', sourceType: 'matchgame',
      sourceId: `1735689600000_a1b2c3:0:word-d4`, expectedStars: 4,
    },
  ]

  for (const c of cases) {
    seed()
    const first = await post({ ledger: 'reward', studentId: STUDENT, rewardType: c.rewardType, sourceType: c.sourceType, sourceId: c.sourceId })
    check(`${c.label} — 정상 지급 ok:true (응답 ${JSON.stringify(first.body)})`, first.body?.ok === true && first.body?.duplicate === false)
    check(`${c.label} — 금액 ${c.expectedStars}별(REWARD_STARS와 일치)`, first.body?.stars === c.expectedStars)
    check(`${c.label} — 원장 1건`, ledger().length === 1)
    const expectedKey = rewardIdempotencyKey(STUDENT, c.rewardType, c.sourceType, c.sourceId)
    check(`${c.label} — idempotency_key === ${'${sid}:${type}:${sourceType}:${sourceId}'}`, ledger()[0]?.idempotency_key === expectedKey)
    check(`${c.label} — 원장 stars_delta도 ${c.expectedStars}`, ledger()[0]?.stars_delta === c.expectedStars)

    // 같은 요청 재생 -> duplicate:true, 원장은 여전히 1건.
    const second = await post({ ledger: 'reward', studentId: STUDENT, rewardType: c.rewardType, sourceType: c.sourceType, sourceId: c.sourceId })
    check(`${c.label} — 재생(replay) -> ok:true duplicate:true`, second.body?.ok === true && second.body?.duplicate === true)
    check(`${c.label} — 재생 후에도 원장 1건`, ledger().length === 1)
  }
}

// ── 2) req.body.stars=999 무시 ────────────────────────────────────────────
console.log('\n2. 레거시 6종 — req.body.stars 위조 무시(서버가 항상 REWARD_STARS로 결정)')
{
  seed()
  const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'mission-clear', sourceType: 'mission', sourceId: 'word-forge', stars: 999 })
  check('stars:999을 실어도 서버 금액(3)만 지급', r.body?.ok === true && r.body?.stars === 3)
  check('원장에도 999 아닌 3', ledger()[0]?.stars_delta === 3)
}

// ── 3) invalid sourceId 변형들 -> invalid_reward_source ──────────────────
console.log('\n3. 레거시 6종 — invalid sourceId 변형 거부(invalid_reward_source)')
{
  const invalidCases = [
    ['pronunciation 날짜 없음', 'pronunciation', 'pronunciation', 'word-a1'],
    ['pronunciation 날짜 형식 위조', 'pronunciation', 'pronunciation', 'word-a1:2026-08-15'],
    ['mission-clear 콜론 주입', 'mission-clear', 'mission', 'word-b2:extra'],
    ['daily-mission-bonus 날짜 형식 위조', 'daily-mission-bonus', 'daily-round', '2026-08-15:worda,wordb'],
    ['daily-mission-bonus tokens에 콜론 주입', 'daily-mission-bonus', 'daily-round', `${today}:worda:wordb`],
    ['spelling-combo 콤보 4(마일스톤 아님)', 'spelling-combo', 'spelling-combo', `word-c3:4:${today}`],
    ['spelling-combo 날짜 형식 위조', 'spelling-combo', 'spelling-combo', `word-c3:5:2026-08-15`],
    ['sticker-duplicate 알 수 없는 gift 프리픽스', 'sticker-duplicate', 'gift', 'sticker-owl:unknown:1'],
    ['sticker-duplicate stickerId 콜론 주입', 'sticker-duplicate', 'gift', 'sticker:owl:milestone:7'],
    ['matchgame round 100(> 99)', 'matchgame', 'matchgame', '1735689600000_a1b2c3:100:word-d4'],
    ['matchgame sessionId 형식 위조', 'matchgame', 'matchgame', 'not-a-session:0:word-d4'],
    ['matchgame wordToken 콜론 주입(파트 4개)', 'matchgame', 'matchgame', '1735689600000_a1b2c3:0:bad:token'],
  ]
  for (const [label, rewardType, sourceType, sourceId] of invalidCases) {
    seed()
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType, sourceType, sourceId })
    check(`${label} -> invalid_reward_source`, r.body?.ok === false && r.body?.reason === 'invalid_reward_source')
    check(`${label} -> 원장 0건`, ledger().length === 0)
  }
}

// ── 4) 일일 상한 — 레거시 6종 각각 ────────────────────────────────────────
console.log('\n4. 레거시 6종 — 일일 상한(REWARD_DAILY_CAP) 도달 시 거부')
{
  async function testDailyCap(label, rewardType, sourceType, sourceIdGen, cap) {
    seed()
    let ok = 0, capped = 0
    const extra = 3
    for (let i = 0; i < cap + extra; i++) {
      const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType, sourceType, sourceId: sourceIdGen(i) })
      if (r.body?.ok === true) ok++
      else if (r.body?.reason === 'daily_cap_reached') capped++
    }
    check(`${label} — 상한 ${cap}건까지만 지급 (실제 ${ok})`, ok === cap)
    check(`${label} — 초과분 ${extra}건 daily_cap_reached (실제 ${capped})`, capped === extra)
    check(`${label} — 원장 ${cap}건(무제한 아님)`, ledger().length === cap)
  }

  await testDailyCap('pronunciation', 'pronunciation', 'pronunciation', (i) => `word-p${i}:${today}`, REWARD_DAILY_CAP['pronunciation'])
  await testDailyCap('mission-clear', 'mission-clear', 'mission', (i) => `word-m${i}`, REWARD_DAILY_CAP['mission-clear'])
  await testDailyCap('daily-mission-bonus', 'daily-mission-bonus', 'daily-round', (i) => `${today}:worda${i},wordb${i}`, REWARD_DAILY_CAP['daily-mission-bonus'])
  await testDailyCap('spelling-combo', 'spelling-combo', 'spelling-combo', (i) => `word-s${i}:5:${today}`, REWARD_DAILY_CAP['spelling-combo'])
  await testDailyCap('sticker-duplicate', 'sticker-duplicate', 'gift', (i) => `sticker-${i}:milestone:${(i % 9) + 1}`, REWARD_DAILY_CAP['sticker-duplicate'])

  // matchgame — 운영자 지정 문구대로 "6번째 지급 -> daily_cap_reached"를
  // 명시적으로도 확인(cap=5이므로 6번째가 정확히 첫 초과분).
  {
    seed()
    const cap = REWARD_DAILY_CAP['matchgame']
    check('matchgame 상한이 5로 고정됨(구조적 상한 전제 확인)', cap === 5)
    const results = []
    for (let i = 0; i < 6; i++) {
      results.push(await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'matchgame', sourceType: 'matchgame', sourceId: `1735689600000_a1b2c3:${i}:word-d4` }))
    }
    check('matchgame — 1~5번째 지급 성공', results.slice(0, 5).every(r => r.body?.ok === true))
    check('matchgame — 6번째 grant -> daily_cap_reached', results[5]?.body?.ok === false && results[5]?.body?.reason === 'daily_cap_reached')
    check('matchgame — 원장 5건(6번째 미기록)', ledger().length === 5)
  }
}

// ── 5) 알 수 없는 rewardType(pronunciation-unidentified) -> unknown_reward_type ──
console.log('\n5. pronunciation-unidentified — 서버화 대상 아님(rewardType 자체가 화이트리스트에 없음)')
{
  seed()
  const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'pronunciation-unidentified', sourceType: 'pronunciation', sourceId: `x:${today}` })
  check("rewardType 'pronunciation-unidentified' -> unknown_reward_type", r.body?.ok === false && r.body?.reason === 'unknown_reward_type')
  check('원장 0건', ledger().length === 0)
}

// ── 6) V1 word-session-complete 무회귀 ────────────────────────────────────
console.log('\n6. V1 word-session-complete — 레거시 6종 추가 후에도 무회귀')
{
  seed()
  const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'word-session-complete', sourceType: 'daily-words', sourceId: today })
  check('word-session-complete 정상 지급(무회귀)', r.body?.ok === true && r.body?.duplicate === false)
  check('금액 1별(REWARD_STARS 무변경)', r.body?.stars === 1 && r.body?.stars === REWARD_STARS['word-session-complete'])
  check('원장 1건', ledger().length === 1)
}

// ── 7) 기존 XP 경로 무회귀 ─────────────────────────────────────────────────
console.log('\n7. XP 경로(ledger 필드 없는 요청) — 레거시 6종 추가 후에도 무회귀')
{
  seed()
  const r = await post({ studentId: STUDENT, eventType: 'word-view-complete', sourceEventId: `word-view-complete:${new Date().toISOString().slice(0, 10)}` })
  check('XP 경로 응답이 reward 전용 사유가 아님(XP 분기로 흘러감)', r.body?.reason !== 'student_not_found' && r.body?.reason !== 'daily_cap_reached' && r.body?.reason !== 'invalid_reward_source')
  check('reward_ledger에는 기록되지 않음', fake.__db.reward_ledger.length === 0)
}

// ── 8) WORD_SLUG_TOKEN_RE(2026-09-06 커버리지 수정) — 실제 wordSlug 형식
// 종단 지급 검증. wordId 자리는 실제로 uuid가 아니라 wordSlug(word) =
// word.toLowerCase().replace(/\s+/g,'_')(wordLibrary.js:3588)라, production
// 1,975개 단어 중 27개(1.4%)가 예전 WORD_TOKEN_RE에서 거부됐다(아포스트로피/
// 괄호/물결/한글 등). mission-clear/spelling-combo/wrong-word-recovered
// 세 위치가 이제 이 슬러그를 실제로 지급까지 완주하는지 서버 핸들러로
// 확인한다(rewardEngine.js 단위 테스트는 isValidRewardSource만 보므로,
// 여기서는 grant-xp.js 전체 경로 — 인증/실재검증/상한/insert — 를 통과하는지
// 까지 확인).
console.log('\n8. WORD_SLUG_TOKEN_RE 커버리지 수정 — 실제 wordSlug(아포스트로피/괄호/물결/한글) 종단 지급')
{
  const SLUGS = ["do_one's_best", 'practice_(noun)', 'just_as_~_as', '어휘']

  for (const slug of SLUGS) {
    seed()
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'mission-clear', sourceType: 'mission', sourceId: slug })
    check(`mission-clear(${slug}) — 정상 지급`, r.body?.ok === true && r.body?.duplicate === false && r.body?.stars === 3)
    check(`mission-clear(${slug}) — 원장 1건, stars_delta 3`, ledger().length === 1 && ledger()[0]?.stars_delta === 3)
  }

  for (const slug of SLUGS) {
    seed()
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'spelling-combo', sourceType: 'spelling-combo', sourceId: `${slug}:10:${today}` })
    check(`spelling-combo(${slug}) — 정상 지급(combo=10 -> +3)`, r.body?.ok === true && r.body?.duplicate === false && r.body?.stars === 3)
    check(`spelling-combo(${slug}) — 원장 1건`, ledger().length === 1)
  }

  // wrong-word-recovered(V1 기존 앵커, 2026-09-06 이전부터 이미 존재) —
  // 이 커버리지 수정 전에는 이 타입이 이미 production에서 슬러그 27개를
  // 거부하고 있었다(구조 자체는 기존 것, 정규식만 넓어짐).
  for (const slug of SLUGS) {
    seed()
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'wrong-word-recovered', sourceType: 'spelling-review', sourceId: `${today}:${slug}` })
    check(`wrong-word-recovered(${slug}) — 정상 지급(무회귀 + 커버리지 확장)`, r.body?.ok === true && r.body?.duplicate === false && r.body?.stars === 1)
    check(`wrong-word-recovered(${slug}) — 원장 1건`, ledger().length === 1)
  }

  // 콜론 주입/공백 포함 슬러그는 여전히 거부 — 확장이 신뢰 경계를 넓히지
  // 않았음을 종단(end-to-end)으로 재확인.
  seed()
  const badColon = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'mission-clear', sourceType: 'mission', sourceId: 'word:evil' })
  check("mission-clear — 콜론 주입 슬러그는 여전히 invalid_reward_source", badColon.body?.ok === false && badColon.body?.reason === 'invalid_reward_source')
  check('콜론 주입 시도 -> 원장 0건', ledger().length === 0)

  seed()
  const badSpace = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'wrong-word-recovered', sourceType: 'spelling-review', sourceId: `${today}:do one's best` })
  check("wrong-word-recovered — 공백 포함 슬러그는 여전히 invalid_reward_source", badSpace.body?.ok === false && badSpace.body?.reason === 'invalid_reward_source')
  check('공백 포함 시도 -> 원장 0건', ledger().length === 0)
}

// ── 9) TOKENS_LIST_RE(2026-09-06 리뷰 지적 수정) — daily-mission-bonus/
// sticker-duplicate(round:) 종단 지급 검증. 리뷰 발견: 이 두 위치의 tokens
// (콤마로 이어붙인 wordSlug 목록, useStudent.js round.wordsViewed 정렬 join)
// 도 uuid가 아니라 wordSlug라, 같은 27/1,975 슬러그가 여기서도 걸려
// daily-mission-bonus(+10)/sticker-duplicate round(+20)가 조용히 서버에
// 도달하지 못했다(전체 라운드의 ~6~7%, 단어 5개 중 하나라도 걸리면 전체
// tokens 문자열이 거부됨). 수정 후 실제로 끝까지 지급되는지 확인한다.
console.log('\n9. TOKENS_LIST_RE 커버리지 수정 — daily-mission-bonus/sticker-duplicate(round:) 종단 지급')
{
  const tokensWithSlug = `apple,banana,cherry,date_fruit,do_one's_best`

  seed()
  {
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'daily-mission-bonus', sourceType: 'daily-round', sourceId: `${today}:${tokensWithSlug}` })
    check("daily-mission-bonus(tokens에 do_one's_best 포함) — 정상 지급", r.body?.ok === true && r.body?.duplicate === false && r.body?.stars === 10)
    check('daily-mission-bonus — 원장 1건', ledger().length === 1)
  }

  seed()
  {
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'sticker-duplicate', sourceType: 'gift', sourceId: `sticker-fox:round:${today}:${tokensWithSlug}` })
    check("sticker-duplicate(round:, tokens에 do_one's_best 포함) — 정상 지급", r.body?.ok === true && r.body?.duplicate === false && r.body?.stars === 20)
    check('sticker-duplicate(round:) — 원장 1건', ledger().length === 1)
  }

  // 확장이 신뢰 경계를 넓히지 않았음을 종단으로 재확인 — tokens에 ':' 주입.
  seed()
  {
    const r = await post({ ledger: 'reward', studentId: STUDENT, rewardType: 'daily-mission-bonus', sourceType: 'daily-round', sourceId: `${today}:apple,ba:d` })
    check("daily-mission-bonus — tokens ':' 주입은 여전히 invalid_reward_source", r.body?.ok === false && r.body?.reason === 'invalid_reward_source')
    check("':' 주입 시도 -> 원장 0건", ledger().length === 0)
  }
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '모든 단언 통과 — 레거시 6종 서버 흡수 검증 ✅'
  : `${failures}개 단언 실패 ❌`)
process.exit(failures === 0 ? 0 : 1)
