// scripts/testRewardRetryExactlyOneRow.mjs
//
// QA 감사(2026-09-10, qa/reward-audit-2026-09-10) — "클라이언트 재시도 큐
// ⇒ 서버 원장에 정확히 1행"을 end-to-end로 고정한다. 지금까지 등록된
// 테스트는 이 조합을 각자 절반씩만 다뤘다:
//   · scripts/testRewardPostQueue.mjs — 큐 정책(enqueue/attempts/제거)을
//     가짜 fetch 응답(jsonResponse 리터럴)으로만 검증. 실제 api/grant-xp.js
//     핸들러는 한 번도 구동하지 않는다.
//   · scripts/testRewardServerHardeningBehavior.mjs /
//     scripts/testRewardCapRace.mjs — 실제 핸들러를 인메모리 가짜 Supabase
//     위에서 구동하지만, 호출부는 이 테스트 파일의 `post()` 헬퍼(큐 없음,
//     매번 즉시 fetch)다. wordLibrary.js의 재시도 큐(sendRewardPostOnce/
//     postRewardEvent/flushRewardPostQueue)는 관여하지 않는다.
// 즉 "클라이언트가 실패를 재시도 큐에 쌓았다가, 나중에 flush했을 때 서버
// 원장에 중복 없이 딱 1건만 남는가"라는 실제 운영 시나리오(네트워크 순단,
// 서버 500, 재로그인 사이 재시도)는 어느 등록 테스트도 끝까지 잇지
// 않았다 — 이 파일이 그 공백을 메운다.
//
// 하네스 = 두 기존 파일의 패턴을 그대로 합성(재구현 없음, CLAUDE.md 규칙 3):
//   1) src/utils/wordLibrary.js를 esbuild로 무수정 번들(testRewardPostQueue.mjs
//      와 동일한 방식 — .env VITE_SUPABASE_* 치환, 페이크 localStorage/fetch).
//   2) api/grant-xp.js를 esbuild로 무수정 번들하되 @supabase/supabase-js만
//      이 파일 전용 인메모리 가짜로 치환(testRewardServerHardeningBehavior.mjs/
//      testRewardCapRace.mjs와 동일 방식). api/_pinAuth.js는 실제
//      signSessionToken/verifySessionToken을 그대로 재사용(스텁은 URL/KEY
//      상수만 대체).
//   3) 이 파일의 globalThis.fetch(wordLibrary.js가 부르는 유일한 네트워크
//      진입점)를 "실제 HTTP를 전혀 만들지 않고" 바로 위 handler(req,res)를
//      직접 호출하는 브리지로 교체한다 — 이 브리지 자체가 유일한 신규
//      로직이고, 큐 정책도 서버 검증 로직도 재구현하지 않는다(둘 다 실제
//      소스를 그대로 구동).
//
// 산출물은 이 파일 전용 이름(scripts/.tmp/*RetryExactlyOneRow*)을 써서 다른
// 테스트의 산출물과 충돌하지 않는다(CLAUDE.md 규칙 16).
//
// 등록: npm run verify:reward-retry-exactly-one (rewardSystem 그룹, extra:false)
// 네트워크 0, production 요청 0, 실제 Supabase 접촉 0.

import esbuild from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let failures = 0
let asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

// ── 1) wordLibrary.js 번들 (testRewardPostQueue.mjs와 동일 방식) ────────
const env = fs.readFileSync('.env', 'utf8')
const supaUrl = (env.match(/VITE_SUPABASE_URL=(.*)/) || [, 'https://example.invalid'])[1].trim()
const supaKey = (env.match(/VITE_SUPABASE_ANON_KEY=(.*)/) || [, 'test-anon-key'])[1].trim()

const wordLibOutfile = path.join(TMP, 'wordLibrary.retryExactlyOneRow.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/utils/wordLibrary.js'],
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile: wordLibOutfile,
  define: {
    'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(supaUrl),
    'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify(supaKey),
  },
})

// ── 2) 이 파일 전용 인메모리 가짜 Supabase + api/grant-xp.js 번들
//    (testRewardServerHardeningBehavior.mjs 패턴 재사용, 독립 산출물) ─────
const fakeDbPath = path.join(TMP, 'fakeSupabaseForRetryExactlyOneRow.mjs')
fs.writeFileSync(fakeDbPath, `// AUTO-GENERATED by scripts/testRewardRetryExactlyOneRow.mjs
export const __db = { students: [], entrance_test_results: [], reward_ledger: [] }
// __fail[table] — 그 테이블의 select 계열(maybeSingle/count) 쿼리를 실패시킨다
// (insert에는 영향 없음 — 아래 makeQuery.then/maybeSingle에서만 참조).
export const __fail = { students: null, entrance_test_results: null, reward_ledger: null }
// __forceInsertError — insert()만 특정 실패로 강제한다. select 계열과 완전히
// 분리된 훅이라(실제 운영 시나리오인 "L1~L3는 전부 통과했지만 최종 insert가
// 알 수 없는 이유로 실패해 HTTP 500이 난다"를 select 단계 오염 없이 재현할
// 수 있다 — testRewardServerHardeningBehavior.mjs의 공유 __fail[table]은
// select/insert를 구분하지 못해 이 시나리오를 못 만든다).
export let __forceInsertError = null
export function __setForceInsertError(v) { __forceInsertError = v }
export function __reset() {
  __db.students = []; __db.entrance_test_results = []; __db.reward_ledger = []
  __fail.students = null; __fail.entrance_test_results = null; __fail.reward_ledger = null
  __forceInsertError = null
}
function matchRow(row, filters) {
  return filters.every(([c, v]) => {
    if (c.startsWith('__gte__')) return String(row[c.slice(7)]) >= String(v)
    return String(row[c]) === String(v)
  })
}
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    maybeSingle() {
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      const rows = __db[table] || []
      const hit = rows.find((r) => matchRow(r, filters))
      return Promise.resolve({ data: hit || null, error: null })
    },
    then(resolve) {
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      const rows = __db[table] || []
      const hit = rows.filter((r) => matchRow(r, filters))
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}
export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          if (__forceInsertError && __forceInsertError.table === table) {
            return Promise.resolve({ error: __forceInsertError.error })
          }
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
  }
}
`, 'utf8')
const fakeDbUrl = pathToFileURL(fakeDbPath).href

const fakePinAuthPath = path.join(TMP, 'fakePinAuthForRetryExactlyOneRow.mjs')
const realPinAuthUrl = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuthUrl)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const grantXpOutfile = path.join(TMP, 'grantXp.retryExactlyOneRow.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile: grantXpOutfile,
  plugins: [{
    name: 'fake-supabase-retry-exactly-one-row',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeDbUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

// ── 3) 페이크 localStorage/window + fetch 브리지(신규 로직은 이것뿐) ─────
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
globalThis.localStorage = new FakeStorage()
globalThis.window = globalThis.window || { addEventListener() {}, removeEventListener() {} }

process.env.SESSION_SECRET = 'retry-exactly-one-row-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')
const fakeDb = await import(fakeDbUrl)
const handler = (await import(pathToFileURL(grantXpOutfile).href)).default

function makeRes() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
// "실제 핸들러로 직접 호출" 브리지 — HTTP를 전혀 만들지 않는다(네트워크 0).
// wordLibrary.js가 만드는 fetch(url, opts) 시그니처 그대로 받아 opts.body
// (JSON 문자열)를 파싱해 handler(req,res)에 그대로 넘긴다. res.ok는 실제
// grant-xp.js가 쓰는 관례(성공/거부 모두 200, 진짜 서버 오류만 500/405)를
// 그대로 반영해 code<400이면 true.
async function bridgeToRealHandler(url, opts) {
  const body = JSON.parse(opts.body)
  const req = { method: (opts && opts.method) || 'POST', body, headers: {} }
  const r = makeRes()
  await handler(req, r)
  return { ok: typeof r.code === 'number' && r.code < 400, json: async () => r.body }
}
// 강제 네트워크 실패(reject) 브리지 — "핸들러에 아예 도달하지 못한" 순수
// 네트워크 순단을 재현(연결 자체가 안 됨, 서버는 아무 것도 못 봄).
async function bridgeNetworkReject() {
  throw new Error('시뮬레이션 — 네트워크 순단(핸들러 미도달)')
}
// 강제 HTTP 500 브리지 — 핸들러가 실제로 실행돼 처리를 시도했지만(원장
// insert까지 도달) 알 수 없는 이유로 실패해 res.status(500)을 반환하는
// 경우. __forceInsertError 훅으로 이 경로만 정확히 트리거한다(위 fakeDb
// 헤더 주석 참고) — 핸들러 코드 자체는 무수정.
async function bridgeForcedHttp500(url, opts) {
  const body = JSON.parse(opts.body)
  const req = { method: 'POST', body, headers: {} }
  const r = makeRes()
  await handler(req, r)
  return { ok: typeof r.code === 'number' && r.code < 400, json: async () => r.body }
}

let fetchImpl = async () => { throw new Error('네트워크 금지 — fetchImpl 미설정') }
globalThis.fetch = (...args) => fetchImpl(...args)

const lib = await import(pathToFileURL(wordLibOutfile).href)
const {
  postRewardEvent, flushRewardPostQueue, setSessionToken,
  __rewardPostQueueForTest, __resetRewardPostQueueForTest, holdRewardPosts,
} = lib

function resetAll() {
  __resetRewardPostQueueForTest()
  setSessionToken(null)
  holdRewardPosts(false)
  fakeDb.__reset()
  fetchImpl = async () => { throw new Error('네트워크 금지 — fetchImpl 미설정') }
}
const flush = () => new Promise((r) => setImmediate(r))

const STUDENT = '11111111-2222-4333-8444-555555555555'
const TEST_ID = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'
const today = new Date().toDateString()
const tokenFor = (sid) => signSessionToken(sid)

console.log('=== Reward 재시도 큐 ⇒ 서버 원장 정확히 1행 (실제 핸들러 e2e, 네트워크 0) ===')

console.log('\n1. 네트워크 순단(reject) 후 flush 성공 -> 서버 원장 정확히 1행, 3번째(replay) 호출도 여전히 1행')
{
  resetAll()
  fakeDb.__db.students.push({ id: STUDENT })
  fakeDb.__db.entrance_test_results.push({ test_id: TEST_ID, student_id: STUDENT })
  setSessionToken(tokenFor(STUDENT)) // 큐가 비어있는 시점이라 이 setSessionToken의 flush는 no-op

  // 시도 1 — 네트워크 순단(reject). postRewardEvent는 fire-and-forget이라
  // 이 호출 자체는 절대 throw하지 않는다(await 통과 확인 포함).
  fetchImpl = bridgeNetworkReject
  await postRewardEvent(STUDENT, 'exam-complete', 'entrance-test', TEST_ID)
  check('시도 1(네트워크 순단) 후 원장 0행(아직 서버에 도달 못 함)', fakeDb.__db.reward_ledger.length === 0)
  const qAfterAttempt1 = __rewardPostQueueForTest()
  check('시도 1 실패 후 큐에 1건 유지', qAfterAttempt1.length === 1)
  check('attempts === 1', qAfterAttempt1[0] && qAfterAttempt1[0].attempts === 1)

  // 시도 2(flush) — 실제 handler(가짜 DB)로 전달 -> 성공.
  fetchImpl = bridgeToRealHandler
  await flushRewardPostQueue()
  check('flush 후 원장 정확히 1행', fakeDb.__db.reward_ledger.length === 1)
  check('stars_delta === 2(exam-complete)', fakeDb.__db.reward_ledger[0]?.stars_delta === 2)
  check('idempotency_key가 서버 조립값 형태(studentId 포함)', String(fakeDb.__db.reward_ledger[0]?.idempotency_key || '').includes(STUDENT))
  check('flush 후 큐 비어있음', __rewardPostQueueForTest().length === 0)

  // 시도 3 — "리로드 후 재생"(같은 이벤트가 클라이언트 쪽에서 한 번 더
  // 트리거됐다고 가정 — 예: 화면 재마운트로 grantLedgerReward가 다시
  // postRewardEvent를 부름). 서버는 idempotency_key로 이미 지급된 걸 알고
  // duplicate:true로 응답해야 하고, 원장은 여전히 1행이어야 한다.
  await postRewardEvent(STUDENT, 'exam-complete', 'entrance-test', TEST_ID)
  check('3번째(replay) 호출 후에도 원장 정확히 1행(중복 삽입 없음)', fakeDb.__db.reward_ledger.length === 1)
  check('3번째 호출도 성공 처리되어 큐에서 제거됨(duplicate:true는 정의상 removeFromQueue:true)', __rewardPostQueueForTest().length === 0)
}

console.log('\n2. 대조군 — HTTP 500(핸들러는 실행됐으나 insert가 알 수 없는 이유로 실패) 후 flush 성공 -> 원장 정확히 1행')
{
  resetAll()
  fakeDb.__db.students.push({ id: STUDENT })
  setSessionToken(tokenFor(STUDENT))

  const sourceId = `${today}:retry_500_word`
  // 시도 1 — 핸들러는 L1~L3를 전부 통과하지만 최종 insert가 강제로
  // 알 수 없는 오류(코드 미상)를 반환 -> 핸들러가 res.status(500) 응답.
  fakeDb.__setForceInsertError({ table: 'reward_ledger', error: { code: 'XX999', message: 'boom' } })
  fetchImpl = bridgeForcedHttp500
  await postRewardEvent(STUDENT, 'wrong-word-recovered', 'spelling-review', sourceId)
  check('HTTP 500 시도 1 후 원장 0행', fakeDb.__db.reward_ledger.length === 0)
  const qAfter500 = __rewardPostQueueForTest()
  check('HTTP 500 후에도 큐에 1건 유지(재시도 대상)', qAfter500.length === 1)
  check('attempts === 1', qAfter500[0] && qAfter500[0].attempts === 1)

  // 시도 2(flush) — insert 강제 실패 해제, 실제 handler로 성공.
  fakeDb.__setForceInsertError(null)
  fetchImpl = bridgeToRealHandler
  await flushRewardPostQueue()
  check('flush 후 원장 정확히 1행(HTTP 500 케이스도 네트워크 순단과 동일한 최종 결과)', fakeDb.__db.reward_ledger.length === 1)
  check('stars_delta === 1(wrong-word-recovered)', fakeDb.__db.reward_ledger[0]?.stars_delta === 1)
  check('flush 후 큐 비어있음', __rewardPostQueueForTest().length === 0)

  // 3번째 호출(replay) — 여전히 1행.
  await postRewardEvent(STUDENT, 'wrong-word-recovered', 'spelling-review', sourceId)
  check('3번째(replay) 호출 후에도 원장 정확히 1행', fakeDb.__db.reward_ledger.length === 1)
  check('3번째 호출 후 큐 비어있음', __rewardPostQueueForTest().length === 0)
}

console.log('\n3. "재로드로 큐를 다시 읽는다" 재현 — 새 __rewardPostQueueForTest() 스냅샷으로 재확인(같은 페이크 localStorage 인스턴스, 모듈 재import 없이도 파일 헤더 계약 확인)')
{
  // 이 스위트는 페이크 localStorage(FakeStorage)를 프로세스 전체에서 하나만
  // 쓴다 — 즉 위 두 섹션에서 큐가 이미 이 인스턴스에 실제로 쓰였다가
  // 지워진 것이지, 메모리상 변수만 바뀐 게 아니다(readRewardPostQueue/
  // writeRewardPostQueue가 매번 실제로 JSON.stringify -> localStorage.setItem
  // 왕복을 한다). 이 절은 그 사실 자체(실 스토리지 왕복)를 명시적으로
  // 고정한다 — 큐가 진짜로 비어 있다는 걸 "직렬화된 원문"을 다시 파싱해
  // 재확인.
  const raw = globalThis.localStorage.getItem('paul_easy_reward_post_queue')
  const parsed = raw ? JSON.parse(raw) : []
  check('섹션 1·2 종료 시점 — 직렬화된 큐 원문도 빈 배열([])', Array.isArray(parsed) && parsed.length === 0)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '\n모든 단언 통과 — 재시도 큐 ⇒ 서버 원장 정확히 1행 e2e 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
