// scripts/testLegacyGrantCoverage.mjs
//
// 레거시 클라이언트 별 지급 6종(2026-09-06, 서버 원장 흡수) 커버리지
// 테스트. scripts/testRewardIdempotencyStress.mjs와 완전히 같은 구동 방식
// (esbuild 자체 번들 + fakeReact.mjs 최소 hooks 런타임 + fake clock +
// FakeStorage/FakeDocument + settle() 헬퍼) — 새 테스트 프레임워크를
// 발명하지 않는다. 이 파일 전용 산출물(scripts/.tmp/useStudent.
// legacyCoverage.bundle.mjs, scripts/.tmp/wordLibraryLegacyCoverageStub.mjs)
// 을 독자적으로 생성해서, 기존 wordLibraryRaceStub.mjs(다른 여러 테스트가
// 공유하는 재대입 불가 export)를 전혀 건드리지 않는다(CLAUDE.md 규칙 16,
// 파일당 소유권).
//
// 무엇을 검증하는가: useStudent.js의 grantReward가 레거시 dedupKey 6종
// (pronunciation/mission-clear/daily-mission-bonus/spelling-combo/
// sticker-duplicate/matchgame)을 parseLegacyDedupKey로 해석해 서버
// postRewardEvent를 정확히 1회만 호출하는가 — 로컬 별 지급 금액/조건은
// 단 한 글자도 바뀌지 않았다는 전제 위에서(그건 이미 검증된 기존 로직,
// CLAUDE.md 규칙 3) "그 위에 얹은 서버 통지"만 새로 검증한다.
let expectedUnhandledRejections = 0
process.on('unhandledRejection', () => {
  expectedUnhandledRejections++
})

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'
import { parseLegacyDedupKey, LEGACY_REWARD_TYPES, REWARD_STARS } from '../src/utils/rewardEngine.js'

// ── 1) 자체 esbuild 번들(헤더 주석 참고) ────────────────────────────────
const TMP_DIR = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP_DIR, { recursive: true })

const raceStubPath = path.resolve('scripts/wordLibraryRaceStub.mjs')
const raceStubUrl = pathToFileURL(raceStubPath).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const generatedStubPath = path.join(TMP_DIR, 'wordLibraryLegacyCoverageStub.mjs')
const generatedStubContent = `// AUTO-GENERATED by scripts/testLegacyGrantCoverage.mjs — do not edit by hand.
export * from ${JSON.stringify(raceStubUrl)}

export const __postRewardEventLog = []
let __rejectQueue = []
export function __queuePostRewardEventRejects(n) {
  for (let i = 0; i < n; i++) __rejectQueue.push(true)
}
export function __resetPostRewardEventProbe() {
  __postRewardEventLog.length = 0
  __rejectQueue.length = 0
}
export async function postRewardEvent(studentId, rewardType, sourceType, sourceId) {
  __postRewardEventLog.push({ studentId, rewardType, sourceType, sourceId, at: __postRewardEventLog.length })
  if (__rejectQueue.length > 0) {
    __rejectQueue.shift()
    throw new Error('simulated network failure (testLegacyGrantCoverage stub)')
  }
}
`
fs.writeFileSync(generatedStubPath, generatedStubContent, 'utf8')
const generatedStubUrl = pathToFileURL(generatedStubPath).href

const outfile = path.join(TMP_DIR, 'useStudent.legacyCoverage.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile,
  plugins: [{
    name: 'legacy-coverage-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: generatedStubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)

const stub = await import(generatedStubUrl)
const bundle = await import(pathToFileURL(outfile).href)
const { useStudent, todayStr } = bundle

// ── 2) 하네스 보일러플레이트(testRewardIdempotencyStress.mjs와 동일 패턴) ──
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(type, fn) { (this.listeners[type] ||= []).push(fn) }
  removeEventListener(type, fn) { this.listeners[type] = (this.listeners[type] || []).filter(f => f !== fn) }
  dispatch(type) { (this.listeners[type] || []).forEach(fn => fn()) }
}

let failures = 0
let asserted = 0
const scenarioFailures = {}
let currentScenario = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else {
    console.log(`  FAIL  ${label}`)
    failures++
    scenarioFailures[currentScenario] = (scenarioFailures[currentScenario] || 0) + 1
  }
}
const flush = () => new Promise((r) => process.nextTick(r))
const flushMacro = () => new Promise((r) => setImmediate(r))

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  stub.__resetPostRewardEventProbe()
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}

function mountOnCurrentEnv(id, name) {
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}
function mountFresh(id, name) {
  freshEnv()
  return mountOnCurrentEnv(id, name)
}
function mountSeeded(id, name, seedRecord) {
  freshEnv()
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify({ [id]: seedRecord }))
  return mountOnCurrentEnv(id, name)
}
function remount(id, name) {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}
function settle(host) {
  host.rerender()
  return host
}
function freshRoundSeed() {
  return { date: todayStr(), wordsViewed: [], examplesHeard: 0, quizSolved: 0, pronunciationOk: 0, pronunciationOkWordIds: [], spellingWrongToday: [], spellingCombo: 0, starGrantLog: [], completedToday: [] }
}
function daysAgoStr(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toDateString()
}
function seedHistoryForStreak(priorDays) {
  const history = { [todayStr()]: { categoriesCompleted: 4 } }
  for (let i = 1; i <= priorDays; i++) history[daysAgoStr(i)] = { categoriesCompleted: 4 }
  return history
}
function completeFullRound(host, prefix) {
  for (let i = 0; i < 5; i++) host.result.markWordViewed(`${prefix}-v${i}`)
  for (let i = 0; i < 5; i++) host.result.markExampleHeard()
  for (let i = 0; i < 5; i++) host.result.markQuizSolved()
  for (let i = 0; i < 5; i++) host.result.markPronunciationOk(`${prefix}-p${i}`)
  settle(host)
}
function logSince(idx) { return stub.__postRewardEventLog.slice(idx) }
function findLog(entries, rewardType) { return entries.filter((e) => e.rewardType === rewardType) }
// 현재 로컬 스토어(paul_easy_progress)의 특정 학생 record.round.starGrantLog
// 에서 특정 dedupKey 하나만 제거 — "이 정확한 지급 이벤트가 아직 안
// 일어난 것처럼" 되돌려서 sticker-duplicate의 giftKey 안정성 계약("같은
// giftKey는 한 번만, 다른 giftKey는 매번")을 자연스러운 재방문 흐름으로
// 검증하기 위한 보조 함수 — 내부 함수(grantSticker)를 직접 호출하지
// 않고, 공개 API(localStorage 계약)만으로 시나리오를 구성한다.
function removeStarGrantLogEntry(id, dedupKey) {
  const raw = globalThis.localStorage.getItem('paul_easy_progress')
  const store = raw ? JSON.parse(raw) : {}
  const rec = store[id]
  if (!rec || !rec.round) return
  rec.round.starGrantLog = (rec.round.starGrantLog || []).filter((k) => k !== dedupKey)
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify(store))
}

console.log('=== 레거시 클라이언트 별 지급 6종 서버 원장 흡수 커버리지 ===')

// ── 시나리오 1 — pronunciation (+1) ─────────────────────────────────────
currentScenario = 1
console.log('\n시나리오 1 — pronunciation: markPronunciationOk(wordId)')
{
  const ID = '33330000-0000-0000-0000-000000000001'
  const { host } = mountFresh(ID, 'QA_Legacy_Pronunciation')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  host.result.markPronunciationOk('word-p1')
  const entries = findLog(logSince(postBefore), 'pronunciation')
  check('totalStars +1', host.result.stars === before + 1)
  check('postRewardEvent 정확히 1회(pronunciation)', entries.length === 1)
  const expected = parseLegacyDedupKey(`pronunciation:word-p1:${todayStr()}`)
  check('rewardType/sourceType/sourceId 일치', entries[0] && entries[0].sourceType === expected.sourceType && entries[0].sourceId === expected.sourceId)
  check('studentId가 호출 학생 그대로', entries[0] && entries[0].studentId === ID)

  // 재진입(같은 wordId 재호출) — dedup, 추가 지급/포스트 없음.
  const before2 = host.result.stars
  const postBefore2 = stub.__postRewardEventLog.length
  host.result.markPronunciationOk('word-p1')
  check('재진입 — totalStars 변화 없음', host.result.stars === before2)
  check('재진입 — 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore2)

  // 리마운트(새로고침/재로그인) 후 같은 조건 재발화 시도 — dedup 유지.
  const { host: host2 } = remount(ID, 'QA_Legacy_Pronunciation')
  await flush(); await flush(); await flush()
  const postBefore3 = stub.__postRewardEventLog.length
  const before3 = host2.result.stars
  host2.result.markPronunciationOk('word-p1')
  check('리마운트 후 재발화 — totalStars 변화 없음', host2.result.stars === before3)
  check('리마운트 후 재발화 — 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore3)

  // dedup 신원 안정성 — 서로 다른(독립) 학생이 같은 입력으로 같은 sourceId.
  const ID_B = '33330000-0000-0000-0000-0000000001b'
  const { host: hostB } = mountFresh(ID_B, 'QA_Legacy_PronunciationB')
  await flush(); await flush(); await flush()
  const postBeforeB = stub.__postRewardEventLog.length
  hostB.result.markPronunciationOk('word-p1')
  const entryB = findLog(logSince(postBeforeB), 'pronunciation')[0]
  check('서로 다른 학생, 같은 입력 → 동일 sourceId', entryB && entryB.sourceId === entries[0].sourceId)

  // pronunciation-unidentified(wordId 없음) — 서버화 대상 아님, 0 포스트.
  const postBeforeU = stub.__postRewardEventLog.length
  const beforeU = hostB.result.stars
  hostB.result.markPronunciationOk(null)
  check('pronunciation-unidentified — totalStars +1(로컬 지급은 유지)', hostB.result.stars === beforeU + 1)
  check('pronunciation-unidentified — postRewardEvent 0건(의도된 동작)', stub.__postRewardEventLog.length === postBeforeU)

  // 서버 실패 — 로컬 지급/흐름에 영향 없음, throw 없음.
  const ID_F = '33330000-0000-0000-0000-0000000001f'
  const { host: hostF } = mountFresh(ID_F, 'QA_Legacy_PronunciationFail')
  await flush(); await flush(); await flush()
  stub.__queuePostRewardEventRejects(1)
  const beforeF = hostF.result.stars
  hostF.result.markPronunciationOk('word-fail')
  await flush(); await flush(); await flushMacro()
  check('서버 실패해도 totalStars +1(로컬 지급 유지)', hostF.result.stars === beforeF + 1)
}

// ── 시나리오 2 — mission-clear (+3) ─────────────────────────────────────
currentScenario = 2
console.log('\n시나리오 2 — mission-clear: addMission + answerMission x3')
{
  const ID = '33330000-0000-0000-0000-000000000002'
  const { host } = mountFresh(ID, 'QA_Legacy_MissionClear')
  await flush(); await flush(); await flush()
  host.result.addMission('mission-word-1')
  settle(host)
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  host.result.answerMission('mission-word-1')
  host.result.answerMission('mission-word-1')
  host.result.answerMission('mission-word-1') // 3번째에서 클리어 → +3
  const entries = findLog(logSince(postBefore), 'mission-clear')
  check('totalStars +3', host.result.stars === before + 3)
  check('postRewardEvent 정확히 1회(mission-clear)', entries.length === 1)
  const expected = parseLegacyDedupKey('mission-clear:mission-word-1')
  check('rewardType/sourceType/sourceId 일치', entries[0] && entries[0].sourceType === expected.sourceType && entries[0].sourceId === expected.sourceId)

  // 재진입 — mission.done이라 grantReward 호출 자체가 안 됨(willClear=false).
  const before2 = host.result.stars
  const postBefore2 = stub.__postRewardEventLog.length
  host.result.answerMission('mission-word-1')
  check('재진입 — totalStars 변화 없음', host.result.stars === before2)
  check('재진입 — 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore2)

  // 리마운트 후 재진입.
  const { host: host2 } = remount(ID, 'QA_Legacy_MissionClear')
  await flush(); await flush(); await flush()
  const postBefore3 = stub.__postRewardEventLog.length
  const before3 = host2.result.stars
  host2.result.answerMission('mission-word-1')
  check('리마운트 후 재진입 — totalStars 변화 없음', host2.result.stars === before3)
  check('리마운트 후 재진입 — 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore3)

  // dedup 신원 안정성.
  const ID_B = '33330000-0000-0000-0000-0000000002b'
  const { host: hostB } = mountFresh(ID_B, 'QA_Legacy_MissionClearB')
  await flush(); await flush(); await flush()
  hostB.result.addMission('mission-word-1')
  settle(hostB)
  const postBeforeB = stub.__postRewardEventLog.length
  hostB.result.answerMission('mission-word-1')
  hostB.result.answerMission('mission-word-1')
  hostB.result.answerMission('mission-word-1')
  const entryB = findLog(logSince(postBeforeB), 'mission-clear')[0]
  check('서로 다른 학생, 같은 입력 → 동일 sourceId', entryB && entryB.sourceId === entries[0].sourceId)

  // 서버 실패.
  const ID_F = '33330000-0000-0000-0000-000000002f'
  const { host: hostF } = mountFresh(ID_F, 'QA_Legacy_MissionClearFail')
  await flush(); await flush(); await flush()
  hostF.result.addMission('mission-word-fail')
  settle(hostF)
  stub.__queuePostRewardEventRejects(1)
  const beforeF = hostF.result.stars
  hostF.result.answerMission('mission-word-fail')
  hostF.result.answerMission('mission-word-fail')
  hostF.result.answerMission('mission-word-fail')
  await flush(); await flush(); await flushMacro()
  check('서버 실패해도 totalStars +3(로컬 지급 유지)', hostF.result.stars === beforeF + 3)
}

// ── 시나리오 3 — daily-mission-bonus (+10) ───────────────────────────────
currentScenario = 3
console.log('\n시나리오 3 — daily-mission-bonus: 4/4 라운드 완료(completeFullRound)')
{
  const ID = '33330000-0000-0000-0000-000000000003'
  const { host } = mountFresh(ID, 'QA_Legacy_DailyBonus')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  completeFullRound(host, 'db1')
  const entries = findLog(logSince(postBefore), 'daily-mission-bonus')
  // completeFullRound 안의 markPronunciationOk x5도 pronunciation 레거시를
  // 함께 발화시키므로(의도된 정상 동작), daily-mission-bonus만 필터링해서 확인.
  check('daily-mission-bonus postRewardEvent 정확히 1회', entries.length === 1)
  check('totalStars에 daily-mission-bonus 몫(+10) 포함', host.result.stars >= before + 10)

  // 재진입 — 같은 5개 단어로 다시 완주(같은 signature) → 라운드가 이미
  // freshRound()로 리셋됐으므로 wordsViewed를 다시 채워야 같은 signature가
  // 재현된다. handledRoundRef도 이번엔 리마운트 없이 그대로라 이중 방어.
  const postBefore2 = stub.__postRewardEventLog.length
  completeFullRound(host, 'db1')
  const entries2 = findLog(logSince(postBefore2), 'daily-mission-bonus')
  check('재진입(같은 signature) — daily-mission-bonus 추가 포스트 없음', entries2.length === 0)

  // 리마운트 후 같은 signature 재현.
  const { host: host2 } = remount(ID, 'QA_Legacy_DailyBonus')
  await flush(); await flush(); await flush()
  const postBefore3 = stub.__postRewardEventLog.length
  completeFullRound(host2, 'db1')
  const entries3 = findLog(logSince(postBefore3), 'daily-mission-bonus')
  check('리마운트 후 같은 signature 재현 — daily-mission-bonus 추가 포스트 없음', entries3.length === 0)

  // dedup 신원 안정성 — 서로 다른 학생, 같은 wordset(같은 signature).
  const ID_B = '33330000-0000-0000-0000-0000000003b'
  const { host: hostB } = mountFresh(ID_B, 'QA_Legacy_DailyBonusB')
  await flush(); await flush(); await flush()
  const postBeforeB = stub.__postRewardEventLog.length
  completeFullRound(hostB, 'db1')
  const entryB = findLog(logSince(postBeforeB), 'daily-mission-bonus')[0]
  check('서로 다른 학생, 같은 wordset → 동일 sourceId', entryB && entryB.sourceId === entries[0].sourceId)

  // 서버 실패.
  const ID_F = '33330000-0000-0000-0000-000000003f'
  const { host: hostF } = mountFresh(ID_F, 'QA_Legacy_DailyBonusFail')
  await flush(); await flush(); await flush()
  stub.__queuePostRewardEventRejects(6) // pronunciation 5회 + daily-mission-bonus 1회 중 하나라도 맞도록 여유
  const beforeF = hostF.result.stars
  completeFullRound(hostF, 'dbf')
  await flush(); await flush(); await flushMacro()
  check('서버 실패해도 daily-mission-bonus 몫(+10) 포함 지급 유지', hostF.result.stars >= beforeF + 10)
}

// ── 시나리오 4 — spelling-combo (+1/+2/+3 at 3/5/10) ─────────────────────
currentScenario = 4
console.log('\n시나리오 4 — spelling-combo: 연속 정답 스트릭 3/5/10')
{
  const ID = '33330000-0000-0000-0000-000000000004'
  const { host } = mountFresh(ID, 'QA_Legacy_SpellingCombo')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  // 10연속 정답 — combo 3/5/10 세 마일스톤을 한 번에 통과.
  for (let i = 0; i < 10; i++) host.result.recordSpellingAnswer(`sc-${i}`, true)
  const entries = findLog(logSince(postBefore), 'spelling-combo')
  check('spelling-combo postRewardEvent 정확히 3회(3/5/10)', entries.length === 3)
  check('totalStars에 spelling-combo 몫(+1+2+3=6) 포함', host.result.stars >= before + 6)
  const combo3 = parseLegacyDedupKey(`spelling-combo:sc-2:3:${todayStr()}`)
  const combo5 = parseLegacyDedupKey(`spelling-combo:sc-4:5:${todayStr()}`)
  const combo10 = parseLegacyDedupKey(`spelling-combo:sc-9:10:${todayStr()}`)
  check('combo=3 sourceId 일치(word=sc-2)', entries.some((e) => e.sourceId === combo3.sourceId))
  check('combo=5 sourceId 일치(word=sc-4)', entries.some((e) => e.sourceId === combo5.sourceId))
  check('combo=10 sourceId 일치(word=sc-9)', entries.some((e) => e.sourceId === combo10.sourceId))
  check('REWARD_STARS 매핑과 무관 — 실제 금액은 LEGACY_SPELLING_COMBO_BONUS(서버)에서 조회(클라이언트 금액 불변 확인용 참고)', REWARD_STARS['spelling-combo'] === 0)

  // 재진입 — 오답으로 콤보를 끊었다가 정확히 같은 3단어 시퀀스 재현(같은
  // wordId+combo+date 조합) → 마지막(combo=3) dedupKey가 이미 있으므로 dedup.
  host.result.recordSpellingAnswer('sc-reset', false)
  const postBefore2 = stub.__postRewardEventLog.length
  host.result.recordSpellingAnswer('sc-0', true)
  host.result.recordSpellingAnswer('sc-1', true)
  host.result.recordSpellingAnswer('sc-2', true) // combo=3, 같은 wordId=sc-2, 같은 날짜 → 이미 지급된 키
  const entries2 = findLog(logSince(postBefore2), 'spelling-combo')
  check('재진입(동일 wordId+combo+date) — 추가 포스트 없음', entries2.length === 0)

  // dedup 신원 안정성.
  const ID_B = '33330000-0000-0000-0000-0000000004b'
  const { host: hostB } = mountFresh(ID_B, 'QA_Legacy_SpellingComboB')
  await flush(); await flush(); await flush()
  const postBeforeB = stub.__postRewardEventLog.length
  for (let i = 0; i < 3; i++) hostB.result.recordSpellingAnswer(`sc-${i}`, true)
  const entryB = findLog(logSince(postBeforeB), 'spelling-combo')[0]
  check('서로 다른 학생, 같은 입력 → 동일 sourceId', entryB && entryB.sourceId === combo3.sourceId)

  // 서버 실패.
  const ID_F = '33330000-0000-0000-0000-000000004f'
  const { host: hostF } = mountFresh(ID_F, 'QA_Legacy_SpellingComboFail')
  await flush(); await flush(); await flush()
  stub.__queuePostRewardEventRejects(1)
  const beforeF = hostF.result.stars
  for (let i = 0; i < 3; i++) hostF.result.recordSpellingAnswer(`scf-${i}`, true)
  await flush(); await flush(); await flushMacro()
  check('서버 실패해도 combo=3 몫(+1) 포함 지급 유지', hostF.result.stars >= beforeF + 1)
}

// ── 시나리오 5 — sticker-duplicate (+20), giftKey 안정성 ─────────────────
currentScenario = 5
console.log('\n시나리오 5 — sticker-duplicate: 라운드 선물(giftKey=round:signature), 같은/다른 giftKey')
{
  const ID = '33330000-0000-0000-0000-000000000005'
  // sticker1을 이미 보유한 상태로 시작 — 라운드 완료 시 뽑히는 스티커가
  // 항상 중복 처리되게 한다(Math.random 결정론 고정, 아래).
  const seed = { studentId: ID, totalStars: 0, round: freshRoundSeed(), stickers: ['sticker1'], history: {} }
  const { host } = mountSeeded(ID, 'QA_Legacy_StickerDup', seed)
  await flush(); await flush(); await flush()

  const RealRandom = Math.random
  Math.random = () => 0 // getRandomSticker() → 항상 common 풀의 첫 항목(sticker1)
  try {
    const before = host.result.stars
    const postBefore = stub.__postRewardEventLog.length
    completeFullRound(host, 'sd1') // 라운드1 — giftKey round:sig1
    const sig1 = `${todayStr()}:${['sd1-v0', 'sd1-v1', 'sd1-v2', 'sd1-v3', 'sd1-v4'].sort().join(',')}`
    const entries1 = findLog(logSince(postBefore), 'sticker-duplicate')
    check('라운드1 — sticker-duplicate postRewardEvent 정확히 1회', entries1.length === 1)
    const expected1 = parseLegacyDedupKey(`sticker-duplicate:sticker1:round:${sig1}`)
    check('라운드1 — sourceId가 giftKey=round:sig1 기반', entries1[0] && expected1 && entries1[0].sourceId === expected1.sourceId)
    check('라운드1 — totalStars에 sticker-duplicate 몫(+20) 포함', host.result.stars >= before + 20)

    // 다른 giftKey(라운드2 — 다른 단어셋) → 다시 지급(legacy 동작 보존).
    const postBefore2 = stub.__postRewardEventLog.length
    const before2 = host.result.stars
    completeFullRound(host, 'sd2')
    const sig2 = `${todayStr()}:${['sd2-v0', 'sd2-v1', 'sd2-v2', 'sd2-v3', 'sd2-v4'].sort().join(',')}`
    const entries2 = findLog(logSince(postBefore2), 'sticker-duplicate')
    check('라운드2(다른 giftKey) — sticker-duplicate 다시 지급 1회', entries2.length === 1)
    // +20(sticker-duplicate) +10(daily-mission-bonus, 새 signature라 재지급)
    // +5(completeFullRound 안의 markPronunciationOk x5, 매번 새 wordId라 별개 지급).
    check('라운드2 — totalStars +35 추가(20+10+5)', host.result.stars === before2 + 20 + 10 + 5)
    check('라운드1/2 sourceId 서로 다름(다른 giftKey)', entries1[0].sourceId !== entries2[0].sourceId)

    // 같은 giftKey(라운드1의 signature)로 되돌아가 재현 — daily-mission-bonus
    // 쪽 dedup만 지워서 bonusGranted가 다시 true가 되게 하고, sticker-duplicate
    // 쪽 dedup은 그대로 둬서 "같은 giftKey는 한 번만" 계약을 자연스러운
    // 재방문 흐름으로 검증한다(내부 함수 직접 호출 없이 공개 localStorage
    // 계약만 사용).
    removeStarGrantLogEntry(ID, `daily-mission-bonus:${sig1}`)
    const { host: host3 } = remount(ID, 'QA_Legacy_StickerDup')
    await flush(); await flush(); await flush()
    const postBefore3 = stub.__postRewardEventLog.length
    const before3 = host3.result.stars
    completeFullRound(host3, 'sd1') // 라운드1과 정확히 같은 wordset → 같은 sig1
    const entriesDaily3 = findLog(logSince(postBefore3), 'daily-mission-bonus')
    const entriesSticker3 = findLog(logSince(postBefore3), 'sticker-duplicate')
    check('같은 giftKey 재현 — daily-mission-bonus는 재지급(dedup 별도 해제)', entriesDaily3.length === 1)
    check('같은 giftKey 재현 — sticker-duplicate는 추가 지급 0(같은 giftKey는 한 번만)', entriesSticker3.length === 0)
    check('같은 giftKey 재현 — totalStars는 daily-mission-bonus 몫(+10)만 늘어남(sticker 몫 없음)', host3.result.stars === before3 + 10)
  } finally {
    Math.random = RealRandom
  }
}

// ── 시나리오 6 — matchgame (+4, MatchGameShell.jsx 소유 — grantReward만 경유) ──
currentScenario = 6
console.log('\n시나리오 6 — matchgame: grantReward(4, matchgame:...) 직접 호출(호출부는 MatchGameShell.jsx, 여기선 grantReward 경유만 검증)')
{
  const ID = '33330000-0000-0000-0000-000000000006'
  const { host } = mountFresh(ID, 'QA_Legacy_Matchgame')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  const uuid = '11111111-1111-4111-8111-111111111111'
  const dedupKey = `matchgame:1700000000000_ab12cd:0:${uuid}`
  const granted = host.result.grantReward(4, dedupKey)
  const entries = findLog(logSince(postBefore), 'matchgame')
  check('grantReward 반환값 true(지급됨)', granted === true)
  check('totalStars +4', host.result.stars === before + 4)
  check('matchgame postRewardEvent 정확히 1회', entries.length === 1)
  const expected = parseLegacyDedupKey(dedupKey)
  check('sourceId가 sessionId:round:wordToken 형식 그대로', entries[0] && expected && entries[0].sourceId === expected.sourceId)

  // 재진입 — 같은 dedupKey.
  const postBefore2 = stub.__postRewardEventLog.length
  const before2 = host.result.stars
  const granted2 = host.result.grantReward(4, dedupKey)
  check('재진입 — grantReward 반환값 false', granted2 === false)
  check('재진입 — totalStars 변화 없음', host.result.stars === before2)
  check('재진입 — 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore2)
}

// ── 시나리오 7 — V1 앵커 6종은 여전히 grantLedgerReward 경로로 각 1건
//    (parseLegacyDedupKey가 uuid-prefixed 키는 null을 돌려줘 grantReward의
//    새 후킹이 중복 전송을 만들지 않음을 확인) ─────────────────────────
currentScenario = 7
console.log('\n시나리오 7 — V1 앵커 6종: grantLedgerReward 경로 각 1건, grantReward 후킹으로 인한 중복 전송 없음')
{
  const ID = '33330000-0000-0000-0000-000000000007'
  const seed = {
    studentId: ID, totalStars: 0, round: freshRoundSeed(),
    spellingReviewQueue: ['anchor-wrong-word'],
    history: seedHistoryForStreak(2), // streak=3 → streak-bonus +2
  }
  const { host } = mountSeeded(ID, 'QA_Legacy_V1Anchors', seed)
  await flush(); await flush(); await flush()
  settle(host); settle(host) // streak-bonus 재평가

  const postBefore1 = 0 // 마운트 시점부터 계측(streak-bonus는 마운트 시 useEffect로 지급 시도)
  check('streak-bonus 정확히 1건', findLog(stub.__postRewardEventLog.slice(postBefore1), 'streak-bonus').length === 1)

  const postA = stub.__postRewardEventLog.length
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`va-${i}`)
  settle(host)
  check('word-session-complete 정확히 1건(추가분)', findLog(logSince(postA), 'word-session-complete').length === 1)

  const postB = stub.__postRewardEventLog.length
  for (let i = 0; i < 5; i++) host.result.recordSpellingAnswer(`vaw-${i}`, true)
  check('writing-complete 정확히 1건(추가분)', findLog(logSince(postB), 'writing-complete').length === 1)

  const postC = stub.__postRewardEventLog.length
  host.result.recordExamCompleted('va-exam-1')
  check('exam-complete 정확히 1건(추가분)', findLog(logSince(postC), 'exam-complete').length === 1)

  const postD = stub.__postRewardEventLog.length
  host.result.clearSpellingReviewWord('anchor-wrong-word')
  check('wrong-word-recovered 정확히 1건(추가분)', findLog(logSince(postD), 'wrong-word-recovered').length === 1)

  const postE = stub.__postRewardEventLog.length
  completeFullRound(host, 'vad')
  check('daily-goal-complete 정확히 1건(추가분, pronunciation 5건은 별개)', findLog(logSince(postE), 'daily-goal-complete').length === 1)

  const v1Total = findLog(stub.__postRewardEventLog, 'streak-bonus').length
    + findLog(stub.__postRewardEventLog, 'word-session-complete').length
    + findLog(stub.__postRewardEventLog, 'writing-complete').length
    + findLog(stub.__postRewardEventLog, 'exam-complete').length
    + findLog(stub.__postRewardEventLog, 'wrong-word-recovered').length
    + findLog(stub.__postRewardEventLog, 'daily-goal-complete').length
  check('V1 앵커 6종 각 정확히 1건, 합계 6건', v1Total === 6)

  // V1 앵커 키(uuid-prefixed)는 parseLegacyDedupKey에서 null — grantReward의
  // 새 후킹이 이 6건에 대해 중복 postRewardEvent를 만들지 않았음을 재확인
  // (총 postRewardEvent 수가 위 개별 합계와 정확히 같아야 함 — pronunciation/
  // daily-mission-bonus 등 이 시나리오에서 함께 발생한 레거시 포스트 제외).
  const legacyInThisScenario = LEGACY_REWARD_TYPES.reduce((sum, t) => sum + findLog(stub.__postRewardEventLog, t).length, 0)
  check('이 시나리오의 전체 포스트 = V1 앵커 6건 + 레거시 발생분(합, 중복 없음)', stub.__postRewardEventLog.length === v1Total + legacyInThisScenario)
}

// ── 결과 요약 ────────────────────────────────────────────────────────
console.log('\n─── 결과 요약 ───')
for (const n of Object.keys(scenarioFailures)) console.log(`시나리오 ${n} 실패 수: ${scenarioFailures[n]}`)
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(`(참고) 의도된 unhandledRejection 흡수 횟수: ${expectedUnhandledRejections}`)
console.log(failures === 0
  ? '\n모든 단언 통과 — 레거시 6종 서버 원장 흡수 커버리지 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
