// 2026-10-10(244차) 하이브리드 월드 배선(App.jsx/features.js/GrammarCourseScreen.jsx) 소스 핀. 네트워크 0, 저장소 0.
import fs from 'node:fs'
let fail = 0
const check = (n, ok) => { console.log(`${ok ? 'PASS' : 'FAIL'} ${n}`); if (!ok) fail++ }
const app = fs.readFileSync('src/App.jsx', 'utf8')
const feat = fs.readFileSync('src/config/features.js', 'utf8')
const gc = fs.readFileSync('src/components/GrammarCourseScreen.jsx', 'utf8')
const panel = fs.readFileSync('src/components/FeatureManagementPanel.jsx', 'utf8')
const count = (s, re) => (s.match(re) || []).length

check('플래그 paulTownWorld 기본값 true(245차: 접근은 테스터 목록, 플래그는 기기별 OFF 스위치)', /^\s*paulTownWorld:\s*true,/m.test(feat))
check('관리자 카테고리 목록에 paulTownWorld', /attachment: \[[^\]]*'paulTownWorld'/.test(feat))
check('FEATURE_DETAILS에 paulTownWorld 설명', /paulTownWorld: \{\s*label:/.test(panel))
check('townWorldEnabled = 플래그 AND isTownWorldTester(studentId)', /const townWorldEnabled = useSyncExternalStore\([^\n]*isFeatureEnabled\('paulTownWorld'\)[^\n]*&& isTownWorldTester\(studentId\)/.test(app) && !/townWorldEnabled = [^\n]*qaTestStudent/.test(app))
check('QA_ONLY_SCREENS에 townWorld 없음 + 별도 가드', !/const QA_ONLY_SCREENS = \[[^\]]*'townWorld'/.test(app) && /if \(!townWorldEnabled && screen === 'townWorld'\) setScreen\('dashboard'\)/.test(app))
check('TownWorld는 React.lazy 별도 청크(프리로드/정적 import 없음)', /const TownWorld = React\.lazy\(\(\) => import\('\.\/components\/town\/proto2_5d\/world\/TownWorld'\)\)/.test(app) && !/^import[^\n]*world\/TownWorld/m.test(app))
check('화면은 townWorldEnabled && screen === townWorld 일 때만 렌더', /\{townWorldEnabled && screen === 'townWorld' && \(/.test(app))
check("홈 paulTown 버튼: townWorldEnabled가 proto25d보다 우선", /\(townWorldEnabled && t === 'paulTown'\) \? 'townWorld' : \(paulTown2_5dEnabled && t === 'paulTown'\) \? 'proto25d'/.test(app))
check('canEnterTown에 townWorldEnabled 포함', /canEnterTown=\{[^\n]*townWorldEnabled\}/.test(app))
check('TownWorld에 세션/완료 유닛/미션/뒤로가기 props 전달', /<TownWorld initial=\{townWorldSession\} onSessionChange=\{setTownWorldSession\} completedUnitIds=\{completedUnitIds\}\s+onOpenMission=\{qaTestStudent \? openWorldMission : null\}/.test(app))
check('월드 onBack: 복귀 표식만 비우고 세션 유지', /setWorldReturn\(null\); setScreen\(studentHomeEnabled \? 'home' : 'dashboard'\)/.test(app) && !/setTownWorldSession\(\{ pos: null/.test(app.slice(app.indexOf("screen === 'townWorld'"))))
check('복귀 헬퍼 learningHome 단 하나', count(app, /const learningHome = /g) === 1 && /worldReturn === 'world' && townWorldEnabled \? 'townWorld' : 'home'/.test(app))
// 헬퍼를 쓰는 퇴장 지점 7곳(speaking onBack, writing onBack/onHome, unit-load-home, grammar-load-home, grammar onBack, UnitScreen onBack)
check('learningHome() 사용처 7곳', count(app, /learningHome\(\)/g) === 7)
check('마을 경유 학습 화면 퇴장 지점에 하드코딩 home 없음', !/unit-load-home[^\n]*setScreen\('home'\)/.test(app) && !/<UnitScreen [^\n]*setScreen\('home'\)/.test(app) && !/onHome=\{\(\) => \{ setWritingLink\(null\); setUnitLink\(null\); setScreen\('home'\)/.test(app))
check('openWorldMission: grammar → grammarEntry returnTo world + grammarCourses', /kind === 'grammar'\) setGrammarEntry\(\{ unitId: mission\.unitId, returnTo: 'world' \}\)/.test(app) && /mission\.kind === 'grammar' \? 'grammarCourses' : 'unit'/.test(app))
check("openWorldMission: writing → intent 'writing', 선택 없음", /setUnitIntent\(mission\.kind === 'writing' \? 'writing' : null\)/.test(app) && /mission\.kind === 'course' \? \{ courseId: mission\.courseId \} : null/.test(app))
check('openWorldMission: worldReturn=world 설정 + pilotUnits 로드', /const openWorldMission = [^\n]*\n\s*setWorldReturn\('world'\)/.test(app) && /openWorldMission[\s\S]{0,700}loadPilotUnits\(\)/.test(app))
check('GrammarCourseScreen: returnTo world를 town처럼 취급', /returnTo === 'town' \|\| returnTo === 'village' \|\| returnTo === 'world'/.test(gc))
check('문법 덱 마을 복귀 테스트아이디 유지(gu-back, gd-to-town)', gc.includes('data-testid="gu-back"') && gc.includes('data-testid="gd-to-town"'))
check('완료 유닛은 기존 completedUnitIds 상태를 그대로 전달', /onUnitComplete=\{\(uid\) => \{ setCompletedUnitIds/.test(app))
const world = app.slice(app.indexOf('townWorldEnabled = useSyncExternalStore'), app.indexOf('const villageReturn'))
check('월드 배선에 저장소 키 없음(localStorage/sessionStorage)', !/localStorage|sessionStorage/.test(world))
check('보상/XP 호출 없음', !/grantReward|rewardEngine|addStars/.test(world))
// 245차 접근 분리 핀
const qa = fs.readFileSync('src/config/qaTestAccounts.js', 'utf8')
const dash = fs.readFileSync('src/components/Dashboard.jsx', 'utf8')
const pt = fs.readFileSync('src/components/PaulTown.jsx', 'utf8')
const sheet = fs.readFileSync('src/components/town/proto2_5d/world/PlaceSheet.jsx', 'utf8')
const idsOf = (name) => { const i = qa.indexOf(`${name} = `); const body = qa.slice(i, qa.indexOf(']))', i)); return [...body.matchAll(/'([0-9a-f-]{36})'/g)].map((x) => x[1]) }
const town = idsOf('TOWN_WORLD_TEST_STUDENT_IDS'), qaIds = idsOf('QA_TEST_STUDENT_IDS')
const PAUL = '335a9560-d1f1-4628-bd8d-26bcaa8eaee7'
check('마을 테스터 목록에 Paul 없음', town.length > 0 && !town.includes(PAUL))
check('마을 테스터 목록에 실계정 4명(Kinney/Jinaa/Barry/Cookie) 존재', ['e0fe0f50-8927-44d9-9331-e454620524d9', '738443f3-2676-4b89-9f17-cc7f22aa993c', '1056c7db-8464-45a4-9f3d-d13223c708b6', 'a63923a1-473d-4ba1-bca6-6b8685848cd3'].every((i) => town.includes(i)))
check('마을 목록 e2e 합성 id 2개(a001, a002), 총 6개', town.includes('e2e00000-0000-4000-8000-00000000a001') && town.includes('e2e00000-0000-4000-8000-00000000a002') && town.length === 6)
check('QA 목록 불변(실계정 3 + fixture 1)', qaIds.length === 4 && [PAUL, 'a63923a1-473d-4ba1-bca6-6b8685848cd3', '738443f3-2676-4b89-9f17-cc7f22aa993c', 'e2e00000-0000-4000-8000-00000000a001'].every((i) => qaIds.includes(i)))
check('isTownWorldTester export', /export function isTownWorldTester\(/.test(qa))
check('Dashboard/PaulTown 둘 다 onGoWorld를 goTownWorld로 전달(없으면 null)', count(app, /onGoWorld=\{townWorldEnabled \? goTownWorld : null\}/g) === 2 && /const goTownWorld = \(\) => \{ setWorldReturn\(null\); setScreen\('townWorld'\) \}/.test(app))
check('Dashboard 진입 버튼은 onGoWorld일 때만(dash-town-world)', /\{onGoWorld && \(\s*<button[^>]*data-testid="dash-town-world"/.test(dash))
check('PaulTown 진입 카드는 onGoWorld일 때만 + 래퍼 조건 포함', /\{onGoWorld && \(\s*<button[^>]*data-testid="paul-town-world-entry"/.test(pt) && /\(onGoTown \|\| onGoWorld \|\|/.test(pt))
check('PlaceSheet: 미션 비허용이면 tw-missions-closed + disabled', /!missionsOpen && \(\s*<p data-testid="tw-missions-closed"/.test(sheet) && /disabled=\{!missionsOpen\}/.test(sheet))
if (fail) { console.log(`\n${fail}건 FAIL`); process.exit(1) } else console.log('\nALL PASS')
