// scripts/testRewardCapRace.mjs
//
// Reward System V1 서버측 일일 상한(L3, api/grant-xp.js ~424-457) — 동시
// 요청 TOCTOU(Time-Of-Check-To-Time-Of-Use) 레이스 관측용 테스트. 결정
// 지원용(non-gating, extra:true) — "이 레이스가 있으면 안 된다"를 주장하지
// 않고, "지금 실제로 이런 동작이 관측된다"를 정직하게 고정한다(운영자가
// DB 레벨 가드 도입 여부를 판단할 때 근거로 쓰기 위함).
//
// ── 배경(읽기 전용 분석) ────────────────────────────────────────────────
// api/grant-xp.js의 일일 상한 검사는 "SELECT count → count < cap이면
// INSERT"(check-then-insert)다. DB 유일성 제약은 idempotency_key(요청당
// 1건, 같은 이벤트의 재시도만 막는다) 하나뿐이고, (student_id, reward_type,
// day) 조합에는 유일성 제약이 없다 — 즉 서로 다른 sourceId(=서로 다른
// idempotency_key)를 가진 동시 요청 N개가 count = cap-1인 순간에 도착하면
// 전부 "아직 상한 미만"으로 읽어(각자 정확한 값을 읽지만 서로의 쓰기를
// 못 봄) 전부 INSERT를 시도하고, 서로 다른 키라 23505 충돌도 없이 전부
// 성공할 수 있다 — 최종 건수가 cap을 최대 N-1건 초과한다.
//
// scripts/testRewardServerHardeningBehavior.mjs §7(~248-262)은 상한
// 도달을 "순차" 호출로만 검증하고, §3(~190-197)의 Promise.all은 "같은
// 이벤트"(같은 sourceId → 같은 idempotency_key) 동시 20회만 다뤄
// idempotency만 확인한다 — 서로 다른 sourceId의 진짜 카운트 레이스는 그
// 파일도, 다른 어떤 등록된 테스트도 다루지 않는다. 이 파일이 그 공백을
// 메운다.
//
// ── 하네스 설계 — 정직한 TOCTOU 모델링 ───────────────────────────────────
// scripts/testRewardServerHardeningBehavior.mjs가 만드는
// scripts/.tmp/fakeSupabaseForRewardApi.mjs는 그 파일이 "실행 시" 스스로
// 생성하는 산출물이라 이 파일이 import해서 재사용할 안정적인 모듈이
// 아니다(그 파일을 수정하지 않는다는 원칙과 별개로, 애초에 참조 가능한
// 공유 소스가 없다) — 그래서 이 파일은 같은 스타일(esbuild + 인메모리 가짜
// @supabase/supabase-js)을 따르되 완전히 독립된 가짜 DB를 자체 생성한다.
//
// 이 가짜 DB의 일일 상한 COUNT 쿼리는 "즉시 응답"이 아니라 "배리어(barrier)"
// 방식으로 동작한다 — 실제 동시 HTTP 요청 N개가 거의 같은 시각에 각자
// COUNT를 실행하면, 그 N개의 SELECT 각각은 호출 시점의 정확한 값을
// 돌려주지만(진짜 DB의 SELECT는 항상 정직하다), 그 응답이 클라이언트(=이
// 핸들러)에 돌아오는 시각은 네트워크/DB 왕복 지연 때문에 서로 겹친다 — 즉
// N개 요청 전부가 "아직 아무도 INSERT하지 않은" 시점의 카운트를 손에 쥔
// 채로 각자 INSERT를 결정한다. 이를 정직하게 재현하기 위해, cap-count
// SELECT는 호출 시점에 값을 스냅샷(정확한 값)해 두고, 그 Promise의 resolve는
// 같은 배리어에 걸린 SELECT가 N개 모일 때까지 보류한다 — "테스트가 결과를
// 조작"하는 게 아니라 "N개의 동시 요청이 실제로 서로의 쓰기를 보지 못하는
// 창(window)"을 결정론적으로 만드는 것이다. 순차(비동시) 시나리오는 배리어
// 크기를 1로 둬 매 SELECT가 즉시 응답하므로(레이스 없음) 정상적인
// check-then-insert가 그대로 재현된다 — 즉 시퀀셜 케이스는 기존
// testRewardServerHardeningBehavior.mjs §7과 동일한 "상한이 정확히
// 강제된다"를 회귀 대조군으로 다시 확인한다.
//
// 등록: npm run verify:reward-cap-race (extra:true, non-gating)
// production 요청 0, 실제 DB 접촉 0. api/grant-xp.js/rewardEngine.js는
// 한 글자도 수정하지 않고 esbuild로 그대로 번들해 구동한다.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

// ── 1) 독립 인메모리 가짜 Supabase(배리어 지원 COUNT) ───────────────────
const fakePath = path.join(TMP, 'fakeSupabaseForRewardCapRace.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testRewardCapRace.mjs — 이 세션 전용, 다른
// 테스트의 산출물과 이름이 겹치지 않는다(fakeSupabaseForRewardApi.mjs와는
// 별개 파일).
export const __db = { students: [], reward_ledger: [] }
export const __calls = []
let barrierSize = 1
let pendingCap = []

export function __reset() {
  __db.students = []
  __db.reward_ledger = []
  __calls.length = 0
  barrierSize = 1
  pendingCap = []
}

// barrierSize > 1 이면 cap-count SELECT가 barrierSize개 모일 때까지
// resolve를 보류한다(위 파일 헤더 "정직한 TOCTOU 모델링" 참고). 각 SELECT는
// 호출된 그 순간의 정확한 카운트를 스냅샷해 두므로, 배리어가 풀릴 때 각자
// 자신이 호출된 시점의(=아직 서로의 INSERT를 보지 못한) 값을 돌려받는다.
export function __setCapBarrier(n) {
  barrierSize = n
  pendingCap = []
}

function matchRow(row, filters) {
  return filters.every(([c, v]) => {
    if (c.startsWith('gte:')) return String(row[c.slice(4)]) >= String(v)
    return String(row[c]) === String(v)
  })
}

function flushPendingCap() {
  const batch = pendingCap
  pendingCap = []
  for (const entry of batch) entry.resolve({ data: null, count: entry.snapshotCount, error: null })
}

function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['gte:' + col, val]); return q },
    maybeSingle() {
      __calls.push({ table, op: 'maybeSingle', filters: [...filters] })
      const rows = __db[table] || []
      const hit = rows.find((r) => matchRow(r, filters))
      return Promise.resolve({ data: hit || null, error: null })
    },
    then(resolve) {
      const isCapCount = table === 'reward_ledger' && headCount
      __calls.push({ table, op: isCapCount ? 'capCount' : (headCount ? 'count' : 'select'), filters: [...filters] })
      const rows = __db[table] || []
      const hit = rows.filter((r) => matchRow(r, filters))
      if (!isCapCount || barrierSize <= 1) {
        resolve({ data: headCount ? null : hit, count: hit.length, error: null })
        return
      }
      // 배리어 대상(cap-count) — 지금 이 순간의 정확한 개수를 스냅샷해
      // 두고, barrierSize개가 다 모이면 한꺼번에 flush한다.
      pendingCap.push({ resolve, snapshotCount: hit.length })
      if (pendingCap.length >= barrierSize) flushPendingCap()
    },
  }
  return q
}

export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          __calls.push({ table, op: 'insert', row })
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: row.created_at || new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

// ── 2) _pinAuth 스텁 — 실제 서명/검증 함수는 그대로 재사용(인증 로직 자체는
// 이 테스트 대상이 아니다, testSessionTokenAuth.mjs가 이미 전담) ─────────
const realPinAuthUrl = pathToFileURL(path.resolve('api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForRewardCapRace.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuthUrl)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

// ── 3) api/grant-xp.js를 무수정 그대로 esbuild 번들 ─────────────────────
const outfile = path.join(TMP, 'grantXp.capRace.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-cap-race',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default
const { REWARD_DAILY_CAP } = await import('../src/utils/rewardEngine.js')

process.env.SESSION_SECRET = 'reward-cap-race-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

const STUDENT = 'aaaaaaaa-1111-4222-8333-444444444444'
const today = new Date().toDateString()
const tokenFor = (sid) => signSessionToken(sid)

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
function post(body) {
  const withAuth = (body.token === undefined) ? { ...body, token: tokenFor(body.studentId) } : body
  const r = res()
  return handler({ method: 'POST', body: withAuth, headers: {} }, r).then(() => r)
}
function seedAtCapMinusOne(rewardType, n) {
  fake.__reset()
  fake.__db.students.push({ id: STUDENT })
  for (let i = 0; i < n; i++) {
    fake.__db.reward_ledger.push({
      student_id: STUDENT, reward_type: rewardType, idempotency_key: `seed-${rewardType}-${i}`,
      stars_delta: 1, created_at: new Date().toISOString(),
    })
  }
}
const rewardType = 'pronunciation' // cap 120 — REWARD_DAILY_CAP['pronunciation'], rewardEngine.js:556
const cap = REWARD_DAILY_CAP[rewardType]
const reqBody = (i) => ({
  ledger: 'reward', studentId: STUDENT, rewardType,
  sourceType: 'pronunciation', sourceId: `raceTok${i}:${today}`,
})

console.log(`\n0. 픽스처 확인 — rewardType='${rewardType}' 상한(cap) = ${cap}`)
check('cap이 최소 5 이상(N=5 동시 요청 시나리오를 담기 위한 전제)', cap >= 5)

console.log('\n1. 회귀 대조군(순차) — N개 순차 요청이면 상한이 정확히 강제된다')
{
  fake.__setCapBarrier(1) // 배리어 없음 = 매 SELECT 즉시 응답(레이스 없음)
  seedAtCapMinusOne(rewardType, cap - 1)
  const N = 3
  const results = []
  for (let i = 0; i < N; i++) results.push(await post(reqBody(`seq${i}`)))
  const oks = results.filter((r) => r.body?.ok === true).length
  const capped = results.filter((r) => r.body?.reason === 'daily_cap_reached').length
  check(`순차 ${N}회 중 정확히 1건 성공(count=cap-1에서 시작)`, oks === 1)
  check(`나머지 ${N - 1}건은 daily_cap_reached로 거부`, capped === N - 1)
  check(`원장 최종 건수 = cap(${cap}) — 초과 없음`, fake.__db.reward_ledger.length === cap)
}

console.log('\n2. ★ 동시 요청(Promise.all) — 서로 다른 sourceId N개가 count=cap-1에서 경합')
{
  const N = 5
  fake.__setCapBarrier(N) // N개의 cap-count SELECT가 다 모여야 응답(정직한 TOCTOU 창)
  seedAtCapMinusOne(rewardType, cap - 1)
  const results = await Promise.all(Array.from({ length: N }, (_, i) => post(reqBody(`race${i}`))))
  const successCount = results.filter((r) => r.body?.ok === true).length
  const cappedCount = results.filter((r) => r.body?.reason === 'daily_cap_reached').length
  console.log(`  관측: 동시 ${N}건 중 성공 ${successCount}건, 거부 ${cappedCount}건, 원장 최종 ${fake.__db.reward_ledger.length}건(시작 ${cap - 1}건 + 성공분)`)
  console.log(`  관측된 초과분(overshoot) = 성공 ${successCount}건 - 상한상 기대 1건 = ${successCount - 1}`)
  check('성공 건수는 1 이상 N 이하(핸들러가 크래시하거나 전부 거부되지 않음)', successCount >= 1 && successCount <= N)
  check('원장 최종 건수 = 시작(cap-1) + 성공 건수(정합성)', fake.__db.reward_ledger.length === (cap - 1) + successCount)
  check(
    'KNOWN GAP (결정 대기): 동시 요청이 상한을 초과할 수 있다 — DB 레벨 (student,type,day) 가드 부재. ' +
    '이 단언은 "지금 이 동작이 실제로 재현된다"를 기록하는 것이지 바람직하다는 뜻이 아니다 — DB 가드가 ' +
    '도입되면 successCount는 항상 1이 되어 이 단언은 뒤집힌다(그때 이 테스트를 반드시 함께 갱신할 것).',
    successCount > 1,
  )
}

console.log('\n3. 대조군 — 같은 이벤트(같은 sourceId) 동시 N회는 여전히 정확히 1건만 (idempotency 무회귀)')
{
  fake.__setCapBarrier(1) // idempotency 방어는 배리어와 무관 — insert 자체가 동기적으로 직렬화된다
  seedAtCapMinusOne(rewardType, 0)
  const N = 8
  const sameBody = reqBody('same-event')
  const results = await Promise.all(Array.from({ length: N }, () => post(sameBody)))
  check(`동시 ${N}회(같은 sourceId) -> 원장 정확히 1건`, fake.__db.reward_ledger.length === 1)
  check('성공 응답 중 duplicate:false는 정확히 1건, 나머지는 duplicate:true 또는 성공(23505 흡수)',
    results.every((r) => r.body?.ok === true))
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '모든 단언 통과 — 동시 요청 상한 레이스 관측 고정(레이스 자체는 KNOWN GAP, 해결 아님) ✅'
  : `${failures}개 단언 실패 ❌`)
process.exit(failures === 0 ? 0 : 1)
