// scripts/testTownFullLoop45.mjs
//
// QA 하네스(2026-09-11, qa/town-loop-hardening-2026-09-11) — Phase 9 "학생당
// 전 구간 루프"(로그인 → 학습 이벤트 → 서버 보상 원장 → 폴달러 트리거 →
// 마을 환영/조회/구매/이동 → 새로고침/재로그인) + Phase 8 "구매 경계 엣지
// 케이스" 8종을 5/10/20/45명 동시성 규모로 종단 검증한다.
//
// ── 정직한 고지(이 저장소 관례, testTownPurchaseStress45.mjs/testTownV1Sql.mjs
// 와 동일 원칙) ─────────────────────────────────────────────────────────────
// 이 파일은 실제 PostgreSQL을 구동하지 않는다. api/grant-xp.js 핸들러
// 코드는 한 글자도 바꾸지 않고 esbuild로 그대로 번들해 실행하지만, 그
// 핸들러가 호출하는 supabase.rpc('purchase_town_item'|'get_town_shop_state'|
// 'grant_town_welcome_credit', ...)와 reward_ledger AFTER INSERT 트리거
// (fn_reward_ledger_to_dollars, supabase_v3_49_paul_dollar.sql)는 순수 JS
// 인메모리 시뮬레이션이다 — supabase_v3_49/v3_50 SQL 파일의 문장 순서와
// 반환 shape을 최대한 충실히 미러링할 뿐, Postgres 트랜잭션/
// pg_advisory_xact_lock 자체의 원자성을 구동하지 않는다("설계가 이대로면
// 경합이 이렇게 수렴해야 한다"를 검증하는 근사 — 실제 배포 후 재확인은
// 별도).
//
// ── 재사용(복사, import 아님 — CLAUDE.md 규칙 3 "재구현 금지"의 반대
// 방향: 이미 검증된 패턴을 다시 발명하지 않는다) ───────────────────────────
//   · scripts/testTownWelcomeExactlyOnce.mjs — api/grant-xp.js를 esbuild로
//     무수정 번들 + fake @supabase/supabase-js + fake _pinAuth.js(실제
//     sign/verifySessionToken 재사용) 골격, claim_town_welcome 더블클릭
//     시나리오.
//   · scripts/testTownPurchaseStress45.mjs — purchase_town_item RPC
//     시뮬레이터의 문장 순서(학생확인→아이템/화폐조회→레벨잠금(advisory
//     lock 이전)→학생별 advisory lock(promise 체인)→잔액재계산→
//     already_owned→insufficient→두 INSERT 원자적)와 townLevelForStars
//     레벨 매핑.
//   · scripts/testTownLayoutIsolationStress45.mjs — useStudent 훅 배선
//     (fakeReact.mjs renderHook/createFakeClock + wordLibraryRaceStub.mjs)
//     으로 배치(placeTownItem/moveTownItem) 격리 stress + mergeTownLayout
//     스테일 tombstone 프로브.
//   · scripts/testRewardStress45.mjs — reward_ledger 인메모리 가짜(select/
//     eq/gte/maybeSingle/then(count) 체인, 학생 존재확인 L1/중복확인
//     L2.5/일일상한 L3 지원)의 makeQuery/matchRow 헬퍼.
//
// 이 파일이 새로 더하는 것: 위 네 패턴을 하나의 학생별 "전 구간" 흐름으로
// 엮고(로그인→학습 보상 4종→폴달러 트리거→환영→조회→구매(성공/잠김/
// 무효아이템/무효학생)→배치→이동→새로고침→재로그인), Phase 8 구매 경계
// 엣지 케이스(정확한 잔액/중복/타임아웃 재시도/잠금 해제/두 탭 동시성)를
// 추가한다. 기존 형제 테스트가 이미 다루는 것(환영 10시나리오, 구매
// 5/10/20/45 stress, 배치 격리 stress)은 재구현하지 않는다.
//
// src/api 수정 0, git/DDL 실행 0, 네트워크 0(Production 요청 절대 없음),
// 실제 Production 호출 없음. 실행 전 useStudent 훅 번들이 없으면 먼저
// `node scripts/buildRaceBundle.mjs`.
//
// 실행: `node scripts/buildRaceBundle.mjs && node scripts/testTownFullLoop45.mjs`

import esbuild from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'
import { mergeTownLayout } from '../src/utils/town/townLayout.js'

const ROOT = path.resolve(fileURLToPath(import.meta.url), '..', '..')
const TMP = path.join(ROOT, 'scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let asserted = 0
let failures = 0
function check(label, cond, detail) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}${detail !== undefined ? ' — ' + JSON.stringify(detail) : ''}`); failures++ }
}
function section(name) { console.log(`\n-- ${name} --`) }

console.log('='.repeat(78))
console.log('scripts/testTownFullLoop45.mjs — Paul Town V1 "학생당 전 구간 루프"')
console.log('⚠️  이 파일은 JS 인메모리 시뮬레이션이다(supabase_v3_49/v3_50 SQL 계약을')
console.log('    미러링) — 실제 PostgreSQL 트랜잭션/advisory lock을 구동하지 않는다.')
console.log('    api/grant-xp.js 핸들러 코드 자체는 esbuild로 무수정 그대로 번들한다.')
console.log('='.repeat(78))

// ============================================================================
// 0. 가짜 @supabase/supabase-js — reward_ledger(makeQuery 재사용) + 3개
//    town RPC(get_town_shop_state/purchase_town_item/grant_town_welcome_credit)
//    시뮬레이터를 한 모듈에 결합. reward_ledger.insert()가 성공하면 그
//    자리에서 AFTER INSERT 트리거(fn_reward_ledger_to_dollars)를 흉내내
//    dollar_ledger에 같은 비율(rate=1, v3_49 시드)로 폴달러 행을 추가한다.
// ============================================================================
const townLevelUrl = pathToFileURL(path.join(ROOT, 'src/utils/town/townLevel.js')).href
const fakePath = path.join(TMP, 'fakeSupabaseForFullLoop45.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testTownFullLoop45.mjs — 독립 산출물(다른
// 테스트의 fake와 파일명/전역 상태 공유 없음).
import { townLevelForStars } from ${JSON.stringify(townLevelUrl)}

export const __db = { students: [], reward_ledger: [], dollar_ledger: [], town_purchases: [], town_items: [] }
export const __locks = new Map()
export const __calls = []

// reward_ledger -> dollar_ledger 트리거 비율(supabase_v3_49_paul_dollar.sql
// dollar_rules 시드, 이 테스트가 실제로 쓰는 4종만 — 나머지 8종은 이
// 시나리오에서 호출하지 않으므로 생략해도 무해).
const DOLLAR_RATE_BY_REWARD_TYPE = {
  'word-session-complete': 1,
  'writing-complete': 1,
  'daily-goal-complete': 1,
  'wrong-word-recovered': 1,
}

function seedTownItems() {
  // supabase_v3_50_town_v1.sql 카탈로그의 부분집합(가격/레벨 그대로) — 이
  // 테스트가 실제로 필요로 하는 3개만.
  __db.town_items = [
    { id: 'tree', name: '나무', emoji: '🌳', price: 10, price_currency: 'dollars', active: true, category: 'nature', sort_order: 10, min_level: 1, asset_key: 'nature/tree' },
    { id: 'cat', name: '고양이', emoji: '🐱', price: 20, price_currency: 'dollars', active: true, category: 'animal', sort_order: 10, min_level: 2, asset_key: 'animals/cat' },
    { id: 'bench', name: '벤치', emoji: '🪑', price: 15, price_currency: 'dollars', active: true, category: 'decoration', sort_order: 20, min_level: 1, asset_key: 'decorations/bench' },
  ]
}
seedTownItems()

export function __reset() {
  __db.students = []
  __db.reward_ledger = []
  __db.dollar_ledger = []
  __db.town_purchases = []
  seedTownItems()
  __locks.clear()
  __calls.length = 0
}
export function __seedStudent(id) {
  if (!__db.students.some((s) => s.id === id)) __db.students.push({ id })
}
// 테스트 전용 스캐폴딩(v3_50 계약의 일부가 아님) — Phase 8 "정확한 잔액"류
// 엣지 케이스를 실제 보상 이벤트를 여러 번 반복하지 않고 정확한 시작
// 잔액으로 세팅하기 위한 직접 시드(dollar_ledger에 임의 양수 1행 추가).
export function __seedDollar(sid, amount, tag) {
  __db.dollar_ledger.push({
    student_id: sid, event_type: 'seed:' + tag, dollars_delta: amount,
    source_type: 'seed', source_id: tag,
    idempotency_key: sid + ':seed:' + tag + ':' + Math.random().toString(36).slice(2),
  })
}

function tick() { return new Promise((r) => setImmediate(r)) }

function matchRow(row, filters) {
  return filters.every(([c, v]) => {
    if (c.startsWith('__gte__')) return String(row[c.slice(7)]) >= String(v)
    return String(row[c]) === String(v)
  })
}
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    async maybeSingle() {
      await tick()
      const rows = __db[table] || []
      const hit = rows.find((r) => matchRow(r, filters))
      return { data: hit || null, error: null }
    },
    then(resolve, reject) {
      ;(async () => {
        await tick()
        const rows = __db[table] || []
        const hit = rows.filter((r) => matchRow(r, filters))
        resolve({ data: headCount ? null : hit, count: hit.length, error: null })
      })().catch(reject)
    },
  }
  return q
}

// fn_reward_ledger_to_dollars(v3_49) 흉내 — reward_ledger에 양수 stars_delta
// 행이 커밋되면 같은 트랜잭션(여기서는 같은 insert() 호출) 안에서 dollar_rules
// 화이트리스트 비율만큼 dollar_ledger에도 행을 추가한다. idempotency_key는
// 원본 키 + ':dollar'(on conflict do nothing과 동일하게 중복 방지).
function injectDollarFromReward(row) {
  const rate = DOLLAR_RATE_BY_REWARD_TYPE[row.reward_type]
  if (!(row.stars_delta > 0) || !rate) return
  const key = row.idempotency_key + ':dollar'
  if (__db.dollar_ledger.some((e) => e.idempotency_key === key)) return
  __db.dollar_ledger.push({
    student_id: row.student_id,
    event_type: 'reward:' + row.reward_type,
    dollars_delta: row.stars_delta * rate,
    source_type: row.source_type,
    source_id: row.source_id,
    idempotency_key: key,
  })
}

function dollarBalance(sid) { return __db.dollar_ledger.filter((e) => e.student_id === sid).reduce((s, e) => s + e.dollars_delta, 0) }
function starsEarnedOf(sid) { return __db.reward_ledger.filter((e) => e.student_id === sid).reduce((s, e) => s + (e.stars_delta > 0 ? e.stars_delta : 0), 0) }
function ownedItemsOf(sid) { return __db.town_purchases.filter((p) => p.student_id === sid).map((p) => p.item_id) }

function getTownShopStateSim(sid) {
  const stars = starsEarnedOf(sid)
  const avail = dollarBalance(sid)
  const earned = __db.dollar_ledger.filter((e) => e.student_id === sid && e.dollars_delta > 0).reduce((s, e) => s + e.dollars_delta, 0)
  const spent = __db.dollar_ledger.filter((e) => e.student_id === sid && e.dollars_delta < 0).reduce((s, e) => s - e.dollars_delta, 0)
  return { stars_earned: stars, dollars_available: Math.max(0, avail), dollars_earned: earned, dollars_spent: spent, owned_item_ids: ownedItemsOf(sid) }
}

async function grantWelcomeSim(sid) {
  await tick()
  if (!__db.students.some((s) => s.id === sid)) return { granted: false, balance_after: 0 }
  const key = sid + ':welcome:town-v1'
  if (__db.dollar_ledger.some((e) => e.idempotency_key === key)) return { granted: false, balance_after: dollarBalance(sid) }
  __db.dollar_ledger.push({ student_id: sid, event_type: 'welcome:town-v1', dollars_delta: 20, source_type: 'welcome', source_id: 'town-v1', idempotency_key: key })
  return { granted: true, balance_after: dollarBalance(sid) }
}

// 학생별 advisory lock 흉내(testTownPurchaseStress45.mjs와 동일 패턴) — 같은
// studentId 호출끼리만 promise 체인으로 직렬화, 다른 studentId는 완전 병렬.
function withStudentLock(sid, fn) {
  const prevTail = __locks.get(sid) || Promise.resolve()
  const result = prevTail.then(() => fn())
  __locks.set(sid, result.then(() => undefined, () => undefined))
  return result
}

async function purchaseTownItemSim(sid, itemId) {
  if (!__db.students.some((s) => s.id === sid)) return { ok: false, reason: 'student_not_found', dollars_spent: 0, balance_after: 0 }
  await tick()
  const item = __db.town_items.find((i) => i.id === itemId && i.active)
  if (!item) return { ok: false, reason: 'item_not_found', dollars_spent: 0, balance_after: 0 }
  if (item.price_currency !== 'dollars') return { ok: false, reason: 'item_not_purchasable', dollars_spent: 0, balance_after: 0 }
  await tick()
  const level = townLevelForStars(starsEarnedOf(sid))
  if (item.min_level > level) {
    return { ok: false, reason: 'locked', dollars_spent: 0, balance_after: dollarBalance(sid) }
  }
  return withStudentLock(sid, async () => {
    await tick()
    const balance = dollarBalance(sid)
    if (ownedItemsOf(sid).includes(itemId)) return { ok: true, reason: 'already_owned', dollars_spent: 0, balance_after: balance }
    if (balance < item.price) return { ok: false, reason: 'insufficient', dollars_spent: 0, balance_after: balance }
    if (__db.town_purchases.some((p) => p.student_id === sid && p.item_id === itemId)) return { ok: true, reason: 'already_owned', dollars_spent: 0, balance_after: balance }
    __db.town_purchases.push({ student_id: sid, item_id: itemId, currency: 'dollars', price_paid: item.price })
    __db.dollar_ledger.push({ student_id: sid, event_type: 'purchase:' + itemId, dollars_delta: -item.price, source_type: 'purchase', source_id: itemId, idempotency_key: sid + ':purchase:' + itemId })
    return { ok: true, reason: 'purchased', dollars_spent: item.price, balance_after: balance - item.price }
  })
}

export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        async insert(row) {
          await tick()
          if (!__db[table]) __db[table] = []
          const dup = row.idempotency_key && __db[table].some((r) => r.idempotency_key === row.idempotency_key)
          if (dup) return { error: { code: '23505', message: 'duplicate key' } }
          const stored = { ...row, id: table + __db[table].length, created_at: row.created_at || new Date().toISOString() }
          __db[table].push(stored)
          if (table === 'reward_ledger') injectDollarFromReward(stored)
          return { error: null }
        },
      }
    },
    async rpc(name, args) {
      __calls.push({ rpc: name, args })
      if (name === 'get_town_shop_state') return { data: [getTownShopStateSim(args.p_student_id)], error: null }
      if (name === 'purchase_town_item') return { data: [await purchaseTownItemSim(args.p_student_id, args.p_item_id)], error: null }
      if (name === 'grant_town_welcome_credit') return { data: [await grantWelcomeSim(args.p_student_id)], error: null }
      return { data: null, error: { code: 'XX000', message: 'unknown rpc ' + name } }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const realPinAuthUrl = pathToFileURL(path.join(ROOT, 'api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForFullLoop45.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuthUrl)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const outfile = path.join(TMP, 'grantXp.fullLoop45.bundle.mjs')
await esbuild.build({
  entryPoints: [path.join(ROOT, 'api/grant-xp.js')],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-fullloop45',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fakeDb = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default
process.env.SESSION_SECRET = 'town-full-loop45-test-secret'
process.env.TOWN_V1_WELCOME_ENABLED = '1'
const { signSessionToken } = await import(pathToFileURL(path.join(ROOT, 'api/_pinAuth.js')).href)

// ============================================================================
// 1. useStudent 훅 배선(배치/이동/새로고침/재로그인 전용) — scripts/
//    testTownLayoutIsolationStress45.mjs와 동일 산출물(scripts/.tmp/
//    useStudent.race.bundle.mjs)을 재사용한다. 없으면 먼저
//    `node scripts/buildRaceBundle.mjs`.
// ============================================================================
const raceBundlePath = path.join(TMP, 'useStudent.race.bundle.mjs')
if (!fs.existsSync(raceBundlePath)) {
  console.log(`  FAIL  ${raceBundlePath} 가 없습니다 — 먼저 'node scripts/buildRaceBundle.mjs'를 실행하세요.`)
  process.exit(1)
}

class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(type, fn) { (this.listeners[type] ||= []).push(fn) }
  removeEventListener(type, fn) { this.listeners[type] = (this.listeners[type] || []).filter((f) => f !== fn) }
  dispatch(type) { (this.listeners[type] || []).forEach((fn) => fn()) }
}

globalThis.localStorage = new FakeStorage()
globalThis.document = new FakeDocument()
const raceStub = await import(pathToFileURL(path.join(ROOT, 'scripts/wordLibraryRaceStub.mjs')).href)
const { useStudent } = await import(pathToFileURL(raceBundlePath).href)
raceStub.setStrictBackup(null)

function freshMount(studentId) {
  raceStub.resetFetchFullProgressDeferred()
  globalThis.document = new FakeDocument()
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(studentId), clock)
  return { host, clock }
}

// ============================================================================
// 2. 호출 헬퍼 — api/grant-xp.js 핸들러를 직접 호출(HTTP 없음).
// ============================================================================
function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
async function callReward(studentId, rewardType, sourceType, sourceId, token) {
  const r = res()
  await handler({ method: 'POST', body: { ledger: 'reward', studentId, rewardType, sourceType, sourceId, token: token || signSessionToken(studentId) }, headers: {} }, r)
  return r
}
async function callTown(action, body, token) {
  const r = res()
  await handler({ method: 'POST', body: { action, ...body, token }, headers: {} }, r)
  return r
}
function jitter(maxMs) { return new Promise((r) => setTimeout(r, Math.random() * maxMs)) }

const TODAY = new Date().toDateString() // rewardEngine.js DATE_TOKEN_RE 실제 형식

// ============================================================================
// PHASE 9 — 학생당 전 구간 루프, N ∈ {5,10,20,45}
// ============================================================================
console.log('\n' + '='.repeat(78))
console.log('PHASE 9 — 학생당 전 구간 루프(로그인→학습 보상→환영→구매→배치→새로고침/재로그인)')
console.log('='.repeat(78))

async function runStudentFull(sid, idx, isWrongWord) {
  await jitter(30) // "0-30ms jitter" — 학생 간 동시 시작 시각 흩뿌리기
  fakeDb.__seedStudent(sid) // 로그인 전제(학생 실재) — students 테이블 시드
  const token = signSessionToken(sid) // "로그인" — 세션 토큰 발급(studentId만 담음)

  // 학습 이벤트 3종(모든 학생 공통) + 일부 학생은 오답 회복 2건 추가.
  const rWord = await callReward(sid, 'word-session-complete', 'daily-words', TODAY, token)
  const rWrite = await callReward(sid, 'writing-complete', 'daily-writing', TODAY, token)
  const rGoal = await callReward(sid, 'daily-goal-complete', 'daily-goal', TODAY, token)
  let rWrong1 = null
  let rWrong2 = null
  if (isWrongWord) {
    rWrong1 = await callReward(sid, 'wrong-word-recovered', 'spelling-review', `${TODAY}:apple`, token)
    rWrong2 = await callReward(sid, 'wrong-word-recovered', 'spelling-review', `${TODAY}:banana`, token)
  }

  // 환영 크레딧을 더블클릭(동시 2회) — exactly-once 계약 재확인(다른 각도).
  const [w1, w2] = await Promise.all([
    callTown('claim_town_welcome', {}, token),
    callTown('claim_town_welcome', {}, token),
  ])

  const shopBefore = await callTown('get_town_shop_state', {}, token)
  const buyTree = await callTown('purchase_town_item', { itemId: 'tree' }, token) // 10, L1 — 성공 기대
  const buyCat = await callTown('purchase_town_item', { itemId: 'cat' }, token)   // 20, L2 — 레벨1 학생은 잠김 기대
  const buyInvalid = await callTown('purchase_town_item', { itemId: 'not-a-real-item' }, token) // item_not_found 기대
  const shopAfter = await callTown('get_town_shop_state', {}, token)

  return { sid, idx, wrong: isWrongWord, rWord, rWrite, rGoal, rWrong1, rWrong2, w1, w2, shopBefore, buyTree, buyCat, buyInvalid, shopAfter }
}

const LEVELS = [5, 10, 20, 45]
const tableRows = []

for (const N of LEVELS) {
  section(`N=${N} — 경제 루프(reward → dollar 트리거 → welcome → shop → purchase)`)
  fakeDb.__reset()
  globalThis.localStorage = new FakeStorage()

  const students = Array.from({ length: N }, () => crypto.randomUUID())
  check(`N=${N}: 학생 UUID ${N}개 전부 서로 다름`, new Set(students).size === N)

  const numPairs = Math.min(3, Math.floor(N / 2)) // N=5는 6명이 필요한 3쌍을 못 채워 2쌍으로 축소(문서화된 편차)
  const pairs = Array.from({ length: numPairs }, (_, p) => [2 * p, 2 * p + 1])
  const isWrongWord = (i) => i % 2 === 1 // "일부 학생"만 오답 회복 2건 추가

  const results = await Promise.all(students.map((sid, i) => runStudentFull(sid, i, isWrongWord(i))))

  // ── 학습 보상 4종 ok:true ────────────────────────────────────────────
  check(`N=${N}: 전원 word-session-complete ok:true`, results.every((r) => r.rWord.body.ok === true))
  check(`N=${N}: 전원 writing-complete ok:true`, results.every((r) => r.rWrite.body.ok === true))
  check(`N=${N}: 전원 daily-goal-complete ok:true`, results.every((r) => r.rGoal.body.ok === true))
  check(`N=${N}: wrong-word 대상 학생 전원 오답회복 2건 ok:true`,
    results.filter((r) => r.wrong).every((r) => r.rWrong1.body.ok === true && r.rWrong2.body.ok === true))

  // ── 환영(더블클릭) exactly-once ──────────────────────────────────────
  check(`N=${N}: 전원 welcome 더블클릭 중 정확히 1개만 granted:true`,
    results.every((r) => [r.w1.body.granted, r.w2.body.granted].filter(Boolean).length === 1))
  check(`N=${N}: 전원 welcome 응답 ok:true(granted 여부 무관)`,
    results.every((r) => r.w1.body.ok === true && r.w2.body.ok === true))

  // ── 구매 전 잔액/레벨 — 그룹별(3건 vs 5건 보상) 정확 ─────────────────
  check(`N=${N}: 구매 전 잔액 == 20(welcome) + 보상합(6 또는 8), 그룹별 정확`,
    results.every((r) => r.shopBefore.body.dollarsAvailable === 20 + (r.wrong ? 8 : 6)))
  check(`N=${N}: 구매 전 별 총량 == 6 또는 8(그룹별), 레벨 1`,
    results.every((r) => r.shopBefore.body.starsEarned === (r.wrong ? 8 : 6) && r.shopBefore.body.level === 1))

  // ── 구매: tree 성공 / cat 잠김 / 무효 아이템 ──────────────────────────
  check(`N=${N}: 전원 tree(10, L1) 구매 성공(reason:purchased, dollarsSpent:10)`,
    results.every((r) => r.buyTree.body.ok === true && r.buyTree.body.reason === 'purchased' && r.buyTree.body.dollarsSpent === 10))
  check(`N=${N}: 전원 cat(20, L2) 구매 시도 -> locked(레벨1 미달, 신규 학생 전원)`,
    results.every((r) => r.buyCat.body.ok === false && r.buyCat.body.reason === 'locked'))
  check(`N=${N}: 전원 존재하지 않는 아이템 -> item_not_found`,
    results.every((r) => r.buyInvalid.body.ok === false && r.buyInvalid.body.reason === 'item_not_found'))

  // ── 구매 후 상태 — 잔액/보유목록/별(불변)/레벨 ────────────────────────
  check(`N=${N}: 구매 후 잔액 == 10+보상(그룹별), == shopAfter.dollarsAvailable`,
    results.every((r) => {
      const expected = 10 + (r.wrong ? 8 : 6)
      return r.buyTree.body.balanceAfter === expected && r.shopAfter.body.dollarsAvailable === expected
    }))
  check(`N=${N}: 구매 후 dollarsSpent==10, dollarsEarned 불변(20+보상)`,
    results.every((r) => r.shopAfter.body.dollarsSpent === 10 && r.shopAfter.body.dollarsEarned === 20 + (r.wrong ? 8 : 6)))
  check(`N=${N}: 구매 후 owned에 tree 포함·cat 미포함 전원`,
    results.every((r) => r.shopAfter.body.owned.includes('tree') && !r.shopAfter.body.owned.includes('cat')))
  check(`N=${N}: 구매(cat locked 시도) 후에도 별 총량 불변(구매 실패가 별을 건드리지 않음)`,
    results.every((r) => r.shopAfter.body.starsEarned === r.shopBefore.body.starsEarned))
  check(`N=${N}: 구매 후에도 레벨 1 유지 전원(별 20 미만)`, results.every((r) => r.shopAfter.body.level === 1))

  // ── 원장 집계(전역) ───────────────────────────────────────────────────
  const expectedLedgerRows = students.reduce((s, _sid, i) => s + (isWrongWord(i) ? 5 : 3), 0)
  const ledgerRowsTotal = fakeDb.__db.reward_ledger.filter((e) => students.includes(e.student_id)).length
  check(`N=${N}: reward_ledger 총 행수 == ${expectedLedgerRows}(3 또는 5 x N)`, ledgerRowsTotal === expectedLedgerRows)

  const expectedDollarRows = expectedLedgerRows + N /* welcome */ + N /* tree 구매 */
  const dollarRowsTotal = fakeDb.__db.dollar_ledger.filter((e) => students.includes(e.student_id)).length
  check(`N=${N}: dollar_ledger 총 행수 == ${expectedDollarRows}(=보상 트리거행+welcome N+구매 N)`, dollarRowsTotal === expectedDollarRows)

  const welcomeGrantedCount = results.filter((r) => r.w1.body.granted || r.w2.body.granted).length
  check(`N=${N}: welcome 지급 학생 수 == N(=${N})`, welcomeGrantedCount === N)

  const treePurchases = fakeDb.__db.town_purchases.filter((p) => students.includes(p.student_id) && p.item_id === 'tree')
  check(`N=${N}: town_purchases(tree) == N(=${N}), 중복 0`,
    treePurchases.length === N && new Set(treePurchases.map((p) => p.student_id)).size === N)
  const catPurchases = fakeDb.__db.town_purchases.filter((p) => p.item_id === 'cat')
  check(`N=${N}: town_purchases(cat) == 0(전원 레벨1 미달로 잠김)`, catPurchases.length === 0)

  const lockedCount = results.filter((r) => r.buyCat.body.reason === 'locked').length
  const itemNotFoundCount = results.filter((r) => r.buyInvalid.body.reason === 'item_not_found').length

  // ── 인증 실패 — 등록되지 않은(유령) 학생 토큰: 서명은 유효하나 students에
  //    없음 -> RPC 데이터 계층에서 실패, 부작용(행 생성) 0 ─────────────────
  const ghostId = crypto.randomUUID()
  const ghostToken = signSessionToken(ghostId)
  const ghostPurchase = await callTown('purchase_town_item', { itemId: 'tree' }, ghostToken)
  check(`N=${N}: 미등록(유령) 학생 토큰으로 구매 시도 -> student_not_found`,
    ghostPurchase.body.ok === false && ghostPurchase.body.reason === 'student_not_found')
  const ghostRows = fakeDb.__db.dollar_ledger.filter((e) => e.student_id === ghostId).length
    + fakeDb.__db.town_purchases.filter((p) => p.student_id === ghostId).length
  check(`N=${N}: 유령 학생 관련 행 0개(auth 실패가 어떤 부작용도 남기지 않음)`, ghostRows === 0)
  const invalidCount = itemNotFoundCount + 1 // 무효 아이템 N건 + 유령 학생 1건

  // ── 교차 오염(leak) — 명단 밖 학생 행 0, 호출자 본인 studentId만 등장 ──
  const foreignReward = fakeDb.__db.reward_ledger.filter((e) => !students.includes(e.student_id) && e.student_id !== ghostId)
  const foreignDollar = fakeDb.__db.dollar_ledger.filter((e) => !students.includes(e.student_id) && e.student_id !== ghostId)
  const foreignPurchase = fakeDb.__db.town_purchases.filter((p) => !students.includes(p.student_id))
  check(`N=${N}: 명단 밖 학생 행 0(reward/dollar/purchase 전부)`,
    foreignReward.length === 0 && foreignDollar.length === 0 && foreignPurchase.length === 0)
  check(`N=${N}: 어떤 행도 호출자(studentId) 아닌 다른 학생으로 새지 않음`,
    results.every((r) => fakeDb.__db.dollar_ledger.filter((e) => e.idempotency_key.startsWith(r.sid + ':')).every((e) => e.student_id === r.sid)))

  let pairViolations = 0
  for (const [a, b] of pairs) {
    const sidA = students[a]
    const sidB = students[b]
    const aRows = fakeDb.__db.dollar_ledger.filter((e) => e.student_id === sidA)
    const bRows = fakeDb.__db.dollar_ledger.filter((e) => e.student_id === sidB)
    if (aRows.some((e) => e.idempotency_key.includes(sidB))) pairViolations++
    if (bRows.some((e) => e.idempotency_key.includes(sidA))) pairViolations++
  }
  check(`N=${N}: 동명이인 ${numPairs}쌍(UUID만 다름) dollar_ledger idempotency_key 교차오염 0`, pairViolations === 0)

  // ── lost — "성공"이라 응답했는데 실제 행이 없는 경우 0 ────────────────
  let lost = 0
  for (const r of results) {
    if (r.buyTree.body.reason === 'purchased' && !fakeDb.__db.town_purchases.some((p) => p.student_id === r.sid && p.item_id === 'tree')) lost++
    if ((r.w1.body.granted || r.w2.body.granted) && !fakeDb.__db.dollar_ledger.some((e) => e.idempotency_key === r.sid + ':welcome:town-v1')) lost++
  }
  check(`N=${N}: 구매/환영 성공 응답 중 실제 행 유실 0건`, lost === 0)

  // ==========================================================================
  // N=${N} — 배치 루프(useStudent 훅) — place → move → refresh → relogin
  // ==========================================================================
  section(`N=${N} — 배치 루프(useStudent 훅) — place → move → refresh → relogin`)
  const placementIdBySid = new Map()
  let placeFail = 0
  let moveFail = 0
  for (let i = 0; i < N; i++) {
    const sid = students[i]
    const { host } = freshMount(sid)
    const placeRes = host.result.placeTownItem('tree', 0, 0, ['tree']) // 구매 확정된 tree를 owned로 가정(경제 루프에서 실제로 성공 확인함)
    if (!placeRes.ok) placeFail++
    const pid = (host.result.townPlacements.find((p) => p.itemId === 'tree') || {}).placementId
    placementIdBySid.set(sid, pid)
    const moveRes = host.result.moveTownItem(pid, 1, 1)
    if (!moveRes.ok) moveFail++
  }
  check(`N=${N}: 전원 tree 배치 성공(설정 오류 0)`, placeFail === 0)
  check(`N=${N}: 전원 tree 이동 성공`, moveFail === 0)
  check(`N=${N}: placementId 전역 유일(공유 0)`, new Set(placementIdBySid.values()).size === N)

  let refreshMismatch = 0
  let reloginNotEmpty = 0
  for (let i = 0; i < N; i++) {
    const sid = students[i]
    const pid = placementIdBySid.get(sid)
    const { host: hostRefresh } = freshMount(sid) // 새로고침 — 같은 UUID, 같은 localStorage
    const p = hostRefresh.result.townPlacements.find((pp) => pp.placementId === pid)
    if (!p || p.x !== 1 || p.y !== 1) refreshMismatch++
    const otherId = crypto.randomUUID() // 재로그인 — 다른 UUID(전혀 다른 학생)
    const { host: hostOther } = freshMount(otherId)
    if (hostOther.result.townPlacements.length !== 0) reloginNotEmpty++
  }
  check(`N=${N}: 새로고침(재마운트, 동일 UUID) 후 전원 이동한 좌표(1,1) 유지`, refreshMismatch === 0)
  check(`N=${N}: 재로그인(다른 UUID) 시 전원 빈 레이아웃(교차 노출 0)`, reloginNotEmpty === 0)

  for (const [a, b] of pairs) {
    const sidA = students[a]
    const sidB = students[b]
    const { host: hostA } = freshMount(sidA)
    const { host: hostB } = freshMount(sidB)
    check(`N=${N}: 동명이인 쌍(idx ${a}/${b}) 배치 완전 격리(A/B 각 1건, placementId 불일치)`,
      hostA.result.townPlacements.length === 1 && hostB.result.townPlacements.length === 1 &&
      hostA.result.townPlacements[0].placementId !== hostB.result.townPlacements[0].placementId)
  }

  // ── 스테일 상태: 로컬(오래됨, 아직 배치가 보임) + 클라우드(이미
  //    tombstone) 병합 시 재소환 금지 ─────────────────────────────────────
  const staleSid = students[0]
  const stalePid = placementIdBySid.get(staleSid)
  const staleLocalStillHasIt = { townPlacements: [{ placementId: stalePid, itemId: 'tree', x: 1, y: 1, placedAt: 1000, updatedAt: 1000 }], townRemovedIds: [] }
  const staleCloudAlreadyTombstoned = { townPlacements: [], townRemovedIds: [stalePid] }
  const staleMerged = mergeTownLayout(staleLocalStillHasIt, staleCloudAlreadyTombstoned)
  check(`N=${N}: 스테일 로컬(오래된 스냅샷, 배치 아직 보임) + 클라우드(이미 tombstone) 병합 -> 재소환 없음`,
    !staleMerged.townPlacements.some((p) => p.placementId === stalePid))
  check(`N=${N}: 병합 후 tombstone 유지(union)`, staleMerged.townRemovedIds.includes(stalePid))

  const leaksThisLevel = foreignReward.length + foreignDollar.length + foreignPurchase.length + pairViolations
  tableRows.push({
    N, students: N, ledgerRows: ledgerRowsTotal, dollarRows: dollarRowsTotal,
    welcome: welcomeGrantedCount, purchases: treePurchases.length, locked: lockedCount,
    invalid: invalidCount, leaks: leaksThisLevel, lost,
  })
}

// ── 표 출력 ──────────────────────────────────────────────────────────────
console.log('\n=== PHASE 9 요약 표 ===')
{
  const header = ['level', 'students', 'ledger rows', 'dollar rows', 'welcome', 'purchases', 'locked', 'invalid', 'leaks', 'lost']
  console.log('  ' + header.map((h) => h.padStart(12)).join(' | '))
  for (const row of tableRows) {
    console.log('  ' + [
      row.N, row.students, row.ledgerRows, row.dollarRows, row.welcome, row.purchases, row.locked, row.invalid, row.leaks, row.lost,
    ].map((v) => String(v).padStart(12)).join(' | '))
  }
}
{
  const grandLeaks = tableRows.reduce((s, r) => s + r.leaks, 0)
  const grandLost = tableRows.reduce((s, r) => s + r.lost, 0)
  check('PHASE 9 전체 합산 — 모든 레벨 leaks 합계 0', grandLeaks === 0)
  check('PHASE 9 전체 합산 — 모든 레벨 lost 합계 0', grandLost === 0)
  check('PHASE 9 전체 합산 — 4개 동시성 레벨 전부 실행됨(5/10/20/45)',
    tableRows.length === 4 && tableRows.every((r, i) => r.N === LEVELS[i]))
}

// ============================================================================
// PHASE 8 — 구매 경계 엣지 케이스 8종(단일 학생, 마지막 1건만 2탭 동시성)
// ============================================================================
console.log('\n' + '='.repeat(78))
console.log('PHASE 8 — 구매 경계 엣지 케이스(정확한 잔액/중복/타임아웃/잠금해제/두 탭 등)')
console.log('='.repeat(78))

let negBalance = 0
let doubleCharge = 0
let dupOwnership = 0
let wrongStudent = 0
let lockedBypass = 0
let lostUpdate = 0

section('8.1 정확한 잔액 — balance 10, item 10 -> 성공, 잔액 0, 이후 구매 -> insufficient')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  fakeDb.__seedDollar(sid, 10, 'exact-balance')
  const token = signSessionToken(sid)
  const r1 = await callTown('purchase_town_item', { itemId: 'tree' }, token)
  check('8.1 정확한 잔액(10) — tree(10) 구매 성공, 잔액 0', r1.body.ok === true && r1.body.reason === 'purchased' && r1.body.balanceAfter === 0)
  const r2 = await callTown('purchase_town_item', { itemId: 'bench' }, token) // 15, L1(레벨 무관 — 잔액만 문제)
  check('8.1 잔액 0에서 bench(15) 구매 -> insufficient', r2.body.ok === false && r2.body.reason === 'insufficient')
  if (r1.body.balanceAfter < 0 || r2.body.balanceAfter < 0) negBalance++
  if (!fakeDb.__db.town_purchases.some((p) => p.student_id === sid && p.item_id === 'tree')) lostUpdate++
}

section('8.2 중복 구매(성공 후 재요청) — already_owned, 0 차감')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  fakeDb.__seedDollar(sid, 10, 'dup')
  const token = signSessionToken(sid)
  await callTown('purchase_town_item', { itemId: 'tree' }, token)
  const r2 = await callTown('purchase_town_item', { itemId: 'tree' }, token)
  check('8.2 중복 구매 -> already_owned, dollarsSpent 0', r2.body.ok === true && r2.body.reason === 'already_owned' && r2.body.dollarsSpent === 0)
  const owned = fakeDb.__db.town_purchases.filter((p) => p.student_id === sid && p.item_id === 'tree')
  if (owned.length > 1) dupOwnership++
  if (r2.body.dollarsSpent > 0) doubleCharge++
}

section('8.3 타임아웃 재시도 — 첫 호출은 서버에서 커밋됐지만 응답 유실 가정, 재전송 -> already_owned')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  fakeDb.__seedDollar(sid, 10, 'timeout')
  const token = signSessionToken(sid)
  const r1 = await callTown('purchase_town_item', { itemId: 'tree' }, token) // 서버 커밋 완료(응답은 "유실"됐다고 가정 — 이 테스트 관점에서는 확인하지 않음)
  const r2 = await callTown('purchase_town_item', { itemId: 'tree' }, token) // 클라이언트 재전송
  check('8.3 첫 호출 실제로 커밋됨(참고용)', r1.body.ok === true && r1.body.reason === 'purchased')
  check('8.3 타임아웃 재시도(재전송) -> already_owned', r2.body.ok === true && r2.body.reason === 'already_owned' && r2.body.dollarsSpent === 0)
  const owned = fakeDb.__db.town_purchases.filter((p) => p.student_id === sid && p.item_id === 'tree')
  if (owned.length > 1) dupOwnership++
  if (r2.body.dollarsSpent > 0) doubleCharge++
}

section('8.4 잠금 -> 해제 — 별 19(레벨1) locked, 별 20(레벨2 달성) 구매 성공')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  const token = signSessionToken(sid)
  for (let i = 0; i < 19; i++) await callReward(sid, 'wrong-word-recovered', 'spelling-review', `${TODAY}:tok${i}`, token)
  const rLocked = await callTown('purchase_town_item', { itemId: 'cat' }, token)
  check('8.4 별 19(레벨1) — cat(L2) 구매 시도 -> locked', rLocked.body.ok === false && rLocked.body.reason === 'locked')
  if (rLocked.body.ok === true) lockedBypass++
  await callReward(sid, 'wrong-word-recovered', 'spelling-review', `${TODAY}:tok19`, token) // 20번째 -> 별 20 -> 레벨2
  const rUnlocked = await callTown('purchase_town_item', { itemId: 'cat' }, token)
  check('8.4 별 20(레벨2 달성) — cat(L2) 구매 성공, 잔액 0(20원 정확히 지불)',
    rUnlocked.body.ok === true && rUnlocked.body.reason === 'purchased' && rUnlocked.body.balanceAfter === 0)
}

section('8.5 무효 아이템 -> item_not_found')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  const token = signSessionToken(sid)
  const r = await callTown('purchase_town_item', { itemId: 'no-such-item' }, token)
  check('8.5 존재하지 않는 아이템 -> item_not_found', r.body.ok === false && r.body.reason === 'item_not_found')
}

section('8.6 무효 학생(존재하지 않는 uuid) -> student_not_found')
{
  fakeDb.__reset()
  const ghost = crypto.randomUUID() // students에 절대 시드하지 않음
  const token = signSessionToken(ghost) // 서명 자체는 유효(HMAC은 studentId 존재를 모름) — RPC 데이터 계층이 최종 거부
  const r = await callTown('purchase_town_item', { itemId: 'tree' }, token)
  check('8.6 존재하지 않는 학생 uuid -> student_not_found', r.body.ok === false && r.body.reason === 'student_not_found')
  if (r.body.ok === true) wrongStudent++
  if (fakeDb.__db.town_purchases.some((p) => p.student_id === ghost)) wrongStudent++
}

section('8.7 두 탭 — 같은 토큰/같은 아이템 동시 2회 -> 정확히 성공 1 + already_owned 1')
{
  fakeDb.__reset()
  const sid = crypto.randomUUID()
  fakeDb.__seedStudent(sid)
  fakeDb.__seedDollar(sid, 10, 'twotabs')
  const token = signSessionToken(sid)
  const [ra, rb] = await Promise.all([
    callTown('purchase_town_item', { itemId: 'tree' }, token),
    callTown('purchase_town_item', { itemId: 'tree' }, token),
  ])
  const purchasedCount = [ra, rb].filter((r) => r.body.reason === 'purchased').length
  const ownedCount = [ra, rb].filter((r) => r.body.reason === 'already_owned').length
  check('8.7 두 탭 동시 동일 토큰/아이템 -> 정확히 성공 1 + already_owned 1(never both/never neither)',
    purchasedCount === 1 && ownedCount === 1)
  if (purchasedCount > 1) doubleCharge++
  const ownedRows = fakeDb.__db.town_purchases.filter((p) => p.student_id === sid && p.item_id === 'tree')
  if (ownedRows.length !== 1) dupOwnership++
}

console.log('\n=== PHASE 8 종합 단언(전체 8종에 걸쳐 0이어야 함) ===')
check('PHASE 8 종합 — 음수 잔액(negative balance) 0건', negBalance === 0)
check('PHASE 8 종합 — 이중 차감(double charge) 0건', doubleCharge === 0)
check('PHASE 8 종합 — 중복 소유(duplicate ownership) 0건', dupOwnership === 0)
check('PHASE 8 종합 — 타 학생 오염(wrong-student) 0건', wrongStudent === 0)
check('PHASE 8 종합 — 잠금 우회(locked bypass) 0건', lockedBypass === 0)
check('PHASE 8 종합 — 유실 업데이트(lost update) 0건', lostUpdate === 0)

// ============================================================================
console.log('\n' + '='.repeat(78))
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '모든 단언 통과 — Paul Town V1 전 구간 루프(Phase 9) + 구매 경계 엣지 케이스(Phase 8) 무결성 확인'
  : `${failures}개 단언 실패`)
process.exit(failures === 0 ? 0 : 1)
