// scripts/testMissionBonusIdempotency.mjs
//
// 레거시 `daily-mission-bonus`(+10) 중복 지급 버그 회귀 고정 (2026-08-23).
//
// ── 확정된 원인 ─────────────────────────────────────────────────────────
// useStudent.js의 4/4 완료 useEffect가 같은 tick 안에서
//   L1391  grantReward(+10, `daily-mission-bonus:<signature>`)  ← starGrantLog에 키 기록
//   L1421  patch(() => ({ round: freshRound() }))               ← starGrantLog = [] ★
// 를 연달아 실행한다. freshRound()가 방금 기록한 dedup 키를 지워버리므로
// 이 이벤트에는 중복 방지 기억이 남지 않는다. 유일한 가드인 handledRoundRef는
// useRef라 재마운트(새로고침/재로그인/탭 전환)마다 null로 초기화된다.
//
// 여기에 병합 로직(useStudent.js 597~611)이 결합한다:
//   wordsViewed: unionList / examplesHeard·quizSolved·pronunciationOk: maxNum
// 즉 freshRound()로 0이 된 카운터가 클라우드/다른 탭 사본과 병합되면 다시
// 4/4로 복원되는데, dedup 기억은 복원되지 않는다 → 학습 액션 0개로 +10과
// 선물상자가 재발한다.
//
// ── production 실측 증거 ────────────────────────────────────────────────
//   · starGrantLog가 비어있지 않은 학생 16명의 키 종류:
//     pronunciation 66 / spelling-combo 99 / matchgame 32 / daily-mission-bonus **0**
//     (같은 로그 안에서 다른 키는 살아남는데 이것만 전멸)
//   · 권교빈 2026-07-23: 선물상자 37개 = 퀴즈 185회 필요, 실제 기록 20회
//   · 이상 지급 총합 570별(전체 획득 별의 3.0%), 그중 510별이 위 하루에 집중
//
// ── 수정 ────────────────────────────────────────────────────────────────
// 리셋이 dedup 기억을 지우지 않게 한다(1줄):
//   patch(prev => ({ round: { ...freshRound(), starGrantLog: prev.round.starGrantLog } }))
// 자정 롤오버는 별도 경로(round.date !== todayStr() -> round: freshRound())가
// 담당하므로 일별 초기화는 그대로 유지된다.
//
// 구동 방식은 scripts/testRewardIdempotencyStress.mjs와 동일한 하네스를
// 재사용한다(fakeReact.mjs + 자체 esbuild 번들 + wordLibrary 스텁). 산출물
// 경로만 이 파일 전용으로 분리해 기존 테스트와 충돌하지 않게 한다(규칙 16).
//
// 등록: npm run verify:mission-bonus
// production 소스 무접촉(검증만). 네트워크 0, Supabase 0, 학생 데이터 0.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'

const TMP_DIR = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP_DIR, { recursive: true })
const raceStubUrl = pathToFileURL(path.resolve('scripts/wordLibraryRaceStub.mjs')).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const stubPath = path.join(TMP_DIR, 'wordLibraryMissionBonusStub.mjs')
fs.writeFileSync(stubPath, `// AUTO-GENERATED by scripts/testMissionBonusIdempotency.mjs — do not edit by hand.
export * from ${JSON.stringify(raceStubUrl)}
export async function postRewardEvent() {}
`, 'utf8')
const stubUrl = pathToFileURL(stubPath).href

const outfile = path.join(TMP_DIR, 'useStudent.missionBonus.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'mission-bonus-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: stubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)
const stub = await import(stubUrl)
const { useStudent } = await import(pathToFileURL(outfile).href)

class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(t, f) { (this.listeners[t] ||= []).push(f) }
  removeEventListener() {}
  dispatch() {}
}

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}
const flush = () => new Promise(r => process.nextTick(r))
const STORE = 'paul_easy_progress'
const ID = '99999999-1111-2222-3333-444444444444'

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}
function mountOnCurrentEnv() {
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(ID, 'QA_MissionBonus'), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return host
}
function mountFresh() { freshEnv(); return mountOnCurrentEnv() }
// 같은 localStorage 위에서 새 렌더 트리 = 새로고침 / 재로그인 / 탭 전환
function remount() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  return mountOnCurrentEnv()
}
const settle = (h) => { h.rerender(); return h }
const logOf = (h) => (h.result.round?.starGrantLog) || []
const hasMissionKey = (h) => logOf(h).some(k => String(k).startsWith('daily-mission-bonus'))
const giftsToday = (h) => {
  const d = h.result.history?.[h.result.round?.date]
  return Number(d?.giftsToday) || 0
}
function completeFullRound(host, prefix) {
  for (let i = 0; i < 5; i++) host.result.markWordViewed(`${prefix}-v${i}`)
  for (let i = 0; i < 5; i++) host.result.markExampleHeard()
  for (let i = 0; i < 5; i++) host.result.markQuizSolved()
  for (let i = 0; i < 5; i++) host.result.markPronunciationOk(`${prefix}-p${i}`)
  settle(host)
}
// 병합(unionList/maxNum)이 카운터를 4/4로 되살리는 상황을 저장소에 그대로 재현.
// starGrantLog는 앱이 실제로 저장한 값을 그대로 둔다 — 그게 이 버그의 핵심이다.
function simulateMergeRestore(prefix) {
  const store = JSON.parse(globalThis.localStorage.getItem(STORE) || '{}')
  const rec = store[ID]
  if (!rec) throw new Error('저장된 레코드 없음')
  rec.round.wordsViewed = Array.from({ length: 5 }, (_, i) => `${prefix}-v${i}`)
  rec.round.examplesHeard = 5
  rec.round.quizSolved = 5
  rec.round.pronunciationOk = 5
  globalThis.localStorage.setItem(STORE, JSON.stringify(store))
  return rec
}

console.log('\n=== daily-mission-bonus 중복 지급 회귀 고정 ===')

console.log('\n1. 정상 4/4 완료 — 보상이 정확히 1회 지급되는가')
let host = mountFresh()
settle(host)
await flush()
const stars0 = host.result.stars
completeFullRound(host, 'r1')
await flush(); settle(host)
const gained1 = host.result.stars - stars0
check(`4/4 완료로 별이 늘었다 (+${gained1})`, gained1 > 0)
check('미션 보너스 +10이 포함됐다', gained1 >= 10)
check(`선물상자 1개 지급 (실제 ${giftsToday(host)})`, giftsToday(host) === 1)

console.log('\n2. ★ 핵심 — 지급 후 dedup 기억이 남아 있는가')
check('starGrantLog에 daily-mission-bonus 키가 남아 있다 (수정 전에는 freshRound()가 지움)',
  hasMissionKey(host))

console.log('\n3. 재마운트 + 병합 복원(새로고침/재로그인/탭 전환) — 재지급 0이어야 한다')
const starsAfterRound = host.result.stars
const giftsAfterRound = giftsToday(host)
simulateMergeRestore('r1')
let host2 = remount()
settle(host2); await flush(); settle(host2)
check(`학습 액션 0개인데 별이 늘지 않았다 (${starsAfterRound} -> ${host2.result.stars})`,
  host2.result.stars === starsAfterRound)
check(`선물상자도 늘지 않았다 (${giftsAfterRound} -> ${giftsToday(host2)})`,
  giftsToday(host2) === giftsAfterRound)

console.log('\n4. 복원 반복 5회 — 누적 재지급 0이어야 한다')
{
  let h = host2
  const base = h.result.stars
  const baseGifts = giftsToday(h)
  for (let i = 0; i < 5; i++) {
    simulateMergeRestore('r1')
    h = remount()
    settle(h); await flush(); settle(h)
  }
  check(`5회 반복 복원 후에도 별 증가 0 (${base} -> ${h.result.stars})`, h.result.stars === base)
  check(`선물상자 증가 0 (${baseGifts} -> ${giftsToday(h)})`, giftsToday(h) === baseGifts)
  host2 = h
}

console.log('\n5. 무회귀 — 실제로 새 라운드를 다시 하면 보상은 정상 지급된다')
{
  const before = host2.result.stars
  const beforeGifts = giftsToday(host2)
  completeFullRound(host2, 'r2')
  await flush(); settle(host2)
  const gained = host2.result.stars - before
  check(`새 라운드(액션 20개) 완료 시 보상 정상 지급 (+${gained})`, gained >= 10)
  check(`선물상자도 1개 추가 (${beforeGifts} -> ${giftsToday(host2)})`, giftsToday(host2) === beforeGifts + 1)
  check('새 라운드의 dedup 키도 로그에 남는다', hasMissionKey(host2))
}

console.log('\n6. 소스 계약 — 리셋이 dedup 기억을 보존한다')
{
  const src = fs.readFileSync('src/hooks/useStudent.js', 'utf8')
  const code = src.split('\n').map(l => l.replace(/\r$/, '').replace(/\/\/.*$/, '')).join('\n')
  check('4/4 완료 경로가 starGrantLog를 통째로 버리지 않는다',
    !/patch\(\(\) => \(\{ round: freshRound\(\) \}\)\)/.test(code))
  check('리셋 시 이전 starGrantLog를 이어받는다',
    /round: \{ \.\.\.freshRound\(\), starGrantLog: prev\.round\.starGrantLog \}/.test(code))
  check('자정 롤오버 경로는 여전히 전체 초기화(일별 리셋 유지)',
    /round\.date !== todayStr\(\)/.test(code) && /round: freshRound\(\),/.test(code))
}

console.log('\n7. daily-goal-complete(+3, Reward V1)는 같은 취약 구조인가 — 조사용 검증')
{
  // 구조 차이: rewardLedger는 record **최상위** 필드라 freshRound()가 건드리지
  // 않는다(freshRound 정의에 rewardLedger 언급 0건). 그래서 1차 가드
  // hasRewardEntry(rewardLedger, key)가 라운드 리셋을 넘어 살아남는다.
  // daily-mission-bonus는 1차 가드가 round.starGrantLog뿐이라 함께 지워졌다.
  const src = fs.readFileSync('src/hooks/useStudent.js', 'utf8')
  const code = src.split('\n').map(l => l.replace(/\r$/, '').replace(/\/\/.*$/, '')).join('\n')
  const freshRoundBody = (code.match(/const freshRound = \(\) => \(\{[\s\S]*?\n\}\)/) || [''])[0]
  check('freshRound()가 rewardLedger를 초기화하지 않는다', !/rewardLedger/.test(freshRoundBody))
  check('rewardLedger는 record 최상위 필드', /^\s*rewardLedger: \[\],/m.test(code))
  check('grantLedgerReward의 1차 가드가 rewardLedger(영속) 기준', /hasRewardEntry\(rewardLedger, key\)/.test(code))
  check('병합도 원장 단위(mergeRewardLedgers)로 보존', /rewardLedger: mergeRewardLedgers\(/.test(code))
  check('daily-goal-complete는 날짜 키(하루 1회)를 쓴다', /grantLedgerReward\('daily-goal-complete', 'daily-goal', todayStr\(\)\)/.test(code))

  // 실측: 4/4 라운드를 완료한 뒤 복원-재마운트를 3회 반복해도 원장에
  // daily-goal-complete 항목이 정확히 1건이어야 한다.
  const ledgerOf = (h) => (Array.isArray(h.result.rewardLedger) ? h.result.rewardLedger : [])
  const goalEntries = (h) => ledgerOf(h).filter(e => e && e.reward_type === 'daily-goal-complete').length
  let h = mountFresh()
  settle(h); await flush()
  completeFullRound(h, 'g1')
  await flush(); settle(h)
  const after1 = goalEntries(h)
  check(`4/4 완료 후 daily-goal-complete 원장 1건 (실제 ${after1})`, after1 === 1)
  for (let i = 0; i < 3; i++) {
    simulateMergeRestore('g1')
    h = remount()
    settle(h); await flush(); settle(h)
  }
  check(`복원-재마운트 3회 후에도 여전히 1건 (실제 ${goalEntries(h)}) — 취약하지 않음`, goalEntries(h) === 1)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0 ? '모든 단언 통과 — daily-mission-bonus 중복 지급 고정 ✅' : `${failures}개 단언 실패 ❌`)
process.exit(failures === 0 ? 0 : 1)
