// PIN 자기설정 계정 탈취 차단 — 보안 계약 테스트 (2026-08-29)
//
// 배경(감사 실측): 최초 PIN 설정 시점에는 학생과 서버가 공유하는 비밀이
// 없다. 학생의 유일한 자격증명이 될 것이 바로 지금 만들려는 그 PIN이기
// 때문이다. 그래서 api/self-set-student-pin.js의 두 게이트
// (pin_setup_allowed===true / pin_hash IS NULL)는 "요청자가 그 학생
// 본인인가"에 대해 아무것도 말해주지 않는다 — 둘 다 계정의 *상태*일 뿐이다.
//
// 확인된 공격 체인(실제 공격은 수행하지 않음, 모델링만):
//   A. anon key로 students.id 열거 가능(라이브 HTTP 200 실측 — 로그인
//      화면이 반 명단을 그리려면 필요해서 구조적으로 열려 있다)
//   B. 관리자가 어떤 학생에게 "PIN 설정 허용"을 눌러 둔 상태
//   C. 무인증 /api/student-pin-status 가 pinSetupAllowed 를 불리언으로
//      돌려준다(anon 직접 조회는 42501로 막혀 있는데 service_role 이
//      우회 노출)
//   D. 무인증 /api/self-set-student-pin 으로 공격자가 임의 PIN 설정
//   E. verify-student-pin 로그인 -> signSessionToken 발급 -> 그 학생의
//      보상 원장 쓰기 권한까지 획득(2026-08-24 인증 강화가 무력화됨)
//
// 해결(A안, 운영자 승인 2026-08-29): 관리자가 발급하는 1회용 setup code를
// 제2 인증 요소로 요구한다. 코드는 SESSION_SECRET 에서 파생하므로
// **어디에도 저장하지 않는다**:
//   code = base32( HMAC-SHA256(SESSION_SECRET,
//                  'pinsetup:v1:' + studentId + ':' + bucket) )[0..7]
//   bucket = floor(now / 10분).  현재/직전 두 버킷을 허용 -> 유효기간은
//   최소 10분, **최대 20분**(운영자 지정 TTL 20분을 절대 넘지 않는다).
// 1회성은 새 플래그 없이 기존 원자적 UPDATE(.is('pin_hash', null))가
// 그대로 강제한다 — 성공 즉시 pin_hash 가 NULL -> NOT NULL 로 전이하므로
// 같은 코드로 다시 시도해도 already_set 이다. 즉 **DB 컬럼/테이블 추가 0**.
//
// 하네스: api/self-set-student-pin.js / student-pin-status.js /
// verify-student-pin.js / admin-pin-actions.js 를 esbuild 로 번들하되
// @supabase/supabase-js 만 인메모리 가짜로 치환해 실제 핸들러를 구동한다
// (production 코드 무수정). 네트워크 0, 실제 DB 접촉 0, 실학생 요청 0.
// 기존 scripts/testStudentPinSelfSetup.mjs 는 프로덕션 Supabase 에 QA
// 학생/반을 INSERT 하므로(그래서 anon INSERT 락다운 이후 항상 SKIP)
// 이 시나리오의 FAIL-first 재현에 쓸 수 없다 — 그 대체재가 이 파일이다.
//
// 등록: npm run verify:pin-setup-capability
import fs from 'node:fs'
import path from 'node:path'
import esbuild from 'esbuild'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

process.env.SESSION_SECRET = 'pin-setup-capability-test-secret'
process.env.ADMIN_PIN = '4729'

// ── 가짜 Supabase — 이 4개 핸들러가 쓰는 체이닝만 구현 ────────────────────
const fakePath = path.join(TMP, 'fakeSupabaseForPinSetup.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testPinSetupCapability.mjs
export const __db = { students: [], classes: [] }
export function __reset() { __db.students = []; __db.classes = [] }
const val = (row, col) => (col === 'classes(name)' ? undefined : row[col])
function matches(row, filters) {
  return filters.every(([kind, col, v]) => {
    if (kind === 'eq') return val(row, col) === v
    if (kind === 'in') return v.includes(val(row, col))
    if (kind === 'is') return val(row, col) === null || val(row, col) === undefined
    if (kind === 'ilike') {
      const pat = String(v).replace(/%/g, '').toLowerCase()
      return String(val(row, col) ?? '').toLowerCase() === pat
    }
    return true
  })
}
function makeQuery(table) {
  const filters = []
  let mode = 'select'
  let patch = null
  const q = {
    select() { return q },
    eq(c, v) { filters.push(['eq', c, v]); return q },
    in(c, v) { filters.push(['in', c, v]); return q },
    is(c, _v) { filters.push(['is', c, null]); return q },
    ilike(c, v) { filters.push(['ilike', c, v]); return q },
    update(p) { mode = 'update'; patch = p; return q },
    insert(rows) { mode = 'insert'; patch = rows; return q },
    limit() { return q },
    order() { return q },
    then(resolve) { resolve(run()); return Promise.resolve(run()) },
    maybeSingle() { const r = run(); return Promise.resolve({ data: r.data[0] ?? null, error: r.error }) },
    single() { const r = run(); return Promise.resolve({ data: r.data[0] ?? null, error: r.error }) },
  }
  function run() {
    const rows = __db[table] || []
    if (mode === 'update') {
      const hit = rows.filter((r) => matches(r, filters))
      for (const r of hit) Object.assign(r, patch)
      return { data: hit.map((r) => ({ ...r })), error: null }
    }
    if (mode === 'insert') {
      const list = Array.isArray(patch) ? patch : [patch]
      for (const r of list) rows.push({ ...r })
      return { data: list.map((r) => ({ ...r })), error: null }
    }
    return { data: rows.filter((r) => matches(r, filters)).map((r) => ({ ...r })), error: null }
  }
  return q
}
export function createClient() { return { from: (t) => makeQuery(t) } }
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

// _pinAuth 는 실제 구현을 쓴다(해싱/서명/코드 파생이 검증 대상) —
// supabase 접속 정보만 가짜로 바꾼다.
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForPinSetup.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export * from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const ENTRIES = {
  selfSet: 'api/self-set-student-pin.js',
  status: 'api/student-pin-status.js',
  login: 'api/verify-student-pin.js',
  admin: 'api/admin-pin-actions.js',
}
const handlers = {}
for (const [key, entry] of Object.entries(ENTRIES)) {
  const outfile = path.join(TMP, `pinSetup.${key}.bundle.mjs`)
  await esbuild.build({
    entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', outfile,
    plugins: [{
      name: 'fake-deps',
      setup(b) {
        b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
        b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
      },
    }],
  })
  handlers[key] = (await import(pathToFileURL(outfile).href + '?t=' + Date.now())).default
}

const fake = await import(fakeUrl)
const pinAuth = await import(realPinAuth)

function callHandler(handler, body, headers = {}) {
  return new Promise((resolve) => {
    const res = {
      statusCode: 0, body: null,
      status(c) { this.statusCode = c; return this },
      json(b) { this.body = b; resolve({ statusCode: this.statusCode, body: b }) },
    }
    handler({ method: 'POST', body, headers }, res)
  })
}

let failures = 0, asserted = 0
function check(label, cond, detail) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}${detail ? ' — ' + detail : ''}`); failures++ }
}

const SID = '11111111-2222-4333-8444-555555555555'
const SID2 = '99999999-8888-4777-8666-555555555555'
const CLASS_ID = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'
const ADMIN_PIN = process.env.ADMIN_PIN

function seed({ allowed = true, pinHash = null, id = SID, name = 'QA초등학생' } = {}) {
  fake.__reset()
  fake.__db.classes.push({ id: CLASS_ID, name: 'QA반' })
  fake.__db.students.push({
    id, name, class_id: CLASS_ID, unit_name: 'Unit 1',
    pin_hash: pinHash, pin_setup_allowed: allowed, pin_fail_count: 0, pin_locked_until: null,
  })
  return fake.__db.students.find((s) => s.id === id)
}
// 수정 전(파생 API 부재) 상태에서도 하네스가 끝까지 돌아 FAIL 증거를
// 남기도록, 코드가 없으면 통과할 리 없는 더미 문자열을 쓴다.
const codeNow = (id) => pinAuth.pinSetupCode?.(id) ?? '__NOCODE__'

console.log('\n=== PIN 자기설정 탈취 차단 — 보안 계약 ===\n')

console.log('0. 파생 코드 API 계약 (SESSION_SECRET 기반, 저장 없음)')
{
  check('pinSetupCode / verifyPinSetupCode 가 export 되어 있다',
    typeof pinAuth.pinSetupCode === 'function' && typeof pinAuth.verifyPinSetupCode === 'function')
  const c = codeNow(SID)
  check('코드가 8자다', typeof c === 'string' && c.length === 8, String(c))
  check('코드에 혼동 문자(0/1/8/9)가 없다', typeof c === 'string' && !/[0189]/.test(c), String(c))
  check('같은 학생·같은 시각이면 코드가 안정적이다', c === codeNow(SID))
  check('학생이 다르면 코드가 다르다', c !== codeNow(SID2))
  check('코드에 studentId 원문이 들어있지 않다', typeof c === 'string' && !c.includes(SID.slice(0, 8)))
  check('코드에 SESSION_SECRET 조각이 들어있지 않다',
    typeof c === 'string' && !c.toUpperCase().includes('SECRET'))
  const ttl = pinAuth.PIN_SETUP_CODE_TTL_MS
  check('TTL 상수가 20분이다', ttl === 20 * 60 * 1000, String(ttl))
}

console.log('\n1. [공격 D] UUID만 알고 코드 없이 self-set — 반드시 거부')
{
  seed({ allowed: true })
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468' })
  check('코드 없는 요청은 거부된다', r.body?.ok === false, JSON.stringify(r.body))
  check('거부 사유가 setup_code 계열이다', /code/.test(String(r.body?.reason)), String(r.body?.reason))
  check('pin_hash 가 여전히 비어 있다', fake.__db.students[0].pin_hash == null)
  check('pin_setup_allowed 가 소모되지 않았다(정상 학생이 나중에 쓸 수 있어야 함)',
    fake.__db.students[0].pin_setup_allowed === true)
}

console.log('\n2. 잘못된 코드 — 거부')
{
  seed({ allowed: true })
  // 2026-09-01 — 이 목록에 있던 `codeNow(SID).slice(0, 7) + 'Z'`는 실제 코드의
  // 8번째 문자가 우연히 'Z'일 때(알파벳 32자 중 1자 = 약 1/32 확률) 진짜 유효한
  // 코드와 같아져 이 단언이 무작위로 FAIL하던 flaky 픽스처였다. "마지막 한
  // 글자만 다른 well-formed 코드"라는 원래 의도는 그대로 두고 결정적으로 만든다
  // — verifyPinSetupCode가 허용하는 모든 버킷(직전/현재)과, 실행 도중 버킷
  // 경계를 넘는 경우의 다음 버킷까지 세 코드의 마지막 문자를 전부 제외한
  // 문자를 고르므로 어떤 타이밍에도 유효 코드와 일치할 수 없다(확률 논증 아님).
  const BUCKET_MS = 10 * 60 * 1000
  const nearbyCodes = [
    codeNow(SID),
    pinAuth.pinSetupCode?.(SID, { now: Date.now() - BUCKET_MS }) ?? '',
    pinAuth.pinSetupCode?.(SID, { now: Date.now() + BUCKET_MS }) ?? '',
  ]
  const usedLastChars = new Set(nearbyCodes.map((c) => c.slice(-1)))
  // 후보 4개 중 배제되는 건 최대 3개(버킷 3개)라 반드시 하나가 남는다.
  const swapChar = ['A', 'B', 'C', 'D'].find((ch) => !usedLastChars.has(ch))
  const lastCharDiffers = codeNow(SID).slice(0, 7) + swapChar
  // 규칙 15 — 픽스처 자체가 유효한지(진짜 코드와 정말 다른지) 먼저 단언한다.
  check('마지막 글자만 바꾼 픽스처가 유효 코드 어느 버킷과도 다르다(테스트 자체의 유효성)',
    typeof swapChar === 'string' && !nearbyCodes.includes(lastCharDiffers))
  for (const bad of ['AAAAAAAA', '', 'ZZZZ', codeNow(SID2), lastCharDiffers]) {
    const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: bad })
    check(`잘못된 코드 거부: ${JSON.stringify(String(bad).slice(0, 10))}`, r.body?.ok === false)
  }
  check('실패 시도 후에도 pin_hash 는 비어 있다', fake.__db.students[0].pin_hash == null)
}

console.log('\n3. 만료된 코드 — 거부 (TTL 20분 초과)')
{
  seed({ allowed: true })
  const past = Date.now() - 21 * 60 * 1000
  const expired = pinAuth.pinSetupCode(SID, { now: past })
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: expired })
  check('21분 전 코드는 거부된다', r.body?.ok === false, JSON.stringify(r.body))
  const fresh9 = pinAuth.pinSetupCode(SID, { now: Date.now() - 9 * 60 * 1000 })
  check('9분 전 코드는 아직 유효하다(정상 UX)',
    pinAuth.verifyPinSetupCode(SID, fresh9).ok === true)
  const old31 = pinAuth.pinSetupCode(SID, { now: Date.now() - 31 * 60 * 1000 })
  check('31분 전 코드는 무효다', pinAuth.verifyPinSetupCode(SID, old31).ok === false)
}

console.log('\n4. 다른 학생의 코드로 교차 사용 — 거부')
{
  seed({ allowed: true })
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: codeNow(SID2) })
  check('학생 B 코드로 학생 A PIN 설정 불가', r.body?.ok === false)
  check('pin_hash 미변경', fake.__db.students[0].pin_hash == null)
}

console.log('\n5. 정상 최초 설정 — 반드시 성공 (회귀 방지)')
{
  seed({ allowed: true })
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: codeNow(SID) })
  check('정상 코드 + 정상 PIN 이면 설정 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('pin_hash 가 저장됐다', typeof fake.__db.students[0].pin_hash === 'string' && fake.__db.students[0].pin_hash.length > 0)
  check('pin_setup_allowed 가 false 로 원복됐다(1회성)', fake.__db.students[0].pin_setup_allowed === false)
  check('응답에 pin_hash / 코드가 실려 나가지 않는다',
    !JSON.stringify(r.body).includes('pin_hash') && !JSON.stringify(r.body).includes(codeNow(SID)))
}

console.log('\n6. [replay] 같은 코드 재사용 — 거부')
{
  seed({ allowed: true })
  const code = codeNow(SID)
  const first = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: code })
  check('1회차 성공', first.body?.ok === true)
  const firstHash = fake.__db.students[0].pin_hash
  for (let i = 0; i < 5; i++) {
    const again = await callHandler(handlers.selfSet, { studentId: SID, pin: '9911', pinConfirm: '9911', setupCode: code })
    check(`재사용 ${i + 1}회차 거부(already_set)`, again.body?.ok === false && again.body?.reason === 'already_set')
  }
  check('재사용 시도 후에도 PIN 해시가 바뀌지 않았다', fake.__db.students[0].pin_hash === firstHash)
}

console.log('\n7. 이미 PIN 이 있는 계정 덮어쓰기 — 거부')
{
  const s = seed({ allowed: true, pinHash: pinAuth.hashPin('1357') })
  const before = s.pin_hash
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: codeNow(SID) })
  check('유효한 코드가 있어도 기존 PIN 은 덮어쓸 수 없다', r.body?.ok === false && r.body?.reason === 'already_set')
  check('PIN 해시 불변', fake.__db.students[0].pin_hash === before)
}

console.log('\n8. pin_setup_allowed=false — 유효한 코드가 있어도 거부')
{
  seed({ allowed: false })
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: codeNow(SID) })
  check('관리자 허용이 없으면 코드가 있어도 거부', r.body?.ok === false && r.body?.reason === 'not_allowed')
  check('pin_hash 미변경', fake.__db.students[0].pin_hash == null)
}

console.log('\n9. SESSION_SECRET 미설정 — fail-closed')
{
  seed({ allowed: true })
  const saved = process.env.SESSION_SECRET
  const code = codeNow(SID)
  delete process.env.SESSION_SECRET
  const r = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: code })
  const derived = pinAuth.pinSetupCode(SID)
  const verified = pinAuth.verifyPinSetupCode(SID, 'ANYTHING')
  process.env.SESSION_SECRET = saved
  check('시크릿 없으면 코드를 발급하지 않는다(null)', derived === null, String(derived))
  check('시크릿 없으면 어떤 코드도 통과시키지 않는다', verified.ok === false && verified.reason === 'no_secret')
  check('시크릿 없으면 PIN 설정이 거부된다(fail-closed)', r.body?.ok === false)
  check('pin_hash 미변경', fake.__db.students[0].pin_hash == null)
}

console.log('\n9b. SESSION_SECRET 미설정 — 관리자 일괄 발급도 코드를 새어보내지 않는다')
{
  // 2026-08-30 추가 — 관리자 발급 관점(§11/§11b)에서도 fail-closed가
  // 지켜지는지 확인한다. §9는 self-set 관점만 다뤄서 이 갭이 비어 있었다.
  seed({ allowed: false })
  fake.__db.students.push({ id: SID2, name: 'QA다른학생', class_id: CLASS_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: false, pin_fail_count: 0, pin_locked_until: null })
  const saved = process.env.SESSION_SECRET
  delete process.env.SESSION_SECRET
  const r = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID, SID2], allowed: true, adminPin: ADMIN_PIN })
  const selfSet = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: 'ANYTHING' })
  process.env.SESSION_SECRET = saved
  check('시크릿 없어도 허용 자체(pin_setup_allowed 토글)는 기존대로 성공한다', r.body?.ok === true, JSON.stringify(r.body))
  check('시크릿 없으면 setupCodes가 빈 배열이다(코드가 새어나가지 않는다)',
    Array.isArray(r.body?.setupCodes) && r.body.setupCodes.length === 0, JSON.stringify(r.body?.setupCodes))
  check('시크릿 없는 상태에서 발급된(사실상 없는) 코드로는 self-set이 여전히 거부된다', selfSet.body?.ok === false)
}

console.log('\n10. [공격 C] student-pin-status 열거 축소')
{
  seed({ allowed: true })
  fake.__db.students.push({ id: SID2, name: 'QA다른학생', class_id: CLASS_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null })
  const many = Array.from({ length: 300 }, (_, i) => `id-${i}`)
  const r = await callHandler(handlers.status, { studentIds: many })
  check('대량 배치 조회는 거부된다(열거 축소)', r.statusCode === 400 || (r.body?.results || []).length === 0, JSON.stringify(r.body).slice(0, 120))
  const ok = await callHandler(handlers.status, { studentIds: [SID, SID2] })
  check('정상 크기 배치는 기존대로 동작한다(회귀 방지)', Array.isArray(ok.body?.results) && ok.body.results.length === 2)
  check('응답에 pin_hash 원문이 없다', !JSON.stringify(ok.body).includes('pin_hash'))
  check('응답에 setup code 가 들어있지 않다', !JSON.stringify(ok.body).includes(codeNow(SID)))
}

console.log('\n11. 관리자만 코드를 발급받는다')
{
  seed({ allowed: false })
  const noAuth = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID], allowed: true })
  check('adminPin 없으면 허용/발급 모두 거부', noAuth.body?.ok !== true, JSON.stringify(noAuth.body).slice(0, 90))
  check('거부 시 코드가 응답에 없다', !JSON.stringify(noAuth.body).includes(codeNow(SID)))
  const authed = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID], allowed: true, adminPin: ADMIN_PIN })
  check('adminPin 이면 허용 성공', authed.body?.ok === true, JSON.stringify(authed.body).slice(0, 90))
  const codes = authed.body?.setupCodes
  check('허용 시 setup code 가 함께 발급된다', Array.isArray(codes) && codes.length === 1)
  check('발급된 코드가 서버 파생값과 일치한다', codes?.[0]?.code === codeNow(SID))
  check('발급 응답에 만료 시각이 포함된다', typeof codes?.[0]?.expiresAt === 'number' && codes[0].expiresAt > Date.now())
  check('발급 응답에 SESSION_SECRET 이 없다', !JSON.stringify(authed.body).includes(process.env.SESSION_SECRET))
  const revoke = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID], allowed: false, adminPin: ADMIN_PIN })
  check('allowed=false 회수 시에는 코드를 발급하지 않는다', !revoke.body?.setupCodes)
}

console.log('\n11b. 반별 일괄 발급 — N명분 코드 계약 (UI 회귀 고정용)')
{
  // 2026-08-30 추가 — §11은 단건(studentIds: [SID])만 검증해서, 서버가
  // N명분을 한번에 돌려주는 계약(각 항목의 studentId로 매칭해야 하는 것)이
  // 비어 있었다. 이 계약이 UI 쪽 handleBulkAllowPinSetup 회귀(§14)의 근거.
  seed({ allowed: false })
  fake.__db.students.push({ id: SID2, name: 'QA다른학생', class_id: CLASS_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: false, pin_fail_count: 0, pin_locked_until: null })
  const bulk = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID, SID2], allowed: true, adminPin: ADMIN_PIN })
  check('일괄 허용 성공', bulk.body?.ok === true, JSON.stringify(bulk.body).slice(0, 120))
  const codes = bulk.body?.setupCodes
  check('반환된 코드가 2건이다', Array.isArray(codes) && codes.length === 2, JSON.stringify(codes))
  const c1 = codes?.find((c) => c.studentId === SID)
  const c2 = codes?.find((c) => c.studentId === SID2)
  check('학생 A 코드가 서버 파생값과 일치한다', c1?.code === codeNow(SID))
  check('학생 B 코드가 서버 파생값과 일치한다', c2?.code === codeNow(SID2))
  check('두 학생의 코드가 서로 다르다', !!c1?.code && !!c2?.code && c1.code !== c2.code)
  check('각 항목에 studentId가 담겨 UI가 UUID로 이름을 매칭할 수 있다(헌법 규칙 4)',
    Array.isArray(codes) && codes.every((c) => typeof c.studentId === 'string' && c.studentId.length > 0))
  check('각 항목에 만료 시각이 있고 미래다',
    Array.isArray(codes) && codes.every((c) => typeof c.expiresAt === 'number' && c.expiresAt > Date.now()))
  check('응답 어디에도 pin_hash가 실려있지 않다', !JSON.stringify(bulk.body).includes('pin_hash'))
}

console.log('\n12. [공격 E] 로그인/세션 발급 회귀 없음')
{
  seed({ allowed: true })
  const set = await callHandler(handlers.selfSet, { studentId: SID, pin: '2468', pinConfirm: '2468', setupCode: codeNow(SID) })
  check('선행: 정상 설정 성공', set.body?.ok === true)
  const good = await callHandler(handlers.login, { name: 'QA초등학생', pin: '2468' })
  check('설정한 PIN 으로 로그인 성공', good.body?.ok === true, JSON.stringify(good.body).slice(0, 120))
  check('로그인 성공 시 세션 토큰이 발급된다', typeof good.body?.token === 'string' && good.body.token.includes('.'))
  check('발급 토큰이 그 학생 것으로 검증된다',
    pinAuth.verifySessionToken(good.body?.token, { studentId: SID }).ok === true)
  const bad = await callHandler(handlers.login, { name: 'QA초등학생', pin: '9999' })
  check('틀린 PIN 은 로그인 실패', bad.body?.ok !== true)
  check('실패 응답에 토큰이 없다', !bad.body?.token)
  check('로그인 응답에 pin_hash 가 없다', !JSON.stringify(good.body).includes('pin_hash'))
}

console.log('\n13. 공격 체인 종단 재현 — UUID만으로는 세션까지 갈 수 없다')
{
  seed({ allowed: true })
  const d = await callHandler(handlers.selfSet, { studentId: SID, pin: '1379', pinConfirm: '1379' })
  check('D 단계 차단', d.body?.ok !== true)
  const e = await callHandler(handlers.login, { name: 'QA초등학생', pin: '1379' })
  check('E 단계 도달 불가(공격자 PIN 으로 로그인 실패)', e.body?.ok !== true)
  check('세션 토큰 미발급', !e.body?.token)
  check('학생 데이터 무변경(pin_hash null 유지)', fake.__db.students[0].pin_hash == null)
}

console.log('\n14. UI 소비 계약 정적 검사 (StudentDirectory.jsx) — 반별 일괄 발급 P0 회귀 고정')
{
  // 2026-08-30 추가 — 배경: 단건 핸들러(handleTogglePinSetupAllowed)는
  // data.setupCodes[0]을 읽어 화면에 띄우지만, 반별 일괄 핸들러
  // (handleBulkAllowPinSetup)는 서버가 N명분 코드를 돌려줘도 이를 전혀
  // 읽지 않아 화면에 하나도 안 뜨는 P0 구멍이 있었다(일괄 허용한 반
  // 전원이 PIN을 만들 수 없게 됨). 정적 소스 검사로 이 계약을 고정한다.
  const uiSrc = fs.readFileSync(path.resolve('src/components/admin/StudentDirectory.jsx'), 'utf8')
  // 이 파일은 "코드를 로그/스토리지에 남기지 않는다"는 한국어 주석을 코드
  // 바로 옆(라인 주석 // ...뿐 아니라 JSX 블록 주석 {/* ... */}에도)에
  // 남기는 관례가 있어서(예: "로그/localStorage 저장 없음",
  // "console/localStorage/sessionStorage 사용 금지"), 주석까지 그대로
  // 검사하면 그 안전 안내 문구 자체가 오탐(단어 근접 매칭)을 유발한다.
  // 라인 주석과 블록 주석을 모두 제거한 소스로 누출 검사를 수행해 실제
  // 코드만 본다.
  const stripComments = (src) => src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split('\n').map((line) => {
      const m = line.match(/(?<!:)\/\/.*/)
      return m ? line.slice(0, m.index) : line
    }).join('\n')
  const uiCodeOnly = stripComments(uiSrc)
  const bulkStart = uiSrc.indexOf('const handleBulkAllowPinSetup')
  check('handleBulkAllowPinSetup 함수를 찾았다', bulkStart >= 0)
  const nextHandleIdx = uiSrc.indexOf('const handle', bulkStart + 1)
  const bulkBody = bulkStart >= 0 ? uiSrc.slice(bulkStart, nextHandleIdx > 0 ? nextHandleIdx : uiSrc.length) : ''
  check('일괄 허용 경로가 setupCodes를 읽는다(이번에 고친 P0 회귀를 고정하는 핵심 단언)',
    /setupCodes/.test(bulkBody))
  check('일괄 허용 경로가 setSetupCodeNotice를 호출해 화면에 반영한다', /setSetupCodeNotice/.test(bulkBody))
  check('일괄 허용 경로가 이름이 아니라 studentId(UUID)로 매칭한다(헌법 규칙 4)', /studentId/.test(bulkBody))
  check('코드가 console.log로 새지 않는다', !/console\.log\([^)]*setupCode/i.test(uiCodeOnly))
  check('코드가 localStorage로 새지 않는다',
    !/localStorage[\s\S]{0,80}setupCode/i.test(uiCodeOnly) && !/setupCode[\s\S]{0,80}localStorage/i.test(uiCodeOnly))
  check('코드가 sessionStorage로 새지 않는다',
    !/sessionStorage[\s\S]{0,80}setupCode/i.test(uiCodeOnly) && !/setupCode[\s\S]{0,80}sessionStorage/i.test(uiCodeOnly))
}

console.log('\n15. [신규] get_pin_setup_code — 조회 전용 확인코드 재확인 액션')
{
  // 2026-08-30 추가 — 배경: 확인코드를 볼 수 있는 유일한 경로가
  // set_pin_setup_allowed(허용 토글) 응답 1회뿐이라, 관리자가 안내 카드를
  // 닫거나 새로고침하면 "이 학생 코드 뭐였지?"에 답할 UI가 없어 실 운영이
  // 막혔다. 새 action은 SELECT만 하고(UPDATE 0), 이미 허용된 학생의 코드를
  // 다시 파생해 보여주기만 한다.
  console.log('  15a. adminPin 없으면 거부되고 코드가 없다')
  {
    seed({ allowed: true })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID })
    check('adminPin 없으면 ok:false', r.body?.ok !== true, JSON.stringify(r.body))
    check('거부 응답에 코드가 없다', !JSON.stringify(r.body).includes(codeNow(SID)))
  }

  console.log('  15b. 정상 호출 — 코드가 서버 파생값과 일치')
  {
    seed({ allowed: true })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    check('정상 조회 성공', r.body?.ok === true, JSON.stringify(r.body))
    check('반환된 코드가 서버 파생값과 일치한다', r.body?.code === codeNow(SID))
    check('학생 이름이 함께 온다(다른 학생 코드와 혼동 방지)', r.body?.name === 'QA초등학생')
    check('studentId가 응답에 담겨 있다', r.body?.studentId === SID)
    check('만료 시각이 포함되고 미래다', typeof r.body?.expiresAt === 'number' && r.body.expiresAt > Date.now())
  }

  console.log('  15c. 조회만으로는 DB 상태가 전혀 바뀌지 않는다(조회 전용 증명)')
  {
    const s = seed({ allowed: true })
    const beforeAllowed = s.pin_setup_allowed
    const beforeHash = s.pin_hash
    await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    check('여러 번 조회해도 pin_setup_allowed가 그대로다', fake.__db.students[0].pin_setup_allowed === beforeAllowed)
    check('여러 번 조회해도 pin_hash가 그대로다(null 유지)', fake.__db.students[0].pin_hash === beforeHash)
  }

  console.log('  15d. pin_setup_allowed=false — not_allowed, 코드 미노출')
  {
    seed({ allowed: false })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    check('허용 전이면 not_allowed', r.body?.ok === false && r.body?.reason === 'not_allowed', JSON.stringify(r.body))
    check('코드가 응답에 없다', !JSON.stringify(r.body).includes(codeNow(SID)))
  }

  console.log('  15e. 이미 PIN이 있는 학생 — already_set, 코드 미노출')
  {
    seed({ allowed: true, pinHash: pinAuth.hashPin('1357') })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    check('PIN이 이미 있으면 already_set', r.body?.ok === false && r.body?.reason === 'already_set', JSON.stringify(r.body))
    check('코드가 응답에 없다', !JSON.stringify(r.body).includes(codeNow(SID)))
    check('응답에 pin_hash가 실려있지 않다(규칙 11)', !JSON.stringify(r.body).includes('pin_hash') && !JSON.stringify(r.body).includes(pinAuth.hashPin('1357')))
  }

  console.log('  15f. SESSION_SECRET 미설정 — no_secret, fail-closed')
  {
    seed({ allowed: true })
    const saved = process.env.SESSION_SECRET
    delete process.env.SESSION_SECRET
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    process.env.SESSION_SECRET = saved
    check('시크릿 없으면 no_secret', r.body?.ok === false && r.body?.reason === 'no_secret', JSON.stringify(r.body))
    check('시크릿 없어도 코드가 새지 않는다', !JSON.stringify(r.body).includes(codeNow(SID)))
  }

  console.log('  15g. 존재하지 않는 학생 — not_found')
  {
    seed({ allowed: true })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID2, adminPin: ADMIN_PIN })
    check('존재하지 않으면 not_found', r.body?.ok === false && r.body?.reason === 'not_found', JSON.stringify(r.body))
  }

  console.log('  15h. 응답 어디에도 pin_hash가 없다(정상 케이스)')
  {
    seed({ allowed: true })
    const r = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
    check('정상 응답에도 pin_hash 키가 없다', !JSON.stringify(r.body).includes('pin_hash'))
  }
}

console.log('\n16. 종단 흐름 — 허용 → 코드 재조회 → 학생 self-set → 로그인 → 세션 발급 (가짜 픽스처 전용)')
{
  // 요구사항 7: 관리자가 "PIN 설정 허용"을 누른 뒤, 관리자가 새로 만든
  // get_pin_setup_code로 코드를 (재)조회해서 학생에게 전달하고, 학생이 그
  // 코드+PIN 2회 입력으로 self-set에 성공하고, 그 PIN으로 로그인해 세션
  // 토큰까지 받는 전체 경로. 실학생 UUID는 절대 쓰지 않고(SID는 이 파일
  // 상단에 정의된 하네스 전용 가짜 UUID) 이름도 QA 픽스처 이름만 쓴다.
  seed({ allowed: false }) // 학생은 아직 PIN 미설정, 허용도 안 된 초기 상태
  const allow = await callHandler(handlers.admin, { action: 'set_pin_setup_allowed', studentIds: [SID], allowed: true, adminPin: ADMIN_PIN })
  check('1) 관리자 허용 성공', allow.body?.ok === true, JSON.stringify(allow.body))

  const lookup = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
  check('2) 관리자가 확인코드를 (재)조회할 수 있다', lookup.body?.ok === true, JSON.stringify(lookup.body))
  check('2) 조회한 코드가 허용 응답의 코드와 동일하다(같은 시간버킷)', lookup.body?.code === allow.body?.setupCodes?.[0]?.code)

  const selfSet = await callHandler(handlers.selfSet, {
    studentId: SID, pin: '3579', pinConfirm: '3579', setupCode: lookup.body.code,
  })
  check('3) 학생이 코드+PIN 2회 입력으로 self-set 성공', selfSet.body?.ok === true, JSON.stringify(selfSet.body))

  const login = await callHandler(handlers.login, { name: 'QA초등학생', pin: '3579' })
  check('4) 방금 만든 PIN으로 로그인 성공', login.body?.ok === true, JSON.stringify(login.body))
  check('4) 로그인 응답에 세션 토큰이 실려있다', typeof login.body?.token === 'string' && login.body.token.includes('.'))
  check('4) 발급된 토큰이 그 학생(SID) 것으로 검증된다',
    pinAuth.verifySessionToken(login.body?.token, { studentId: SID }).ok === true)

  // 조회 후 다시 조회해도(관리자가 "코드 다시 보기"를 여러 번 눌러도)
  // 이미 소모된(already_set) 계정이므로 더 이상 코드를 내주지 않아야 한다.
  const afterUse = await callHandler(handlers.admin, { action: 'get_pin_setup_code', studentId: SID, adminPin: ADMIN_PIN })
  check('5) PIN 설정 완료 후에는 재조회가 already_set으로 거부된다(1회성 유지)',
    afterUse.body?.ok === false && afterUse.body?.reason === 'already_set', JSON.stringify(afterUse.body))
}

console.log('\n17. UI 소비 계약 정적 검사 — 확인코드 "보기" 버튼 (StudentDirectory.jsx)')
{
  // 관리자가 코드를 잃어버렸을 때 다시 볼 수 있는 유일한 신규 진입점 —
  // PIN이 없는 학생 카드에 get_pin_setup_code를 호출하는 버튼이 있어야
  // 하고, 그 결과 코드가 로그/스토리지로 새면 안 된다(§14와 동일한 정적
  // 검사 관례 재사용).
  const uiSrc = fs.readFileSync(path.resolve('src/components/admin/StudentDirectory.jsx'), 'utf8')
  const stripComments = (src) => src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split('\n').map((line) => {
      const m = line.match(/(?<!:)\/\/.*/)
      return m ? line.slice(0, m.index) : line
    }).join('\n')
  const uiCodeOnly = stripComments(uiSrc)
  check('get_pin_setup_code 액션을 호출하는 코드가 있다', /get_pin_setup_code/.test(uiCodeOnly))
  check('확인코드 관련 문구가 "확인코드"로 통일되어 있다(StudentSelect.jsx와 용어 일치)',
    /확인코드/.test(uiCodeOnly))
  check('코드가 console.log로 새지 않는다(신규 조회 경로 포함)',
    !/console\.log\([^)]*code/i.test(uiCodeOnly))
  check('코드가 localStorage로 새지 않는다(신규 조회 경로 포함)',
    !/localStorage[\s\S]{0,120}\.code\b/i.test(uiCodeOnly) && !/\.code\b[\s\S]{0,120}localStorage/i.test(uiCodeOnly))
  check('코드가 sessionStorage로 새지 않는다(신규 조회 경로 포함)',
    !/sessionStorage[\s\S]{0,120}\.code\b/i.test(uiCodeOnly) && !/\.code\b[\s\S]{0,120}sessionStorage/i.test(uiCodeOnly))
}

console.log('\n' + '='.repeat(60))
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
if (failures > 0) { console.log('FAILED'); process.exit(1) }
console.log('ALL PASS — UUID만으로는 PIN 설정도 세션 획득도 불가함을 확인')
