// scripts/testRewardConcurrencyMatrix.mjs
//
// Reward System V1 — 동시성/부하 매트릭스 (2026-08-22 야간 감사, Phase 4).
//
// 기존 자산과의 관계(대체하지 않음, 위에 얹음):
//   - scripts/testRewardFlow.mjs           : "각 앵커가 정상 배선됐는가"(1~2회 호출)
//   - scripts/testRewardIdempotencyStress.mjs : "심한 중복 호출에도 1회만"(<=10회, 순차)
//   - 이 파일                                : "2/5/10/50/100회를 **한 tick 안에서**
//                                              몰아쳐도" 불변식이 지켜지는가 +
//                                              Promise.all 동시 요청 + 6개 앵커 전수
//
// 검증하는 단일 불변식(운영자 정의):
//   ONE ELIGIBLE ACTION = ONE REWARD EVENT = ONE LEDGER ENTRY = ONE BALANCE CHANGE
//   여기에 서버 축을 하나 더 붙여 검증한다: POST(postRewardEvent) <= 1회.
//
// 구동 방식은 scripts/testRewardIdempotencyStress.mjs와 동일한 하네스를
// 그대로 재사용한다(fakeReact.mjs + 자체 esbuild 번들 + wordLibrary 스텁).
// 새 프레임워크를 발명하지 않는다. 번들/스텁 산출물 경로만 이 파일 전용으로
// 분리해(scripts/.tmp/useStudent.concurrency.bundle.mjs,
// scripts/.tmp/wordLibraryConcurrencyStub.mjs) 기존 테스트의 산출물과
// 충돌하지 않게 한다 — 기존 파일은 한 글자도 건드리지 않는다(규칙 16).
//
// production 소스 무접촉. 네트워크 0. Supabase 0. 학생 데이터 0.
//
// 등록: npm run verify:reward-concurrency

let expectedUnhandledRejections = 0
process.on('unhandledRejection', () => { expectedUnhandledRejections++ })

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'
import { earnedStars, REWARD_STARS, rewardIdempotencyKey } from '../src/utils/rewardEngine.js'

// ── 1) 번들 준비 ────────────────────────────────────────────────────────
const TMP_DIR = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP_DIR, { recursive: true })

const raceStubUrl = pathToFileURL(path.resolve('scripts/wordLibraryRaceStub.mjs')).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const generatedStubPath = path.join(TMP_DIR, 'wordLibraryConcurrencyStub.mjs')
fs.writeFileSync(generatedStubPath, `// AUTO-GENERATED by scripts/testRewardConcurrencyMatrix.mjs — do not edit by hand.
export * from ${JSON.stringify(raceStubUrl)}
export const __postRewardEventLog = []
let __delayMs = 0
export function __setPostRewardEventDelay(ms) { __delayMs = ms }
export function __resetPostRewardEventProbe() { __postRewardEventLog.length = 0; __delayMs = 0 }
export async function postRewardEvent(studentId, rewardType, sourceType, sourceId) {
  __postRewardEventLog.push({ studentId, rewardType, sourceType, sourceId })
  if (__delayMs > 0) await new Promise((r) => setTimeout(r, __delayMs))
}
`, 'utf8')
const generatedStubUrl = pathToFileURL(generatedStubPath).href

const outfile = path.join(TMP_DIR, 'useStudent.concurrency.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'concurrency-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: generatedStubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)

const stub = await import(generatedStubUrl)
const { useStudent, todayStr } = await import(pathToFileURL(outfile).href)

// ── 2) 하네스 ───────────────────────────────────────────────────────────
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(t, f) { (this.listeners[t] ||= []).push(f) }
  removeEventListener(t, f) { this.listeners[t] = (this.listeners[t] || []).filter(x => x !== f) }
  dispatch(t) { (this.listeners[t] || []).forEach(f => f()) }
}

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}
const flush = () => new Promise(r => process.nextTick(r))

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  stub.__resetPostRewardEventProbe()
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}
function mountFresh(id, name) {
  freshEnv()
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}
const settle = (host) => { host.rerender(); return host }
const ledgerArr = (host) => (Array.isArray(host.result.rewardLedger) ? host.result.rewardLedger : [])
const ledgerCount = (host, type) => ledgerArr(host).filter(e => e && e.reward_type === type).length
const postCount = (type) => stub.__postRewardEventLog.filter(e => e.rewardType === type).length

const SID = '11111111-2222-3333-4444-555555555555'
const N_MATRIX = [2, 5, 10, 50, 100]

// 앵커별 "정확히 1회만 지급돼야 하는 동일 행동"을 반복 호출하는 트리거.
// 각 트리거는 **완전히 동일한 논리적 이벤트**를 n번 호출한다.
const ANCHORS = [
  {
    name: 'wrong-word-recovered (spelling-review)',
    rewardType: 'wrong-word-recovered',
    expectStars: REWARD_STARS['wrong-word-recovered'],
    seed: (host) => { host.result.recordSpellingAnswer('conc-word', false); settle(host) },
    fire: (host) => host.result.clearSpellingReviewWord('conc-word'),
  },
  {
    name: 'exam-complete (entrance-test)',
    rewardType: 'exam-complete',
    expectStars: REWARD_STARS['exam-complete'],
    seed: () => {},
    fire: (host) => host.result.recordExamCompleted('conc-exam-1'),
  },
]

console.log('\n=== Phase 4 — 동시성/부하 매트릭스 ===')
console.log('불변식: ONE ACTION = ONE EVENT = ONE LEDGER ENTRY = ONE BALANCE CHANGE (+ POST <= 1)')

// ── 시나리오 A: 같은 tick 안에서 n회 연속 호출 (동기 폭주) ──────────────
for (const anchor of ANCHORS) {
  console.log(`\nA. 동기 폭주 — ${anchor.name}`)
  for (const n of N_MATRIX) {
    const { host } = mountFresh(SID, 'Conc')
    settle(host)
    anchor.seed(host)
    const starsBefore = host.result.stars
    for (let i = 0; i < n; i++) anchor.fire(host)
    settle(host)
    await flush()
    settle(host)
    const entries = ledgerCount(host, anchor.rewardType)
    const delta = host.result.stars - starsBefore
    const posts = postCount(anchor.rewardType)
    check(`n=${String(n).padStart(3)} → 원장 1건 (실제 ${entries})`, entries === 1)
    check(`n=${String(n).padStart(3)} → 잔액 +${anchor.expectStars} (실제 +${delta})`, delta === anchor.expectStars)
    check(`n=${String(n).padStart(3)} → 서버 POST <= 1 (실제 ${posts})`, posts <= 1)
  }
}

// ── 시나리오 B: Promise.all 동시 요청 ───────────────────────────────────
for (const anchor of ANCHORS) {
  console.log(`\nB. Promise.all 동시 요청 — ${anchor.name}`)
  for (const n of N_MATRIX) {
    const { host } = mountFresh(SID, 'Conc')
    settle(host)
    anchor.seed(host)
    const starsBefore = host.result.stars
    await Promise.all(Array.from({ length: n }, () => Promise.resolve().then(() => anchor.fire(host))))
    settle(host)
    await flush()
    settle(host)
    const entries = ledgerCount(host, anchor.rewardType)
    const delta = host.result.stars - starsBefore
    check(`n=${String(n).padStart(3)} → 원장 1건 (실제 ${entries})`, entries === 1)
    check(`n=${String(n).padStart(3)} → 잔액 +${anchor.expectStars} (실제 +${delta})`, delta === anchor.expectStars)
  }
}

// ── 시나리오 C: 느린 서버(POST 지연) 중 재호출 ─────────────────────────
console.log('\nC. 느린 네트워크(POST 50ms 지연) 중 100회 재호출')
{
  const { host } = mountFresh(SID, 'Conc')
  settle(host)
  stub.__setPostRewardEventDelay(50)
  host.result.recordSpellingAnswer('slow-word', false); settle(host)
  const before = host.result.stars
  host.result.clearSpellingReviewWord('slow-word'); settle(host)
  for (let i = 0; i < 100; i++) host.result.clearSpellingReviewWord('slow-word')
  settle(host); await flush(); settle(host)
  check(`원장 1건 (실제 ${ledgerCount(host, 'wrong-word-recovered')})`, ledgerCount(host, 'wrong-word-recovered') === 1)
  check(`잔액 +1 (실제 +${host.result.stars - before})`, host.result.stars - before === 1)
  check(`POST <= 1 (실제 ${postCount('wrong-word-recovered')})`, postCount('wrong-word-recovered') <= 1)
}

// ── 시나리오 D: 서로 다른 이벤트 100개는 정확히 100건 (누락 없음) ──────
console.log('\nD. 누락 검사 — 서로 다른 100개 이벤트는 정확히 100건 지급')
{
  const { host } = mountFresh(SID, 'Conc')
  settle(host)
  const before = host.result.stars
  for (let i = 0; i < 100; i++) { host.result.recordSpellingAnswer(`miss-${i}`, false) }
  settle(host)
  for (let i = 0; i < 100; i++) host.result.clearSpellingReviewWord(`miss-${i}`)
  settle(host); await flush(); settle(host)
  const entries = ledgerCount(host, 'wrong-word-recovered')
  check(`원장 100건 (실제 ${entries}) — 중복 방지가 정상 지급까지 막지 않음`, entries === 100)
  check(`잔액 +100 (실제 +${host.result.stars - before})`, host.result.stars - before === 100)
}

// ── 시나리오 E: idempotency key 안정성 ──────────────────────────────────
console.log('\nE. idempotency key — 같은 입력 100회 호출 시 항상 동일 키')
{
  const keys = new Set()
  for (let i = 0; i < 100; i++) keys.add(rewardIdempotencyKey(SID, 'exam-complete', 'entrance-test', 'exam-1'))
  check(`키 종류 1개 (실제 ${keys.size})`, keys.size === 1)
  const diff = new Set()
  for (let i = 0; i < 100; i++) diff.add(rewardIdempotencyKey(SID, 'exam-complete', 'entrance-test', `exam-${i}`))
  check(`서로 다른 이벤트 100개 → 키 100개 (실제 ${diff.size})`, diff.size === 100)
}

// ── 시나리오 F: Phase 3 데이터 정합성 — earnedStars(원장) vs 잔액 delta ──
console.log('\nF. Phase 3 정합성 — earnedStars(원장 합계)와 실제 잔액 증가분 일치')
{
  const { host } = mountFresh(SID, 'Conc')
  settle(host)
  const before = host.result.stars
  for (let i = 0; i < 20; i++) { host.result.recordSpellingAnswer(`cons-${i}`, false) }
  settle(host)
  for (let i = 0; i < 20; i++) { host.result.clearSpellingReviewWord(`cons-${i}`); host.result.clearSpellingReviewWord(`cons-${i}`) }
  host.result.recordExamCompleted('cons-exam')
  host.result.recordExamCompleted('cons-exam')
  settle(host); await flush(); settle(host)
  const ledgerSum = earnedStars(ledgerArr(host))
  const delta = host.result.stars - before
  check(`원장 합계 ${ledgerSum} === 잔액 증가분 ${delta}`, ledgerSum === delta)
  check(`원장 항목 수 21건 (오답회복 20 + 시험 1, 실제 ${ledgerArr(host).length})`, ledgerArr(host).length === 21)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
if (expectedUnhandledRejections > 0) console.log(`(참고: 예상된 unhandled rejection ${expectedUnhandledRejections}건)`)
console.log(failures === 0 ? '모든 단언 통과 ✅' : `${failures}개 단언 실패 ❌`)
process.exit(failures === 0 ? 0 : 1)
