// scripts/testRewardStress45.mjs
//
// QA 하네스(2026-09-11, qa/elementary-45-readiness) — "45명 동시 사용" 규모
// 가정 하에 Reward System V1 서버 원장(api/grant-xp.js `ledger:'reward'` 분기)
// 이 REWARD_SOURCE_RULES에 실제로 정의된 **모든** 보상 타입 × 여러 재시도/
// 동시성/하루경계 시나리오에서 idempotency 계약(정확히 1행)을 지키는지
// 넓게 스윕한다.
//
// 이미 등록된 형제 테스트가 각각 검증하는 것과 겹치지 않는다(재구현 금지,
// CLAUDE.md 규칙 3) — 이 파일은 그 로직을 다시 만들지 않고 실제
// api/grant-xp.js를 esbuild로 무수정 그대로 번들해 구동한다:
//   · scripts/testRewardRetryExactlyOneRow.mjs — 클라이언트 재시도 큐
//     (wordLibrary.js postRewardEvent/flushRewardPostQueue)까지 연결한
//     end-to-end. 이 파일은 큐를 거치지 않고 핸들러를 직접 호출한다(더 넓은
//     타입 커버리지를 낮은 비용으로 얻기 위한 의도적 경계 — 큐 자체의
//     정책은 그 파일이 이미 전담).
//   · scripts/testRewardCapRace.mjs — 상한(L3) check-then-insert TOCTOU를
//     'pronunciation' 단일 타입, barrier 5로 관측. 이 파일은 같은 barrier
//     기법을 재사용하되 45명 규모로 재확인하고(아래 "정보용 프로브" 절),
//     그 파일이 다루지 않는 "12개 타입 전체 × 9개 시나리오" 매트릭스를
//     새로 추가한다.
//   · scripts/testRewardServerHardeningBehavior.mjs — 동일 이벤트 20회
//     동시 호출(§3)과 순차 상한 도달(§7)을 검증. 이 파일의 시나리오
//     2/5(동시 동일 이벤트)는 그 커버리지의 "45명 × 12타입" 확장판이다.
//   · scripts/testRewardDayBoundaryDeviceClock.mjs — reward 날짜 토큰이
//     형식만 검사되고(미래/과거 통과) XP 기간키와 다른 계약임을 순수
//     함수 호출로 문서화. 이 파일의 시나리오 7/8은 같은 사실을 실제
//     핸들러 e2e(서버 시각을 Date.now() 몽키패치로 통제)로 재확인한다.
//
// ── 타입 목록은 추측하지 않는다 ─────────────────────────────────────────
// REWARD_SOURCE_RULES(src/utils/rewardEngine.js, 클라이언트가 실제로 지급
// 요청 가능한 화이트리스트)의 키를 그대로 열거한다 — 'legacy-baseline'은
// REWARD_STARS에는 있지만 REWARD_SOURCE_RULES에 없어(마이그레이션 SQL
// 전용, isValidRewardType이 항상 거부) 대상에서 자연히 빠진다.
//
// ── 하네스 재사용 ────────────────────────────────────────────────────────
// esbuild + 인메모리 가짜 @supabase/supabase-js(UNIQUE(idempotency_key)
// 강제, select/eq/gte/maybeSingle/then(count) 체인, setImmediate 기반
// 마이크로태스크 양보로 동시 handler 호출이 실제로 인터리브되게 함) +
// 실제 sign/verifySessionToken 재사용(api/_pinAuth.js, 상수만 스텁) —
// testRewardCapRace.mjs/testRewardRetryExactlyOneRow.mjs와 같은 스타일의
// **완전히 독립된** 가짜 DB(그 파일들의 런타임 산출물을 참조하지 않음,
// 파일명도 이 스크립트 전용).
//
// ── 9개 시나리오의 실제 구현(정직한 고지) ───────────────────────────────
// (1)"두 번 순차" (3)"새로고침 후 재전송" (4)"네트워크 재시도(커밋 후
// 재전송)" (9)"재로그인 후 재전송" — 넷 다 서버 관점에서는 "같은
// idempotency_key로 두 번째 POST가 도착"이라는 동일한 계약을 검증한다
// (트리거 서사만 다르고 메커니즘은 동일 — scenarioSameKeyTwice 하나를
// 공유, (9)만 두 번째 호출에 새 토큰을 발급해 "재로그인"을 반영).
// (2)"더블클릭" (5)"동시 동일 이벤트" — 둘 다 "같은 sourceId로 2건 동시
// 호출"이라는 동일한 계약(scenarioConcurrentSame 공유).
// (6)"서로 다른 sourceId 동시 2건" — 타입에 하루 1건짜리 날짜 전용
// 패턴('date')이면 애초에 오늘 유효한 sourceId가 하나뿐이라 이 시나리오가
// 구조적으로 (5)와 같아진다 — 버그가 아니라 REWARD_SOURCE_RULES 설계이고,
// 아래 표/코드에 그대로 드러난다(속이지 않음).
// (7)"KST 23:59:59 → 00:00:01 하루 경계, 같은 sourceId" (8)"UTC 자정
// (=KST 09:00, 하루 경계 아님) 전후, 서로 다른 sourceId" — 둘 다
// api/grant-xp.js의 L3 상한 창(`kstDayStartMs(Date.now())`)이 실제
// 서버 시각에서 파생되므로, Date.now()를 일시적으로 몽키패치해 재현한다
// (grant-xp.js 소스 무수정, 전역 함수 참조 스와핑만). 이 두 시나리오는
// 배치 안 다른 학생과 전역 시계를 공유하면 안 되므로(동시에 몽키패치가
// 겹치면 서로의 "지금"을 오염시킨다) 이 두 시나리오만 배치 내 학생을
// **순차** 처리한다(동시성 레벨은 "학생 수"에는 그대로 적용되고, 실행
// 방식만 순차 — 아래 SCENARIOS의 sequential:true 참고).
//
// ── 성공 기준(모든 (타입,시나리오,동시성) 조합에 걸쳐 감사) ──────────────
//   · 어떤 idempotency_key도 reward_ledger에 2행 이상 존재하지 않는다
//     (duplicates 열, 항상 0이어야 함).
//   · 정확히 1행이 존재하면 그 행의 stars_delta === resolveRewardStars(...),
//     xp_delta === 0, student_id가 idempotency_key의 studentId 접두사와
//     일치(다른 학생 id로 새지 않음) — 하나라도 어긋나면 mismatches++.
//   · HTTP 500(서버 크래시) 0건.
// 상한(daily_cap_reached)에 걸려 0행인 것은 실패가 아니다 — 상한이 정상
// 동작한 것이므로 rows=0/duplicates=0/mismatches=0으로 정직하게 집계된다.
//
// ── L3 상한 TOCTOU(정보용, 미단언 아님 — testRewardCapRace.mjs와 동일
// KNOWN GAP 관례로 단언은 하되 "고쳐야 한다"는 뜻이 아니라 "지금 이렇다"는
// 뜻) ──────────────────────────────────────────────────────────────────
// 별도 마지막 절에서 exam-complete(cap=10) 1명에게 cap-1개를 미리 채운 뒤
// 서로 다른 sourceId 45개를 barrier로 강제 동시 도착시켜 초과분을 측정하고
// 숫자만 보고한다(수정하지 않음).
//
// 네트워크 0, production 요청 0, 실제 Supabase 접촉 0. api/grant-xp.js /
// src/utils/rewardEngine.js / api/_pinAuth.js 전부 무수정, 그대로 번들.
// 실행 시간 목표 60초 이내(실 setTimeout은 시나리오 7/8/probe의 시계
// 몽키패치 지점 외에는 쓰지 않음 — 동시성은 setImmediate 마이크로태스크
// 양보로만 만든다).

import esbuild from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let failures = 0
let asserted = 0
function check(label, cond, detail) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}${detail !== undefined ? ' — ' + JSON.stringify(detail) : ''}`); failures++ }
}

// ── 1) 독립 인메모리 가짜 Supabase(UNIQUE(idempotency_key) 강제 + cap-count
//    barrier + setImmediate 기반 진짜 인터리브) — 이 스크립트 전용 산출물.
const fakePath = path.join(TMP, 'fakeSupabaseForRewardStress45.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testRewardStress45.mjs — 다른 테스트의 산출물과
// 이름이 겹치지 않는 독립 인메모리 가짜.
export const __db = { students: [], entrance_test_results: [], reward_ledger: [] }
let barrierSize = 1
let pendingCap = []

export function __reset() {
  __db.students = []
  __db.entrance_test_results = []
  __db.reward_ledger = []
  barrierSize = 1
  pendingCap = []
}
export function __setCapBarrier(n) { barrierSize = n; pendingCap = [] }

function tick() { return new Promise((r) => setImmediate(r)) }

function matchRow(row, filters) {
  return filters.every(([c, v]) => {
    if (c.startsWith('__gte__')) return String(row[c.slice(7)]) >= String(v)
    return String(row[c]) === String(v)
  })
}
function flushPendingCap() {
  const batch = pendingCap
  pendingCap = []
  for (const entry of batch) entry.resolve({ data: null, count: entry.snapshotCount, error: null })
}
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    async maybeSingle() {
      await tick()
      const rows = __db[table] || []
      const hit = rows.find((r) => matchRow(r, filters))
      return { data: hit || null, error: null }
    },
    then(resolve, reject) {
      ;(async () => {
        await tick()
        const isCapCount = table === 'reward_ledger' && headCount
        const rows = __db[table] || []
        const hit = rows.filter((r) => matchRow(r, filters))
        if (!isCapCount || barrierSize <= 1) {
          resolve({ data: headCount ? null : hit, count: hit.length, error: null })
          return
        }
        pendingCap.push({ resolve, snapshotCount: hit.length })
        if (pendingCap.length >= barrierSize) flushPendingCap()
      })().catch(reject)
    },
  }
  return q
}
export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        async insert(row) {
          await tick()
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return { error: { code: '23505', message: 'duplicate key' } }
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: row.created_at || new Date(Date.now()).toISOString() })
          return { error: null }
        },
      }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

// ── 2) _pinAuth 스텁 — 실제 sign/verifySessionToken 재사용(인증 로직 자체는
//    이 테스트 대상이 아님, testSessionTokenAuth.mjs가 전담) ──────────────
const realPinAuthUrl = pathToFileURL(path.resolve('api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForRewardStress45.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuthUrl)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

// ── 3) api/grant-xp.js를 무수정 그대로 esbuild 번들 ─────────────────────
const outfile = path.join(TMP, 'grantXp.stress45.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-stress45',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fakeDb = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default
process.env.SESSION_SECRET = 'reward-stress45-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')
const {
  REWARD_SOURCE_RULES, REWARD_DAILY_CAP, resolveRewardStars, rewardVariantFromSource,
  rewardIdempotencyKey, isValidRewardSource, kstDayStartMs,
} = await import('../src/utils/rewardEngine.js')

// ── 4) 픽스처/헬퍼 ───────────────────────────────────────────────────────
const REWARD_TYPES = Object.keys(REWARD_SOURCE_RULES) // 추측 없음 — 실제 export
const STUDENTS = Array.from({ length: 45 }, () => crypto.randomUUID())
const DAY_MS = 24 * 60 * 60 * 1000
const TODAY = new Date().toDateString() // DATE_TOKEN_RE 실제 형식(rewardEngine.js 주석)

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
let http500Count = 0
async function call(body, token) {
  const withAuth = { ...body, token: token || signSessionToken(body.studentId) }
  const r = res()
  await handler({ method: 'POST', body: withAuth, headers: {} }, r)
  if (r.code >= 500) http500Count++
  return r
}
async function withMockedNow(ms, fn) {
  const orig = Date.now
  Date.now = () => ms
  try { return await fn() } finally { Date.now = orig }
}

// sourceId 생성 — 타입별 REWARD_SOURCE_RULES pattern에 맞춰 항상 유효한
// 값을 만든다(형식 위조 테스트가 목적이 아니므로 아래 0절에서 전수
// isValidRewardSource로 사전 검증한다).
function sourceIdFor(rewardType, seed) {
  const rule = REWARD_SOURCE_RULES[rewardType]
  switch (rule.pattern) {
    case 'date': return TODAY // cap=1/일 — 오늘 유효한 값은 이거 하나뿐(설계, 속이지 않음)
    case 'uuid': return crypto.randomUUID()
    case 'date:token': return `${TODAY}:word_${seed}`
    case 'date:streak': { const s = [3, 5, 7]; return `${TODAY}:${s[seed % s.length]}` }
    case 'token:date': return `word_${seed}:${TODAY}`
    case 'token': return `word_${seed}`
    case 'date:tokens': return `${TODAY}:word_${seed}a,word_${seed}b`
    case 'token:combo:date': { const c = [3, 5, 10]; return `word_${seed}:${c[seed % c.length]}:${TODAY}` }
    case 'token:gift': return `sticker_${seed}:milestone:${(seed % 900) + 1}`
    case 'session:round:word': {
      const ms13 = String(1700000000000 + seed).padStart(13, '0').slice(-13)
      const sessionId = `${ms13}_s${(seed % 999999).toString(36)}`
      const round = seed % 50
      return `${sessionId}:${round}:word_${seed}`
    }
    default: throw new Error(`unhandled pattern ${rule.pattern} for ${rewardType}`)
  }
}
function bodyFor(rewardType, studentId, sourceId) {
  return { ledger: 'reward', studentId, rewardType, sourceType: REWARD_SOURCE_RULES[rewardType].sourceType, sourceId }
}
async function seedIfNeeded(rewardType, studentId, sourceId) {
  if (rewardType === 'exam-complete') fakeDb.__db.entrance_test_results.push({ test_id: sourceId, student_id: studentId })
}

// 발생한 (idempotency_key, studentId, rewardType, variant) 하나를 감사해
// {rows, duplicate, mismatch}를 반환. rows>1이면 duplicate=1(치명). rows===1
// 이면 stars_delta/xp_delta/student_id 정합을 확인. rows===0(상한 등으로
// 아예 안 들어간 경우)은 duplicate=0/mismatch=0 — 실패 아님(정상 거부).
function auditKey(key, studentId, rewardType, variant) {
  const rows = fakeDb.__db.reward_ledger.filter((r) => r.idempotency_key === key)
  const duplicate = rows.length > 1 ? 1 : 0
  let mismatch = 0
  if (rows.length === 1) {
    const r = rows[0]
    const expected = resolveRewardStars(rewardType, variant)
    if (r.stars_delta !== expected) mismatch++
    if (r.xp_delta !== 0) mismatch++
    if (r.student_id !== studentId) mismatch++
    if (!key.startsWith(studentId + ':')) mismatch++
  }
  return { rows: rows.length, duplicate, mismatch }
}
function keyFor(type, studentId, sourceId) {
  return rewardIdempotencyKey(studentId, type, REWARD_SOURCE_RULES[type].sourceType, sourceId)
}

// ── 5) 시나리오 구현(6개 메커니즘이 위 9개 이름을 커버 — 헤더 주석 참고) ──
async function scenarioSameKeyTwice(type, studentId, seed, { freshTokenOnRetry } = {}) {
  const sourceId = sourceIdFor(type, seed)
  await seedIfNeeded(type, studentId, sourceId)
  const variant = rewardVariantFromSource(type, sourceId)
  const body = bodyFor(type, studentId, sourceId)
  await call(body, signSessionToken(studentId))
  await call(body, freshTokenOnRetry ? signSessionToken(studentId) : undefined)
  return [{ key: keyFor(type, studentId, sourceId), studentId, type, variant }]
}
async function scenarioConcurrentSame(type, studentId, seed) {
  const sourceId = sourceIdFor(type, seed)
  await seedIfNeeded(type, studentId, sourceId)
  const variant = rewardVariantFromSource(type, sourceId)
  const body = bodyFor(type, studentId, sourceId)
  await Promise.all([call(body), call(body)])
  return [{ key: keyFor(type, studentId, sourceId), studentId, type, variant }]
}
async function scenarioConcurrentDifferent(type, studentId, seedA, seedB) {
  const idA = sourceIdFor(type, seedA)
  const idB = sourceIdFor(type, seedB) // date-only 패턴이면 idA와 자연히 같아짐(설계, 위 헤더 주석)
  await seedIfNeeded(type, studentId, idA)
  if (idB !== idA) await seedIfNeeded(type, studentId, idB)
  await Promise.all([call(bodyFor(type, studentId, idA)), call(bodyFor(type, studentId, idB))])
  const keys = new Map()
  keys.set(keyFor(type, studentId, idA), rewardVariantFromSource(type, idA))
  keys.set(keyFor(type, studentId, idB), rewardVariantFromSource(type, idB))
  return [...keys.entries()].map(([key, variant]) => ({ key, studentId, type, variant }))
}
async function scenarioDayBoundary(type, studentId, seed) {
  const sourceId = sourceIdFor(type, seed)
  await seedIfNeeded(type, studentId, sourceId)
  const variant = rewardVariantFromSource(type, sourceId)
  const body = bodyFor(type, studentId, sourceId)
  const token = signSessionToken(studentId) // 실제 now로 서명 — 몽키패치된 시각과 무관하게 유효
  const kstMidnightToday = kstDayStartMs(Date.now())
  const t2359 = kstMidnightToday + DAY_MS - 100 // 오늘 23:59:59.9 KST
  const t0001 = kstMidnightToday + DAY_MS + 60000 // 내일 00:01:00 KST
  await withMockedNow(t2359, () => call(body, token))
  await withMockedNow(t0001, () => call(body, token)) // 같은 sourceId — dedupe 여부만 관측
  return [{ key: keyFor(type, studentId, sourceId), studentId, type, variant }]
}
async function scenarioUtcMidnight(type, studentId, seedA, seedB) {
  const idA = sourceIdFor(type, seedA)
  const idB = sourceIdFor(type, seedB)
  await seedIfNeeded(type, studentId, idA)
  if (idB !== idA) await seedIfNeeded(type, studentId, idB)
  const token = signSessionToken(studentId)
  const kstMidnightToday = kstDayStartMs(Date.now())
  const utcMidnightWithinKstDay = kstMidnightToday + 9 * 60 * 60 * 1000 // 같은 KST 날짜 안의 UTC 자정
  const tBefore = utcMidnightWithinKstDay - 500
  const tAfter = utcMidnightWithinKstDay + 500
  if (kstDayStartMs(tBefore) !== kstDayStartMs(tAfter)) throw new Error('픽스처 오류: tBefore/tAfter가 같은 KST 날짜가 아님')
  await withMockedNow(tBefore, () => call(bodyFor(type, studentId, idA), token))
  await withMockedNow(tAfter, () => call(bodyFor(type, studentId, idB), token))
  const keys = new Map()
  keys.set(keyFor(type, studentId, idA), rewardVariantFromSource(type, idA))
  keys.set(keyFor(type, studentId, idB), rewardVariantFromSource(type, idB))
  return [...keys.entries()].map(([key, variant]) => ({ key, studentId, type, variant }))
}

const SCENARIOS = [
  { key: '1-same-event-twice-sequential', run: (t, s, a) => scenarioSameKeyTwice(t, s, a) },
  { key: '2-double-click-concurrent-2', run: (t, s, a) => scenarioConcurrentSame(t, s, a) },
  { key: '3-refresh-then-resend', run: (t, s, a) => scenarioSameKeyTwice(t, s, a) },
  { key: '4-network-retry-after-committed', run: (t, s, a) => scenarioSameKeyTwice(t, s, a) },
  { key: '5-concurrent-identical-2', run: (t, s, a) => scenarioConcurrentSame(t, s, a) },
  { key: '6-concurrent-different-sourceIds-2', run: (t, s, a, b) => scenarioConcurrentDifferent(t, s, a, b) },
  { key: '7-day-boundary-2359-0001-kst', run: (t, s, a) => scenarioDayBoundary(t, s, a), sequential: true },
  { key: '8-utc-midnight-vs-kst-cap-window', run: (t, s, a, b) => scenarioUtcMidnight(t, s, a, b), sequential: true },
  { key: '9-relogin-new-token-resend', run: (t, s, a) => scenarioSameKeyTwice(t, s, a, { freshTokenOnRetry: true }) },
]

console.log('=== Reward Stress 45 — 45명 x 전체 보상 타입 x 9개 재시도/동시성/하루경계 시나리오 ===')
console.log(`REWARD_TYPES(${REWARD_TYPES.length}개, REWARD_SOURCE_RULES에서 그대로 열거): ${REWARD_TYPES.join(', ')}`)

console.log('\n0. 픽스처 — sourceIdFor가 만든 샘플이 실제로 isValidRewardSource를 통과하는지 사전 검증')
for (const type of REWARD_TYPES) {
  const sid = sourceIdFor(type, 1)
  check(`${type}: sourceIdFor(1) 샘플 "${sid}" 통과`, isValidRewardSource(type, REWARD_SOURCE_RULES[type].sourceType, sid))
}

// ── 6) 메인 매트릭스 — 동시성 레벨별로 DB를 완전히 리셋하고, 각 레벨에서
//    12타입 x 9시나리오를 그 레벨의 학생 수만큼 배치 실행한다. 표는
//    레벨을 합산해 12x9=108행으로 출력(레벨별 108x4=432행은 가독성을
//    해쳐 생략 — 레벨별 통과/실패는 아래 3개 집계 단언으로 별도 확인).
const CONCURRENCY_LEVELS = [5, 10, 20, 45]
const summary = new Map() // `${type}::${scenarioKey}` -> {rows,duplicates,mismatches,attempts}

for (const N of CONCURRENCY_LEVELS) {
  fakeDb.__reset()
  const batch = STUDENTS.slice(0, N)
  for (const sid of batch) fakeDb.__db.students.push({ id: sid })

  for (const type of REWARD_TYPES) {
    for (const scenario of SCENARIOS) {
      const runOne = async (studentId, idx) => {
        // 선형(seedBase + idx*k) 조합은 streak-bonus([3,5,7], mod3)/spelling-combo
        // ([3,5,10], mod3) 같은 짧은 순환주기 값 선택과 우연히 주기적으로 aliasing되어
        // (예: 3칸 간격 시나리오가 서로 같은 streak 값을 골라 "같은 sourceId"가 되는
        // 우연의 일치) 요약표의 rows가 실제로 그 시나리오가 새로 만든 행이 아니라
        // 이전 시나리오가 이미 만든 행을 가리키는 착시를 만든다(무결성 단언 자체는
        // 영향 없음 — auditKey는 항상 실제 key 기준으로 정확 — 표의 가독성 문제만).
        // 문자열 해시로 끊어 각 (타입,시나리오,학생인덱스) 조합이 독립적인 값을
        // 고르게 한다.
        const hash = (s) => { let h = 0; for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0; return h }
        const a = hash(`${type}|${scenario.key}|${idx}|a`)
        const b = hash(`${type}|${scenario.key}|${idx}|b`)
        try { return await scenario.run(type, studentId, a, b) }
        catch (e) { return { __error: String(e && e.message || e) } }
      }
      const results = scenario.sequential
        ? await (async () => { const out = []; for (let i = 0; i < batch.length; i++) out.push(await runOne(batch[i], i)); return out })()
        : await Promise.all(batch.map((sid, i) => runOne(sid, i)))

      const bucketKey = `${type}::${scenario.key}`
      const bucket = summary.get(bucketKey) || { rows: 0, duplicates: 0, mismatches: 0, attempts: 0, errors: 0 }
      for (const r of results) {
        bucket.attempts++
        if (r && r.__error) { bucket.errors++; continue }
        for (const item of r) {
          const a = auditKey(item.key, item.studentId, item.type, item.variant)
          bucket.rows += a.rows
          bucket.duplicates += a.duplicate
          bucket.mismatches += a.mismatch
        }
      }
      summary.set(bucketKey, bucket)
    }
  }

  const levelDuplicates = [...summary.values()].reduce((s, b) => s + b.duplicates, 0)
  const levelMismatches = [...summary.values()].reduce((s, b) => s + b.mismatches, 0)
  const levelErrors = [...summary.values()].reduce((s, b) => s + b.errors, 0)
  console.log(`\n동시성 레벨 N=${N} 완료 — 누적 중복 ${levelDuplicates}, 누적 불일치 ${levelMismatches}, 시나리오 실행 예외 ${levelErrors}, 누적 HTTP500 ${http500Count}`)
  check(`N=${N}: 이 시점까지 누적 duplicate 0`, levelDuplicates === 0)
  check(`N=${N}: 이 시점까지 누적 mismatch 0`, levelMismatches === 0)
  check(`N=${N}: 이 시점까지 시나리오 실행 자체의 예외 0`, levelErrors === 0)
}

console.log(`\n총 HTTP 500(서버 크래시) 발생: ${http500Count}`)
check('전체 실행 동안 HTTP 500 0건', http500Count === 0)

console.log('\n=== 요약 표 — type x scenario -> rows(성공 행 수) / duplicates(같은 key 2행 이상) / mismatches(내용 불일치) ===')
console.log('(4개 동시성 레벨 합산치. duplicates/mismatches는 항상 0이어야 정상 — rows가 타입별 cap보다 작은 것은 실패 아님, 상한이 정상 작동한 것)')
for (const type of REWARD_TYPES) {
  for (const scenario of SCENARIOS) {
    const b = summary.get(`${type}::${scenario.key}`) || { rows: 0, duplicates: 0, mismatches: 0, attempts: 0, errors: 0 }
    console.log(`  ${type.padEnd(24)} ${scenario.key.padEnd(34)} rows=${String(b.rows).padStart(3)}  duplicates=${b.duplicates}  mismatches=${b.mismatches}  attempts=${b.attempts}`)
  }
}

// ── 7) L3 상한 TOCTOU — 정보용 프로브(testRewardCapRace.mjs와 동일 관례,
//    barrier로 "N개 동시 요청이 서로의 INSERT를 못 보는 창"을 결정론적으로
//    재현). 45명이 아니라 "학생 1명에게 서로 다른 sourceId 45개가 동시
//    도착"하는 시나리오다(지시사항 문구 그대로) — exam-complete(cap=10)로
//    실측한다.
console.log('\n=== L3 일일 상한 TOCTOU — 정보용 프로브(수정 아님, 숫자만 보고) ===')
{
  fakeDb.__reset()
  const probeType = 'exam-complete'
  const cap = REWARD_DAILY_CAP[probeType]
  const studentId = crypto.randomUUID()
  fakeDb.__db.students.push({ id: studentId })
  for (let i = 0; i < cap - 1; i++) {
    fakeDb.__db.reward_ledger.push({
      student_id: studentId, reward_type: probeType, idempotency_key: `seed-${i}`,
      stars_delta: 2, xp_delta: 0, created_at: new Date().toISOString(),
    })
  }
  const N = 45
  const testIds = Array.from({ length: N }, () => crypto.randomUUID())
  for (const tid of testIds) fakeDb.__db.entrance_test_results.push({ test_id: tid, student_id: studentId })
  fakeDb.__setCapBarrier(N)
  const results = await Promise.all(testIds.map((tid) => call(bodyFor(probeType, studentId, tid), signSessionToken(studentId))))
  const successCount = results.filter((r) => r.body?.ok === true && r.body?.duplicate === false).length
  const finalRows = fakeDb.__db.reward_ledger.filter((r) => r.student_id === studentId && r.reward_type === probeType).length
  console.log(`  관측(정보용, cap=${cap}, 시작 rows=${cap - 1}): 서로 다른 sourceId ${N}건 동시 도착 -> 성공 ${successCount}건, 최종 rows=${finalRows}, cap 초과분=${finalRows - cap}`)
  check(
    'KNOWN GAP(정보용, testRewardCapRace.mjs와 동일 결론) — 서로 다른 sourceId N건이 count=cap-1에서 경합하면 상한을 초과할 수 있다. ' +
    '이 단언은 "지금 이렇다"를 고정하는 것이지 바람직하다는 뜻이 아니다 — DB 레벨 (student,type,day) 가드가 도입되면 successCount는 ' +
    '1이 되어 이 단언이 뒤집힌다(그때 이 파일을 함께 갱신할 것).',
    successCount > 1,
  )
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '\n모든 단언 통과 — Reward 45명 스트레스(12타입 x 9시나리오 x 동시성 4레벨) 무결성 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
