// scripts/testRewardIdempotencyStress.mjs
//
// Reward System V1 — 중복 지급 방지 스트레스 테스트(2026-08-19). 이미
// PASS 상태인 scripts/testRewardFlow.mjs(55단언, 배선 정상 동작 확인)를
// 대체하지 않는다 — 그 파일은 "각 앵커가 정상적으로 배선됐는가"를 1~2회
// 호출로 확인하고, 이 파일은 그 위에 "얼마나 심하게 중복 호출해도 정확히
// 1회만 지급되는가"(더블클릭/연타/StrictMode/새로고침/재로그인/네트워크
// 재시도 등)를 추가로 검증한다.
//
// 구동 방식은 scripts/testRewardFlow.mjs와 완전히 동일(fakeReact.mjs의
// 최소 hooks 런타임 + fake clock + FakeStorage/FakeDocument + settle()
// 헬퍼) — 새 테스트 프레임워크를 발명하지 않는다. 다만 이 파일은
// scripts/buildRaceBundle.mjs의 고정 산출물(scripts/.tmp/useStudent.race.
// bundle.mjs, scripts/wordLibraryRaceStub.mjs 사용)을 재사용하지 않고
// 독자적으로 esbuild 번들을 만든다 — postRewardEvent 호출 횟수를 계측하고
// (필요 시) 실패를 시뮬레이션해야 하는데, wordLibraryRaceStub.mjs의
// postRewardEvent는 다른 여러 테스트(testRewardFlow.mjs/testStarDeltaOnEntry.mjs/
// testRestoreSyncRace.mjs/testMultiTabRace.mjs/testLoginRestoreCrash.mjs/
// testIdentityMigration.mjs)가 공유하는 `export const`(재대입 불가) 바인딩이라
// 그 파일을 고치지 않고는 카운터를 주입할 수 없다 — 그래서 이 파일 하나
// 안에서 자체 esbuild 번들(출력: 새 경로 scripts/.tmp/useStudent.
// rewardStress.bundle.mjs)과 자체 wordLibrary 스텁(출력: 새 경로
// scripts/.tmp/wordLibraryRewardStressStub.mjs, `export * from
// wordLibraryRaceStub.mjs` + postRewardEvent만 계측 가능하게 오버라이드)을
// 런타임에 생성한다 — 기존 파일은 한 글자도 건드리지 않는다(CLAUDE.md
// 규칙 16, 파일당 소유권). 두 산출물 모두 scripts/.tmp/(gitignore) 안.
//
// 등록: npm run verify:reward-stress
//   (node scripts/buildRaceBundle.mjs && node scripts/testRewardIdempotencyStress.mjs)
// buildRaceBundle.mjs 실행은 무해하지만(다른 테스트용 산출물을 만들 뿐,
// 이 파일은 쓰지 않음) 운영자 지정 등록 커맨드를 그대로 따른다.
//
// postRewardEvent는 실제로는(src/utils/wordLibrary.js) 내부에서 fetch를
// try/catch로 감싸 "네트워크 실패해도 호출자에게 절대 reject를 전파하지
// 않는다"는 계약을 갖는다(주석 참고) — useStudent.js의 grantLedgerReward도
// 이 함수를 await 없이 fire-and-forget 호출한다. 이 스텁은 그 계약보다
// 한 단계 더 엄격한(방어적인) 상황까지 검증하기 위해 실제로 reject하는
// 옵션을 제공한다 — 그 결과 fire-and-forget 호출부에서 unhandled rejection이
// 발생할 수 있어 아래 전역 핸들러로 흡수한다(이 테스트 파일 안에서만 의도된
// 것 — 진짜 버그를 가리는 게 아니라, 실제 postRewardEvent라면 절대 도달하지
// 않는 경로를 일부러 만든 것).
let expectedUnhandledRejections = 0
process.on('unhandledRejection', () => {
  expectedUnhandledRejections++
})

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'
import {
  rewardIdempotencyKey, hasRewardEntry, appendRewardEntry, buildRewardEntry,
  earnedStars, REWARD_STARS,
} from '../src/utils/rewardEngine.js'

// ── 1) 자체 esbuild 번들 준비(위 헤더 주석 참고) ────────────────────────
const TMP_DIR = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP_DIR, { recursive: true })

const raceStubPath = path.resolve('scripts/wordLibraryRaceStub.mjs')
const raceStubUrl = pathToFileURL(raceStubPath).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const generatedStubPath = path.join(TMP_DIR, 'wordLibraryRewardStressStub.mjs')
const generatedStubContent = `// AUTO-GENERATED by scripts/testRewardIdempotencyStress.mjs — do not edit by hand.
// wordLibraryRaceStub.mjs의 모든 export를 그대로 재노출하되(getStudents/
// syncStudentProgress/fetchFullProgress/syncCalls 등), postRewardEvent만
// 계측 가능한 버전으로 오버라이드한다(ES 모듈에서 뒤에 선언된 로컬 export가
// export * 충돌을 이긴다 — 표준 동작).
export * from ${JSON.stringify(raceStubUrl)}

export const __postRewardEventLog = []
let __rejectQueue = []
export function __queuePostRewardEventRejects(n) {
  for (let i = 0; i < n; i++) __rejectQueue.push(true)
}
export function __resetPostRewardEventProbe() {
  __postRewardEventLog.length = 0
  __rejectQueue.length = 0
}
export async function postRewardEvent(studentId, rewardType, sourceType, sourceId) {
  __postRewardEventLog.push({ studentId, rewardType, sourceType, sourceId, at: __postRewardEventLog.length })
  if (__rejectQueue.length > 0) {
    __rejectQueue.shift()
    throw new Error('simulated network failure (testRewardIdempotencyStress stub)')
  }
}
`
fs.writeFileSync(generatedStubPath, generatedStubContent, 'utf8')
const generatedStubUrl = pathToFileURL(generatedStubPath).href

const outfile = path.join(TMP_DIR, 'useStudent.rewardStress.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile,
  plugins: [{
    name: 'reward-stress-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: generatedStubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)

const stub = await import(generatedStubUrl)
const bundle = await import(pathToFileURL(outfile).href)
const { useStudent, todayStr } = bundle

// ── 2) 하네스 보일러플레이트(scripts/testRewardFlow.mjs와 동일 패턴) ────
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(type, fn) { (this.listeners[type] ||= []).push(fn) }
  removeEventListener(type, fn) { this.listeners[type] = (this.listeners[type] || []).filter(f => f !== fn) }
  dispatch(type) { (this.listeners[type] || []).forEach(fn => fn()) }
}

let failures = 0
let asserted = 0
const scenarioFailures = {}
let currentScenario = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else {
    console.log(`  FAIL  ${label}`)
    failures++
    scenarioFailures[currentScenario] = (scenarioFailures[currentScenario] || 0) + 1
  }
}
const flush = () => new Promise((r) => process.nextTick(r))
// Node는 process.nextTick만으로는 unhandledRejection을 아직 신호하지 않는다
// (매크로태스크 한 턴이 더 필요 — 실측 확인됨). 시나리오 9의 "postRewardEvent가
// 실제로 reject됐다"는 진단성 카운터(expectedUnhandledRejections)를 정확히
// 세기 위한 용도로만 쓴다 — 어떤 check() 단언도 이 타이밍에 의존하지 않는다.
const flushMacro = () => new Promise((r) => setImmediate(r))

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  stub.__resetPostRewardEventProbe()
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}

function mountOnCurrentEnv(id, name) {
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}

function mountFresh(id, name) {
  freshEnv()
  return mountOnCurrentEnv(id, name)
}

function mountSeeded(id, name, seedRecord) {
  freshEnv()
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify({ [id]: seedRecord }))
  return mountOnCurrentEnv(id, name)
}

// 같은 (공유) localStorage 위에서 새 렌더 트리를 만든다 — "재로그인/
// 새로고침/StrictMode 재마운트"를 전부 이 한 헬퍼로 표현한다(freshEnv()를
// 다시 부르지 않아 localStorage가 그대로 유지됨, testRewardFlow.mjs의
// 테스트 3/4와 동일 기법).
function remount(id, name) {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}

// fakeReact.mjs의 run()이 hookFn() 반환값을 effect 커밋 "전"에 캡처하는
// 특성 우회(testRewardFlow.mjs settle() 헤더 주석과 동일 근거).
function settle(host) {
  host.rerender()
  return host
}

function ledgerArr(host) {
  return Array.isArray(host.result.rewardLedger) ? host.result.rewardLedger : []
}
function ledgerCount(host, rewardType, sourceIdPredicate) {
  return ledgerArr(host).filter((e) => e && e.reward_type === rewardType && (!sourceIdPredicate || sourceIdPredicate(e.source_id))).length
}
function ledgerEntry(host, rewardType, sourceIdPredicate) {
  return ledgerArr(host).find((e) => e && e.reward_type === rewardType && (!sourceIdPredicate || sourceIdPredicate(e.source_id)))
}
function daysAgoStr(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toDateString()
}
function seedHistoryForStreak(priorDays) {
  const history = { [todayStr()]: { categoriesCompleted: 4 } }
  for (let i = 1; i <= priorDays; i++) history[daysAgoStr(i)] = { categoriesCompleted: 4 }
  return history
}
function freshRoundSeed() {
  return { date: todayStr(), wordsViewed: [], examplesHeard: 0, quizSolved: 0, pronunciationOk: 0, pronunciationOkWordIds: [], spellingWrongToday: [], spellingCombo: 0, starGrantLog: [], completedToday: [] }
}

// `new Date()`(useStudent.js todayStr()가 실제로 부르는 것)를 offsetDays일
// 미래로 보이게 하는 임시 오버라이드 — 실행 후 항상 복원(finally). rewardEngine.js
// 자신은 순수(Date 미사용, testRewardEngine.mjs가 소스 레벨로 고정)라 영향 없음 —
// 여기서 흔드는 건 useStudent.js의 todayStr()/calcStreak() 등 "지금이 언제인지"를
// 실제로 물어보는 소수의 경계 함수뿐(설계상 의도된 유일한 impure 지점).
async function withFakeToday(offsetDays, fn) {
  const RealDate = globalThis.Date
  const offsetMs = offsetDays * 24 * 60 * 60 * 1000
  class FakeDate extends RealDate {
    constructor(...args) {
      if (args.length === 0) super(RealDate.now() + offsetMs)
      else super(...args)
    }
    static now() { return RealDate.now() + offsetMs }
  }
  globalThis.Date = FakeDate
  try {
    // fn이 async면 반드시 await해야 한다 — `return fn()`만 하면 fn 내부가
    // 첫 await에서 제어를 돌려주는 순간 이 finally가 먼저 실행돼(fn이 아직
    // 끝나지 않았는데도) Date가 너무 일찍 복원되는 버그가 있었다(실측:
    // fn 안의 두 번째 이후 todayStr() 호출부터 이미 RealDate로 돌아가
    // 있었다 — 디버그 로그로 확인 후 수정).
    return await fn()
  } finally {
    globalThis.Date = RealDate
  }
}

function completeWordSession(host, prefix) {
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`${prefix}-${i}`)
  settle(host)
}
function completeWritingRound(host, prefix) {
  for (let i = 0; i < 5; i++) host.result.recordSpellingAnswer(`${prefix}-${i}`, true)
}
function completeFullRound(host, prefix) {
  for (let i = 0; i < 5; i++) host.result.markWordViewed(`${prefix}-v${i}`)
  for (let i = 0; i < 5; i++) host.result.markExampleHeard()
  for (let i = 0; i < 5; i++) host.result.markQuizSolved()
  for (let i = 0; i < 5; i++) host.result.markPronunciationOk(`${prefix}-p${i}`)
  settle(host)
}

console.log('=== Reward System V1 — 중복 지급 방지 스트레스 테스트 ===')

// ── 시나리오 1 — 더블클릭(word-session-complete) ──────────────────────
currentScenario = 1
console.log('\n시나리오 1 — 더블클릭: 라운드 완료 트리거를 동기적으로 연속 2회 호출')
{
  const ID = '22222222-0000-0000-0000-000000000001'
  const { host } = mountFresh(ID, 'QA_Stress_DoubleClick')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`dc-${i}`)
  // 더블클릭 — 라운드를 완료시킨 마지막 단어를 동기적으로 한 번 더 클릭
  host.result.markWordCompleted('dc-4')
  host.result.markWordCompleted('dc-4')
  settle(host)
  check('rewardLedger 행 수 === 1', ledgerCount(host, 'word-session-complete') === 1)
  check('totalStars 델타 === +1(정확히 1회분)', host.result.stars === before + 1)
  check('postRewardEvent 호출 <= 1회', (stub.__postRewardEventLog.length - postBefore) <= 1)
}

// ── 시나리오 2 — 빠른 연속 클릭 5회(exam-complete, 외부 가드 없이 grantLedgerReward를
//    직접 여러 번 시도하는 가장 순수한 경로) ──────────────────────────
currentScenario = 2
console.log('\n시나리오 2 — 빠른 연속 클릭: 같은 이벤트 5회 연속 호출(exam-complete)')
{
  const ID = '22222222-0000-0000-0000-000000000002'
  const { host } = mountFresh(ID, 'QA_Stress_RapidClick')
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  for (let i = 0; i < 5; i++) host.result.recordExamCompleted('exam-rapid-1')
  check('rewardLedger 행 수 === 1', ledgerCount(host, 'exam-complete', (id) => id === 'exam-rapid-1') === 1)
  check('totalStars 델타 === +2(정확히 1회분)', host.result.stars === before + 2)
  check('postRewardEvent 호출 <= 1회', (stub.__postRewardEventLog.length - postBefore) <= 1)
}

// ── 시나리오 3 — 10회 호출(wrong-word-recovered) ───────────────────────
currentScenario = 3
console.log('\n시나리오 3 — 10회 호출: 같은 이벤트를 10회(wrong-word-recovered, clearSpellingReviewWord)')
{
  const ID = '22222222-0000-0000-0000-000000000003'
  const seed = { studentId: ID, totalStars: 0, round: freshRoundSeed(), spellingReviewQueue: ['ten-call-word'], history: {} }
  const { host } = mountSeeded(ID, 'QA_Stress_TenCalls', seed)
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  for (let i = 0; i < 10; i++) host.result.clearSpellingReviewWord('ten-call-word')
  check('rewardLedger 행 수 === 1', ledgerCount(host, 'wrong-word-recovered', (id) => id.endsWith(':ten-call-word')) === 1)
  check('totalStars 델타 === +1(정확히 1회분)', host.result.stars === before + 1)
  check('postRewardEvent 호출 <= 1회', (stub.__postRewardEventLog.length - postBefore) <= 1)
}

// ── 시나리오 4 — React StrictMode 유사 이중 호출(마운트→언마운트→재마운트) ──
// fakeReact.mjs는 실제 React의 unmount/cleanup을 흉내내지 않으므로(주석
// 참고), 완전히 새 렌더 트리를 같은 localStorage 위에 만드는 remount()로
// "언마운트 후 즉시 재마운트"를 근사한다 — 이미 testRewardFlow.mjs 테스트
// 3/4가 "새로고침/재로그인"에 쓰는 것과 같은 기법이지만, 여기서는 사용자
// 상호작용 없이(라운드 완료 직후, 지연 0) 곧바로 재마운트해 StrictMode의
// "마운트 직후 즉시 재실행" 성격을 강조한다.
currentScenario = 4
console.log('\n시나리오 4 — StrictMode 유사 이중 호출: 같은 effect를 마운트→언마운트→재마운트로 두 번 실행')
{
  const ID = '22222222-0000-0000-0000-000000000004'
  const NAME = 'QA_Stress_StrictMode'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  const before = host.result.stars
  completeWordSession(host, 'sm')
  const afterFirstMount = host.result.stars
  check('첫 마운트 — word-session-complete 1건', ledgerCount(host, 'word-session-complete') === 1)
  check('첫 마운트 — +1', afterFirstMount === before + 1)

  // 지연 없이 즉시 재마운트(StrictMode가 실제로 하는 것 — 같은 tick 근방에서
  // mount->unmount->mount) — 같은 studentId, 같은 localStorage.
  const postBefore = stub.__postRewardEventLog.length
  const { host: host2 } = remount(ID, NAME)
  await flush(); await flush(); await flush()
  check('재마운트 직후 word-session-complete 여전히 1건', ledgerCount(host2, 'word-session-complete') === 1)
  check('재마운트 후 totalStars 변화 없음', host2.result.stars === afterFirstMount)
  check('재마운트로 인한 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore)
}

// ── 시나리오 5 — 새로고침(리마운트 후 같은 조건 재발화) ────────────────
currentScenario = 5
console.log('\n시나리오 5 — 새로고침: 리마운트 후 동일 조건 재발화 시도 → 추가 지급 0')
{
  const ID = '22222222-0000-0000-0000-000000000005'
  const NAME = 'QA_Stress_Refresh'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  completeWordSession(host, 'rf')
  const after1 = host.result.stars
  const { host: host2 } = remount(ID, NAME)
  await flush(); await flush(); await flush()
  // 새로고침 후에도 사용자가 "같은 조건"(이미 완료된 5개 단어를 다시
  // 훑어보며 markWordCompleted를 재호출)을 재현 — 멱등이라 completedToday에도
  // 추가되지 않고, 재지급도 없어야 한다.
  for (let i = 0; i < 5; i++) host2.result.markWordCompleted(`rf-${i}`)
  settle(host2)
  check('새로고침 후 재발화 — word-session-complete 여전히 1건', ledgerCount(host2, 'word-session-complete') === 1)
  check('새로고침 후 totalStars 변화 없음', host2.result.stars === after1)
}

// ── 시나리오 6 — 재로그인(localStorage 재로드 후 같은 이벤트, writing-complete) ──
currentScenario = 6
console.log('\n시나리오 6 — 재로그인: localStorage 재로드 후 같은 이벤트(writing-complete) 재발화 시도')
{
  const ID = '22222222-0000-0000-0000-000000000006'
  const NAME = 'QA_Stress_Relogin'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  completeWritingRound(host, 'rl')
  check('첫 세션 — writing-complete 1건', ledgerCount(host, 'writing-complete') === 1)
  const after1 = host.result.stars

  const { host: host2 } = remount(ID, NAME)
  await flush(); await flush(); await flush()
  // 재로그인 후 같은 화면을 다시 열어 이미 맞힌 단어를 또 정답 처리(사용자가
  // "이미 완료했는지 몰라서" 다시 시도하는 경우) — history.spellingCorrect가
  // 이미 GOAL 이상이라 justCompletedWriting이 다시 true가 될 수 없음.
  host2.result.recordSpellingAnswer('rl-extra', true)
  check('재로그인 후 재발화 — writing-complete 여전히 1건', ledgerCount(host2, 'writing-complete') === 1)
  check('재로그인 후 totalStars(writing-complete 몫) 변화 없음', host2.result.stars <= after1 + 1) // spellingCombo 보너스(grantReward, 별개 dedupKey)는 새로 붙을 수 있으므로 상한만 확인
  const entry = ledgerEntry(host2, 'writing-complete')
  check('writing-complete stars_delta 여전히 2', entry && entry.stars_delta === 2)
}

// ── 시나리오 7 — 동일 Unit 재진입(유닛 전환 후 되돌아와 같은 이벤트) ────
currentScenario = 7
console.log('\n시나리오 7 — 동일 Unit 재진입: 다른 유닛으로 전환 후 되돌아와 같은 단어를 다시 완료 처리')
{
  const ID = '22222222-0000-0000-0000-000000000007'
  const NAME = 'QA_Stress_UnitReentry'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  completeWordSession(host, 'un')
  const after1 = host.result.stars
  const postBefore = stub.__postRewardEventLog.length

  // Unit A(un-*) 학습 위치 기록 → 다른 Unit B로 전환 → 다시 Unit A로 복귀.
  // setLastWordIndex(idx, unitId) — 인자 순서 확인(useStudent.js 1669행).
  host.result.setLastWordIndex?.(4, 'unit-A')
  host.result.setLastWordIndex?.(0, 'unit-B')
  host.result.setLastWordIndex?.(4, 'unit-A')
  // Unit A로 복귀해 같은 5개 단어를 다시 훑는다(재열람 시 markWordCompleted가
  // 다시 불릴 수 있는 실제 UI 경로를 흉내).
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`un-${i}`)
  settle(host)
  check('Unit 재진입 후 word-session-complete 여전히 1건', ledgerCount(host, 'word-session-complete') === 1)
  check('Unit 재진입 후 totalStars 변화 없음', host.result.stars === after1)
  check('Unit 재진입으로 인한 추가 postRewardEvent 없음', stub.__postRewardEventLog.length === postBefore)
}

// ── 시나리오 8 — 같은 단어 재학습(오답 회복, 두 경로 교차 스트레스) ─────
currentScenario = 8
console.log('\n시나리오 8 — 같은 단어 재학습: wrong-word-recovered를 clearSpellingReviewWord/recordSpellingAnswer 양쪽 경로로 교차 반복 호출')
{
  const ID = '22222222-0000-0000-0000-000000000008'
  const seed = { studentId: ID, totalStars: 0, round: freshRoundSeed(), spellingReviewQueue: ['cross-word'], history: {} }
  const { host } = mountSeeded(ID, 'QA_Stress_CrossPath', seed)
  await flush(); await flush(); await flush()
  const before = host.result.stars
  const postBefore = stub.__postRewardEventLog.length
  host.result.clearSpellingReviewWord('cross-word')
  host.result.clearSpellingReviewWord('cross-word')
  host.result.recordSpellingAnswer('cross-word', true)
  host.result.clearSpellingReviewWord('cross-word')
  host.result.recordSpellingAnswer('cross-word', true)
  host.result.clearSpellingReviewWord('cross-word')
  check('rewardLedger 행 수 === 1(교차 호출 9회에도)', ledgerCount(host, 'wrong-word-recovered', (id) => id.endsWith(':cross-word')) === 1)
  check('totalStars 델타 === +1(정확히 1회분)', host.result.stars === before + 1)
  check('postRewardEvent 호출 <= 1회', (stub.__postRewardEventLog.length - postBefore) <= 1)
}

// ── 시나리오 9 — 네트워크 지연/재시도 ───────────────────────────────────
currentScenario = 9
console.log('\n시나리오 9 — 네트워크 지연/재시도: postRewardEvent가 실패(reject)해도 로컬 원장 1건 유지, 재시도해도 로컬 중복 0')
{
  const ID = '22222222-0000-0000-0000-000000000009'
  const NAME = 'QA_Stress_NetworkRetry'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  const before = host.result.stars
  stub.__queuePostRewardEventRejects(1) // 다음 postRewardEvent 호출 1회를 reject
  completeWordSession(host, 'nr')
  await flush(); await flush(); await flushMacro() // fire-and-forget 프라미스가 reject/settle될 시간을 줌(위 flushMacro 주석 참고)
  check('postRewardEvent 실패해도 rewardLedger 1건 유지', ledgerCount(host, 'word-session-complete') === 1)
  check('postRewardEvent 실패해도 totalStars +1(로컬 지급은 서버 응답과 무관)', host.result.stars === before + 1)

  // "재시도" — 새로고침/재접속을 흉내(remount), 같은 이벤트를 다시 유발.
  const postBefore = stub.__postRewardEventLog.length
  const { host: host2 } = remount(ID, NAME)
  await flush(); await flush(); await flush()
  for (let i = 0; i < 5; i++) host2.result.markWordCompleted(`nr-${i}`)
  settle(host2)
  check('재시도 후에도 rewardLedger 여전히 1건(로컬 중복 0)', ledgerCount(host2, 'word-session-complete') === 1)
  check('재시도 후 totalStars 변화 없음', host2.result.stars === before + 1)
  check('재시도는 로컬 dedup에 막혀 postRewardEvent가 추가로 나가지 않음', stub.__postRewardEventLog.length === postBefore)
}

// ── 시나리오 10 — 6종 앵커 각각 2회씩 호출 → 각 1건씩, 총 6건, 총 별 11 ──
currentScenario = 10
console.log('\n시나리오 10 — 6종 앵커 각각 2회씩 호출 → 각 정확히 1건, 총 6건, earnedStars(rewardLedger) === 11')
{
  const ID = '22222222-0000-0000-0000-000000000010'
  const seed = {
    studentId: ID, totalStars: 0, round: freshRoundSeed(),
    spellingReviewQueue: ['anchor-wrong-word'],
    history: seedHistoryForStreak(2), // priorDays=2 + 오늘 = streak 3 → streak-bonus +2
  }
  const { host } = mountSeeded(ID, 'QA_Stress_AllAnchors', seed)
  await flush(); await flush(); await flush()

  // streak-bonus — 마운트 시 useEffect에서 이미 1차 지급 시도, settle()로
  // 한 번 더 재평가(2회째 시도).
  settle(host)
  settle(host)
  check('streak-bonus 1건', ledgerCount(host, 'streak-bonus') === 1)

  // word-session-complete — 완료 + 재시도.
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`aa-${i}`)
  settle(host)
  host.result.markWordCompleted('aa-4')
  settle(host)
  check('word-session-complete 1건', ledgerCount(host, 'word-session-complete') === 1)

  // writing-complete — 완료 + 재시도(다른 단어로 한 번 더 정답 처리).
  for (let i = 0; i < 5; i++) host.result.recordSpellingAnswer(`aaw-${i}`, true)
  host.result.recordSpellingAnswer('aaw-extra', true)
  check('writing-complete 1건', ledgerCount(host, 'writing-complete') === 1)

  // exam-complete — 2회 직접 호출.
  host.result.recordExamCompleted('anchor-exam-1')
  host.result.recordExamCompleted('anchor-exam-1')
  check('exam-complete 1건', ledgerCount(host, 'exam-complete', (id) => id === 'anchor-exam-1') === 1)

  // wrong-word-recovered — 2회 직접 호출.
  host.result.clearSpellingReviewWord('anchor-wrong-word')
  host.result.clearSpellingReviewWord('anchor-wrong-word')
  check('wrong-word-recovered 1건', ledgerCount(host, 'wrong-word-recovered', (id) => id.endsWith(':anchor-wrong-word')) === 1)

  // daily-goal-complete — 4개 카테고리 완료(라운드 반복 2회, 하루 1회 유지).
  completeFullRound(host, 'aar1')
  check('daily-goal-complete 1건(1라운드 후)', ledgerCount(host, 'daily-goal-complete') === 1)
  completeFullRound(host, 'aar2')
  check('daily-goal-complete 여전히 1건(2라운드 후, 하루 1회 유지)', ledgerCount(host, 'daily-goal-complete') === 1)

  const ledger = ledgerArr(host)
  check('rewardLedger 행 수 === 6(6종 앵커 각 1건)', ledger.length === 6)
  check('earnedStars(rewardLedger) === 11(1+2+2+1+3+2)', earnedStars(ledger) === 11)
  const streakEntry = ledgerEntry(host, 'streak-bonus')
  check('streak-bonus stars_delta === 2(streak=3일)', streakEntry && streakEntry.stars_delta === 2)
}

// ── 추가 단언 1 — idempotency_key 안정성(같은 이벤트 반복 호출해도 키 동일) ──
currentScenario = 11
console.log('\n추가 단언 1 — idempotency_key 안정성: 같은 이벤트 반복 호출해도 키 문자열이 항상 동일, 다른 이벤트는 키가 다름')
{
  const ID = '22222222-0000-0000-0000-000000000011'
  const { host } = mountFresh(ID, 'QA_Stress_KeyStability')
  await flush(); await flush(); await flush()
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`ks-${i}`)
  settle(host)
  const entry1 = ledgerEntry(host, 'word-session-complete')
  const key1 = entry1 && entry1.idempotency_key
  host.result.markWordCompleted('ks-4')
  host.result.markWordCompleted('ks-4')
  settle(host)
  const entry2 = ledgerEntry(host, 'word-session-complete')
  check('같은 이벤트 반복 호출 후에도 idempotency_key 동일', entry2 && entry2.idempotency_key === key1)
  check('rewardIdempotencyKey() 순수 계산 결과와 실제 원장 키 일치', key1 === rewardIdempotencyKey(ID, 'word-session-complete', 'daily-words', todayStr()))

  // 서로 다른 이벤트(exam-complete, 다른 testId 2개)는 키가 서로 다름.
  host.result.recordExamCompleted('key-test-A')
  host.result.recordExamCompleted('key-test-B')
  const examA = ledgerEntry(host, 'exam-complete', (id) => id === 'key-test-A')
  const examB = ledgerEntry(host, 'exam-complete', (id) => id === 'key-test-B')
  check('서로 다른 sourceId(exam testId) → 서로 다른 idempotency_key', examA && examB && examA.idempotency_key !== examB.idempotency_key)
  check('word-session-complete와 exam-complete는 서로 다른 idempotency_key', key1 !== examA.idempotency_key)
}

// ── 추가 단언 2 — 날짜 경계(같은 이벤트라도 날짜가 바뀌면 새 키 → 새로 1건) ──
currentScenario = 12
console.log('\n추가 단언 2 — 날짜 경계: 날짜가 바뀌면(fake clock) word-session-complete가 새 키로 별도 1건 추가 지급(정상)')
{
  const ID = '22222222-0000-0000-0000-000000000012'
  const NAME = 'QA_Stress_DateBoundary'
  const { host } = mountFresh(ID, NAME)
  await flush(); await flush(); await flush()
  const before = host.result.stars
  for (let i = 0; i < 5; i++) host.result.markWordCompleted(`db-${i}`)
  settle(host)
  const entryDay0 = ledgerEntry(host, 'word-session-complete')
  check('오늘 word-session-complete 1건', ledgerCount(host, 'word-session-complete') === 1)
  check('오늘 +1', host.result.stars === before + 1)

  await withFakeToday(1, async () => {
    // 다음날(fake) — 같은 localStorage 위에서 재마운트(normalizeRecord의
    // 로드 시점 롤오버가 round.date !== todayStr()를 보고 round를 리셋).
    const { host: hostNextDay } = remount(ID, NAME)
    await flush(); await flush(); await flush()
    for (let i = 0; i < 5; i++) hostNextDay.result.markWordCompleted(`db2-${i}`)
    settle(hostNextDay)
    const entryDay1 = ledgerEntry(hostNextDay, 'word-session-complete', (id) => id !== entryDay0.source_id)
    check('다음날 — word-session-complete 2건째(새 날짜 키)로 정상 추가 지급', ledgerCount(hostNextDay, 'word-session-complete') === 2)
    check('다음날 — idempotency_key가 어제와 다름', entryDay1 && entryDay1.idempotency_key !== entryDay0.idempotency_key)
    check('다음날 — totalStars 추가 +1(누적 +2)', hostNextDay.result.stars === before + 2)
  })
}

// ── 추가 단언 3 — 교차 오염 없음(학생 A의 이벤트가 학생 B의 원장에 나타나지 않음) ──
currentScenario = 13
console.log('\n추가 단언 3 — 교차 오염 없음: 같은 기기(localStorage)에서 학생 A/B가 같은 이벤트를 각자 지급받아도 서로의 원장에 나타나지 않음')
{
  freshEnv()
  const ID_A = '22222222-0000-0000-0000-0000000013a1'
  const ID_B = '22222222-0000-0000-0000-0000000013b2'
  const { host: hostA } = mountOnCurrentEnv(ID_A, 'QA_Stress_StudentA')
  await flush(); await flush(); await flush()
  for (let i = 0; i < 5; i++) hostA.result.markWordCompleted(`xa-${i}`)
  settle(hostA)
  const entryA = ledgerEntry(hostA, 'word-session-complete')
  check('학생 A — word-session-complete 1건', ledgerCount(hostA, 'word-session-complete') === 1)

  // 같은 (공유) localStorage 위에서 학생 B를 새로 마운트(예: 같은 태블릿을
  // 다음 학생이 로그인) — freshEnv() 재호출 없음.
  const { host: hostB } = mountOnCurrentEnv(ID_B, 'QA_Stress_StudentB')
  await flush(); await flush(); await flush()
  check('학생 B 최초 마운트 — rewardLedger에 학생 A의 항목 없음', !ledgerArr(hostB).some((e) => e.idempotency_key === entryA.idempotency_key))
  for (let i = 0; i < 5; i++) hostB.result.markWordCompleted(`xb-${i}`)
  settle(hostB)
  const entryB = ledgerEntry(hostB, 'word-session-complete')
  check('학생 B — word-session-complete 1건(독립 지급)', ledgerCount(hostB, 'word-session-complete') === 1)
  check('학생 A/B의 idempotency_key는 studentId가 달라 서로 다름', entryA.idempotency_key !== entryB.idempotency_key)
  check('idempotency_key에 각자의 studentId가 포함됨', entryA.idempotency_key.startsWith(ID_A) && entryB.idempotency_key.startsWith(ID_B))

  // 학생 A로 다시 돌아가도(재로그인) 원장에 학생 B의 항목이 섞여있지 않음.
  const { host: hostA2 } = mountOnCurrentEnv(ID_A, 'QA_Stress_StudentA')
  await flush(); await flush(); await flush()
  check('학생 A 재로그인 — rewardLedger에 학생 B 항목 없음', !ledgerArr(hostA2).some((e) => e.idempotency_key === entryB.idempotency_key))
  check('학생 A 재로그인 — 여전히 word-session-complete 1건', ledgerCount(hostA2, 'word-session-complete') === 1)
}

// ── 규칙 15(FAIL-first) — 대조군: hasRewardEntry 사전 체크를 우회하면
//    실제로 N건이 쌓인다는 것을 증명(방어의 실효성 대조) ──────────────
currentScenario = 14
console.log('\n대조군(규칙 15) — hasRewardEntry 방어를 우회한 순수 함수로 "방어가 없으면 실제로 중복 쌓인다"를 실측 대조')
{
  // 대조군: 실제 방어(appendRewardEntry의 hasRewardEntry 재검사)를 흉내내지
  // 않고 그냥 무조건 append하는 함수 — 이 파일 안에만 존재, production
  // 코드는 절대 수정하지 않는다.
  function naiveAppendWithoutDedup(ledger, entry) {
    return [...(Array.isArray(ledger) ? ledger : []), entry]
  }
  const studentId = 'control-group-student'
  const entry = buildRewardEntry({ studentId, rewardType: 'word-session-complete', sourceType: 'daily-words', sourceId: '2026-08-19', starsDelta: REWARD_STARS['word-session-complete'], at: '2026-08-19T00:00:00.000Z' })

  // ① 대조군 — 방어 없이 같은 이벤트를 10회 "지급 시도"
  let naiveLedger = []
  for (let i = 0; i < 10; i++) naiveLedger = naiveAppendWithoutDedup(naiveLedger, entry)
  check('[대조군] 방어 없이 10회 시도 → 실제로 10건 쌓임(방어가 없으면 이렇게 된다)', naiveLedger.length === 10)
  check('[대조군] 방어 없이 10회 시도 → earnedStars가 10배로 부풀려짐', earnedStars(naiveLedger) === REWARD_STARS['word-session-complete'] * 10)

  // ② 실제 구현 — appendRewardEntry(hasRewardEntry 재검사 포함)로 같은
  //    이벤트를 10회 시도 → 정확히 1건만 남는다(실제 프로덕션 로직, 대조).
  let realLedger = []
  for (let i = 0; i < 10; i++) realLedger = appendRewardEntry(realLedger, entry)
  check('[실제] appendRewardEntry로 10회 시도 → 정확히 1건(방어가 실제로 동작)', realLedger.length === 1)
  check('[실제] appendRewardEntry로 10회 시도 → earnedStars 정확히 1회분', earnedStars(realLedger) === REWARD_STARS['word-session-complete'])
  check('hasRewardEntry는 대조군 ledger에서도 이미 있음을 정확히 감지(순수 함수 자체는 항상 정상 동작)', hasRewardEntry(naiveLedger, entry.idempotency_key) === true)
}

// ── 결과 요약 ────────────────────────────────────────────────────────
console.log('\n─── 결과 요약 ───')
for (const n of Object.keys(scenarioFailures)) console.log(`시나리오 ${n} 실패 수: ${scenarioFailures[n]}`)
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(`(참고) 의도된 unhandledRejection 흡수 횟수: ${expectedUnhandledRejections}(시나리오 9의 postRewardEvent reject 시뮬레이션 fire-and-forget 경로)`)
console.log(failures === 0
  ? '\n모든 단언 통과 — Reward System V1 중복 지급 방지 실효성 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
