// scripts/testCutoverReconcile.mjs
//
// 레거시 별 이관(action:'reconcile_legacy_baseline', api/grant-xp.js) —
// 학생별(per-student) 이관이 "전역 시각 T 스냅샷" 방식의 컷오버 레이스를
// 실제로 닫는지 검증한다(2026-09-07). 다른 세션이 작성하는 SQL 함수
// reconcile_legacy_baseline()의 계약(이 파일 상단 CONTEXT 주석의 서버측
// 로직 그대로)을 인메모리로 흉내내고, 이 파일 안에서 "클라이언트 디바이스"
// 프로토콜(localTotal/큐/hold/flush/reconcile)까지 함께 시뮬레이션해 실제
// 레이스 시나리오를 재현한다.
//
// 정직한 커버리지 경계(반드시 읽을 것): 진짜 Postgres 함수(원자적 행 잠금/
// 트랜잭션)는 이 파일에서 실행되지 않는다 — 여기서는 (1) api/grant-xp.js의
// `action:'reconcile_legacy_baseline'` 분기가 RPC 반환값을 올바르게
// 응답으로 옮기는지, (2) 클라이언트 프로토콜(먼저 flush, 그 다음 snapshot)
// 이 레이스를 닫는 "설계"인지를 검증한다. RPC 자체의 동시성 원자성 증거는
// SQL 쪽 별도 테스트(있다면)의 몫이다 — §11의 "동시 호출 직렬화"도 이
// 파일의 가짜 rpc()가 학생별 락을 흉내낸 것이지 진짜 DB 트랜잭션이 아니다.
//
// 산출물: scripts/.tmp/(gitignore) — fakeSupabaseForCutover.mjs /
// fakePinAuthCutover.mjs / grantXp.cutover.bundle.mjs (다른 하네스가 쓰는
// 파일명과 충돌하지 않는 테스트 전용 이름).
//
// 등록: 이 스크립트를 harness registry(tests/harness/registry.mjs)에
// 올리는 작업은 이 세션의 책임 밖(별도 소유자) — 여기서는 직접 실행만.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

// ── 가짜 Supabase ──────────────────────────────────────────────────────
// __db 스키마:
//   students: [{ id }]
//   student_progress: { [studentId]: { total_stars, historySince } }
//     · total_stars — 클라이언트가 마지막으로 업로드한(디바운스) 로컬 총합.
//       reconcile_legacy_baseline의 "snapshot > uploaded_total_stars + 200"
//       가드가 참조한다.
//     · historySince — "이 학생의 최근 실제 활동 규모"를 흉내낸 테스트
//       전용 값(실제 SQL의 정확한 정의는 다른 세션의 SQL 파일에 있고 이
//       파일에서는 보이지 않는다 — 계약 텍스트의 "delta > historySince +
//       100 → review" 산수만 재현하면 되므로, 기본값을 넉넉히 크게 두고
//       §9에서만 명시적으로 낮춰 그 가드를 노출시킨다).
//   reward_ledger: [] — 기존 reward:'ledger' 분기(V1)의 실제 지급 행 +
//     이 기능이 학생당 정확히 1건만 남기는 "v2 이관 행"
//     (reward_type:'legacy-baseline', source_type:'legacy-baseline-v2')이
//     함께 쌓인다. reward_totals(student)는 이 배열의 stars_delta 합으로
//     매번 파생한다(저장된 합계 컬럼이 아님 — rewardEngine.js earnedStars()
//     와 동일 원칙).
//   town_items / star_purchases — §12 무회귀(마을상점 두 action) 검증용
//     (testTownShopServer.mjs의 RPC 로직을 그대로 재사용).
const fakePath = path.join(TMP, 'fakeSupabaseForCutover.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testCutoverReconcile.mjs
export const __db = {
  students: [],
  student_progress: {},
  reward_ledger: [],
  town_items: [],
  star_purchases: [],
}
export const __fail = { rpc: null, students: null, reward_ledger: null }
export const __calls = []
const __locks = new Map()

export function __reset() {
  __db.students = []
  __db.student_progress = {}
  __db.reward_ledger = []
  __db.town_items = []
  __db.star_purchases = []
  __fail.rpc = null; __fail.students = null; __fail.reward_ledger = null
  __calls.length = 0
  __locks.clear()
}

// ── 학생별 직렬화(락) 흉내 — 실제 DB 행 잠금이 아니라, 이 프로세스 안에서
// 같은 studentId로 들어온 reconcile 호출들을 순서대로(먼저 온 것부터)
// 완료시키는 프라미스 체인이다(§11 동시 호출 검증용).
function withStudentLock(studentId, fn) {
  const prev = __locks.get(studentId) || Promise.resolve()
  let release
  const gate = new Promise((resolve) => { release = resolve })
  __locks.set(studentId, prev.then(() => gate))
  return prev.then(async () => {
    try {
      return await fn()
    } finally {
      release()
    }
  })
}

function rewardTotalsFor(studentId) {
  return __db.reward_ledger
    .filter((r) => r.student_id === studentId)
    .reduce((sum, r) => sum + (Number(r.stars_delta) || 0), 0)
}

function v2RowFor(studentId) {
  return __db.reward_ledger.find((r) => r.student_id === studentId
    && r.reward_type === 'legacy-baseline' && r.source_type === 'legacy-baseline-v2')
}

function insertV2Row(studentId, delta) {
  __db.reward_ledger.push({
    student_id: studentId,
    reward_type: 'legacy-baseline',
    source_type: 'legacy-baseline-v2',
    source_id: studentId,
    stars_delta: delta,
    xp_delta: 0,
    idempotency_key: studentId + ':legacy-baseline:legacy-baseline-v2:' + studentId,
    created_at: new Date().toISOString(),
  })
}

// reconcile_legacy_baseline(p_student_id, p_snapshot_total) 계약 그대로
// (CONTEXT 주석 원문): 학생 존재 -> 스냅샷 범위 -> 학생별 락 -> earned =
// reward_totals(student) -> v2 행 존재? already_reconciled -> snapshot >
// uploaded+200? review -> delta = snapshot-earned; delta<=0? 0-delta 행
// 삽입, nothing_to_reconcile -> delta > historySince+100 또는 > 1500?
// review(행 없음) -> v2 행 삽입(unique_violation은 already_reconciled로) ->
// reconciled, earned_after = earned+delta.
function rpcReconcileLegacyBaseline(studentId, snapshotTotal) {
  return withStudentLock(studentId, async () => {
    const student = __db.students.find((s) => s.id === studentId)
    if (!student) return { ok: false, reason: 'student_not_found', baseline_stars: 0, earned_after: 0 }
    if (!Number.isInteger(snapshotTotal) || snapshotTotal < 0 || snapshotTotal > 100000) {
      return { ok: false, reason: 'invalid_snapshot', baseline_stars: 0, earned_after: rewardTotalsFor(studentId) }
    }
    const existing = v2RowFor(studentId)
    if (existing) {
      return { ok: true, reason: 'already_reconciled', baseline_stars: existing.stars_delta, earned_after: rewardTotalsFor(studentId) }
    }
    const earned = rewardTotalsFor(studentId)
    const progress = __db.student_progress[studentId] || { total_stars: 0, historySince: 1000000 }
    const uploaded = Number(progress.total_stars) || 0
    if (snapshotTotal > uploaded + 200) {
      return { ok: false, reason: 'review', baseline_stars: 0, earned_after: earned }
    }
    const delta = snapshotTotal - earned
    if (delta <= 0) {
      insertV2Row(studentId, 0)
      return { ok: true, reason: 'nothing_to_reconcile', baseline_stars: 0, earned_after: rewardTotalsFor(studentId) }
    }
    const historySinceRaw = Number(progress.historySince)
    const historySince = Number.isFinite(historySinceRaw) ? historySinceRaw : 1000000
    if (delta > historySince + 100 || delta > 1500) {
      return { ok: false, reason: 'review', baseline_stars: 0, earned_after: earned }
    }
    if (v2RowFor(studentId)) {
      // 방어적 재확인(실제 DB의 unique_violation에 해당) — 이 인메모리
      // 락으로는 실질적으로 도달하지 않지만 계약을 그대로 흉내낸다.
      const row = v2RowFor(studentId)
      return { ok: true, reason: 'already_reconciled', baseline_stars: row.stars_delta, earned_after: rewardTotalsFor(studentId) }
    }
    insertV2Row(studentId, delta)
    return { ok: true, reason: 'reconciled', baseline_stars: delta, earned_after: rewardTotalsFor(studentId) }
  })
}

// ── town_items/star_purchases RPC(§12 무회귀용) — testTownShopServer.mjs의
// 로직을 그대로 재사용하되, earned는 reward_ledger 합산(rewardTotalsFor)에서
// 가져온다(이 파일의 __db에는 별도 reward_totals 딕셔너리가 없다).
function spentFor(studentId) {
  return __db.star_purchases.filter((p) => p.student_id === studentId)
    .reduce((a, p) => a + p.stars_spent, 0)
}
function rpcPurchase(studentId, itemId) {
  const student = __db.students.find((s) => s.id === studentId)
  if (!student) return { ok: false, reason: 'student_not_found', stars_spent: 0, balance_after: 0 }
  const item = __db.town_items.find((i) => i.id === itemId && i.active !== false)
  if (!item) return { ok: false, reason: 'item_not_found', stars_spent: 0, balance_after: 0 }
  const already = __db.star_purchases.some((p) => p.student_id === studentId && p.item_id === itemId)
  const earned = rewardTotalsFor(studentId)
  const spent = spentFor(studentId)
  const available = Math.max(0, earned - spent)
  if (already) return { ok: true, reason: 'already_owned', stars_spent: 0, balance_after: available }
  if (available < item.price) return { ok: false, reason: 'insufficient', stars_spent: 0, balance_after: available }
  __db.star_purchases.push({ student_id: studentId, item_id: itemId, stars_spent: item.price })
  return { ok: true, reason: 'purchased', stars_spent: item.price, balance_after: available - item.price }
}
function rpcState(studentId) {
  const earned = rewardTotalsFor(studentId)
  const spent = spentFor(studentId)
  const available = Math.max(0, earned - spent)
  const owned = __db.star_purchases.filter((p) => p.student_id === studentId).map((p) => p.item_id)
  return { earned, spent, available, owned_item_ids: owned }
}

// select/eq/gte/maybeSingle 체이닝 — testTownShopServer.mjs의 makeQuery와
// 동일 패턴(reward/XP 기존 분기가 쓰는 형태를 그대로 지원해야 §5/§12
// 무회귀 검증이 된다).
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    match(rows) {
      return rows.filter((r) => filters.every(([c, v]) => {
        if (c.startsWith('__gte__')) return String(r[c.slice(7)]) >= String(v)
        return String(r[c]) === String(v)
      }))
    },
    maybeSingle() {
      __calls.push({ table, op: 'maybeSingle', filters: [...filters] })
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return Promise.resolve({ data: hit[0] || null, error: null })
    },
    then(resolve) {
      __calls.push({ table, op: headCount ? 'count' : 'select', filters: [...filters] })
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}

export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          __calls.push({ table, op: 'insert', row })
          if (__fail[table]) return Promise.resolve({ error: __fail[table] })
          if (!__db[table]) __db[table] = []
          const dup = row.idempotency_key
            && __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: row.created_at || new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
    rpc(name, args) {
      __calls.push({ rpc: name, args })
      if (__fail.rpc) return Promise.resolve({ data: null, error: __fail.rpc })
      if (name === 'reconcile_legacy_baseline') {
        return rpcReconcileLegacyBaseline(args.p_student_id, args.p_snapshot_total).then((row) => ({ data: [row], error: null }))
      }
      if (name === 'purchase_town_item') {
        const row = rpcPurchase(args.p_student_id, args.p_item_id)
        return Promise.resolve({ data: [row], error: null })
      }
      if (name === 'get_town_shop_state') {
        const row = rpcState(args.p_student_id)
        return Promise.resolve({ data: [row], error: null })
      }
      return Promise.resolve({ data: null, error: { code: 'XX000', message: 'unknown rpc ' + name } })
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const fakePinAuthPath = path.join(TMP, 'fakePinAuthCutover.mjs')
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const outfile = path.join(TMP, 'grantXp.cutover.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-cutover',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

process.env.SESSION_SECRET = 'cutover-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')
const tokenFor = (sid, opts) => signSessionToken(sid, opts)

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
function call(body, headers = {}) {
  const r = res()
  return handler({ method: 'POST', body: body || {}, headers }, r).then(() => r)
}

let uidCounter = 0
function uuid() {
  uidCounter++
  const hex = uidCounter.toString(16).padStart(8, '0')
  return `${hex}-0000-4000-8000-000000000000`
}
function seedStudent() {
  const sid = uuid()
  fake.__db.students.push({ id: sid })
  return sid
}
const TODAY = new Date().toDateString() // rewardEngine.js DATE_TOKEN_RE 형식(예: 'Mon Sep 07 2026')과 일치
let tokenSeq = 0
function dailyMissionBonusEvent() {
  // rewardType 'daily-mission-bonus' — REWARD_STARS 고정 10, sourceType
  // 'daily-round', pattern 'date:tokens' — 매 호출마다 tokens를 바꿔
  // (idempotency_key가 studentId+rewardType+sourceType+sourceId로 조립되므로)
  // 같은 학생이 여러 번 "+10" 이벤트를 서로 다른 이벤트로 기록할 수 있게 한다.
  tokenSeq++
  return { rewardType: 'daily-mission-bonus', sourceType: 'daily-round', sourceId: `${TODAY}:tok${tokenSeq}` }
}

// ── "디바이스" — 학생 브라우저의 로컬 별 총합 + 대기 중인 지급 큐를 흉내
// 낸다. grant()는 로컬 총합을 즉시 올리고 큐에 넣는다(fire-and-forget과
// 동일하게 실제 POST는 나중에 flush()가 보낸다). reconcile()은 반드시
// "먼저 flush, 그 다음 snapshot 전송"(레이스를 닫는 설계) 순서를 지킨다.
class Device {
  constructor(studentId, token, legacyTotal) {
    this.studentId = studentId
    this.token = token
    this.localTotal = legacyTotal
    this.pending = []
    this.hold = false
    // 생성 시점에 "이미 이 값으로 한 번 업로드된 상태"로 시작한다 — 실제
    // 앱에서 legacy 총합은 이미 여러 번 디바운스 업로드를 거쳐 서버에
    // 반영돼 있는 값이기 때문(§1이 명시적으로 upload()를 부르지 않아도
    // review 가드에 걸리지 않아야 하는 이유).
    fake.__db.student_progress[studentId] = { total_stars: legacyTotal, historySince: 1000000 }
  }
  grant(amount, evt) {
    const item = { amount, ...evt }
    this.localTotal += amount
    this.pending.push(item)
    return item
  }
  async flush() {
    const items = this.pending.slice()
    for (const item of items) {
      const r = await call({
        ledger: 'reward', studentId: this.studentId,
        rewardType: item.rewardType, sourceType: item.sourceType, sourceId: item.sourceId,
        token: this.token,
      })
      item.lastResult = r.body
      if (r.body && r.body.ok) {
        const idx = this.pending.indexOf(item)
        if (idx >= 0) this.pending.splice(idx, 1)
      }
    }
  }
  upload() {
    const row = fake.__db.student_progress[this.studentId] || { total_stars: 0, historySince: 1000000 }
    row.total_stars = this.localTotal
    fake.__db.student_progress[this.studentId] = row
  }
  // opts.midpoint(device) — snapshot 값을 이미 확정한 "직후"(RPC 응답을
  // 기다리는 동안)에 실행된다. §4("hold 중 이벤트")가 이 훅으로 "스냅샷에는
  // 안 잡히지만 이후 flush로는 반영되는" 이벤트를 흉내낸다.
  async reconcile(opts = {}) {
    this.hold = true
    await this.flush()
    let result = null
    if (this.pending.length === 0) {
      const snapshot = this.localTotal
      if (typeof opts.midpoint === 'function') opts.midpoint(this)
      const r = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: snapshot, token: this.token })
      result = r.body
    }
    this.hold = false
    await this.flush()
    return result
  }
}

function earnedOf(sid) {
  return fake.__db.reward_ledger
    .filter((r) => r.student_id === sid)
    .reduce((sum, r) => sum + (Number(r.stars_delta) || 0), 0)
}
function dupKeyCountsOk(sid) {
  const keys = fake.__db.reward_ledger.filter((r) => r.student_id === sid).map((r) => r.idempotency_key)
  return new Set(keys).size === keys.length
}

console.log('\n1. T0 — legacy만 존재(L=300, ledger 0) -> reconciled 300, earned 300')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  const r = await dev.reconcile()
  check(`ok true / reason reconciled (${JSON.stringify(r)})`, r?.ok === true && r?.reason === 'reconciled')
  check('baselineStars 300', r?.baselineStars === 300)
  check('earnedAfter 300', r?.earnedAfter === 300)
  check('실제 earned도 300', earnedOf(sid) === 300)
  check('idempotency_key 중복 없음', dupKeyCountsOk(sid))
}

console.log('\n2. reconcile 이전 이벤트 — grant +10(전송·삽입 완료), upload, reconcile -> baseline 300, earned 310')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  dev.grant(10, dailyMissionBonusEvent())
  await dev.flush()
  check('flush 후 pending 0', dev.pending.length === 0)
  dev.upload()
  const r = await dev.reconcile()
  check(`ok true / reconciled (${JSON.stringify(r)})`, r?.ok === true && r?.reason === 'reconciled')
  check('baselineStars 300', r?.baselineStars === 300)
  check('earnedAfter 310', r?.earnedAfter === 310)
  check('실제 earned 310', earnedOf(sid) === 310)
}

console.log('\n3. in-flight 레이스(구 설계가 이중계산하던 상황) — flush-먼저 설계가 막는지, 그리고 통제군으로 구 설계가 실제로 이중계산함을 증명')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  dev.grant(10, dailyMissionBonusEvent()) // localTotal 310, pending 1건, 아직 전송 안 됨
  dev.upload() // 디바운스 업로드가 먼저 도착(실제로 가능한 순서)
  check('업로드 시점 pending 아직 1건(POST 미전송)', dev.pending.length === 1)
  const r = await dev.reconcile() // reconcile()이 flush를 먼저 하므로 레이스가 닫힌다
  check(`ok true / reconciled (${JSON.stringify(r)})`, r?.ok === true && r?.reason === 'reconciled')
  check('baselineStars 300(이중계산 아님)', r?.baselineStars === 300)
  check('earnedAfter 310(NOT 320)', r?.earnedAfter === 310)
  check('실제 earned 310', earnedOf(sid) === 310)

  console.log('  -- 통제군(구 전역-T 설계 반증): flush 없이 RPC를 직접 호출 --')
  const sidControl = seedStudent()
  const devControl = new Device(sidControl, tokenFor(sidControl), 300)
  devControl.grant(10, dailyMissionBonusEvent()) // localTotal 310, pending 1건, 전송 안 됨
  devControl.upload()
  const rDirect = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: devControl.localTotal, token: devControl.token })
  check(`통제군: flush 없이 reconciled, baseline 310(earned 아직 0) (${JSON.stringify(rDirect.body)})`,
    rDirect.body?.ok === true && rDirect.body?.reason === 'reconciled' && rDirect.body?.baselineStars === 310 && rDirect.body?.earnedAfter === 310)
  await devControl.flush() // 뒤늦게 pending POST가 도착
  const finalEarned = earnedOf(sidControl)
  check(`통제군 반증: 최종 earned가 320(이중계산됨), 310이 아님 (실측 ${finalEarned})`, finalEarned === 320)
  check('이 하네스가 이중계산을 실제로 검출함(320 !== 310)', finalEarned !== 310)
}

console.log('\n4. hold 중 이벤트 — 스냅샷 확정 후·RPC 대기 중 grant(스냅샷에 안 잡힘) -> baseline 300 -> release·flush -> earned 310')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  let midpointRan = false
  const r = await dev.reconcile({
    midpoint: (d) => {
      midpointRan = true
      d.grant(10, dailyMissionBonusEvent()) // hold 중 이벤트: 스냅샷 확정 이후에 발생
    },
  })
  check('midpoint 훅 실행됨', midpointRan)
  check(`ok true / reconciled, baseline 300(hold 중 이벤트는 스냅샷에 안 잡힘) (${JSON.stringify(r)})`,
    r?.ok === true && r?.reason === 'reconciled' && r?.baselineStars === 300)
  check('reconcile() 종료 시점엔 release 후 flush까지 끝나 pending 0건', dev.pending.length === 0)
  check('release 후 flush로 최종 earned 310', earnedOf(sid) === 310)
}

console.log('\n5. reconcile 이후 이벤트 — +10 -> earned 310; 같은 키 재시도 -> duplicate true, 여전히 310')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  const r0 = await dev.reconcile()
  check('사전 reconcile 성공', r0?.ok === true && r0?.reason === 'reconciled')
  const evt = dailyMissionBonusEvent()
  dev.grant(10, evt)
  await dev.flush()
  check('flush 후 earned 310', earnedOf(sid) === 310)
  const retry = await call({
    ledger: 'reward', studentId: sid, rewardType: evt.rewardType, sourceType: evt.sourceType, sourceId: evt.sourceId, token: dev.token,
  })
  check('재시도 -> duplicate true', retry.body?.ok === true && retry.body?.duplicate === true)
  check('재시도 후에도 earned 여전히 310', earnedOf(sid) === 310)
}

console.log('\n6. 재실행 — 같은 디바이스로 다시 reconcile, 다른 스냅샷(999)으로도 -> already_reconciled, 원장/earned 불변')
{
  fake.__reset()
  const sid = seedStudent()
  const dev = new Device(sid, tokenFor(sid), 300)
  const r0 = await dev.reconcile()
  check('최초 reconcile 성공', r0?.ok === true && r0?.reason === 'reconciled')
  const ledgerLenBefore = fake.__db.reward_ledger.length
  const earnedBefore = earnedOf(sid)

  const rAgain = await dev.reconcile()
  check(`같은 디바이스 재실행 -> already_reconciled (${JSON.stringify(rAgain)})`, rAgain?.ok === true && rAgain?.reason === 'already_reconciled')

  const rOtherDevice = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 999, token: dev.token })
  check(`다른 스냅샷(999)의 두 번째 디바이스도 -> already_reconciled (${JSON.stringify(rOtherDevice.body)})`,
    rOtherDevice.body?.ok === true && rOtherDevice.body?.reason === 'already_reconciled')

  check('원장 행 수 불변', fake.__db.reward_ledger.length === ledgerLenBefore)
  check('earned 불변', earnedOf(sid) === earnedBefore)
}

console.log('\n7. 두 학생 교차 — A/B가 번갈아 post/reconcile해도 서로 섞이지 않음')
{
  fake.__reset()
  const sidA = seedStudent()
  const sidB = seedStudent()
  const devA = new Device(sidA, tokenFor(sidA), 100)
  const devB = new Device(sidB, tokenFor(sidB), 500)

  devA.grant(10, dailyMissionBonusEvent())
  devB.grant(10, dailyMissionBonusEvent())
  await devA.flush()
  await devB.flush()
  devA.upload()
  devB.upload()
  const rA = await devA.reconcile()
  const rB = await devB.reconcile()

  check('A: reconciled, baseline 100', rA?.ok === true && rA?.reason === 'reconciled' && rA?.baselineStars === 100)
  check('A: earnedAfter 110', rA?.earnedAfter === 110)
  check('B: reconciled, baseline 500', rB?.ok === true && rB?.reason === 'reconciled' && rB?.baselineStars === 500)
  check('B: earnedAfter 510', rB?.earnedAfter === 510)
  check('A의 원장에 B의 student_id 없음', !fake.__db.reward_ledger.some((r) => r.student_id === sidA && r.source_id === sidB))
  check('실제 earned(A) 110 / earned(B) 510', earnedOf(sidA) === 110 && earnedOf(sidB) === 510)
}

console.log('\n8. nothing_to_reconcile — L=0, ledger에 이미 50(V1 앵커), snapshot 50 -> 0-delta 행, earned 50; 이후 재실행 -> already_reconciled')
{
  fake.__reset()
  const sid = seedStudent()
  // V1 앵커(이 기능 이전에 이미 실제로 지급된 이벤트) — 직접 원장에 심는다.
  fake.__db.reward_ledger.push({
    student_id: sid, reward_type: 'word-session-complete', source_type: 'daily-words', source_id: 'anchor',
    stars_delta: 50, xp_delta: 0, idempotency_key: `${sid}:word-session-complete:daily-words:anchor`,
    created_at: new Date(0).toISOString(),
  })
  const dev = new Device(sid, tokenFor(sid), 0)
  dev.localTotal = 50 // 클라이언트 로컬 총합도 이미 이 V1 지급을 반영한 상태(legacy 추가분 0)
  dev.upload()
  const r = await dev.reconcile()
  check(`ok true / nothing_to_reconcile (${JSON.stringify(r)})`, r?.ok === true && r?.reason === 'nothing_to_reconcile')
  check('baselineStars 0', r?.baselineStars === 0)
  check('earnedAfter 50(불변)', r?.earnedAfter === 50)
  check('실제 earned 50', earnedOf(sid) === 50)

  const rAgain = await dev.reconcile()
  check('재실행 -> already_reconciled', rAgain?.ok === true && rAgain?.reason === 'already_reconciled')
}

console.log('\n9. review 라우팅 — (a) snapshot 5000 vs uploaded 300 -> review, (b) delta > historySince+100 -> review')
{
  fake.__reset()
  const sidA = seedStudent()
  const devA = new Device(sidA, tokenFor(sidA), 300) // uploaded=300
  const rA = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 5000, token: devA.token })
  check(`(a) ok false / review (${JSON.stringify(rA.body)})`, rA.body?.ok === false && rA.body?.reason === 'review')
  check('(a) 행 삽입 안 됨(v2 행 없음)', !fake.__db.reward_ledger.some((r) => r.student_id === sidA))
  check('(a) earned 불변(0)', earnedOf(sidA) === 0)

  const sidB = seedStudent()
  const devB = new Device(sidB, tokenFor(sidB), 300) // uploaded=300, snapshot도 300이라 (a)가드는 통과
  fake.__db.student_progress[sidB].historySince = 50 // delta(300) > 50+100=150 -> (b)가드 발동
  const rB = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300, token: devB.token })
  check(`(b) ok false / review (${JSON.stringify(rB.body)})`, rB.body?.ok === false && rB.body?.reason === 'review')
  check('(b) 행 삽입 안 됨', !fake.__db.reward_ledger.some((r) => r.student_id === sidB))
  check('(b) earned 불변(0)', earnedOf(sidB) === 0)
}

console.log('\n10. 변조/실패 매핑 — studentId 위조, snapshotTotal 형식, 토큰 없음, RPC 42883/일반 실패')
{
  fake.__reset()
  const STUDENT = seedStudent()
  const OTHER = seedStudent()
  const tk = tokenFor(STUDENT)
  fake.__db.student_progress[STUDENT] = { total_stars: 300, historySince: 1000000 } // 실제로는 디바운스 업로드가 이미 300을 반영해 둔 상태

  const rTamper = await call({ action: 'reconcile_legacy_baseline', studentId: OTHER, snapshotTotal: 300, token: tk })
  check(`body.studentId=OTHER, 토큰=STUDENT -> STUDENT 명의로만 처리 (${JSON.stringify(rTamper.body)})`, rTamper.body?.ok === true && rTamper.body?.reason === 'reconciled')
  check('STUDENT 원장에 행 생김', earnedOf(STUDENT) === 300)
  check('OTHER 원장은 여전히 0', earnedOf(OTHER) === 0)

  const rAbc = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 'abc', token: tk })
  check("snapshotTotal 'abc' -> invalid_snapshot", rAbc.body?.ok === false && rAbc.body?.reason === 'invalid_snapshot')
  const rNeg = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: -1, token: tk })
  check('snapshotTotal -1 -> invalid_snapshot', rNeg.body?.ok === false && rNeg.body?.reason === 'invalid_snapshot')
  const rHuge = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 1e9, token: tk })
  check('snapshotTotal 1e9 -> invalid_snapshot', rHuge.body?.ok === false && rHuge.body?.reason === 'invalid_snapshot')

  const rNoToken = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300 })
  check('토큰 없음 -> relogin_required', rNoToken.body?.ok === false && rNoToken.body?.reason === 'relogin_required')

  const SID2 = seedStudent()
  fake.__fail.rpc = { code: '42883', message: 'function does not exist' }
  const r42883 = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300, token: tokenFor(SID2) })
  check('RPC 42883 -> table_missing', r42883.body?.ok === false && r42883.body?.reason === 'table_missing')

  fake.__fail.rpc = { code: 'XX000', message: 'boom' }
  const rGeneric = await call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300, token: tokenFor(SID2) })
  check('RPC 일반 실패 -> rpc_failed', rGeneric.body?.ok === false && rGeneric.body?.reason === 'rpc_failed')
  fake.__fail.rpc = null
}

console.log('\n11. 동시성 — 같은 학생 동시 reconcile 2회(Promise.all) -> v2 행 정확히 1건, 한쪽만 reconciled')
{
  fake.__reset()
  const sid = seedStudent()
  const tk = tokenFor(sid)
  fake.__db.student_progress[sid] = { total_stars: 300, historySince: 1000000 }
  const [r1, r2] = await Promise.all([
    call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300, token: tk }),
    call({ action: 'reconcile_legacy_baseline', snapshotTotal: 300, token: tk }),
  ])
  const v2Rows = fake.__db.reward_ledger.filter((r) => r.student_id === sid && r.reward_type === 'legacy-baseline' && r.source_type === 'legacy-baseline-v2')
  check('v2 행 정확히 1건', v2Rows.length === 1)
  const reasons = [r1.body?.reason, r2.body?.reason].sort()
  check("응답 reason 조합 ['already_reconciled','reconciled']", JSON.stringify(reasons) === JSON.stringify(['already_reconciled', 'reconciled']))
  check('두 응답 모두 ok true', r1.body?.ok === true && r2.body?.ok === true)
}

console.log('\n12. 무회귀 — 기존 ledger:reward / purchase_town_item / get_town_shop_state가 같은 번들에서 여전히 동작')
{
  fake.__reset()
  const sid = seedStudent()
  const tk = tokenFor(sid)
  const evt = dailyMissionBonusEvent()
  const rReward = await call({ ledger: 'reward', studentId: sid, rewardType: evt.rewardType, sourceType: evt.sourceType, sourceId: evt.sourceId, token: tk })
  check('reward 분기 -> ok true, duplicate false', rReward.body?.ok === true && rReward.body?.duplicate === false)

  fake.__db.town_items.push({ id: 'shop-lamp', name: '램프', emoji: '🏮', price: 5, active: true })
  const rPurchase = await call({ action: 'purchase_town_item', itemId: 'shop-lamp', token: tk })
  check(`purchase_town_item -> ok true / purchased (${JSON.stringify(rPurchase.body)})`, rPurchase.body?.ok === true && rPurchase.body?.reason === 'purchased')

  const rState = await call({ action: 'get_town_shop_state', token: tk })
  check(`get_town_shop_state -> ok true, owned에 shop-lamp 포함 (${JSON.stringify(rState.body)})`,
    rState.body?.ok === true && Array.isArray(rState.body?.owned) && rState.body.owned.includes('shop-lamp'))
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0 ? '모든 단언 통과 — 컷오버 레이스 방지(레거시 이관) 검증 완료' : `${failures}개 단언 실패`)
process.exit(failures === 0 ? 0 : 1)
