// scripts/testTownShopServer.mjs
//
// Town Shop(별 소비) 서버 경로 — api/grant-xp.js의 `action:'get_town_shop_state'`
// / `action:'purchase_town_item'` 두 분기의 **동작** 검증(2026-09-06).
// scripts/testRewardServerHardeningBehavior.mjs와 같은 하네스 패턴을 그대로
// 재사용한다: esbuild로 api/grant-xp.js를 번들하되 @supabase/supabase-js와
// ./_pinAuth.js만 인메모리 가짜로 치환한다. 핸들러 코드 자체는 한 글자도
// 바꾸지 않고 그대로 실행된다. 네트워크 0, production 요청 0, DB 무접촉.
//
// 정직한 커버리지 경계(반드시 읽을 것): 실제 구매 원자성(동시에 두 요청이
// 같은 학생/같은 아이템으로 들어왔을 때 "딱 하나만 성공"하는 보장)은
// Postgres 함수 purchase_town_item()의 유니크 제약/트랜잭션에서 나온다 —
// 이 파일의 가짜 supabase.rpc()는 그 SQL을 실행하지 않는다. 여기서는
// "핸들러가 RPC의 반환값(reason:'already_owned' 등)을 올바르게 응답으로
// 옮기는가"만 검증한다. §5(더블클릭)는 가짜 rpc 구현이 "두 번째 insert가
// unique 제약에 걸린다"를 흉내내 already_owned를 반환하게 만든 것이지,
// 실제 DB 트랜잭션 레이스를 재현한 것이 아니다 — SQL 파일 쪽의 별도 테스트
// (동시성 실측)가 있다면 그것이 진짜 원자성 증거이고, 이 파일은 아니다.
//
// 산출물: scripts/.tmp/(gitignore) — fakeSupabaseForTownShop.mjs /
// fakePinAuthTownShop.mjs / grantXp.townShop.bundle.mjs (테스트 전용 파일명,
// testRewardServerHardeningBehavior.mjs가 쓰는 파일명과 충돌하지 않는다).
//
// 등록: 이 스크립트를 harness registry에 올리는 작업은 이 세션의 책임 밖
// (tests/harness/registry.mjs는 별도 소유자가 관리) — 여기서는 직접 실행만.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

// ── 가짜 Supabase ──────────────────────────────────────────────────────
// __db 스키마:
//   students: [{ id }]
//   reward_totals: { [studentId]: earnedStars }   // "이 학생이 지금까지 번 별" 요약(테스트 픽스처 전용 — 실제 스키마는 reward_ledger 합산)
//   star_purchases: [{ student_id, item_id, stars_spent }]
//   town_items: [{ id, name, emoji, price, active }]
//   reward_ledger / xp_ledger: 기존 reward/XP 분기 무회귀 검증용(§15)
const fakePath = path.join(TMP, 'fakeSupabaseForTownShop.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testTownShopServer.mjs
export const __db = {
  students: [],
  reward_totals: {},
  star_purchases: [],
  town_items: [],
  reward_ledger: [],
  xp_ledger: [],
}
export const __fail = { rpc: null, town_items: null, students: null, reward_ledger: null }
export const __calls = []
export function __reset() {
  __db.students = []
  __db.reward_totals = {}
  __db.star_purchases = []
  __db.town_items = []
  __db.reward_ledger = []
  __db.xp_ledger = []
  __fail.rpc = null; __fail.town_items = null; __fail.students = null; __fail.reward_ledger = null
  __calls.length = 0
}

function spentFor(studentId) {
  return __db.star_purchases
    .filter((p) => p.student_id === studentId)
    .reduce((a, p) => a + p.stars_spent, 0)
}

// town_items 조회(select/eq 체이닝) — reward_ledger/xp_ledger 등 기존
// 분기가 쓰는 select().eq().maybeSingle() / select(count:head) 체인도 함께
// 지원한다(§15 무회귀 검증에 필요, testRewardServerHardeningBehavior.mjs의
// makeQuery 로직을 그대로 재사용).
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_cols, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    match(rows) {
      return rows.filter((r) => filters.every(([c, v]) => {
        if (c.startsWith('__gte__')) return String(r[c.slice(7)]) >= String(v)
        return String(r[c]) === String(v)
      }))
    },
    maybeSingle() {
      __calls.push({ table, op: 'maybeSingle', filters: [...filters] })
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return Promise.resolve({ data: hit[0] || null, error: null })
    },
    then(resolve) {
      __calls.push({ table, op: headCount ? 'count' : 'select', filters: [...filters] })
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}

// ── RPC 시뮬레이션 — SQL 함수 계약을 인메모리로 흉내낸다(순서 고정) ──────
// purchase_town_item(p_student_id, p_item_id):
//   1) 학생 존재? 없으면 student_not_found
//   2) 아이템 존재(& active)? 없으면 item_not_found
//   3) 이미 구매(star_purchases에 (student,item) 존재)? 있으면 already_owned, stars_spent 0
//   4) earned - spent(=available) >= price? 부족하면 insufficient, balance_after=available
//   5) insert star_purchases, ok true, reason purchased, stars_spent=price, balance_after=available-price
// __concurrent 모드: 같은 (student,item)에 대해 두 번째 insert 직전에 이미
// 첫 번째가 끼어들어 있으면 unique 제약에 걸린 것처럼 already_owned로
// 전환한다(진짜 DB 트랜잭션이 아니라 이 파일 안에서 순차 실행되는 async
// 흐름을 흉내낸 것 — 파일 상단 커버리지 경계 참고).
function rpcPurchase(studentId, itemId) {
  const student = __db.students.find((s) => s.id === studentId)
  if (!student) return { ok: false, reason: 'student_not_found', stars_spent: 0, balance_after: 0 }
  const item = __db.town_items.find((i) => i.id === itemId && i.active !== false)
  if (!item) return { ok: false, reason: 'item_not_found', stars_spent: 0, balance_after: 0 }
  const already = __db.star_purchases.some((p) => p.student_id === studentId && p.item_id === itemId)
  const earned = __db.reward_totals[studentId] || 0
  const spent = spentFor(studentId)
  const available = Math.max(0, earned - spent)
  if (already) return { ok: true, reason: 'already_owned', stars_spent: 0, balance_after: available }
  if (available < item.price) return { ok: false, reason: 'insufficient', stars_spent: 0, balance_after: available }
  __db.star_purchases.push({ student_id: studentId, item_id: itemId, stars_spent: item.price })
  return { ok: true, reason: 'purchased', stars_spent: item.price, balance_after: available - item.price }
}
function rpcState(studentId) {
  const earned = __db.reward_totals[studentId] || 0
  const spent = spentFor(studentId)
  const available = Math.max(0, earned - spent)
  const owned = __db.star_purchases.filter((p) => p.student_id === studentId).map((p) => p.item_id)
  return { earned, spent, available, owned_item_ids: owned }
}

export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          __calls.push({ table, op: 'insert', row })
          if (__fail[table]) return Promise.resolve({ error: __fail[table] })
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
    rpc(name, args) {
      __calls.push({ rpc: name, args })
      if (__fail.rpc) return Promise.resolve({ data: null, error: __fail.rpc })
      if (name === 'purchase_town_item') {
        const row = rpcPurchase(args.p_student_id, args.p_item_id)
        return Promise.resolve({ data: [row], error: null })
      }
      if (name === 'get_town_shop_state') {
        const row = rpcState(args.p_student_id)
        return Promise.resolve({ data: [row], error: null })
      }
      return Promise.resolve({ data: null, error: { code: 'XX000', message: 'unknown rpc ' + name } })
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const fakePinAuthPath = path.join(TMP, 'fakePinAuthTownShop.mjs')
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const outfile = path.join(TMP, 'grantXp.townShop.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-townshop',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

process.env.SESSION_SECRET = 'townshop-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

const STUDENT = '11111111-2222-4333-8444-555555555555'
const OTHER = '99999999-8888-4777-8666-555555555555'
const ITEM = 'shop-lamp'
const tokenFor = (sid, opts) => signSessionToken(sid, opts)

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
function call(body, headers = {}) {
  const r = res()
  return handler({ method: 'POST', body: body || {}, headers }, r).then(() => r)
}
function seed({ student = true, earned = 100, item = { id: ITEM, name: '램프', emoji: '🏮', price: 60, active: true } } = {}) {
  fake.__reset()
  if (student) fake.__db.students.push({ id: STUDENT })
  fake.__db.reward_totals[STUDENT] = earned
  if (item) fake.__db.town_items.push(item)
}
const purchases = () => fake.__db.star_purchases

console.log('\n1. 충분한 별 -> 구매 성공')
{
  seed({ earned: 100 })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check(`ok true (${JSON.stringify(r.body)})`, r.body?.ok === true)
  check("reason 'purchased'", r.body?.reason === 'purchased')
  check('starsSpent 60', r.body?.starsSpent === 60)
  check('balanceAfter 40 (100-60)', r.body?.balanceAfter === 40)
  check('star_purchases 1건', purchases().length === 1)
}

console.log('\n2. 정확히 60개 보유 -> balanceAfter 0')
{
  seed({ earned: 60 })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check('ok true', r.body?.ok === true)
  check('balanceAfter 0', r.body?.balanceAfter === 0)
}

console.log('\n3. 부족 (59개) -> insufficient, 0건 삽입')
{
  seed({ earned: 59 })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check("ok false / reason 'insufficient'", r.body?.ok === false && r.body?.reason === 'insufficient')
  check('star_purchases 0건', purchases().length === 0)
  check('balanceAfter 59', r.body?.balanceAfter === 59)
}

console.log('\n4. 이미 소유 -> already_owned, duplicate true, 여전히 1건')
{
  seed({ earned: 100 })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  const r2 = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check("ok true / reason 'already_owned'", r2.body?.ok === true && r2.body?.reason === 'already_owned')
  check('duplicate true', r2.body?.duplicate === true)
  check('star_purchases 여전히 1건', purchases().length === 1)
}

console.log('\n5. 더블클릭 — 동시 2회 호출 (커버리지 경계: 파일 상단 주석 참고, 진짜 DB 원자성 검증 아님)')
{
  seed({ earned: 100 })
  const tk = tokenFor(STUDENT)
  const [a, b] = await Promise.all([
    call({ action: 'purchase_town_item', itemId: ITEM, token: tk }),
    call({ action: 'purchase_town_item', itemId: ITEM, token: tk }),
  ])
  check('star_purchases 정확히 1건', purchases().length === 1)
  const reasons = [a.body?.reason, b.body?.reason].sort()
  check("응답 reason 조합이 ['already_owned','purchased'] (한쪽만 실제 구매)", JSON.stringify(reasons) === JSON.stringify(['already_owned', 'purchased']))
}

console.log('\n6. 재시도 — 성공 응답 이후 같은 요청 재전송 -> 여전히 1건')
{
  seed({ earned: 100 })
  const tk = tokenFor(STUDENT)
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tk })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tk })
  check('1건만 유지', purchases().length === 1)
}

console.log('\n7. body 가격/잔액 위조 -> 무시됨 + 정적 검사')
{
  seed({ earned: 100 })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, price: 1, starsSpent: 1, balance: 9999, token: tokenFor(STUDENT) })
  check('starsSpent 여전히 60(위조 무시)', r.body?.starsSpent === 60)
  check('star_purchases 행의 stars_spent도 60', purchases()[0]?.stars_spent === 60)

  const src = fs.readFileSync(path.resolve('api/grant-xp.js'), 'utf8')
  // 주석 제거 후(문자열 리터럴 안의 우연한 일치까지 배제하기 위해 라인
  // 주석·블록 주석을 모두 벗겨낸다) req.body.price/.starsSpent/.balance
  // 참조가 전혀 없어야 한다.
  const stripped = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
  check('소스에 req.body.price 참조 없음', !/req\.body\.price\b/.test(stripped))
  check('소스에 req.body.starsSpent 참조 없음', !/req\.body\.starsSpent\b/.test(stripped))
  check('소스에 req.body.balance 참조 없음', !/req\.body\.balance\b/.test(stripped))
}

console.log('\n8. body.studentId 변조 -> 토큰의 sid가 이긴다 + 정적 검사')
{
  seed({ earned: 100 })
  fake.__db.students.push({ id: OTHER })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, studentId: OTHER, token: tokenFor(STUDENT) })
  check('ok true', r.body?.ok === true)
  check('실제 구매 행의 student_id는 토큰 주체(STUDENT)', purchases()[0]?.student_id === STUDENT)
  check('OTHER 명의로는 구매되지 않음', !purchases().some((p) => p.student_id === OTHER))

  const src = fs.readFileSync(path.resolve('api/grant-xp.js'), 'utf8')
  const stripped = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
  // 두 새 action 분기 블록만 추려서(reward/XP 분기의 기존 studentId 사용은
  // 검사 대상이 아님) req.body.studentId 참조가 없는지 확인한다.
  const shopBlockStart = stripped.indexOf("req.body.action === 'get_town_shop_state'")
  const shopBlockEnd = stripped.indexOf("req.body && req.body.ledger === 'reward'")
  const shopBlock = stripped.slice(Math.max(0, shopBlockStart - 200), shopBlockEnd)
  check('마을상점 분기 소스에 req.body.studentId 참조 없음', !/req\.body\.studentId\b/.test(shopBlock))
}

console.log('\n9. 다른(정당) 토큰 -> 각자 명의로만 구매')
{
  seed({ earned: 100 })
  fake.__db.students.push({ id: OTHER })
  fake.__db.reward_totals[OTHER] = 100
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(OTHER) })
  check('OTHER 명의 구매 1건', purchases().length === 1 && purchases()[0].student_id === OTHER)
  check('STUDENT 명의는 여전히 0건', !purchases().some((p) => p.student_id === STUDENT))
}

console.log('\n10. 인증 실패 경로 — 토큰 없음/위조/만료')
{
  seed({ earned: 100 })
  const noToken = await call({ action: 'purchase_town_item', itemId: ITEM })
  check("토큰 없음 -> relogin_required", noToken.body?.ok === false && noToken.body?.reason === 'relogin_required')

  const badSig = tokenFor(STUDENT).split('.')[0] + '.AAAAAAAA'
  const r2 = await call({ action: 'purchase_town_item', itemId: ITEM, token: badSig })
  check("서명 위조 -> unauthorized(bad_signature)", r2.body?.reason === 'unauthorized' && r2.body?.detail === 'bad_signature')

  const expired = tokenFor(STUDENT, { now: Date.now() - 1000 * 60 * 60 * 24 * 365 })
  const r3 = await call({ action: 'purchase_town_item', itemId: ITEM, token: expired })
  check("만료 토큰 -> unauthorized(expired)", r3.body?.reason === 'unauthorized' && r3.body?.detail === 'expired')

  check('세 경우 모두 구매 0건', purchases().length === 0)

  const stateNoToken = await call({ action: 'get_town_shop_state' })
  check('상태 조회도 토큰 없음 -> relogin_required', stateNoToken.body?.ok === false && stateNoToken.body?.reason === 'relogin_required')
}

console.log('\n11. RPC 실패 매핑 — 일반 실패 -> rpc_failed / 42883 -> table_missing')
{
  seed({ earned: 100 })
  fake.__fail.rpc = { code: 'XX000', message: 'boom' }
  const r1 = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check("일반 rpc 실패 -> ok false / reason 'rpc_failed'", r1.body?.ok === false && r1.body?.reason === 'rpc_failed')
  check('구매 0건', purchases().length === 0)

  fake.__fail.rpc = { code: '42883', message: 'function does not exist' }
  const r2 = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check("42883 -> reason 'table_missing'", r2.body?.reason === 'table_missing')

  fake.__fail.rpc = { code: 'PGRST202', message: 'schema cache miss' }
  const r3 = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check("PGRST202(state) -> reason 'table_missing'", r3.body?.reason === 'table_missing')
}

console.log('\n12. 구매 후 상태 조회 — owned/available/items 일치')
{
  seed({ earned: 100 })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('ok true', r.body?.ok === true)
  check(`owned에 ${ITEM} 포함`, Array.isArray(r.body?.owned) && r.body.owned.includes(ITEM))
  check('available 40 (100-60)', r.body?.available === 40)
  check(`items에 ${ITEM}(price 60) 포함`, Array.isArray(r.body?.items) && r.body.items.some((it) => it.id === ITEM && it.price === 60))

  const noToken = await call({ action: 'get_town_shop_state' })
  check('토큰 없이 상태 조회 -> relogin_required', noToken.body?.reason === 'relogin_required')
}

console.log('\n13. available은 절대 음수로 노출되지 않음 (spent > earned)')
{
  seed({ earned: 100 })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  fake.__db.reward_totals[STUDENT] = 10 // 이후 조정으로 earned < spent가 된 극단 상황을 흉내
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('available 0 (음수 아님)', r.body?.available === 0)
}

console.log('\n14. town_items 조회 실패해도 상태 조회 자체는 ok true, items: []')
{
  seed({ earned: 100 })
  fake.__fail.town_items = { code: 'XX000', message: 'boom' }
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('ok true (부분 실패를 전체 실패로 만들지 않음)', r.body?.ok === true)
  check('items 빈 배열', Array.isArray(r.body?.items) && r.body.items.length === 0)
}

console.log('\n15. 무회귀 — 기존 reward/XP 분기가 같은 번들에서 그대로 동작하는가')
{
  seed({ earned: 100 })
  const today = new Date().toDateString()
  const rewardBody = { ledger: 'reward', studentId: STUDENT, rewardType: 'word-session-complete', sourceType: 'daily-words', sourceId: today, token: tokenFor(STUDENT) }
  const r1 = await call(rewardBody)
  check('reward 분기 1회차 -> ok true', r1.body?.ok === true && r1.body?.duplicate === false)
  const r2 = await call(rewardBody)
  check('reward 분기 2회차(재생) -> duplicate true', r2.body?.duplicate === true)

  const xpBody = { studentId: STUDENT, eventType: 'word-view-complete', sourceEventId: `word-view-complete:${new Date().toISOString().slice(0, 10)}` }
  const r3 = await call(xpBody)
  check('기존 XP 분기 -> ok true 응답', r3.body?.ok === true)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0 ? '모든 단언 통과 — Town Shop 서버 동작 검증 완료' : `${failures}개 단언 실패`)
process.exit(failures === 0 ? 0 : 1)
