// scripts/testDoubleEvents.mjs
//
// 동일 이벤트 2회 발생(더블파이어) 멱등 스위트 (Overnight QA Track T4,
// 2026-09-04). docs/REWARD_LOOP_AUDIT_2026-09-03.md §2~§4가 정리한 "오늘의
// 루프"(학습 행동 → grantReward/grantLedgerReward → rewardEngine.js 규칙 →
// 로컬 rewardLedger + POST /api/grant-xp) 전체를 대상으로, 학습 행동 하나가
// 정확히 같은 이벤트로 두 번 들어와도(더블탭/네트워크 재시도/새로고침·
// 재로그인 remount) 별(stars)/XP/정원(garden)/원장(ledger)/마일스톤 중
// 어느 것도 두 배로 부풀지 않는지를 한 파일에서 통합 확인한다.
//
// 이 파일은 새 회귀를 만들지 않는다 — scripts/testRewardFlow.mjs(개별
// 앵커별 1회 지급 계약)/scripts/testMissionBonusIdempotency.mjs(4/4 미션
// 보너스 remount 회귀 고정)/scripts/testRewardServerHardeningBehavior.mjs
// (서버 replay/concurrent 20회)/scripts/testGardenGrowthSources.mjs(정원
// 성장 소스)가 이미 검증한 것과 같은 소스 코드·같은 하네스 기법을 재사용
//하되, "같은 이벤트를 정확히 두 번 발생시켰을 때"라는 단일 축으로 8개
// 보상 카테고리 전체를 한 번에 훑고, 서버 원장 vs UI 표시값(stars) 대조
// 까지 한 파일에서 마무리한다(운영자 지정 범위).
//
// 하네스: fakeReact.mjs(React state updater 스텁) + esbuild로 직접 번들한
// src/hooks/useStudent.js(scripts/buildRaceBundle.mjs와 동일 기법이되,
// postXpEvent/postRewardEvent 호출을 "캡처"하는 전용 wordLibrary 스텁을
// 새로 생성 — testMissionBonusIdempotency.mjs가 이미 쓴 "자체 스텁 파일
// 생성 후 external 번들" 패턴 재사용, scripts/.tmp/(gitignore)) + 서버
// 섹션은 testRewardServerHardeningBehavior.mjs와 동일하게 api/grant-xp.js를
// 인메모리 가짜 Supabase 위에서 그대로 구동(핸들러 코드 무수정).
// 네트워크 0, 실제 Supabase 접촉 0, production 요청 0.
//
// 등록: npm run verify:double-events
import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let failures = 0
let asserted = 0
const failedLabels = []
let scenario = ''
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++; failedLabels.push(`[${scenario}] ${label}`) }
}

// ── 알려진 "레거시 무원장" 상수(코드 정독, useStudent.js 소스 인용) ─────────
// 아래 값들은 export되지 않은 module-local const라 직접 import할 수 없다
// (import하려면 useStudent.js를 그대로 로드해야 하는데, 이 파일은 React를
// 요구해 plain node에서 직접 import가 불가능 — 그래서 번들 경유로만 쓴다).
// 값 자체는 testMissionBonusIdempotency.mjs/testRewardFlow.mjs가 이미 같은
// 방식(하드코딩 + 주석 인용)으로 고정해 둔 계약과 동일하다.
const MISSION_BONUS_STARS = 10       // useStudent.js:147 (const MISSION_BONUS_STARS = 10)
const PRONUNCIATION_STAR = 1         // useStudent.js:1255 grantReward(1, `pronunciation:${wordId}:${today}`)
// SPELLING_COMBO_BONUS는 export이므로 아래 번들에서 실제로 가져와 쓴다.

// ══════════════════════════════════════════════════════════════════════════
// 0) 번들 — postXpEvent/postRewardEvent 호출을 캡처하는 전용 wordLibrary
//    스텁(기존 wordLibraryRaceStub.mjs를 그대로 재사용하되 두 함수만 캡처용
//    으로 오버라이드 — testMissionBonusIdempotency.mjs가 이미 검증한 기법).
// ══════════════════════════════════════════════════════════════════════════
const raceStubUrl = pathToFileURL(path.resolve('scripts/wordLibraryRaceStub.mjs')).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const capturingStubPath = path.join(TMP, 'wordLibraryDoubleEventsStub.mjs')
fs.writeFileSync(capturingStubPath, `// AUTO-GENERATED by scripts/testDoubleEvents.mjs — do not edit by hand.
export * from ${JSON.stringify(raceStubUrl)}
export const xpCalls = []
export async function postXpEvent(studentId, eventType, sourceEventId) {
  xpCalls.push({ studentId, eventType, sourceEventId })
}
export const rewardCalls = []
export async function postRewardEvent(studentId, rewardType, sourceType, sourceId) {
  rewardCalls.push({ studentId, rewardType, sourceType, sourceId })
}
export function resetCaptures() { xpCalls.length = 0; rewardCalls.length = 0 }
`, 'utf8')
const capturingStubUrl = pathToFileURL(capturingStubPath).href

const outfile = path.join(TMP, 'useStudent.doubleEvents.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'double-events-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: capturingStubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)

const stub = await import(capturingStubUrl)
const bundle = await import(pathToFileURL(outfile).href)
const { useStudent, mergeProgressRecords, todayStr, SPELLING_COMBO_BONUS } = bundle

// ══════════════════════════════════════════════════════════════════════════
// 1) 최소 DOM/스토리지 더블 + 마운트 헬퍼(기존 스위트와 동일 관례)
// ══════════════════════════════════════════════════════════════════════════
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(t, f) { (this.listeners[t] ||= []).push(f) }
  removeEventListener(t, f) { this.listeners[t] = (this.listeners[t] || []).filter(x => x !== f) }
  dispatch(t) { (this.listeners[t] || []).forEach(f => f()) }
}
const flush = () => new Promise(r => process.nextTick(r))
const settle = (h) => { h.rerender(); return h } // useEffect 안에서 일어난 patch() 결과를 읽으려면 명시 재렌더 필요(testRewardFlow.mjs settle() 주석과 동일 이유)

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  stub.resetCaptures()
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}
function mountOnCurrentEnv(id, name) {
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return host
}
function mountFresh(id, name) { freshEnv(); return mountOnCurrentEnv(id, name) }
// 같은 localStorage 위에서 완전히 새 렌더 트리 = 새로고침/재로그인/탭 전환
// (testMissionBonusIdempotency.mjs remount()와 동일 — useRef 가드는 초기화
// 되지만 rewardLedger/round(영속 필드)는 그대로 이어받는다).
function remount(id, name) {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  return mountOnCurrentEnv(id, name)
}

function ledgerArr(h) { return Array.isArray(h.result.rewardLedger) ? h.result.rewardLedger : [] }
function ledgerCount(h, type, pred) { return ledgerArr(h).filter(e => e && e.reward_type === type && (!pred || pred(e.source_id))).length }
function ledgerSum(h) { return ledgerArr(h).reduce((a, e) => a + (Number(e.stars_delta) || 0), 0) }

console.log('\n=== [double-events] 동일 이벤트 2회 발생 멱등 — 퀴즈/철자/시험/미션/스트릭/마일스톤/정원 + 서버 중복 + ledger↔UI 대조 ===')

// ══════════════════════════════════════════════════════════════════════════
// 2) 퀴즈 완료 — recordQuizAnswer 같은 단어 2회 / 5·5 일일 임계 remount 2회
// ══════════════════════════════════════════════════════════════════════════
scenario = '1) 퀴즈 완료'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_quiz_word'
  const h = mountFresh(ID)
  await flush(); settle(h)
  h.result.recordQuizAnswer('applx', true)
  h.result.recordQuizAnswer('applx', true) // 같은 단어 2회(더블탭 시뮬레이션)
  settle(h)
  check('recordQuizAnswer 같은 단어 2회 → clearedWords에 정확히 1번만', h.result.clearedWords.filter(w => w === 'applx').length === 1)
  check('recordQuizAnswer 같은 단어 2회 → 별 지급 없음(퀴즈 자체는 별을 주지 않음)', h.result.stars === 0)

  // 5/5 퀴즈 임계 — 같은 마운트에서 markQuizSolved를 GOAL 이상 계속 불러도
  // XP 지급은 정확히 1회(dailyCategoryXpFiredRef 가드).
  const ID2 = 'QA_DBL_quiz_threshold'
  const h2 = mountFresh(ID2)
  await flush(); settle(h2)
  for (let i = 0; i < 5; i++) h2.result.markQuizSolved()
  settle(h2); await flush()
  const afterFirst = stub.xpCalls.filter(c => c.eventType === 'quiz-complete').length
  check('5/5 도달 직후 quiz-complete XP 호출 정확히 1회', afterFirst === 1)
  for (let i = 0; i < 5; i++) h2.result.markQuizSolved() // 같은 마운트에서 임계 재도달(라운드 반복)
  settle(h2); await flush()
  check('같은 마운트에서 임계 재도달해도 quiz-complete XP 호출 여전히 1회(useRef 가드)',
    stub.xpCalls.filter(c => c.eventType === 'quiz-complete').length === 1)

  // remount(새로고침/재로그인) — useRef 가드는 초기화되므로 클라이언트가
  // grantXp를 다시 호출하는 것은 문서화된 기존 동작(버그 아님, 감사 §11 —
  // xp_ledger UNIQUE(student_id, source_event_id)가 최종 권위). 여기서는
  // "같은 날짜 기간키를 재사용하는가"만 확인하고, 그 결과 서버 원장이
  // 실제로 1건에 머무는지는 아래 섹션 4)에서 이 정확한 시나리오로 검증한다.
  const h3 = remount(ID2)
  await flush(); settle(h3)
  const afterRemount = stub.xpCalls.filter(c => c.eventType === 'quiz-complete')
  check('[문서화됨] remount 후 quiz-complete 클라이언트 재호출 발생(예상된 동작, 버그 아님)', afterRemount.length === 2)
  check('재호출도 동일한 날짜 기간키(source_event_id)를 씀 — 서버 dedup의 전제조건',
    new Set(afterRemount.map(c => c.sourceEventId)).size === 1)
}

// ══════════════════════════════════════════════════════════════════════════
// 3) 철자 정답 — 같은 단어 2회(콤보 제외) / writing-complete 하루 1회
// ══════════════════════════════════════════════════════════════════════════
scenario = '2) 철자 정답'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_spelling_word'
  const h = mountFresh(ID)
  await flush(); settle(h)
  h.result.recordSpellingAnswer('bananax', true)
  h.result.recordSpellingAnswer('bananax', true) // 같은 단어 2회
  settle(h)
  check('recordSpellingAnswer 같은 단어 2회 → clearedWords 정확히 1번만(markWordCleared 멱등)',
    h.result.clearedWords.filter(w => w === 'bananax').length === 1)

  // writing-complete는 GOAL(5) 도달 시점에만 1회 — 이미 완료된 뒤 같은 단어를
  // 다시 정답 처리해도(중복 제출) 재지급되지 않는다.
  const ID2 = 'QA_DBL_writing_goal'
  const h2 = mountFresh(ID2)
  await flush(); settle(h2)
  for (let i = 0; i < 5; i++) h2.result.recordSpellingAnswer(`sw${i}`, true)
  settle(h2)
  check('5/5 완료 → writing-complete 정확히 1건', ledgerCount(h2, 'writing-complete') === 1)
  h2.result.recordSpellingAnswer('sw0', true) // 이미 카운트된 단어를 다시 정답 처리(더블 제출)
  h2.result.recordSpellingAnswer('sw0', true)
  settle(h2)
  check('완료 후 같은 단어 추가 제출 2회 → writing-complete 여전히 1건(재지급 없음)', ledgerCount(h2, 'writing-complete') === 1)

  // 참고(범위 명시, 버그 아님) — 콤보 보너스(SPELLING_COMBO_BONUS)는 "같은
  // 이벤트 재발생"이 아니라 "매 정답 제출마다 콤보가 1씩 진짜로 늘어나는"
  // 별개 축이라, 완료 후에도 계속 정답을 제출하면 콤보값이 계속 올라가
  // 새 콤보 마일스톤(예: 10)에 도달할 수 있다 — 이번 파일의 "더블파이어"
  // 정의(같은 이벤트를 두 번) 범위 밖이므로 단언하지 않고 사실만 기록한다.
  const comboAfterExtra = h2.result.rewardLedger // writing-complete/wrong-word-recovered 외 콤보는 rewardLedger에 없음(레거시 무원장)
  check('[범위 밖 기록] 콤보 보너스는 rewardLedger에 없다(레거시 무원장 경로) — 감사 §3 확인', Array.isArray(comboAfterExtra))
}

// ══════════════════════════════════════════════════════════════════════════
// 4) 시험(유닛) 완료 — recordExamCompleted 같은 testId 2회(main에는 unit-
//    complete 전용 보상 타입이 없다 — 감사 §2/§4, feat/reward-loop 브랜치
//    전용 — 현재 앵커 중 가장 가까운 유닛/시험 단위 앵커는 exam-complete)
// ══════════════════════════════════════════════════════════════════════════
scenario = '3) 시험(유닛) 완료'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_exam'
  const h = mountFresh(ID)
  await flush(); settle(h)
  const before = h.result.stars
  h.result.recordExamCompleted?.('unit-test-1')
  h.result.recordExamCompleted?.('unit-test-1')
  settle(h)
  check('recordExamCompleted 같은 testId 2회 → exam-complete 정확히 1건', ledgerCount(h, 'exam-complete', id => id === 'unit-test-1') === 1)
  check('stars 델타 === +2(1회분만)', h.result.stars === before + 2)
}

// ══════════════════════════════════════════════════════════════════════════
// 5) 미션(오늘의 미션 4/4) — 2회 완료를 freshRound 레이스로 재현
//    (testMissionBonusIdempotency.mjs의 기법 재사용, 축약판) — 2026-08-23
//    수정이 remount 이후에도 여전히 고정돼 있는지 재확인(FAIL-first 대상,
//    "이미 고쳐진 것이 유지되는가").
// ══════════════════════════════════════════════════════════════════════════
scenario = '4) 미션 완료(4/4)'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_mission'
  const STORE = 'paul_easy_progress'
  function completeFullRound(h, prefix) {
    for (let i = 0; i < 5; i++) h.result.markWordViewed(`${prefix}-v${i}`)
    for (let i = 0; i < 5; i++) h.result.markExampleHeard()
    for (let i = 0; i < 5; i++) h.result.markQuizSolved()
    for (let i = 0; i < 5; i++) h.result.markPronunciationOk(`${prefix}-p${i}`)
    settle(h)
  }
  function simulateMergeRestore(prefix) {
    const store = JSON.parse(globalThis.localStorage.getItem(STORE) || '{}')
    const rec = store[ID]
    rec.round.wordsViewed = Array.from({ length: 5 }, (_, i) => `${prefix}-v${i}`)
    rec.round.examplesHeard = 5; rec.round.quizSolved = 5; rec.round.pronunciationOk = 5
    globalThis.localStorage.setItem(STORE, JSON.stringify(store))
  }

  let h = mountFresh(ID)
  await flush(); settle(h)
  completeFullRound(h, 'm1')
  await flush(); settle(h)
  const starsAfterFirst = h.result.stars
  check('4/4 완료(1회차) → 레거시 미션보너스(+10) 이상 포함해 별 지급', starsAfterFirst >= MISSION_BONUS_STARS)
  check('4/4 완료(1회차) → daily-goal-complete 정확히 1건', ledgerCount(h, 'daily-goal-complete') === 1)

  // "같은 이벤트 2회" = 정확히 같은 라운드(같은 단어 집합)가 병합/remount로
  // 되살아난 경우 — 재지급 0이어야 한다(2026-08-23 회귀 고정, 여기서 재확인).
  simulateMergeRestore('m1')
  const h2 = remount(ID)
  await flush(); settle(h2)
  check('remount + 같은 라운드 복원(같은 이벤트 재발생) → 별 추가 지급 0(고정 유지)', h2.result.stars === starsAfterFirst)
  check('remount 후 daily-goal-complete 여전히 1건(추가 없음)', ledgerCount(h2, 'daily-goal-complete') === 1)
}

// ══════════════════════════════════════════════════════════════════════════
// 6) 스트릭 보너스 — 같은 날짜 2회(single mount 재도달 + remount)
// ══════════════════════════════════════════════════════════════════════════
scenario = '5) 스트릭 보너스'
console.log(`\n-- ${scenario}`)
{
  function daysAgoStr(n) { const d = new Date(); d.setDate(d.getDate() - n); return d.toDateString() }
  const ID = 'QA_DBL_streak'
  const history = { [todayStr()]: { categoriesCompleted: 4 } }
  for (let i = 1; i <= 2; i++) history[daysAgoStr(i)] = { categoriesCompleted: 4 } // 연속 2일 + 오늘 = 3일 스트릭 → +2
  const seed = { studentId: ID, totalStars: 0, history }
  freshEnv()
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify({ [ID]: seed }))
  let h = mountOnCurrentEnv(ID)
  await flush(); settle(h)
  check('스트릭 3일 도달(마운트) → streak-bonus 정확히 1건(+2)', ledgerCount(h, 'streak-bonus') === 1)
  const afterFirst = h.result.stars

  // 같은 날짜에 remount(같은 이벤트 재발생) → 재지급 0.
  const h2 = remount(ID)
  await flush(); settle(h2)
  check('같은 날짜에 remount(같은 이벤트) → streak-bonus 여전히 1건', ledgerCount(h2, 'streak-bonus') === 1)
  check('remount 후 stars 추가 없음', h2.result.stars === afterFirst)
}

// ══════════════════════════════════════════════════════════════════════════
// 7) 마일스톤(addMilestones) + 모자 지급(grantHats) — 같은 id 2회
// ══════════════════════════════════════════════════════════════════════════
scenario = '6) 마일스톤 · 모자'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_milestone'
  const h = mountFresh(ID)
  await flush(); settle(h)
  h.result.addMilestones([{ id: 'ms-first-word', type: 'garden', at: new Date().toISOString(), title: 't' }])
  h.result.addMilestones([{ id: 'ms-first-word', type: 'garden', at: new Date().toISOString(), title: 't' }]) // 같은 id 2회
  settle(h)
  check('addMilestones 같은 id 2회 → milestones 배열에 정확히 1건', h.result.milestones.filter(m => m.id === 'ms-first-word').length === 1)

  h.result.grantHats([{ hatId: 'hat-graduation', earnedAt: new Date().toISOString(), source: 'test' }])
  h.result.grantHats([{ hatId: 'hat-graduation', earnedAt: new Date().toISOString(), source: 'test' }]) // 같은 hatId 2회
  settle(h)
  check('grantHats 같은 hatId 2회 → hatInventory에 정확히 1건', h.result.hatInventory.filter(x => x.hatId === 'hat-graduation').length === 1)
}

// ══════════════════════════════════════════════════════════════════════════
// 8) 정원 성장 트리거 — markWordCleared 같은 단어 2회 → 1포인트
// ══════════════════════════════════════════════════════════════════════════
scenario = '7) 정원 성장(markWordCleared)'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_garden'
  const h = mountFresh(ID)
  await flush(); settle(h)
  h.result.markWordCleared('gword')
  h.result.markWordCleared('gword') // 같은 단어 2회
  settle(h)
  const uniquePoints = new Set([...h.result.cleared, ...h.result.completedWords, ...h.result.clearedWords]).size
  check('markWordCleared 같은 단어 2회 → clearedWords 정확히 1번만', h.result.clearedWords.filter(w => w === 'gword').length === 1)
  check('정원 포인트(합집합 크기) === 1(2가 아님)', uniquePoints === 1)
}

console.log(`\n[클라이언트 섹션 소계] 단언 ${asserted}개 중 실패 ${failures}개`)

// ══════════════════════════════════════════════════════════════════════════
// 9) 서버 — 같은 reward 이벤트 2회(직렬) + 10회 동시(concurrent) → 원장 1건.
//    XP 이벤트 같은 source_event_id 2회 → xp_ledger 1건, 23505는 성공(중복)
//    으로 취급. api/grant-xp.js 코드는 한 글자도 수정하지 않고 그대로
//    구동(testRewardServerHardeningBehavior.mjs와 동일 원칙).
// ══════════════════════════════════════════════════════════════════════════
scenario = '8) 서버 — reward/XP 중복 요청'
console.log(`\n-- ${scenario}`)
{
  const fakePath = path.join(TMP, 'fakeSupabaseForDoubleEvents.mjs')
  fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testDoubleEvents.mjs
export const __db = { students: [], entrance_test_results: [], reward_ledger: [], xp_ledger: [] }
export const __fail = { students: null, entrance_test_results: null, reward_ledger: null }
export function __reset() {
  __db.students = []; __db.entrance_test_results = []; __db.reward_ledger = []; __db.xp_ledger = []
  __fail.students = null; __fail.entrance_test_results = null; __fail.reward_ledger = null
}
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_c, opts) { if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    match(rows) {
      return rows.filter(r => filters.every(([c, v]) => {
        if (c.startsWith('__gte__')) return String(r[c.slice(7)]) >= String(v)
        return String(r[c]) === String(v)
      }))
    },
    maybeSingle() {
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return Promise.resolve({ data: hit[0] || null, error: null })
    },
    then(resolve) {
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}
// xp_ledger는 UNIQUE(student_id, source_event_id) — reward_ledger는 UNIQUE(idempotency_key).
// insert가 이 제약을 인메모리로 재현해 23505를 실제로 던진다(핸들러가 이
// 코드로 '이미 지급됨(성공)'을 판정하는 실제 분기를 그대로 태운다).
export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          if (__fail[table]) return Promise.resolve({ error: __fail[table] })
          if (!__db[table]) __db[table] = []
          let dup = false
          if (table === 'reward_ledger') {
            dup = __db[table].some(r => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          } else if (table === 'xp_ledger') {
            dup = __db[table].some(r => r.student_id === row.student_id && r.source_event_id === row.source_event_id)
          }
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
  }
}
`, 'utf8')
  const fakeUrl = pathToFileURL(fakePath).href

  const fakePinAuthPath = path.join(TMP, 'fakePinAuthDoubleEvents.mjs')
  const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
  fs.writeFileSync(fakePinAuthPath,
    `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')
  const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

  const serverOutfile = path.join(TMP, 'grantXp.doubleEvents.bundle.mjs')
  await esbuild.build({
    entryPoints: ['api/grant-xp.js'],
    bundle: true, format: 'esm', platform: 'node', outfile: serverOutfile,
    plugins: [{
      name: 'fake-supabase-double-events',
      setup(b) {
        b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
        b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
      },
    }],
  })
  const fake = await import(fakeUrl)
  const handler = (await import(pathToFileURL(serverOutfile).href)).default

  process.env.SESSION_SECRET = 'double-events-test-secret'
  const { signSessionToken } = await import('../api/_pinAuth.js')

  const STUDENT = '11111111-2222-4333-8444-666666666666'
  const today = new Date().toDateString()
  function res() {
    const r = { code: null, body: null }
    r.status = (c) => { r.code = c; return r }
    r.json = (b) => { r.body = b; return r }
    return r
  }
  const post = (body) => {
    const r = res(); return handler({ method: 'POST', body, headers: {} }, r).then(() => r)
  }
  function seed() { fake.__reset(); fake.__db.students.push({ id: STUDENT }) }

  console.log('  8a) reward: 같은 이벤트 직렬 2회')
  seed()
  {
    const body = { ledger: 'reward', studentId: STUDENT, rewardType: 'word-session-complete', sourceType: 'daily-words', sourceId: today, token: signSessionToken(STUDENT) }
    const r1 = await post(body)
    const r2 = await post(body)
    check('1회차 duplicate:false', r1.body?.ok === true && r1.body?.duplicate === false)
    check('2회차 duplicate:true(원장 재삽입 아님)', r2.body?.ok === true && r2.body?.duplicate === true)
    check('reward_ledger 정확히 1행', fake.__db.reward_ledger.length === 1)
  }

  console.log('  8b) reward: 같은 이벤트 10회 동시(concurrent)')
  seed()
  {
    const tk = signSessionToken(STUDENT)
    const body = { ledger: 'reward', studentId: STUDENT, rewardType: 'writing-complete', sourceType: 'daily-writing', sourceId: today, token: tk }
    const rs = await Promise.all(Array.from({ length: 10 }, () => post(body)))
    check('동시 10회 → reward_ledger 정확히 1행', fake.__db.reward_ledger.length === 1)
    check('전부 ok:true(성공처럼 보임 — 재시도 폭주 방지 원칙)', rs.every(r => r.body?.ok === true))
    check('정확히 1건만 duplicate:false, 나머지는 duplicate:true', rs.filter(r => r.body?.duplicate === false).length === 1)
    check('지급액 합계 === 2(1회분만)', fake.__db.reward_ledger.reduce((a, r) => a + r.stars_delta, 0) === 2)
  }

  console.log('  8c) xp: 같은 source_event_id 직렬 2회 → xp_ledger 1행(23505는 성공 취급)')
  seed()
  {
    const body = { studentId: STUDENT, eventType: 'quiz-complete', sourceEventId: `quiz-complete:${today}` }
    const r1 = await post(body)
    const r2 = await post(body)
    check('1회차 duplicate:false', r1.body?.ok === true && r1.body?.duplicate === false)
    check('2회차 23505를 성공(duplicate:true)으로 취급', r2.body?.ok === true && r2.body?.duplicate === true)
    check('xp_ledger 정확히 1행', fake.__db.xp_ledger.length === 1)
  }

  console.log('  8d) xp: 같은 source_event_id 10회 동시(concurrent)')
  seed()
  {
    const body = { studentId: STUDENT, eventType: 'word-view-complete', sourceEventId: `word-view-complete:${today}` }
    const rs = await Promise.all(Array.from({ length: 10 }, () => post(body)))
    check('동시 10회 → xp_ledger 정확히 1행', fake.__db.xp_ledger.length === 1)
    check('정확히 1건만 duplicate:false', rs.filter(r => r.body?.duplicate === false).length === 1)
  }

  console.log('  8e) 위 8a) 클라이언트 remount 시나리오(섹션 1)의 실제 재현 — quiz-complete 2회 호출을 그대로 서버에 재생')
  seed()
  {
    const sourceEventId = `quiz-complete:${today}`
    const rs = []
    rs.push(await post({ studentId: STUDENT, eventType: 'quiz-complete', sourceEventId }))
    rs.push(await post({ studentId: STUDENT, eventType: 'quiz-complete', sourceEventId })) // remount가 재전송하는 두 번째 호출
    check('클라이언트가 remount로 2번 호출해도 xp_ledger는 1행(서버가 최종 방어)', fake.__db.xp_ledger.length === 1)
    check('2번째 호출도 ok:true(학생 화면에는 실패로 보이지 않음)', rs[1].body?.ok === true)
  }
}

// ══════════════════════════════════════════════════════════════════════════
// 10) ledger ↔ UI 대조 — 스크립트된 세션(퀴즈 2단어 + writing-complete +
//     daily-goal 4/4) 실행 후 stars === initial + Σ(ledger stars_delta) +
//     Σ(레거시 무원장 실제 지급분). 레거시 지급분은 이 세션 구성으로
//     정확히 알려진 값(발음 5×1 + 미션보너스 10, testRewardFlow.mjs 테스트8
//     과 동일 조합/계약)이라 하드코딩 상수로 명시하고 아래에서 그대로
//     투명하게 나열한다.
// ══════════════════════════════════════════════════════════════════════════
scenario = '9) ledger ↔ UI 대조'
console.log(`\n-- ${scenario}`)
{
  const ID = 'QA_DBL_crosscheck'
  const h = mountFresh(ID)
  await flush(); settle(h)
  const initial = h.result.stars
  check('사전 조건: 신규 계정 stars === 0', initial === 0)

  // 퀴즈 2단어(별을 주지 않는 축 — garden에만 반영, 대조 계산에 포함되지 않음을 확인하는 목적)
  h.result.recordQuizAnswer('cqz1', true)
  h.result.recordQuizAnswer('cqz2', true)
  // daily-goal 4/4(발음 5회 legacy +1×5 포함) + writing-complete(5/5, +2)
  for (let i = 0; i < 5; i++) h.result.markWordViewed(`cwv${i}`)
  for (let i = 0; i < 5; i++) h.result.markExampleHeard()
  for (let i = 0; i < 5; i++) h.result.markQuizSolved()
  for (let i = 0; i < 5; i++) h.result.markPronunciationOk(`cpron${i}`)
  for (let i = 0; i < 5; i++) h.result.recordSpellingAnswer(`csw${i}`, true)
  settle(h); await flush()

  const ledgerDelta = ledgerSum(h)
  check('ledger에 daily-goal-complete(+3) 포함', ledgerCount(h, 'daily-goal-complete') === 1)
  check('ledger에 writing-complete(+2) 포함', ledgerCount(h, 'writing-complete') === 1)
  check('ledger 합계 === 5(3+2, 이 세션 구성에는 word-session-complete 없음 — markWordCompleted 미호출)', ledgerDelta === 5)

  // 레거시 비원장 지급 — 이 세션 구성에서 실제로 발생하는 것만 나열:
  //   · 발음 성공 5회(distinct wordId) → +1×5 = +5 (useStudent.js:1255)
  //   · 오늘의 미션 4/4 보너스(라운드 반복 지급 레거시) → +10 (useStudent.js:1411, MISSION_BONUS_STARS)
  //   · 철자 콤보 마일스톤 3/5(SPELLING_COMBO_BONUS) → +1(combo=3) +2(combo=5) = +3
  // 콤보는 완료 후 추가 정답을 제출하지 않았으므로 정확히 이 세션에서는
  // 3/5 두 마일스톤만 도달(10 미도달) — SPELLING_COMBO_BONUS[3]+[5].
  const legacyPronunciation = PRONUNCIATION_STAR * 5
  const legacyMissionBonus = MISSION_BONUS_STARS
  const legacyCombo = (SPELLING_COMBO_BONUS[3] || 0) + (SPELLING_COMBO_BONUS[5] || 0)
  const legacyTotal = legacyPronunciation + legacyMissionBonus + legacyCombo
  console.log(`  [레거시 무원장 지급 목록] 발음 5×${PRONUNCIATION_STAR}=${legacyPronunciation}, 미션보너스=${legacyMissionBonus}, 콤보(3+5)=${legacyCombo} → 합계 ${legacyTotal}`)

  const expected = initial + ledgerDelta + legacyTotal
  check(`stars === initial(${initial}) + ledger(${ledgerDelta}) + legacy(${legacyTotal}) = ${expected} (실제 ${h.result.stars})`, h.result.stars === expected)
  check('stars는 음수/NaN이 아님', Number.isFinite(h.result.stars) && h.result.stars >= 0)
  check('ledger 항목 중 음수 stars_delta 없음', ledgerArr(h).every(e => Number.isFinite(e.stars_delta) && e.stars_delta >= 0))

  // 이 전체 스크립트된 세션을 "그대로 한 번 더" 재생하면 daily-goal/
  // writing-complete 등 날짜 기간키 앵커는 재지급되지 않는다(위 2)~5)에서
  // 이미 개별 검증) — 여기서는 ledger 합계가 그대로 유지되는지만 재확인.
  h.result.recordQuizAnswer('cqz1', true)
  h.result.recordQuizAnswer('cqz2', true)
  for (let i = 0; i < 5; i++) h.result.markWordViewed(`cwv${i}`)
  settle(h); await flush()
  check('세션 재생(같은 단어/같은 날) 후에도 ledger 합계 동일(날짜 기간키 앵커 재지급 없음)', ledgerSum(h) === ledgerDelta)
}

console.log(`\n${'='.repeat(70)}`)
if (failures === 0) {
  console.log(`PASS  double-events — 동일 이벤트 2회 발생 멱등 (${asserted}개 단언)`)
  process.exit(0)
} else {
  console.log(`FAIL  double-events — ${asserted}개 중 ${failures}개 실패`)
  for (const f of failedLabels) console.log(`  - ${f}`)
  process.exit(1)
}
