// scripts/testLoadConcurrency45.mjs
//
// QA 하네스(2026-09-11, qa/elementary-45-readiness) — "45명 동시 사용" 규모
// 가정 하에 실제 학생 학습 파이프라인(로그인성 조회 -> 진행도 업서트 ->
// 스펠링/퀴즈/발음 "정답 제출" 쓰기 -> 보상 지급 -> 완료 저장)을 오프라인
// (네트워크 0)으로 부하 시뮬레이션한다.
//
// 재구현 금지(CLAUDE.md 규칙 3) — 파이프라인 단계는 전부 실제 export
// 함수를 esbuild로 무수정 그대로 번들해 호출한다(추측 없음, src/utils/
// wordLibrary.js/api/grant-xp.js 소스에서 실측 확인):
//   · 로그인성 조회 — refreshWordLibrary/refreshStudents/refreshClassSettings/
//     refreshTextbooks(부팅 시 1회, 이 앱의 실제 캐시 전략 — 유닛/단어/교재는
//     로그인마다 재조회하지 않고 전역 캐시에서 읽는다는 것 자체가 실제
//     아키텍처 사실이다, 정직하게 그대로 반영) + getStudentClassAssignments
//     (studentId당 실제 DB 라운드트립이 있는 유일한 "로그인성" 조회 —
//     testAssignmentUnitGuards.mjs가 이미 이 함수로 boot() 이후 조회를
//     검증한 것과 동일 함수).
//   · 진행도 업서트 — syncStudentProgress(studentId, {...}) — student_progress
//     +student_daily_progress 2개 upsert(useStudent.js 1935행 인근에서
//     실제로 이 함수를 호출).
//   · 스펠링/퀴즈/발음 "정답 제출" 쓰기 — setWordStatus(studentId, wordDbId,
//     status) — useStudent.js가 `syncWordStatus`라는 별칭으로 import하는
//     그 함수(word_status upsert, onConflict student_id,word_id). 이 앱
//     아키텍처에서 스펠링/퀴즈/발음 각각의 "정답 제출"이 만드는 유일한
//     즉시 DB 쓰기가 이 경로다(정오답 판정 자체는 클라이언트 로컬 상태 —
//     기록에 남는 쓰기가 없으면 그렇다고 명시한다는 지시에 따라 정직하게
//     밝힘: student_daily_progress.quiz_correct/quiz_total 같은 집계는
//     위 진행도 업서트 시점에 한꺼번에 반영되고, 문항 단위 즉시 쓰기는
//     없다).
//   · 보상 지급 — api/grant-xp.js `ledger:'reward'` 분기(Part 1,
//     scripts/testRewardStress45.mjs와 동일한 esbuild+가짜 supabase 패턴을
//     이 파일 전용으로 독립 재생성 — 그 파일의 런타임 산출물을 참조하지
//     않음, CLAUDE.md 규칙 16 파일 소유권 경계와 별개로 그냥 서로 다른
//     프로세스 실행이라 애초에 공유가 불가능하기도 함).
//   · 완료 — 세션 종료 시점의 최종 syncStudentProgress 재호출(마지막
//     진행도 스냅샷 저장, 실제 useStudent.js가 학습 종료 시 다시 동기화하는
//     것과 동일 패턴).
//
// ── 오프라인 하네스 ──────────────────────────────────────────────────────
// src/utils/wordLibrary.js를 esbuild로 무수정 오프라인 번들(pattern:
// scripts/testAssignmentUnitGuards.mjs/scripts/testAdminUnitEdit.mjs — 그
// 두 파일이 쓰는 "쓰기 기록형 인메모리 가짜 supabase(select/eq/neq/in/is/
// limit/range/order/update/insert/delete/maybeSingle/single)" builder를
// 이 파일 전용으로 복제하되, 두 가지를 더한 독립 버전을 쓴다(그 두 파일은
// 무수정):
//   1) upsert(rows, {onConflict})가 실제 Postgres UPSERT처럼 충돌 컬럼
//      기준으로 기존 행을 병합한다(원본 builder는 upsert를 단순 insert로
//      취급해 같은 학생이 두 번 진행도를 저장하면 행이 늘어나는 오탐을
//      만든다 — 이 파일의 "duplicate rows 0" 단언이 의미 있으려면 반드시
//      필요한 보정).
//   2) 모든 쿼리 실행 지점에 0~50ms 지연 + 5% 확률의 1회성 재시도 가능
//      오류(retryable, code 57014)를 주입해(__setLatencyRange/
//      __setFailureRate) 재시도 경로를 실제로 태운다.
// api/grant-xp.js는 Part 1과 동일한 스타일(esbuild + 인메모리 가짜
// @supabase/supabase-js, api/_pinAuth.js는 실제 sign/verifySessionToken
// 재사용)로 별도 번들한다.
//
// ── 측정 ────────────────────────────────────────────────────────────────
// 단계별(login-lookup/progress-upsert/answer-submit/reward-grant/
// completion-upsert) success rate, p95 latency(ms), 재시도 횟수, 실패
// 쓰기(재시도 소진) 수를 집계하고, 동시성 레벨(5/10/20/45)마다 표로
// 출력한다. 전 구간 공통 불변식: student_progress/student_daily_progress/
// word_status 중복 행 0, 학생 A의 행에 학생 B의 id가 섞이는 교차오염 0,
// "lost update"(동시 쓰기 후 최종 행이 실제로 발생한 마지막 쓰기 중 하나와
// 정확히 일치하는지, 두 값이 뒤섞인 손상 상태가 아닌지) 전용 프로브 1건.
//
// 네트워크 0, 실제 Supabase 접촉 0, production 요청 0. 실행 시간 목표
// 60초 이내(지연은 최대 50ms이고 동시 실행이라 배치당 벽시계 비용은
// 지연 총합이 아니라 최댓값 근사 — 4개 동시성 레벨 x 파이프라인 5단계
// x 최대 50ms ≈ 1초 내외로 예상).

import esbuild from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

let failures = 0
let asserted = 0
function check(label, cond, detail) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}${detail !== undefined ? ' — ' + JSON.stringify(detail) : ''}`); failures++ }
}

// ── 1) wordLibrary 전용 인메모리 가짜 supabase(쓰기 기록형 builder,
//    testAssignmentUnitGuards.mjs/testAdminUnitEdit.mjs 패턴의 독립
//    복제본 + upsert onConflict 병합 + 지연/일시오류 주입) ────────────────
const fakeWordLibPath = path.join(TMP, 'fakeSupabaseForLoadConcurrency45.mjs')
fs.writeFileSync(fakeWordLibPath, `// AUTO-GENERATED by scripts/testLoadConcurrency45.mjs — 독립 산출물.
export const __db = { classes: [], units: [], words: [], students: [], textbooks: [], class_textbooks: [], student_class_assignments: [], student_progress: [], student_daily_progress: [], word_status: [] }
export const __log = []
let __failureRate = 0
let __latencyMin = 0
let __latencyMax = 0
export function __setFailureRate(r) { __failureRate = r }
export function __setLatencyRange(min, max) { __latencyMin = min; __latencyMax = max }
export function __reset(ds) {
  for (const k of Object.keys(__db)) __db[k] = (ds[k] || []).map((r) => ({ ...r }))
  __log.length = 0
}
function delay(ms) { return new Promise((r) => setTimeout(r, ms)) }
async function simulateNetwork() {
  const span = Math.max(0, __latencyMax - __latencyMin)
  const d = __latencyMin + Math.random() * span
  if (d > 0) await delay(d)
  if (Math.random() < __failureRate) {
    const e = new Error('simulated transient failure (test, retryable)')
    e.code = '57014'
    e.__retryable = true
    throw e
  }
}
function builder(table) {
  const st = { table, cols: '', filters: [], orders: [], range: null, count: null, head: false, mode: 'select', patch: null, onConflict: null, single: null }
  const api = {
    select(c, o) { st.cols = c || ''; st.count = o?.count || null; st.head = !!o?.head; return api },
    order(c, o) { st.orders.push([c, o?.ascending !== false]); return api },
    eq(c, v) { st.filters.push((r) => r[c] === v); return api },
    neq(c, v) { st.filters.push((r) => r[c] !== v); return api },
    in(c, v) { st.filters.push((r) => (v || []).includes(r[c])); return api },
    is(c, v) { st.filters.push((r) => (v === null ? r[c] == null : r[c] === v)); return api },
    limit(n) { st.range = [0, n - 1]; return api },
    range(a, b) { st.range = [a, b]; return api },
    update(p) { st.mode = 'update'; st.patch = p; return api },
    insert(rows) { st.mode = 'insert'; st.patch = rows; return api },
    upsert(rows, opts) { st.mode = 'upsert'; st.patch = rows; st.onConflict = (opts && opts.onConflict) || null; return api },
    delete() { st.mode = 'delete'; return api },
    maybeSingle() { st.single = 'maybe'; return api },
    single() { st.single = 'one'; return api },
    then(resolve, reject) { (async () => { try { resolve(await run()) } catch (e) { reject(e) } })() },
  }
  async function run() {
    await simulateNetwork()
    const rows = __db[st.table] || []
    if (st.mode === 'update') {
      const hit = rows.filter((r) => st.filters.every((f) => f(r)))
      for (const r of hit) Object.assign(r, st.patch)
      __log.push({ table: st.table, op: 'update', patch: st.patch, hit: hit.length })
      return { data: st.cols ? hit : null, error: null }
    }
    if (st.mode === 'insert') {
      const list = Array.isArray(st.patch) ? st.patch : [st.patch]
      for (const r of list) rows.push({ id: 'gen-' + (rows.length + 1), ...r })
      __log.push({ table: st.table, op: 'insert', rows: list.length })
      return { data: list, error: null }
    }
    if (st.mode === 'upsert') {
      const list = Array.isArray(st.patch) ? st.patch : [st.patch]
      const conflictCols = st.onConflict ? st.onConflict.split(',').map((s) => s.trim()) : null
      let merged = 0
      let inserted = 0
      for (const incoming of list) {
        let existing = null
        if (conflictCols) {
          existing = rows.find((r) => conflictCols.every((c) => r[c] === incoming[c]))
        }
        if (existing) { Object.assign(existing, incoming); merged++ }
        else { rows.push({ id: 'gen-' + (rows.length + 1), ...incoming }); inserted++ }
      }
      __log.push({ table: st.table, op: 'upsert', merged, inserted, onConflict: st.onConflict })
      return { data: null, error: null }
    }
    if (st.mode === 'delete') {
      const hit = rows.filter((r) => st.filters.every((f) => f(r)))
      for (const r of hit) rows.splice(rows.indexOf(r), 1)
      __log.push({ table: st.table, op: 'delete', hit: hit.length })
      return { data: null, error: null }
    }
    let out = rows.filter((r) => st.filters.every((f) => f(r)))
    for (const [c, asc] of [...st.orders].reverse()) out.sort((a, b) => (a[c] > b[c] ? 1 : a[c] < b[c] ? -1 : 0) * (asc ? 1 : -1))
    if (st.count) { const n = out.length; if (st.head) return { data: null, count: n, error: null } }
    if (st.range) out = out.slice(st.range[0], st.range[1] + 1)
    if (st.single === 'maybe') return { data: out[0] ?? null, error: null }
    if (st.single === 'one') return out[0] ? { data: out[0], error: null } : { data: null, error: { code: 'PGRST116', message: 'no rows' } }
    return { data: out, error: null }
  }
  return api
}
export const supabase = { from: (t) => builder(t) }
`, 'utf8')
const fakeWordLibUrl = pathToFileURL(fakeWordLibPath).href

const wordLibOutfile = path.join(TMP, 'wordLibrary.loadConcurrency45.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/utils/wordLibrary.js'], bundle: true, format: 'esm', platform: 'node', outfile: wordLibOutfile,
  define: {
    'import.meta.env.VITE_SUPABASE_URL': JSON.stringify('http://offline.invalid'),
    'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify('offline-test-key'),
    'import.meta.env.DEV': 'false',
  },
  plugins: [{ name: 'fake-supabase-load45', setup(b) { b.onResolve({ filter: /supabaseClient(\.js)?$/ }, () => ({ path: fakeWordLibUrl, external: true })) } }],
})
const lib = await import(pathToFileURL(wordLibOutfile).href)
const fakeLib = await import(fakeWordLibUrl)

// ── 2) grant-xp 전용 가짜 supabase + _pinAuth(Part 1과 동일 스타일, 독립
//    산출물) — 이 파이프라인에서는 word-session-complete 1종만 사용 ───────
const fakeRewardPath = path.join(TMP, 'fakeSupabaseForLoadConcurrency45Reward.mjs')
fs.writeFileSync(fakeRewardPath, `export const __db = { students: [], entrance_test_results: [], reward_ledger: [] }
export function __reset() { __db.students = []; __db.entrance_test_results = []; __db.reward_ledger = [] }
function matchRow(row, filters) { return filters.every(([c, v]) => { if (c.startsWith('__gte__')) return String(row[c.slice(7)]) >= String(v); return String(row[c]) === String(v) }) }
function makeQuery(table) {
  const filters = []
  let headCount = false
  const q = {
    select(_c, o) { if (o && o.head) headCount = true; return q },
    eq(c, v) { filters.push([c, v]); return q },
    gte(c, v) { filters.push(['__gte__' + c, v]); return q },
    async maybeSingle() { const rows = __db[table] || []; return { data: rows.find((r) => matchRow(r, filters)) || null, error: null } },
    then(resolve) { const rows = __db[table] || []; const hit = rows.filter((r) => matchRow(r, filters)); resolve({ data: headCount ? null : hit, count: hit.length, error: null }) },
  }
  return q
}
export function createClient() {
  return { from(table) { return {
    select(c, o) { return makeQuery(table).select(c, o) },
    async insert(row) {
      if (!__db[table]) __db[table] = []
      const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
      if (dup) return { error: { code: '23505', message: 'duplicate key' } }
      __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
      return { error: null }
    },
  } } }
}
`, 'utf8')
const fakeRewardUrl = pathToFileURL(fakeRewardPath).href
const realPinAuthUrl = pathToFileURL(path.resolve('api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForLoadConcurrency45.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuthUrl)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href
const grantXpOutfile = path.join(TMP, 'grantXp.loadConcurrency45.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'], bundle: true, format: 'esm', platform: 'node', outfile: grantXpOutfile,
  plugins: [{
    name: 'fake-supabase-load45-reward',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeRewardUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})
const fakeReward = await import(fakeRewardUrl)
const grantHandler = (await import(pathToFileURL(grantXpOutfile).href)).default
process.env.SESSION_SECRET = 'load-concurrency45-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
async function callGrant(studentId, sourceId) {
  const body = { ledger: 'reward', studentId, rewardType: 'word-session-complete', sourceType: 'daily-words', sourceId, token: signSessionToken(studentId) }
  const r = res()
  await grantHandler({ method: 'POST', body, headers: {} }, r)
  return r
}

// ── 3) 픽스처 — 단일 반(비-교재 모드, 자가치유 분기가 절대 안 타도록
//    primary SCA의 class_id/current_unit_id를 students와 항상 일치시킴) ──
const CLASS = 'cls-load45'
const U1 = 'u-load45-1', U2 = 'u-load45-2'
const wordsOf = (uid, n, base) => Array.from({ length: n }, (_, i) => ({ id: `${uid}-w${i}`, unit_id: uid, word: `${base}${i}`, meaning: `뜻${i}`, position: i + 1 }))
const STUDENTS = Array.from({ length: 45 }, () => crypto.randomUUID())
function dataset() {
  return {
    classes: [{ id: CLASS, name: '로드테스트반', class_type: 'regular', spelling_direction: 'kr2en' }],
    textbooks: [], class_textbooks: [],
    units: [{ id: U1, class_id: CLASS, textbook_id: null, name: 'Unit1', position: 0 }, { id: U2, class_id: CLASS, textbook_id: null, name: 'Unit2', position: 1 }],
    words: [...wordsOf(U1, 5, 'one'), ...wordsOf(U2, 5, 'two')],
    students: STUDENTS.map((sid, i) => ({ id: sid, name: `LoadStudent${i}`, class_id: CLASS, unit_name: 'Unit1', current_unit_id: U1 })),
    student_class_assignments: STUDENTS.map((sid, i) => ({ id: `sca-load-${i}`, student_id: sid, class_id: CLASS, textbook_id: null, current_unit_id: U1, is_primary: true })),
    student_progress: [], student_daily_progress: [], word_status: [],
  }
}
async function boot() {
  fakeLib.__reset(dataset())
  fakeReward.__reset()
  for (const sid of STUDENTS) fakeReward.__db.students.push({ id: sid })
  await lib.refreshWordLibrary(); await lib.refreshStudents(); await lib.refreshClassSettings(); await lib.refreshTextbooks()
  lib.invalidateStudentAssignmentsCache?.()
  fakeLib.__log.length = 0
}

// ── 4) 재시도 래퍼 — jitter/5% 일시오류를 소스 무수정으로 "노출"만 하고
//    (규칙 3, 재구현 아님) 재시도 정책 자체는 이 하네스가 가짜 DB 계층
//    에서 흉내낸다(실제 client/server 재시도 로직 재구현이 아니라, 부하
//    시나리오를 재현하기 위한 테스트 드라이버 책임).
async function withRetry(stepName, fn, maxRetries = 5) {
  let attempts = 0
  const t0 = Date.now()
  while (true) {
    attempts++
    try {
      const result = await fn()
      return { ok: true, result, attempts, latencyMs: Date.now() - t0, step: stepName }
    } catch (e) {
      if (e && e.__retryable && attempts <= maxRetries) continue
      return { ok: false, error: e, attempts, latencyMs: Date.now() - t0, step: stepName }
    }
  }
}

const todayToken = new Date().toDateString()
async function runStudentPipeline(studentId, idx) {
  const wordIds = [`${U1}-w0`, `${U1}-w1`, `${U2}-w0`]
  const steps = {}
  steps['1-login-lookup'] = await withRetry('1-login-lookup', () => lib.getStudentClassAssignments(studentId))
  steps['2-progress-upsert'] = await withRetry('2-progress-upsert', () => lib.syncStudentProgress(studentId, {
    totalStars: 5, clearedCount: 2, streak: 1, stickersCount: 0,
    daily: { categoriesCompleted: 1, starsEarned: 5, quizCorrect: 3, quizTotal: 4, pronunciationAttempts: 2, missedWordIds: [] },
  }))
  const answerResults = []
  for (const wid of wordIds) {
    answerResults.push(await withRetry('3-answer-submit', () => lib.setWordStatus(studentId, wid, 'known')))
  }
  steps['3-answer-submit'] = { ok: answerResults.every((r) => r.ok), attempts: answerResults.reduce((s, r) => s + r.attempts, 0), latencyMs: Math.max(...answerResults.map((r) => r.latencyMs)), step: '3-answer-submit' }
  steps['4-reward-grant'] = await withRetry('4-reward-grant', async () => {
    const r = await callGrant(studentId, todayToken)
    if (r.code >= 500) { const e = new Error('grant-xp 500'); throw e }
    return r
  })
  steps['5-completion-upsert'] = await withRetry('5-completion-upsert', () => lib.syncStudentProgress(studentId, {
    totalStars: 6, clearedCount: 3, streak: 1, stickersCount: 0,
    daily: { categoriesCompleted: 1, starsEarned: 6, quizCorrect: 4, quizTotal: 4, pronunciationAttempts: 3, missedWordIds: [] },
  }))
  return steps
}

function percentile(sorted, p) {
  if (sorted.length === 0) return 0
  const idx = Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1)
  return sorted[Math.max(0, idx)]
}

console.log('=== Load/Concurrency 45 — 학생 파이프라인(로그인성 조회 -> 진행도 업서트 -> 정답 제출 -> 보상 지급 -> 완료) 부하 시뮬레이션 ===')
console.log('단계 구성: 1)getStudentClassAssignments 2)syncStudentProgress 3)setWordStatus x3 4)api/grant-xp.js reward 분기 5)syncStudentProgress(완료)')
console.log('(스펠링/퀴즈/발음 문항 단위 즉시 DB 쓰기는 이 아키텍처에 없음 — word_status가 유일한 즉시 쓰기, 집계는 진행도 업서트 시점에 반영. 정직한 커버리지 경계.)')

const CONCURRENCY_LEVELS = [5, 10, 20, 45]
const STEP_NAMES = ['1-login-lookup', '2-progress-upsert', '3-answer-submit', '4-reward-grant', '5-completion-upsert']

for (const N of CONCURRENCY_LEVELS) {
  await boot()
  fakeLib.__setLatencyRange(0, 50)
  fakeLib.__setFailureRate(0.05)

  const batch = STUDENTS.slice(0, N)
  const allResults = await Promise.all(batch.map((sid, i) => runStudentPipeline(sid, i)))

  fakeLib.__setFailureRate(0) // 아래 무결성 감사는 순수 조회 — 잡음(일시오류) 없이 확정적으로 확인

  console.log(`\n--- 동시성 레벨 N=${N} ---`)
  console.log('  step                 successRate  p95LatencyMs  totalRetries  failedWrites')
  for (const step of STEP_NAMES) {
    const rs = allResults.map((r) => r[step])
    const successCount = rs.filter((r) => r.ok).length
    const successRate = ((successCount / rs.length) * 100).toFixed(1) + '%'
    const sortedLat = rs.map((r) => r.latencyMs).sort((a, b) => a - b)
    const p95 = percentile(sortedLat, 95)
    const totalRetries = rs.reduce((s, r) => s + Math.max(0, r.attempts - 1), 0)
    const failedWrites = rs.filter((r) => !r.ok).length
    console.log(`  ${step.padEnd(20)} ${successRate.padStart(11)}  ${String(p95).padStart(12)}  ${String(totalRetries).padStart(12)}  ${String(failedWrites).padStart(12)}`)
    check(`N=${N} ${step}: success rate 100%(재시도 후)`, failedWrites === 0, { successRate, failedWrites })
  }

  // ── 무결성 감사(레벨별) ──────────────────────────────────────────────
  const progressRows = fakeLib.__db.student_progress
  const dailyRows = fakeLib.__db.student_daily_progress
  const wsRows = fakeLib.__db.word_status
  const batchSet = new Set(batch)

  const progressDup = progressRows.length - new Set(progressRows.map((r) => r.student_id)).size
  check(`N=${N}: student_progress 중복 행 0(학생당 정확히 1행)`, progressDup === 0, { rows: progressRows.length, distinct: new Set(progressRows.map((r) => r.student_id)).size })
  check(`N=${N}: student_progress 전 행의 student_id가 이 배치 학생 목록 안에 있음(교차오염 0)`, progressRows.every((r) => batchSet.has(r.student_id)))

  const dailyKey = (r) => `${r.student_id}|${r.date}`
  const dailyDup = dailyRows.length - new Set(dailyRows.map(dailyKey)).size
  check(`N=${N}: student_daily_progress 중복 행 0((student_id,date)당 정확히 1행)`, dailyDup === 0)

  const wsKey = (r) => `${r.student_id}|${r.word_id}`
  const wsDup = wsRows.length - new Set(wsRows.map(wsKey)).size
  check(`N=${N}: word_status 중복 행 0((student_id,word_id)당 정확히 1행)`, wsDup === 0, { rows: wsRows.length, distinct: new Set(wsRows.map(wsKey)).size })
  check(`N=${N}: word_status 전 행의 student_id가 이 배치 학생 목록 안에 있음(교차오염 0)`, wsRows.every((r) => batchSet.has(r.student_id)))

  // completion 단계(마지막 syncStudentProgress)가 실제로 반영됐다면, 각
  // 학생의 최종 student_progress.total_stars == 6(완료 페이로드 값) —
  // "마지막 쓰기가 실제로 최종 상태"라는 lost-update 없음 확인(순차 파이프
  // 라인 내부 검증, 아래 5번 절의 "동시 쓰기" 전용 프로브와는 별개).
  const finalStarsOk = batch.every((sid) => {
    const row = progressRows.find((r) => r.student_id === sid)
    return row && row.total_stars === 6
  })
  check(`N=${N}: 순차 파이프라인 마지막 쓰기(완료, totalStars=6)가 각 학생의 최종 student_progress에 정확히 반영됨(lost update 없음)`, finalStarsOk)

  const reward500 = allResults.some((r) => r['4-reward-grant'].result && r['4-reward-grant'].result.code >= 500)
  check(`N=${N}: 보상 지급 단계 HTTP 500 0건`, !reward500)
}

// ── 5) "lost update" 전용 프로브 — 학생 1명에게 동시에 서로 다른 값으로
//    syncStudentProgress를 2회 호출했을 때, 최종 행이 두 값 중 정확히
//    하나와 일치하고(손상/병합 없음), 행이 2개로 늘지 않는지 확인.
console.log('\n=== Lost-update 전용 프로브 — 학생 1명, 동시 2건의 서로 다른 진행도 업서트 ===')
{
  await boot()
  fakeLib.__setLatencyRange(0, 50)
  fakeLib.__setFailureRate(0.05)
  const targetStudent = STUDENTS[0]
  const payloadA = { totalStars: 11, clearedCount: 1, streak: 1, stickersCount: 0, daily: { categoriesCompleted: 1, starsEarned: 11, quizCorrect: 1, quizTotal: 1, pronunciationAttempts: 0, missedWordIds: [] } }
  const payloadB = { totalStars: 22, clearedCount: 2, streak: 2, stickersCount: 0, daily: { categoriesCompleted: 2, starsEarned: 22, quizCorrect: 2, quizTotal: 2, pronunciationAttempts: 0, missedWordIds: [] } }
  const [ra, rb] = await Promise.all([
    withRetry('lost-update-A', () => lib.syncStudentProgress(targetStudent, payloadA)),
    withRetry('lost-update-B', () => lib.syncStudentProgress(targetStudent, payloadB)),
  ])
  check('두 동시 호출 모두 재시도 끝에 성공', ra.ok && rb.ok, { ra: ra.ok, rb: rb.ok })
  const rows = fakeLib.__db.student_progress.filter((r) => r.student_id === targetStudent)
  check('행이 정확히 1개(동시 upsert가 중복 행을 만들지 않음)', rows.length === 1, rows.length)
  const finalStars = rows[0]?.total_stars
  check('최종 total_stars가 두 페이로드 중 정확히 하나(11 또는 22) — 손상/병합 없음', finalStars === 11 || finalStars === 22, finalStars)
  check('최종 행의 student_id가 대상 학생과 정확히 일치(교차오염 0)', rows[0]?.student_id === targetStudent)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0
  ? '\n모든 단언 통과 — Load/Concurrency 45 파이프라인 무결성 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
