// scripts/testTownV1Server.mjs
//
// Paul Town V1(2026-09-11) 서버 액션 3종의 **동작** 검증 —
// api/grant-xp.js에 새로 추가된 `claim_town_welcome` action과, 기존
// `get_town_shop_state`/`purchase_town_item`에 얹은 신규 필드(카탈로그
// category/sortOrder/minLevel/assetKey, 상태 응답의 level, 'locked' 구매
// 사유)를 다룬다. scripts/testTownShopServer.mjs와 동일한 하네스 패턴을
// 그대로 재사용한다: esbuild로 api/grant-xp.js를 번들하되
// @supabase/supabase-js와 ./_pinAuth.js만 인메모리 가짜로 치환한다.
// 핸들러 코드 자체는 한 글자도 바꾸지 않고 그대로 실행된다. 네트워크 0,
// production 요청 0, DB 무접촉.
//
// 이 파일의 가짜 RPC는 testTownShopServer.mjs보다 한 걸음 더 나아가
// v3_50(town_purchases unique(student,item) + dollar_ledger UNIQUE
// idempotency 원장 + 학생 단위 advisory-lock 직렬화)의 **동시성 의미론**을
// 흉내낸다 — 각 RPC 시뮬레이션 함수 안에 인위적인 비동기 지연(진짜 DB
// 왕복을 흉내)을 넣고, 학생별 promise 체인(withStudentLock)으로 그 지연
// 구간에서도 같은 학생의 두 요청이 서로의 커밋을 못 보고 인터리빙되는
// 레이스가 나지 않게 직렬화한다. 이는 Postgres의
// pg_advisory_xact_lock(hashtext(...||student_id))이 제공하는 것과 같은
// 보장을 JS 레벨에서 재현한 것이지, 실제 SQL 트랜잭션 격리를 검증한 게
// 아니다(정직한 커버리지 경계 — 진짜 원자성 증거는 SQL 파일 쪽 별도
// 테스트). 서로 다른 학생 간에는 잠금을 공유하지 않아 자유롭게 병렬
// 진행된다.
//
// 산출물: scripts/.tmp/(gitignore) — fakeSupabaseForTownV1.mjs /
// fakePinAuthTownV1.mjs / grantXp.townV1.bundle.mjs (이 파일 전용 이름,
// testTownShopServer.mjs/testCutoverReconcile.mjs가 쓰는 파일명과 충돌하지
// 않는다).

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

const realTownLevelUrl = pathToFileURL(path.resolve('src/utils/town/townLevel.js')).href

// ── 가짜 Supabase ──────────────────────────────────────────────────────
// __db 스키마:
//   students: [{ id, name }]
//   stars_earned: { [studentId]: N }        // 마을 레벨 산정용(townLevelForStars)
//   dollar_ledger: [{ student_id, amount, idempotency_key }] // 잔액의 유일한 원천(SUM) — 환영 크레딧(+)과 구매 차감(-) 둘 다 여기 쌓인다(v3_50 계약 흉내)
//   town_purchases: [{ student_id, item_id, dollars_spent }] // unique(student_id, item_id) 흉내
//   town_items: [{ id, name, emoji, price, price_currency, active, category, sort_order, min_level, asset_key }]
//   reward_ledger / xp_ledger: 기존 reward/XP 분기 무회귀 검증용
const fakePath = path.join(TMP, 'fakeSupabaseForTownV1.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testTownV1Server.mjs
import { townLevelForStars } from ${JSON.stringify(realTownLevelUrl)}

export const __db = {
  students: [],
  stars_earned: {},
  dollar_ledger: [],
  town_purchases: [],
  town_items: [],
  reward_ledger: [],
  xp_ledger: [],
}
export const __fail = { rpc: null, town_items: null, town_items_new_columns: null, town_items_price_currency: null, students: null, reward_ledger: null }
export const __calls = []
export function __reset() {
  __db.students = []
  __db.stars_earned = {}
  __db.dollar_ledger = []
  __db.town_purchases = []
  __db.town_items = []
  __db.reward_ledger = []
  __db.xp_ledger = []
  __fail.rpc = null; __fail.town_items = null; __fail.town_items_new_columns = null; __fail.town_items_price_currency = null; __fail.students = null; __fail.reward_ledger = null
  __calls.length = 0
  __locks.clear()
}

function balanceOf(studentId) {
  return __db.dollar_ledger.filter((e) => e.student_id === studentId).reduce((a, e) => a + e.amount, 0)
}
function levelOf(studentId) {
  return townLevelForStars(__db.stars_earned[studentId] || 0)
}
function tick() {
  // 진짜 DB 왕복(네트워크+쿼리 지연)을 흉내내는 인위적 비동기 틈 — 이 틈
  // 사이에 다른 "동시" 요청이 끼어들 수 있어야 락의 효과를 실제로
  // 증명한다(틈이 없으면 JS 싱글스레드 특성만으로 우연히 직렬화돼 락이
  // 없어도 통과하는 거짓 양성 테스트가 된다).
  return new Promise((resolve) => setTimeout(resolve, 0))
}

// ── 학생 단위 advisory-lock 흉내 — 같은 studentId의 RPC 호출은 promise
// 체인으로 직렬화(먼저 걸린 호출이 끝나야 다음이 시작), 다른 studentId는
// 서로 완전히 독립적으로 병렬 진행된다. ─────────────────────────────────
const __locks = new Map()
function withStudentLock(studentId, fn) {
  const prevTail = __locks.get(studentId) || Promise.resolve()
  const run = prevTail.then(fn, fn)
  __locks.set(studentId, run.then(() => {}, () => {}))
  return run
}

function makeQuery(table) {
  const filters = []
  let headCount = false
  let selectedCols = null
  const q = {
    select(cols, opts) { selectedCols = cols; if (opts && opts.head) headCount = true; return q },
    eq(col, val) { filters.push([col, val]); return q },
    gte(col, val) { filters.push(['__gte__' + col, val]); return q },
    match(rows) {
      return rows.filter((r) => filters.every(([c, v]) => {
        if (c.startsWith('__gte__')) return String(r[c.slice(7)]) >= String(v)
        return String(r[c]) === String(v)
      }))
    },
    maybeSingle() {
      __calls.push({ table, op: 'maybeSingle', filters: [...filters] })
      if (__fail[table]) return Promise.resolve({ data: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return Promise.resolve({ data: hit[0] || null, error: null })
    },
    then(resolve) {
      __calls.push({ table, op: headCount ? 'count' : 'select', filters: [...filters], cols: selectedCols })
      if (table === 'town_items' && __fail.town_items_new_columns && typeof selectedCols === 'string' && selectedCols.includes('sort_order')) {
        return resolve({ data: null, count: null, error: { code: '42703', message: 'column "sort_order" does not exist' } })
      }
      if (table === 'town_items' && __fail.town_items_price_currency && typeof selectedCols === 'string' && selectedCols.includes('price_currency')) {
        return resolve({ data: null, count: null, error: { code: '42703', message: 'column "price_currency" does not exist' } })
      }
      if (__fail[table]) return resolve({ data: null, count: null, error: __fail[table] })
      const hit = q.match(__db[table] || [])
      return resolve({ data: headCount ? null : hit, count: hit.length, error: null })
    },
  }
  return q
}

// ── RPC 시뮬레이션(v3_50 계약 흉내, 순서 고정) ────────────────────────
// grant_town_welcome_credit(p_student_id):
//   1) idempotency_key = 'town-welcome:'+studentId 로 dollar_ledger 조회
//   2) 이미 있으면 granted:false, balance_after=현재잔액(불변)
//   3) 없으면 +WELCOME_CREDIT 원장 삽입, granted:true, balance_after=신규잔액
const WELCOME_CREDIT = 20
async function rpcWelcome(studentId) {
  return withStudentLock(studentId, async () => {
    await tick()
    const key = 'town-welcome:' + studentId
    const already = __db.dollar_ledger.some((e) => e.idempotency_key === key)
    if (already) return { granted: false, balance_after: balanceOf(studentId) }
    __db.dollar_ledger.push({ student_id: studentId, amount: WELCOME_CREDIT, idempotency_key: key })
    return { granted: true, balance_after: balanceOf(studentId) }
  })
}

// purchase_town_item(p_student_id, p_item_id):
//   1) 학생/아이템 존재 확인
//   2) 마을 레벨 < min_level 이면 locked (신규, v3_50)
//   3) 이미 구매(town_purchases unique) 이면 already_owned
//   4) dollar_ledger SUM(=available) < price 이면 insufficient
//   5) town_purchases insert + dollar_ledger에 음수(-price) 행 insert(원자적, 둘 다 락 안에서)
async function rpcPurchase(studentId, itemId) {
  return withStudentLock(studentId, async () => {
    await tick()
    const student = __db.students.find((s) => s.id === studentId)
    if (!student) return { ok: false, reason: 'student_not_found', dollars_spent: 0, balance_after: 0 }
    const item = __db.town_items.find((i) => i.id === itemId && i.active !== false)
    if (!item) return { ok: false, reason: 'item_not_found', dollars_spent: 0, balance_after: 0 }
    const available = balanceOf(studentId)
    const minLevel = Number(item.min_level) || 0
    if (minLevel > 0 && levelOf(studentId) < minLevel) {
      return { ok: false, reason: 'locked', dollars_spent: 0, balance_after: available }
    }
    const already = __db.town_purchases.some((p) => p.student_id === studentId && p.item_id === itemId)
    if (already) return { ok: true, reason: 'already_owned', dollars_spent: 0, balance_after: available }
    if (available < item.price) return { ok: false, reason: 'insufficient', dollars_spent: 0, balance_after: available }
    __db.town_purchases.push({ student_id: studentId, item_id: itemId, dollars_spent: item.price })
    __db.dollar_ledger.push({ student_id: studentId, amount: -item.price, idempotency_key: 'purchase:' + studentId + ':' + itemId })
    return { ok: true, reason: 'purchased', dollars_spent: item.price, balance_after: available - item.price }
  })
}

function rpcState(studentId) {
  const starsEarned = __db.stars_earned[studentId] || 0
  const dollarsAvailable = Math.max(0, balanceOf(studentId))
  const dollarsSpent = __db.dollar_ledger.filter((e) => e.student_id === studentId && e.amount < 0).reduce((a, e) => a - e.amount, 0)
  const dollarsEarned = dollarsSpent + dollarsAvailable
  const owned = __db.town_purchases.filter((p) => p.student_id === studentId).map((p) => p.item_id)
  return { stars_earned: starsEarned, dollars_earned: dollarsEarned, dollars_spent: dollarsSpent, dollars_available: dollarsAvailable, owned_item_ids: owned }
}

export function createClient() {
  return {
    from(table) {
      return {
        select(cols, opts) { return makeQuery(table).select(cols, opts) },
        insert(row) {
          __calls.push({ table, op: 'insert', row })
          if (__fail[table]) return Promise.resolve({ error: __fail[table] })
          if (!__db[table]) __db[table] = []
          const dup = __db[table].some((r) => r.idempotency_key && r.idempotency_key === row.idempotency_key)
          if (dup) return Promise.resolve({ error: { code: '23505', message: 'duplicate key' } })
          __db[table].push({ ...row, id: 'row' + __db[table].length, created_at: new Date().toISOString() })
          return Promise.resolve({ error: null })
        },
      }
    },
    async rpc(name, args) {
      __calls.push({ rpc: name, args })
      if (__fail.rpc) return { data: null, error: __fail.rpc }
      if (name === 'grant_town_welcome_credit') {
        const row = await rpcWelcome(args.p_student_id)
        return { data: [row], error: null }
      }
      if (name === 'purchase_town_item') {
        const row = await rpcPurchase(args.p_student_id, args.p_item_id)
        return { data: [row], error: null }
      }
      if (name === 'get_town_shop_state') {
        const row = rpcState(args.p_student_id)
        return { data: [row], error: null }
      }
      return { data: null, error: { code: 'XX000', message: 'unknown rpc ' + name } }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const fakePinAuthPath = path.join(TMP, 'fakePinAuthTownV1.mjs')
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const outfile = path.join(TMP, 'grantXp.townV1.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-townv1',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

process.env.SESSION_SECRET = 'townv1-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

const STUDENT = '11111111-2222-4333-8444-555555555555'
const OTHER = '99999999-8888-4777-8666-555555555555'
const ITEM = 'shop-lamp'
const LOCKED_ITEM = 'shop-clocktower'
const tokenFor = (sid, opts) => signSessionToken(sid, opts)

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
function call(body, headers = {}) {
  const r = res()
  return handler({ method: 'POST', body: body || {}, headers }, r).then(() => r)
}
function seedStudent(id, name) {
  if (!fake.__db.students.some((s) => s.id === id)) fake.__db.students.push({ id, name })
}
function seedDollars(studentId, amount) {
  fake.__db.dollar_ledger.push({ student_id: studentId, amount, idempotency_key: 'seed:' + studentId + ':' + Math.random() })
}
function seedItem(item) {
  fake.__db.town_items.push(item)
}
function balanceOf(studentId) {
  return fake.__db.dollar_ledger.filter((e) => e.student_id === studentId).reduce((a, e) => a + e.amount, 0)
}
function reset() { fake.__reset() }
function rpcCallCount(name) {
  return fake.__calls.filter((c) => c.rpc === name).length
}

function uuidFor(seed) {
  const hex = seed.toString(16).padStart(8, '0')
  return `${hex}-1111-4111-8111-11111111${hex.slice(0, 4)}`
}

// ============================================================================
console.log('\n1. 환경 스위치 OFF(TOWN_V1_WELCOME_ENABLED 미설정) -> disabled, RPC 미호출')
{
  reset()
  seedStudent(STUDENT)
  delete process.env.TOWN_V1_WELCOME_ENABLED
  const r = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  check("ok false / reason 'disabled'", r.body?.ok === false && r.body?.reason === 'disabled')
  check('grant_town_welcome_credit RPC 호출 0회(더블 게이트 — 클라 플래그 켜도 서버 스위치 없으면 무배포)', rpcCallCount('grant_town_welcome_credit') === 0)

  process.env.TOWN_V1_WELCOME_ENABLED = '0'
  const r2 = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  check("스위치 '0'(문자열)도 여전히 disabled", r2.body?.ok === false && r2.body?.reason === 'disabled')
  check('여전히 RPC 호출 0회', rpcCallCount('grant_town_welcome_credit') === 0)
}

console.log('\n2. 환경 스위치 ON -> 최초 청구 granted true, balance 20')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  const r = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  check(`ok true (${JSON.stringify(r.body)})`, r.body?.ok === true)
  check('granted true', r.body?.granted === true)
  check('balanceAfter 20', r.body?.balanceAfter === 20)
  check('dollar_ledger에 town-welcome 키 1건', fake.__db.dollar_ledger.filter((e) => e.idempotency_key === 'town-welcome:' + STUDENT).length === 1)
}

console.log('\n3. 같은 토큰으로 재청구 -> granted false, balance 여전히 20(불변)')
{
  const r = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  check('ok true(재청구 자체는 실패 아님)', r.body?.ok === true)
  check('granted false', r.body?.granted === false)
  check('balanceAfter 20(불변)', r.body?.balanceAfter === 20)
  check('dollar_ledger에 town-welcome 키 여전히 1건', fake.__db.dollar_ledger.filter((e) => e.idempotency_key === 'town-welcome:' + STUDENT).length === 1)
}

console.log('\n4. 재로그인(같은 학생, 새 토큰) -> 여전히 granted false, balance 20')
{
  const newToken = tokenFor(STUDENT, { now: Date.now() + 1000 })
  const r = await call({ action: 'claim_town_welcome', token: newToken })
  check('granted false(토큰이 달라도 studentId 기준 멱등)', r.body?.granted === false)
  check('balanceAfter 20', r.body?.balanceAfter === 20)
}

console.log('\n5. 더블클릭 — 동시 2회 환영 청구 -> 정확히 한쪽만 granted true, ledger 1건, balance 둘 다 20')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  const tk = tokenFor(STUDENT)
  const [a, b] = await Promise.all([
    call({ action: 'claim_town_welcome', token: tk }),
    call({ action: 'claim_town_welcome', token: tk }),
  ])
  const granted = [a.body?.granted, b.body?.granted].sort()
  check('granted 조합이 [false,true](한쪽만 실제 지급)', JSON.stringify(granted) === JSON.stringify([false, true]))
  check('두 응답 모두 balanceAfter 20', a.body?.balanceAfter === 20 && b.body?.balanceAfter === 20)
  check('dollar_ledger에 town-welcome 키 정확히 1건(락이 레이스 방지)', fake.__db.dollar_ledger.filter((e) => e.idempotency_key === 'town-welcome:' + STUDENT).length === 1)
}

console.log('\n6. table_missing 매핑 — 42P01/PGRST205/42883/PGRST202 전부')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  for (const code of ['42P01', 'PGRST205', '42883', 'PGRST202']) {
    fake.__fail.rpc = { code, message: 'missing' }
    const r = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
    check(`${code} -> reason 'table_missing'`, r.body?.ok === false && r.body?.reason === 'table_missing')
  }
  fake.__fail.rpc = null
}

console.log('\n7. 일반 RPC 실패 -> rpc_failed')
{
  fake.__fail.rpc = { code: 'XX000', message: 'boom' }
  const r = await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  check("reason 'rpc_failed'", r.body?.ok === false && r.body?.reason === 'rpc_failed')
  fake.__fail.rpc = null
}

console.log('\n8. 인증 실패 경로 — 토큰 없음/위조/만료 (claim_town_welcome)')
{
  const baselineRpcCalls = rpcCallCount('grant_town_welcome_credit')
  const noToken = await call({ action: 'claim_town_welcome' })
  check("토큰 없음 -> relogin_required", noToken.body?.ok === false && noToken.body?.reason === 'relogin_required')

  const badSig = tokenFor(STUDENT).split('.')[0] + '.AAAAAAAA'
  const r2 = await call({ action: 'claim_town_welcome', token: badSig })
  check("서명 위조 -> unauthorized(bad_signature)", r2.body?.reason === 'unauthorized' && r2.body?.detail === 'bad_signature')

  const expired = tokenFor(STUDENT, { now: Date.now() - 1000 * 60 * 60 * 24 * 365 })
  const r3 = await call({ action: 'claim_town_welcome', token: expired })
  check("만료 토큰 -> unauthorized(expired)", r3.body?.reason === 'unauthorized' && r3.body?.detail === 'expired')

  check('인증 실패 3종 모두 RPC 미호출(호출 카운트 변화 0)', rpcCallCount('grant_town_welcome_credit') === baselineRpcCalls)
}

console.log('\n9. body.studentId 변조 -> 토큰의 sid가 이긴다')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedStudent(OTHER)
  const r = await call({ action: 'claim_town_welcome', studentId: OTHER, token: tokenFor(STUDENT) })
  check('granted true(토큰 주체 STUDENT 명의로 지급)', r.body?.granted === true)
  check('OTHER 명의 ledger 0건', fake.__db.dollar_ledger.filter((e) => e.idempotency_key === 'town-welcome:' + OTHER).length === 0)
  check('STUDENT 명의 ledger 1건', fake.__db.dollar_ledger.filter((e) => e.idempotency_key === 'town-welcome:' + STUDENT).length === 1)

  const src = fs.readFileSync(path.resolve('api/grant-xp.js'), 'utf8')
  const stripped = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
  const blockStart = stripped.indexOf("req.body.action === 'claim_town_welcome'")
  const blockEnd = stripped.indexOf("레거시 별 이관", blockStart)
  const block = stripped.slice(Math.max(0, blockStart - 200), blockEnd === -1 ? undefined : blockEnd)
  check('claim_town_welcome 분기 소스에 req.body.studentId 참조 없음', !/req\.body\.studentId\b/.test(block))
}

console.log('\n10. 잠긴(min_level 미달) 아이템 구매 -> reason locked, ledger/purchases 불변')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedDollars(STUDENT, 1000) // 돈은 충분해도 레벨 미달이면 locked
  fake.__db.stars_earned[STUDENT] = 0 // 레벨 1
  seedItem({ id: LOCKED_ITEM, name: '시계탑', emoji: '\u{1F570}', price: 60, price_currency: 'dollars', active: true, min_level: 8, category: 'landmark', sort_order: 5, asset_key: 'clocktower' })
  const r = await call({ action: 'purchase_town_item', itemId: LOCKED_ITEM, token: tokenFor(STUDENT) })
  check("ok false / reason 'locked'", r.body?.ok === false && r.body?.reason === 'locked')
  check('town_purchases 0건', fake.__db.town_purchases.length === 0)
  check('balanceAfter 1000(차감 없음)', r.body?.balanceAfter === 1000)
  check('dollar_ledger 음수 행 0건(잠금 상태에서는 지출 자체가 안 남음)', !fake.__db.dollar_ledger.some((e) => e.amount < 0))
}

console.log('\n10b. 레벨 충족 시 같은 아이템 구매 성공')
{
  fake.__db.stars_earned[STUDENT] = 800 // townLevelForStars(800) === 8 (min과 정확히 같음)
  const r = await call({ action: 'purchase_town_item', itemId: LOCKED_ITEM, token: tokenFor(STUDENT) })
  check("ok true / reason 'purchased'", r.body?.ok === true && r.body?.reason === 'purchased')
  check('town_purchases 1건', fake.__db.town_purchases.length === 1)
}

console.log('\n11. 잔액 부족 -> insufficient, 0건')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedDollars(STUDENT, 59)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, min_level: 0 })
  const r = await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })
  check("ok false / reason 'insufficient'", r.body?.ok === false && r.body?.reason === 'insufficient')
  check('town_purchases 0건', fake.__db.town_purchases.length === 0)
  check('balanceAfter 59', r.body?.balanceAfter === 59)
}

console.log('\n12. 더블클릭 — 동시 2회 구매 -> 정확히 town_purchases 1건 + 음수 ledger 1건')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedDollars(STUDENT, 100)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, min_level: 0 })
  const tk = tokenFor(STUDENT)
  const [a, b] = await Promise.all([
    call({ action: 'purchase_town_item', itemId: ITEM, token: tk }),
    call({ action: 'purchase_town_item', itemId: ITEM, token: tk }),
  ])
  check('town_purchases 정확히 1건', fake.__db.town_purchases.length === 1)
  const reasons = [a.body?.reason, b.body?.reason].sort()
  check("reason 조합이 ['already_owned','purchased']", JSON.stringify(reasons) === JSON.stringify(['already_owned', 'purchased']))
  check('음수(-60) dollar_ledger 행 정확히 1건', fake.__db.dollar_ledger.filter((e) => e.amount === -60).length === 1)
}

console.log('\n13. 네트워크 재시도 — 같은 요청 3회 순차 재전송 -> 여전히 1건')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedDollars(STUDENT, 100)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, min_level: 0 })
  const tk = tokenFor(STUDENT)
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tk })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tk })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tk })
  check('town_purchases 1건만 유지(3회 재전송)', fake.__db.town_purchases.length === 1)
  check('음수 ledger 행도 1건만', fake.__db.dollar_ledger.filter((e) => e.amount < 0).length === 1)
}

console.log('\n14. 성공 후 상태 조회 — owned에 해당 아이템 정확히 1번')
{
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('ok true', r.body?.ok === true)
  const ownedCount = (r.body?.owned || []).filter((id) => id === ITEM).length
  check('owned에 램프 정확히 1개(중복 없음)', ownedCount === 1)
}

console.log('\n15. get_town_shop_state — 신규 컬럼 폴백(42703 on 첫 select -> 중간 select 사용)')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedDollars(STUDENT, 100)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, category: 'deco', sort_order: 1, min_level: 0, asset_key: 'lamp' })
  fake.__fail.town_items_new_columns = true
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('ok true(폴백 성공)', r.body?.ok === true)
  const item = (r.body?.items || []).find((it) => it.id === ITEM)
  check('폴백된 아이템에 priceCurrency는 여전히 존재', item?.priceCurrency === 'dollars')
  check('폴백된 아이템은 category/sortOrder/minLevel/assetKey가 undefined(중간 select엔 없음)',
    item && item.category === undefined && item.sortOrder === undefined && item.minLevel === undefined && item.assetKey === undefined)
  // 첫 select(신규 4컬럼 포함)는 실패했고, 두 번째(price_currency만)가 쓰였는지 호출 로그로 확인
  const townItemSelects = fake.__calls.filter((c) => c.table === 'town_items' && c.op === 'select')
  check('town_items select가 최소 2번 시도됨(첫 select 42703 -> 재조회)', townItemSelects.length >= 2)
  check('첫 select는 sort_order를 포함한 전체 컬럼 요청이었음', typeof townItemSelects[0]?.cols === 'string' && townItemSelects[0].cols.includes('sort_order'))
  check('두 번째 select는 price_currency까지만 요청(신규 4컬럼 제외)', typeof townItemSelects[1]?.cols === 'string' && !townItemSelects[1].cols.includes('sort_order'))
  fake.__fail.town_items_new_columns = false
}

console.log('\n16. get_town_shop_state — 신규 컬럼 정상 응답 시 매핑 + level 필드')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  fake.__db.stars_earned[STUDENT] = 550 // townLevelForStars(550) === 7
  seedDollars(STUDENT, 100)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, category: 'deco', sort_order: 3, min_level: 2, asset_key: 'lamp-v1' })
  const r = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('ok true', r.body?.ok === true)
  check('level 7', r.body?.level === 7)
  const item = (r.body?.items || []).find((it) => it.id === ITEM)
  check('category deco', item?.category === 'deco')
  check('sortOrder 3', item?.sortOrder === 3)
  check('minLevel 2', item?.minLevel === 2)
  check('assetKey lamp-v1', item?.assetKey === 'lamp-v1')
}

console.log('\n17. 학생 A/B 격리 — A의 환영/구매가 B 아래 전혀 보이지 않음')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  seedStudent(STUDENT)
  seedStudent(OTHER)
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, min_level: 0 })
  await call({ action: 'claim_town_welcome', token: tokenFor(STUDENT) })
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(STUDENT) })

  const stateOther = await call({ action: 'get_town_shop_state', token: tokenFor(OTHER) })
  check('B의 dollarsAvailable 0(A의 환영 크레딧이 새지 않음)', stateOther.body?.dollarsAvailable === 0)
  check('B의 owned가 비어있음(A의 구매가 새지 않음)', Array.isArray(stateOther.body?.owned) && stateOther.body.owned.length === 0)

  const stateSelf = await call({ action: 'get_town_shop_state', token: tokenFor(STUDENT) })
  check('A 자신은 잔액 20(환영만 반영, 60짜리 구매는 잔액부족으로 실패해 owned에 없음)',
    stateSelf.body?.dollarsAvailable === 20 && !(stateSelf.body?.owned || []).includes(ITEM))
}

console.log('\n18. 이름이 같은 두 학생(다른 UUID) — 완전히 독립적으로 회계')
{
  reset()
  process.env.TOWN_V1_WELCOME_ENABLED = '1'
  const A = uuidFor(1001)
  const B = uuidFor(1002)
  seedStudent(A, '김민준')
  seedStudent(B, '김민준') // 이름 동일, id만 다름
  seedItem({ id: ITEM, name: '램프', emoji: '\u{1F3EE}', price: 60, price_currency: 'dollars', active: true, min_level: 0 })
  await call({ action: 'claim_town_welcome', token: tokenFor(A) })
  seedDollars(A, 40) // 환영 20 + 40 = 60(정확히 가격), 잔액부족 없이 구매 성공 경로로 격리를 검증
  await call({ action: 'purchase_town_item', itemId: ITEM, token: tokenFor(A) })
  const bState = await call({ action: 'get_town_shop_state', token: tokenFor(B) })
  check('동명이인 B는 A의 지급/구매와 완전 무관 — dollarsAvailable 0', bState.body?.dollarsAvailable === 0)
  check('동명이인 B는 owned 비어있음', Array.isArray(bState.body?.owned) && bState.body.owned.length === 0)
  const aState = await call({ action: 'get_town_shop_state', token: tokenFor(A) })
  check('A는 자신의 구매만 owned에 반영', Array.isArray(aState.body?.owned) && aState.body.owned.includes(ITEM))
}

console.log('\n19. 동시성 매트릭스 — N명 학생이 각각 환영+아이템 2개 구매를 동시에 (N ∈ 5,10,20,45)')
{
  for (const N of [5, 10, 20, 45]) {
    reset()
    process.env.TOWN_V1_WELCOME_ENABLED = '1'
    const ITEM_A = 'town-item-a'
    const ITEM_B = 'town-item-b'
    seedItem({ id: ITEM_A, name: 'A', emoji: '\u{1F3E0}', price: 5, price_currency: 'dollars', active: true, min_level: 0 })
    seedItem({ id: ITEM_B, name: 'B', emoji: '\u{1F333}', price: 5, price_currency: 'dollars', active: true, min_level: 0 })
    const students = Array.from({ length: N }, (_, i) => uuidFor(2000 + i))
    students.forEach((sid) => seedStudent(sid, `학생${sid}`))

    async function flow(sid) {
      const tk = tokenFor(sid)
      await call({ action: 'claim_town_welcome', token: tk }) // +20
      await call({ action: 'purchase_town_item', itemId: ITEM_A, token: tk }) // -5
      await call({ action: 'purchase_town_item', itemId: ITEM_B, token: tk }) // -5
    }
    await Promise.all(students.map(flow))

    const welcomeCount = fake.__db.dollar_ledger.filter((e) => e.idempotency_key.startsWith('town-welcome:')).length
    check(`N=${N}: 환영 크레딧 정확히 ${N}건`, welcomeCount === N)
    check(`N=${N}: town_purchases 정확히 ${2 * N}건`, fake.__db.town_purchases.length === 2 * N)

    // 교차 오염 없음 — 각 학생 정확히 2건(자기 아이템 2개)만, 잔액은 20-5-5=10.
    const perStudentCounts = students.map((sid) => fake.__db.town_purchases.filter((p) => p.student_id === sid).length)
    check(`N=${N}: 모든 학생이 정확히 2건씩 구매(누락/중복 0)`, perStudentCounts.every((c) => c === 2))
    const balances = students.map((sid) => balanceOf(sid))
    check(`N=${N}: 모든 학생 잔액 정확히 10(20-5-5, 교차 오염 없음)`, balances.every((b) => b === 10))
    const foreignRows = fake.__db.town_purchases.filter((p) => !students.includes(p.student_id))
    check(`N=${N}: 이전 라운드 학생의 잔여 행 없음`, foreignRows.length === 0)
  }
}

console.log('\n20. 기존 XP 분기 무회귀 — 같은 번들에서 기존 xp_ledger 지급 1건 정상 동작')
{
  reset()
  seedStudent(STUDENT)
  const xpBody = { studentId: STUDENT, eventType: 'word-view-complete', sourceEventId: `word-view-complete:${new Date().toISOString().slice(0, 10)}` }
  const r = await call(xpBody)
  check('기존 XP 분기 -> ok true 응답(claim_town_welcome 추가가 XP 경로를 건드리지 않음)', r.body?.ok === true)
  check('xp_ledger에 1건 삽입', fake.__db.xp_ledger.length === 1)
  const src = fs.readFileSync(path.resolve('api/grant-xp.js'), 'utf8')
  const xpBranchIdx = src.indexOf('const { studentId, eventType, sourceEventId } = req.body || {}')
  check('git diff 대조용 — XP 분기 진입점 텍스트가 여전히 소스에 원문 그대로 존재', xpBranchIdx !== -1)
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0 ? '모든 단언 통과 — Paul Town V1 서버 액션 검증 완료' : `${failures}개 단언 실패`)
process.exit(failures === 0 ? 0 : 1)
