// Phase 2b Step 1-A — Supabase Auth 세션 발급(플래그) + PIN 로스터 최소화
// 계약 테스트 (2026-09-02)
//
// 배경: 이 앱은 Supabase Auth를 쓰지 않는다(브라우저는 anon key 고정,
// students는 RLS OFF + 컬럼 GRANT). 최종 목표는 PIN 로그인 성공 시
// 서버가 Supabase Auth 세션을 대신 발급해, 이후 클라이언트가
// `authenticated` 롤 + `app_metadata.student_id`로 본인 행만 접근하게
// 하는 것(Phase C에서 RLS 전환)이다. JWT 서명은 Supabase가 한다 — 서버는
// auth.admin.createUser/generateLink로 계정을 준비하고 1회용 magiclink의
// hashed_token만 넘겨준다.
//
// 이번 Step 1-A 범위:
//   1) api/_pinAuth.js — isStudentAuthSessionEnabled/studentAuthEmail/
//      ensureStudentAuthUser/issueStudentAuthTokenHash 추가,
//      checkAdminReauth를 timingSafeEqual로 교체(회귀 없이).
//   2) api/verify-student-pin.js — 플래그 ON + SERVICE_ROLE_KEY 설정 시에만
//      로그인 성공 응답에 authTokenHash를 추가. 어떤 단계가 실패해도 로그인
//      자체는 항상 성공(fail-open, console.warn만 남김).
//   3) api/student-pin-status.js — 관리자가 반 이름만으로 "PIN 미설정 +
//      설정 허용" 학생 로스터를 최소 정보(id,name)로 조회하는 신규 모드.
//
// 하네스는 scripts/testPinSetupCapability.mjs의 esbuild 번들 + 인메모리
// 가짜 @supabase/supabase-js 패턴을 그대로 복제하되, 가짜 클라이언트에
// auth.admin.{createUser,generateLink,updateUserById}를 추가해 호출
// 인자를 기록하고 시나리오별로 성공/실패를 주입할 수 있게 한다.
// production 코드는 무수정 — 실제 DB/네트워크 접촉은 마지막 "라이브
// 기준선" 섹션(읽기 전용 HEAD 1건)뿐이고, .env가 없으면 SKIP한다.
//
// 등록: (package.json 미수정 — 소유 범위 밖) 직접 실행:
//   node scripts/testStudentsRlsPhase2b.mjs
import fs from 'node:fs'
import path from 'node:path'
import esbuild from 'esbuild'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

process.env.SESSION_SECRET = 'phase2b-rls-test-secret'
process.env.ADMIN_PIN = '583917'
// 기본은 항상 OFF에서 시작 — 각 섹션이 필요할 때만 명시적으로 켠다.
delete process.env.STUDENT_AUTH_SESSION
delete process.env.SUPABASE_SERVICE_ROLE_KEY

// ── 가짜 Supabase — students/classes 체이닝 + auth.admin.* ────────────────
const fakePath = path.join(TMP, 'fakeSupabaseForRlsPhase2b.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testStudentsRlsPhase2b.mjs
export const __db = { students: [], classes: [] }
export function __reset() { __db.students = []; __db.classes = [] }

export let __auth = { users: [], calls: { createUser: [], generateLink: [], updateUserById: [] }, scenario: {} }
export function __resetAuth() {
  __auth = { users: [], calls: { createUser: [], generateLink: [], updateUserById: [] }, scenario: {} }
}

const val = (row, col) => (col === 'classes(name)' ? undefined : row[col])
function matches(row, filters) {
  return filters.every(([kind, col, v]) => {
    if (kind === 'eq') return val(row, col) === v
    if (kind === 'in') return v.includes(val(row, col))
    if (kind === 'is') return val(row, col) === null || val(row, col) === undefined
    if (kind === 'ilike') {
      const pat = String(v).replace(/%/g, '').toLowerCase()
      return String(val(row, col) ?? '').toLowerCase() === pat
    }
    return true
  })
}
function makeQuery(table) {
  const filters = []
  let mode = 'select'
  let patch = null
  let limitN = null
  let orderCol = null
  const q = {
    select() { return q },
    eq(c, v) { filters.push(['eq', c, v]); return q },
    in(c, v) { filters.push(['in', c, v]); return q },
    is(c, _v) { filters.push(['is', c, null]); return q },
    ilike(c, v) { filters.push(['ilike', c, v]); return q },
    update(p) { mode = 'update'; patch = p; return q },
    insert(rows) { mode = 'insert'; patch = rows; return q },
    limit(n) { limitN = n; return q },
    order(c) { orderCol = c; return q },
    then(resolve) { resolve(run()); return Promise.resolve(run()) },
    maybeSingle() { const r = run(); return Promise.resolve({ data: r.data[0] ?? null, error: r.error }) },
    single() { const r = run(); return Promise.resolve({ data: r.data[0] ?? null, error: r.error }) },
  }
  function run() {
    const rows = __db[table] || []
    if (mode === 'update') {
      const hit = rows.filter((r) => matches(r, filters))
      for (const r of hit) Object.assign(r, patch)
      return { data: hit.map((r) => ({ ...r })), error: null }
    }
    if (mode === 'insert') {
      const list = Array.isArray(patch) ? patch : [patch]
      for (const r of list) rows.push({ ...r })
      return { data: list.map((r) => ({ ...r })), error: null }
    }
    let out = rows.filter((r) => matches(r, filters)).map((r) => ({ ...r }))
    if (orderCol) {
      out.sort((a, b) => {
        const av = val(a, orderCol), bv = val(b, orderCol)
        return av > bv ? 1 : av < bv ? -1 : 0
      })
    }
    if (typeof limitN === 'number') out = out.slice(0, limitN)
    return { data: out, error: null }
  }
  return q
}

function makeAuthAdmin() {
  return {
    async createUser(opts) {
      __auth.calls.createUser.push(opts)
      const s = __auth.scenario.createUser
      if (s === 'already_422') { const err = new Error('User already registered'); err.status = 422; return { data: null, error: err } }
      if (s === 'already_message') return { data: null, error: { message: 'Email address already exists' } }
      if (s === 'already_code') return { data: null, error: { code: 'email_exists', message: 'exists' } }
      if (s === 'other_error') return { data: null, error: { message: 'boom' } }
      if (s === 'throw') throw new Error('network down')
      const user = { id: 'auth-' + (__auth.users.length + 1), email: opts.email, app_metadata: opts.app_metadata }
      __auth.users.push(user)
      return { data: { user }, error: null }
    },
    async generateLink(opts) {
      __auth.calls.generateLink.push(opts)
      const s = __auth.scenario.generateLink
      if (s === 'throw') throw new Error('link down')
      if (s === 'error') return { data: null, error: { message: 'link error' } }
      let user = __auth.users.find((u) => u.email === opts.email)
      if (!user) { user = { id: 'auth-' + (__auth.users.length + 1), email: opts.email, app_metadata: {} }; __auth.users.push(user) }
      const returnedUser = s === 'missing_meta' ? { id: user.id, app_metadata: {} } : { id: user.id, app_metadata: user.app_metadata }
      return { data: { properties: { hashed_token: 'hash-for-' + opts.email }, user: returnedUser }, error: null }
    },
    async updateUserById(id, patch) {
      __auth.calls.updateUserById.push({ id, patch })
      const s = __auth.scenario.updateUserById
      if (s === 'error') return { data: null, error: { message: 'update failed' } }
      if (s === 'throw') throw new Error('update down')
      const user = __auth.users.find((u) => u.id === id)
      if (user) user.app_metadata = { ...(user.app_metadata || {}), ...(patch.app_metadata || {}) }
      return { data: { user }, error: null }
    },
  }
}
export function createClient() { return { from: (t) => makeQuery(t), auth: { admin: makeAuthAdmin() } } }
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

// _pinAuth는 실제 구현을 쓴다(이번 검증 대상) — supabase 접속 정보만 가짜.
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
const fakePinAuthPath = path.join(TMP, 'fakePinAuthForRlsPhase2b.mjs')
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export * from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const ENTRIES = {
  login: 'api/verify-student-pin.js',
  status: 'api/student-pin-status.js',
}
const handlers = {}
for (const [key, entry] of Object.entries(ENTRIES)) {
  const outfile = path.join(TMP, `rlsPhase2b.${key}.bundle.mjs`)
  await esbuild.build({
    entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', outfile,
    plugins: [{
      name: 'fake-deps',
      setup(b) {
        b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
        b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
      },
    }],
  })
  handlers[key] = (await import(pathToFileURL(outfile).href + '?t=' + Date.now())).default
}

const fake = await import(fakeUrl)
const pinAuth = await import(realPinAuth)

function callHandler(handler, body) {
  return new Promise((resolve) => {
    const res = {
      statusCode: 0, body: null,
      status(c) { this.statusCode = c; return this },
      json(b) { this.body = b; resolve({ statusCode: this.statusCode, body: b }) },
    }
    handler({ method: 'POST', body }, res)
  })
}
function mockRes() {
  return {
    statusCode: 0, body: null,
    status(c) { this.statusCode = c; return this },
    json(b) { this.body = b; return this },
  }
}

let failures = 0, asserted = 0
function check(label, cond, detail) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}${detail ? ' — ' + detail : ''}`); failures++ }
}

const SID = '11111111-2222-4333-8444-555555555555'
const CLASS_ID = 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'
const ADMIN_PIN = process.env.ADMIN_PIN
const LOGIN_OK_KEYS = JSON.stringify(['className', 'name', 'ok', 'studentId', 'token', 'unitName'])

function seed({ id = SID, name = 'QA로그인학생', pinHash = null, failCount = 0, lockedUntil = null, allowed = true } = {}) {
  fake.__reset()
  fake.__db.classes.push({ id: CLASS_ID, name: 'QA반' })
  fake.__db.students.push({
    id, name, class_id: CLASS_ID, unit_name: 'Unit 1',
    pin_hash: pinHash, pin_fail_count: failCount, pin_locked_until: lockedUntil, pin_setup_allowed: allowed,
  })
  return fake.__db.students[0]
}

console.log('\n=== Phase 2b Step 1-A — Auth 세션 발급(플래그) + PIN 로스터 계약 ===\n')

console.log('0. 헬퍼 함수 계약 (isStudentAuthSessionEnabled / studentAuthEmail / 존재 확인)')
{
  check('isStudentAuthSessionEnabled export 존재', typeof pinAuth.isStudentAuthSessionEnabled === 'function')
  check('studentAuthEmail export 존재', typeof pinAuth.studentAuthEmail === 'function')
  check('ensureStudentAuthUser export 존재', typeof pinAuth.ensureStudentAuthUser === 'function')
  check('issueStudentAuthTokenHash export 존재', typeof pinAuth.issueStudentAuthTokenHash === 'function')

  if (typeof pinAuth.isStudentAuthSessionEnabled === 'function') {
    const saved = process.env.STUDENT_AUTH_SESSION
    for (const [v, expected] of [['1', true], ['true', true], ['TRUE', true], ['True', true], ['0', false], ['false', false], [undefined, false], ['', false], ['yes', false]]) {
      if (v === undefined) delete process.env.STUDENT_AUTH_SESSION
      else process.env.STUDENT_AUTH_SESSION = v
      check(`STUDENT_AUTH_SESSION=${JSON.stringify(v)} → ${expected}`, pinAuth.isStudentAuthSessionEnabled() === expected)
    }
    if (saved === undefined) delete process.env.STUDENT_AUTH_SESSION
    else process.env.STUDENT_AUTH_SESSION = saved
  }
  if (typeof pinAuth.studentAuthEmail === 'function') {
    check('studentAuthEmail이 소문자+@students.invalid 형식을 만든다',
      pinAuth.studentAuthEmail(SID) === `${SID.toLowerCase()}@students.invalid`)
    check('studentAuthEmail이 유효하지 않은 studentId는 거부한다(falsy)', !pinAuth.studentAuthEmail('not-a-uuid'))
  }
}

console.log('\n1. [회귀] 플래그 OFF — 로그인 응답 키 집합/실패 응답 무변경')
{
  delete process.env.STUDENT_AUTH_SESSION
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true, JSON.stringify(r.body))
  const keys = JSON.stringify(Object.keys(r.body || {}).sort())
  check('응답 키 집합이 정확히 {ok,studentId,name,className,unitName,token}', keys === LOGIN_OK_KEYS, keys)
  check('authTokenHash 없음', !('authTokenHash' in (r.body || {})))

  const wrong = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '9999' })
  check('오답 PIN 실패', wrong.body?.ok === false)
  check('오답 응답에 authTokenHash 없음', !('authTokenHash' in (wrong.body || {})))
}

console.log('\n2. [신규] 플래그 ON + service key 설정 — authTokenHash 발급 + createUser 인자 검증')
{
  process.env.STUDENT_AUTH_SESSION = '1'
  process.env.SUPABASE_SERVICE_ROLE_KEY = 'fake-service-role-key-for-flag-check'
  fake.__resetAuth()
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('authTokenHash 발급됨', typeof r.body?.authTokenHash === 'string' && r.body.authTokenHash.length > 0, JSON.stringify(r.body))
  const expectedEmail = `${SID.toLowerCase()}@students.invalid`
  check('createUser가 1회 호출됨', fake.__auth.calls.createUser.length === 1, String(fake.__auth.calls.createUser.length))
  const cu = fake.__auth.calls.createUser[0]
  check('createUser email이 <id>@students.invalid 형식', cu?.email === expectedEmail, String(cu?.email))
  check('createUser email_confirm=true', cu?.email_confirm === true)
  check('createUser app_metadata.student_id 일치', cu?.app_metadata?.student_id === SID)
  check('createUser app_metadata.source 지정', cu?.app_metadata?.source === 'paul-easy-voca')
  check('generateLink가 호출됨', fake.__auth.calls.generateLink.length === 1)
  check('발급된 authTokenHash가 generateLink 반환값과 일치', r.body?.authTokenHash === 'hash-for-' + expectedEmail)
}

console.log('\n3. [멱등] createUser already-exists 에도 로그인 성공 + authTokenHash 발급')
{
  fake.__resetAuth()
  fake.__auth.users.push({ id: 'auth-preexisting', email: `${SID.toLowerCase()}@students.invalid`, app_metadata: { student_id: SID, source: 'paul-easy-voca' } })
  fake.__auth.scenario.createUser = 'already_422'
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('already-exists(422)에도 로그인 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('authTokenHash 여전히 발급됨', typeof r.body?.authTokenHash === 'string' && r.body.authTokenHash.length > 0)
}

console.log('  3b. ensureStudentAuthUser — already-exists 판별 3종(422/message/code) + throw 무전파 직접 계약')
if (typeof pinAuth.ensureStudentAuthUser === 'function') {
  for (const [label, scenario] of [['status 422', 'already_422'], ['message already', 'already_message'], ['code email_exists', 'already_code']]) {
    fake.__resetAuth()
    fake.__auth.scenario.createUser = scenario
    const client = fake.createClient()
    const result = await pinAuth.ensureStudentAuthUser(client, SID)
    check(`already-exists(${label})는 ok:true로 처리된다(멱등)`, result?.ok === true, JSON.stringify(result))
  }
  fake.__resetAuth()
  fake.__auth.scenario.createUser = 'other_error'
  const other = await pinAuth.ensureStudentAuthUser(fake.createClient(), SID)
  check('그 외 에러는 auth_user_create_failed로 거부된다', other?.ok === false && other?.reason === 'auth_user_create_failed', JSON.stringify(other))

  fake.__resetAuth()
  fake.__auth.scenario.createUser = 'throw'
  let threw = false, thrownResult
  try { thrownResult = await pinAuth.ensureStudentAuthUser(fake.createClient(), SID) } catch { threw = true }
  check('createUser가 throw해도 ensureStudentAuthUser는 throw하지 않는다', threw === false)
  check('throw 시나리오도 ok:false로 처리된다', thrownResult?.ok === false)
} else {
  check('ensureStudentAuthUser export 존재(3b 스킵 방지용)', false, 'not implemented yet')
}

console.log('\n4. [메타 보정] generateLink 응답에 app_metadata.student_id 없음 → updateUserById 호출')
console.log('  4a. 보정 성공 → authTokenHash 발급 + updateUserById 호출')
{
  fake.__resetAuth()
  fake.__auth.scenario.generateLink = 'missing_meta'
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('updateUserById가 호출됨', fake.__auth.calls.updateUserById.length === 1, String(fake.__auth.calls.updateUserById.length))
  check('보정 patch에 student_id 포함', fake.__auth.calls.updateUserById[0]?.patch?.app_metadata?.student_id === SID)
  check('보정 성공 시 authTokenHash 여전히 발급됨', typeof r.body?.authTokenHash === 'string' && r.body.authTokenHash.length > 0)
}
console.log('  4b. 보정 실패 → authTokenHash 미발급, 로그인은 성공(fail-closed)')
{
  fake.__resetAuth()
  fake.__auth.scenario.generateLink = 'missing_meta'
  fake.__auth.scenario.updateUserById = 'error'
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인은 여전히 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('authTokenHash는 발급되지 않는다', !('authTokenHash' in (r.body || {})))
}

console.log('\n5. [fail-open] generateLink 실패/service key 미설정 — 로그인은 항상 성공, 응답은 플래그 OFF와 동일')
console.log('  5a. generateLink throw')
{
  fake.__resetAuth()
  fake.__auth.scenario.generateLink = 'throw'
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true, JSON.stringify(r.body))
  check('authTokenHash 없음', !('authTokenHash' in (r.body || {})))
  const keys = JSON.stringify(Object.keys(r.body || {}).sort())
  check('응답 키 집합이 플래그 OFF와 동일', keys === LOGIN_OK_KEYS, keys)
}
console.log('  5b. generateLink error(non-throw)')
{
  fake.__resetAuth()
  fake.__auth.scenario.generateLink = 'error'
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true)
  check('authTokenHash 없음', !('authTokenHash' in (r.body || {})))
}
console.log('  5c. 플래그 ON, SUPABASE_SERVICE_ROLE_KEY 미설정 — admin API 호출 0회')
{
  fake.__resetAuth()
  delete process.env.SUPABASE_SERVICE_ROLE_KEY
  seed({ pinHash: pinAuth.hashPin('1234') })
  const r = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '1234' })
  check('로그인 성공', r.body?.ok === true)
  check('authTokenHash 없음', !('authTokenHash' in (r.body || {})))
  check('createUser 호출 0회', fake.__auth.calls.createUser.length === 0)
  check('generateLink 호출 0회', fake.__auth.calls.generateLink.length === 0)
  process.env.SUPABASE_SERVICE_ROLE_KEY = 'fake-service-role-key-for-flag-check' // 이후 섹션 복원
}

console.log('\n6. [보안] wrong_pin/locked/not_found 응답에 authTokenHash·pin_hash 없음(플래그 ON에서도)')
{
  fake.__resetAuth()
  seed({ pinHash: pinAuth.hashPin('1234') })
  const wrong = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '0000' })
  check('오답 PIN 실패', wrong.body?.ok === false)
  check('오답 응답에 authTokenHash 없음', !('authTokenHash' in (wrong.body || {})))
  check('오답 응답에 pin_hash 없음', !JSON.stringify(wrong.body).includes('pin_hash'))
  check('오답 경로에서 admin API 호출 없음', fake.__auth.calls.createUser.length === 0 && fake.__auth.calls.generateLink.length === 0)

  fake.__resetAuth()
  const notfound = await callHandler(handlers.login, { name: '존재하지않는이름QAXYZ', pin: '1234' })
  check('없는 학생 실패', notfound.body?.ok === false)
  check('없는학생 응답에 authTokenHash 없음', !('authTokenHash' in (notfound.body || {})))
  check('없는학생 경로에서 admin API 호출 없음', fake.__auth.calls.createUser.length === 0 && fake.__auth.calls.generateLink.length === 0)

  fake.__resetAuth()
  seed({ pinHash: pinAuth.hashPin('1234') })
  let last
  for (let i = 0; i < 5; i++) last = await callHandler(handlers.login, { name: 'QA로그인학생', pin: '9999' })
  check('5회 오답 후 잠김', last.body?.ok === false && last.body?.reason === 'locked', JSON.stringify(last.body))
  check('잠김 응답에 authTokenHash 없음', !('authTokenHash' in (last.body || {})))
  check('잠금 경로에서도 admin API 호출 없음', fake.__auth.calls.createUser.length === 0 && fake.__auth.calls.generateLink.length === 0)
}

console.log('\n7. [로스터] student-pin-status className 모드')
{
  const CLASS2_ID = 'bbbbbbbb-cccc-4ddd-8eee-ffffffffffff'
  fake.__reset()
  fake.__db.classes.push({ id: CLASS2_ID, name: 'QA반Roster' })
  fake.__db.students.push(
    { id: 's1', name: '나선영', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null },
    { id: 's2', name: '가민준', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null },
    { id: 's3', name: '다은서', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: pinAuth.hashPin('1111'), pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null },
    { id: 's4', name: '라하윤', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: false, pin_fail_count: 0, pin_locked_until: null },
    { id: 's5', name: 'QA_숨김학생', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null },
    { id: 's6', name: '바__INACTIVE__', class_id: CLASS2_ID, unit_name: 'Unit 1', pin_hash: null, pin_setup_allowed: true, pin_fail_count: 0, pin_locked_until: null },
  )

  console.log('  7a. 정상 반 이름 — pin 미설정+허용 학생만, 이름 정렬, 배제 규칙')
  {
    const r = await callHandler(handlers.status, { className: 'QA반Roster' })
    check('200 응답', r.statusCode === 200, String(r.statusCode))
    check('roster 2명(가민준,나선영)만 포함', Array.isArray(r.body?.roster) && r.body.roster.length === 2, JSON.stringify(r.body))
    check('이름순 정렬(가민준, 나선영)', r.body?.roster?.[0]?.name === '가민준' && r.body?.roster?.[1]?.name === '나선영', JSON.stringify(r.body?.roster))
    check('응답에 pin_ 로 시작하는 키가 없다', !/"pin_/.test(JSON.stringify(r.body)))
    check('roster 항목이 id/name만 갖는다', (r.body?.roster || []).every((s) => Object.keys(s).sort().join(',') === 'id,name'))
  }

  console.log('  7b. 존재하지 않는 반 — 빈 배열 200')
  {
    const r = await callHandler(handlers.status, { className: 'QA반절대없음XYZ' })
    check('200 응답', r.statusCode === 200, String(r.statusCode))
    check('results/roster 모두 빈 배열', Array.isArray(r.body?.results) && r.body.results.length === 0 && Array.isArray(r.body?.roster) && r.body.roster.length === 0, JSON.stringify(r.body))
  }

  console.log('  7c. 중복 반 이름 — 400 ambiguous_class')
  {
    fake.__db.classes.push({ id: 'dup-class-2', name: 'QA반Roster' })
    const r = await callHandler(handlers.status, { className: 'QA반Roster' })
    check('400 응답', r.statusCode === 400, String(r.statusCode))
    check('ambiguous_class 사유', /ambiguous_class/.test(JSON.stringify(r.body)), JSON.stringify(r.body))
    fake.__db.classes = fake.__db.classes.filter((c) => c.id !== 'dup-class-2')
  }

  console.log('  7d. studentIds와 className 동시 전달 — 400 invalid_request')
  {
    const r = await callHandler(handlers.status, { studentIds: ['s1'], className: 'QA반Roster' })
    check('400 응답', r.statusCode === 400, String(r.statusCode))
    check('invalid_request 사유', /invalid_request/.test(JSON.stringify(r.body)), JSON.stringify(r.body))
  }

  console.log('  7e. 기존 studentIds 모드 무회귀')
  {
    const r = await callHandler(handlers.status, { studentIds: ['s1', 's2', 's3'] })
    check('200 응답', r.statusCode === 200, String(r.statusCode))
    check('results 배열 3건', Array.isArray(r.body?.results) && r.body.results.length === 3, JSON.stringify(r.body))
    check('결과 형태 무변경(id,hasPinHash,pinSetupAllowed,locked,hasFailedAttempts)',
      (r.body?.results || []).every((x) => Object.keys(x).sort().join(',') === 'hasFailedAttempts,hasPinHash,id,locked,pinSetupAllowed'))
    check('studentIds 모드 응답에도 pin_ 원문 키가 없다', !/"pin_/.test(JSON.stringify(r.body)))
  }
}

console.log('\n8. [관리자] checkAdminReauth — timingSafeEqual 치환 후 응답/상태코드 무변경')
{
  // 2026-09-04 — checkAdminReauth가 실패 지연(브루트포스 스로틀, P12
  // 보안 감사 후속) 도입으로 async가 됐다. 이 섹션 전용으로 지연을
  // 최소화(테스트 전용 오버라이드, api/_pinAuth.js 참고)해 하네스 속도를
  // 지키면서 모든 호출부에 await를 추가한다 — await 없이 호출하면 Promise
  // 객체가 항상 truthy라 '올바른 PIN 통과'/'틀린 PIN 거부' 판정 자체가
  // 무의미해진다.
  const savedDelayMs = process.env.ADMIN_PIN_FAIL_DELAY_MS
  process.env.ADMIN_PIN_FAIL_DELAY_MS = '1'

  const ok = await pinAuth.checkAdminReauth({ body: { adminPin: ADMIN_PIN } }, mockRes())
  check('올바른 PIN 통과', ok === true)

  const wrongRes = mockRes()
  const wrong = await pinAuth.checkAdminReauth({ body: { adminPin: '000000' } }, wrongRes)
  check('틀린 PIN 거부', wrong === false)
  check('틀린 PIN 응답 형태 유지(200 + ok:false + not_authorized)',
    wrongRes.statusCode === 200 && wrongRes.body?.ok === false && wrongRes.body?.reason === 'not_authorized', JSON.stringify(wrongRes.body))

  const emptyRes = mockRes()
  check('빈 값 거부', await pinAuth.checkAdminReauth({ body: { adminPin: '' } }, emptyRes) === false)
  check('빈 값 거부 응답 형태 동일', emptyRes.statusCode === 200 && emptyRes.body?.reason === 'not_authorized')

  const diffLenRes = mockRes()
  check('길이 다른 값 거부', await pinAuth.checkAdminReauth({ body: { adminPin: ADMIN_PIN + '99' } }, diffLenRes) === false)
  check('길이 다른 값 거부 응답 형태 동일', diffLenRes.statusCode === 200 && diffLenRes.body?.reason === 'not_authorized')

  const nonStrRes = mockRes()
  check('비문자열 거부', await pinAuth.checkAdminReauth({ body: { adminPin: 583917 } }, nonStrRes) === false)

  const noBodyRes = mockRes()
  check('adminPin 미제공 거부', await pinAuth.checkAdminReauth({ body: {} }, noBodyRes) === false)

  const savedAdminPin = process.env.ADMIN_PIN
  delete process.env.ADMIN_PIN
  const noConfigRes = mockRes()
  const noConfig = await pinAuth.checkAdminReauth({ body: { adminPin: 'anything' } }, noConfigRes)
  check('ADMIN_PIN 미설정 시 500(서버 설정 오류) 무변경', noConfig === false && noConfigRes.statusCode === 500)
  process.env.ADMIN_PIN = savedAdminPin

  if (savedDelayMs === undefined) delete process.env.ADMIN_PIN_FAIL_DELAY_MS
  else process.env.ADMIN_PIN_FAIL_DELAY_MS = savedDelayMs
}

console.log('\n9. [라이브 기준선, 읽기 전용] anon HEAD students?select=id&limit=1')
{
  let liveUrl, liveAnonKey
  try {
    const envText = fs.readFileSync('.env', 'utf8')
    for (const line of envText.split(/\r?\n/)) {
      const m = line.match(/^([^=]+)=(.*)$/)
      if (!m) continue
      const k = m[1].trim()
      if (k === 'VITE_SUPABASE_URL') liveUrl = m[2].trim()
      if (k === 'VITE_SUPABASE_ANON_KEY') liveAnonKey = m[2].trim()
    }
  } catch { /* .env 없음 — 아래에서 SKIP 처리 */ }

  if (!liveUrl || !liveAnonKey) {
    console.log('  SKIP — .env에 VITE_SUPABASE_URL/VITE_SUPABASE_ANON_KEY 없음(secret 값은 출력하지 않음)')
  } else {
    const resp = await fetch(`${liveUrl}/rest/v1/students?select=id&limit=1`, {
      method: 'HEAD',
      headers: { apikey: liveAnonKey, Authorization: `Bearer ${liveAnonKey}`, Prefer: 'count=exact' },
    })
    const range = resp.headers.get('content-range') || ''
    const status = resp.status
    if (process.env.PHASE2B_EXPECT_LOCKED === '1') {
      check('Phase C 이후: anon 직접 조회는 401/403(RLS 차단)이어야 한다', status === 401 || status === 403, `status=${status}`)
    } else {
      console.log(`  기준선(단언 아님): status=${status} content-range=${range} — Phase C 전 열림 예상`)
    }
  }
}

console.log('\n' + '='.repeat(60))
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
if (failures > 0) {
  console.log('FAILED')
  // 2026-09-02 — process.exit(1)을 강제 호출하면 Node 24 + Windows에서
  // esbuild 서비스 프로세스와 라이브 fetch(섹션 9)의 undici 연결 정리가
  // 겹칠 때 `Assertion failed: !(handle->flags & UV_HANDLE_CLOSING)`로
  // 네이티브 크래시가 난다(로컬 실측 재현, esbuild/fetch 각각 단독으로는
  // 재현 안 됨 — 둘의 조합 + 강제 종료 타이밍 문제). exitCode만 설정하고
  // 이벤트 루프가 스스로 비워지길 기다리면(정상 종료) 크래시 없이 같은
  // 종료 코드(1)를 낸다.
  process.exitCode = 1
} else {
  console.log('ALL PASS — Phase 2b Step 1-A 계약 충족')
}
