// scripts/testTownWelcomeExactlyOnce.mjs
//
// Paul Town V1(2026-09-11) 환영 보상(claim_town_welcome, +20 Paul Dollar)이
// "학생 평생 정확히 1회"라는 계약을 10가지 동시성/재시도 시나리오에서
// 증명한다. api/grant-xp.js의 claim_town_welcome 분기(핸들러 코드는 한
// 글자도 바꾸지 않고 esbuild로 그대로 번들)를 scripts/testTownV1Server.mjs와
// 같은 패턴(가짜 @supabase/supabase-js + ./_pinAuth.js)으로 실행하되, 이
// 파일은 그 파일을 import하지 않고(둘 다 scripts/.tmp에 서로 다른 이름의
// 산출물을 쓴다) 독립적으로 하네스를 새로 구성한다.
//
// 가짜 RPC(grant_town_welcome_credit)는 supabase_v3_50_town_v1.sql의 실제
// 계약을 그대로 흉내낸다 —
//   idempotency_key = `${student_id}:welcome:town-v1`
//   insert ... on conflict (idempotency_key) do nothing
//   granted = (row_count > 0), balance_after = SUM(dollar_ledger.dollars_delta)
// 이 함수는 (구매 함수 purchase_town_item과 달리) advisory lock을 전혀 쓰지
// 않는다 — "정확히 1회"는 오직 dollar_ledger.idempotency_key의 UNIQUE
// 제약과 insert의 원자성만으로 보장된다(SQL 파일 본문 참고). 그래서 이
// 가짜 구현도 학생별 promise 락을 두지 않고, "중복 확인 + insert"를 두
// await 사이에 걸치지 않는 단일 동기 블록으로 작성해 JS 단일 스레드
// 특성이 Postgres UNIQUE 제약의 원자성과 동일한 보장을 제공하게 한다 —
// 두 "동시" 호출이 각자의 인위적 지연(tick/setTimeout)에서 깨어난 순서대로
// 정확히 하나만 그 블록을 통과한다.
//
// 지연(latency) 주입은 전역 FIFO 큐가 아니라 **학생별** FIFO 큐
// (__latencyQueues: studentId -> ms[])로 구현한다 — 45명 동시 매트릭스에서
// 서로 다른 학생의 호출이 이벤트 루프에서 뒤섞여도, 각 학생 자신의 호출
// 순서(그 학생의 시나리오 함수가 동기적으로 큐를 소비하는 순서)만으로
// 지연값이 정확히 배정되게 하기 위함이다(다른 학생과의 인터리빙에 영향받지
// 않음).
//
// 산출물: scripts/.tmp/(gitignore) — fakeSupabaseForWelcomeOnce.mjs /
// fakePinAuthWelcomeOnce.mjs / grantXp.welcomeOnce.bundle.mjs (이 파일
// 전용 이름, testTownV1Server.mjs/testTownShopServer.mjs가 쓰는 파일명과
// 충돌하지 않는다). 네트워크 0, production 요청 0, DB 무접촉.

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'

const TMP = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP, { recursive: true })

// ── 가짜 Supabase ──────────────────────────────────────────────────────
// claim_town_welcome 분기는 인증(verifySessionToken, DB 무접촉) + env
// 게이트 확인 + supabase.rpc('grant_town_welcome_credit', ...) 호출뿐이다
// (api/grant-xp.js 248~279행) — 다른 action은 이 하네스가 호출하지 않으므로
// .from()은 안전망으로만 최소 스텁을 둔다.
const fakePath = path.join(TMP, 'fakeSupabaseForWelcomeOnce.mjs')
fs.writeFileSync(fakePath, `// AUTO-GENERATED by scripts/testTownWelcomeExactlyOnce.mjs
export const __db = { students: [], dollar_ledger: [] }
export const __fail = { rpc: null }
export const __calls = []
export const __latencyQueues = new Map() // studentId -> ms[] (FIFO, 학생별 독립)
export function __reset() {
  __db.students = []
  __db.dollar_ledger = []
  __fail.rpc = null
  __calls.length = 0
  __latencyQueues.clear()
}
export function __setLatencies(studentId, msList) {
  __latencyQueues.set(studentId, [...msList])
}

function balanceOf(studentId) {
  return __db.dollar_ledger.filter((e) => e.student_id === studentId).reduce((a, e) => a + e.dollars_delta, 0)
}
function tick() {
  // 최소한의 인위적 비동기 틈 — 이 틈이 없으면 동시 호출이 우연히
  // 직렬화돼(락 없이도 통과하는) 거짓 양성 테스트가 된다.
  return new Promise((resolve) => setTimeout(resolve, 0))
}
async function delayFor(studentId) {
  const q = __latencyQueues.get(studentId)
  const ms = (q && q.length) ? q.shift() : null
  if (typeof ms === 'number' && ms > 0) {
    await new Promise((resolve) => setTimeout(resolve, ms))
  } else {
    await tick()
  }
}

// grant_town_welcome_credit(p_student_id) — v3_50 SQL 본문 흉내.
// 주의: "중복 확인 + insert"는 이 함수 안에서 await 없이 동기적으로
// 이어진다(위 파일 헤더 설명) — 이게 UNIQUE 제약의 원자성을 재현하는
// 핵심이다. 지연은 그 앞에서만 발생시킨다(진짜 DB 왕복 지연 위치).
async function rpcWelcome(studentId) {
  await delayFor(studentId)
  const key = studentId + ':welcome:town-v1'
  const already = __db.dollar_ledger.some((e) => e.idempotency_key === key)
  if (already) return { granted: false, balance_after: balanceOf(studentId) }
  __db.dollar_ledger.push({ student_id: studentId, dollars_delta: 20, event_type: 'welcome:town-v1', idempotency_key: key })
  return { granted: true, balance_after: balanceOf(studentId) }
}

export function createClient() {
  return {
    from(table) {
      return {
        select() { return { eq() { return { maybeSingle: () => Promise.resolve({ data: null, error: null }) } } } },
        insert() { return Promise.resolve({ error: null }) },
      }
    },
    async rpc(name, args) {
      __calls.push({ rpc: name, args })
      if (__fail.rpc) return { data: null, error: __fail.rpc }
      if (name === 'grant_town_welcome_credit') {
        const row = await rpcWelcome(args.p_student_id)
        return { data: [row], error: null }
      }
      return { data: null, error: { code: 'XX000', message: 'unknown rpc ' + name } }
    },
  }
}
`, 'utf8')
const fakeUrl = pathToFileURL(fakePath).href

const fakePinAuthPath = path.join(TMP, 'fakePinAuthWelcomeOnce.mjs')
const realPinAuth = pathToFileURL(path.resolve('api/_pinAuth.js')).href
fs.writeFileSync(fakePinAuthPath,
  `export const supabaseAdminUrl = () => 'https://fake.supabase.co'
export const supabaseAdminKey = () => 'fake-service-role-key'
export { signSessionToken, verifySessionToken, SESSION_TOKEN_TTL_MS } from ${JSON.stringify(realPinAuth)}
`, 'utf8')
const fakePinAuthUrl = pathToFileURL(fakePinAuthPath).href

const outfile = path.join(TMP, 'grantXp.welcomeOnce.bundle.mjs')
await esbuild.build({
  entryPoints: ['api/grant-xp.js'],
  bundle: true, format: 'esm', platform: 'node', outfile,
  plugins: [{
    name: 'fake-supabase-welcome-once',
    setup(b) {
      b.onResolve({ filter: /^@supabase\/supabase-js$/ }, () => ({ path: fakeUrl, external: true }))
      b.onResolve({ filter: /_pinAuth\.js$/ }, () => ({ path: fakePinAuthUrl, external: true }))
    },
  }],
})

const fake = await import(fakeUrl)
const handler = (await import(pathToFileURL(outfile).href)).default

let failures = 0, asserted = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else { console.log(`  FAIL  ${label}`); failures++ }
}

process.env.SESSION_SECRET = 'welcome-once-test-secret'
const { signSessionToken } = await import('../api/_pinAuth.js')

function tokenFor(sid, opts) { return signSessionToken(sid, opts) }

function res() {
  const r = { code: null, body: null }
  r.status = (c) => { r.code = c; return r }
  r.json = (b) => { r.body = b; return r }
  return r
}
function call(token, headers = {}) {
  const r = res()
  return handler({ method: 'POST', body: token === undefined ? {} : { action: 'claim_town_welcome', token }, headers }, r).then(() => r)
}
function callAction(body, headers = {}) {
  const r = res()
  return handler({ method: 'POST', body: body || {}, headers }, r).then(() => r)
}
function seedStudent(id, name) {
  if (!fake.__db.students.some((s) => s.id === id)) fake.__db.students.push({ id, name: name || id })
}
function reset() { fake.__reset() }
function rpcCallCount() { return fake.__calls.filter((c) => c.rpc === 'grant_town_welcome_credit').length }
function keyFor(sid) { return sid + ':welcome:town-v1' }
function ledgerRowsFor(sid) { return fake.__db.dollar_ledger.filter((e) => e.idempotency_key === keyFor(sid)) }
function sumFor(sid) { return ledgerRowsFor(sid).reduce((a, e) => a + e.dollars_delta, 0) }

function uuidFor(seed) {
  const hex = seed.toString(16).padStart(8, '0')
  return `${hex}-1111-4111-8111-11111111${hex.slice(0, 4)}`
}

function enableGate() { process.env.TOWN_V1_WELCOME_ENABLED = '1' }

// ── 시나리오 실행기 — 10가지 재사용 가능한 흐름 ─────────────────────────
// 각 함수는 { responses: Response[] }를 반환한다. 지연은 fake.__setLatencies
// 로 학생별 FIFO 큐에 미리 채워둔다(설계 근거는 파일 헤더 참고).
async function scenarioFirstVisit(sid) {
  const tk = tokenFor(sid)
  const r = await call(tk)
  return { responses: [r] }
}
async function scenarioRefresh(sid) {
  const tk = tokenFor(sid)
  const r1 = await call(tk)
  const r2 = await call(tk) // 같은 토큰으로 두 번째 핸들러 호출(새로고침)
  return { responses: [r1, r2] }
}
async function scenarioRelogin(sid) {
  const tk1 = tokenFor(sid)
  const r1 = await call(tk1)
  const tk2 = tokenFor(sid, { now: Date.now() + 1000 }) // 새 세션 토큰, 같은 studentId
  const r2 = await call(tk2)
  return { responses: [r1, r2] }
}
async function scenarioDoubleClick(sid) {
  const tk = tokenFor(sid)
  const [r1, r2] = await Promise.all([call(tk), call(tk)])
  return { responses: [r1, r2] }
}
async function scenarioTwoTabs(sid) {
  const tk1 = tokenFor(sid)
  const tk2 = tokenFor(sid, { now: Date.now() + 500 }) // 다른 토큰, 같은 학생
  const [r1, r2] = await Promise.all([call(tk1), call(tk2)])
  return { responses: [r1, r2] }
}
async function scenarioTwoDevicesSkew(sid) {
  const tk1 = tokenFor(sid)
  const tk2 = tokenFor(sid, { now: Date.now() + 500 })
  fake.__setLatencies(sid, [10, 200]) // 디바이스A 10ms(빠른 회선), 디바이스B 200ms(지연 회선)
  const [r1, r2] = await Promise.all([call(tk1), call(tk2)])
  return { responses: [r1, r2], fastIndex: 0, slowIndex: 1 }
}
async function scenarioSimultaneous10(sid) {
  const tk = tokenFor(sid)
  const responses = await Promise.all(Array.from({ length: 10 }, () => call(tk)))
  return { responses }
}
async function scenarioNetworkRetry(sid) {
  const tk = tokenFor(sid)
  const r1 = await call(tk) // 서버는 이미 커밋했지만 응답이 유실됐다고 가정
  const r2 = await call(tk) // 클라이언트 재전송
  return { responses: [r1, r2] }
}
async function scenarioSlowResponse(sid) {
  const tk1 = tokenFor(sid)
  const tk2 = tokenFor(sid, { now: Date.now() + 500 })
  fake.__setLatencies(sid, [800, 5]) // 첫 요청 800ms 지연 도중 두 번째 요청 도착(5ms, 빠르게 완료)
  const p1 = call(tk1)
  const p2 = call(tk2)
  const [r1, r2] = await Promise.all([p1, p2])
  return { responses: [r1, r2], slowIndex: 0, fastIndex: 1 }
}
async function scenarioTimeoutRetry(sid) {
  const tk1 = tokenFor(sid)
  fake.__setLatencies(sid, [300, 5]) // 첫 요청 300ms에 클라이언트가 포기(재시도 발사)하지만 서버는 계속 처리 -> 두 번째(재시도)는 5ms로 빠르게 완료
  const p1 = call(tk1) // 클라이언트가 응답을 기다리지 않고 포기한 요청(하지만 서버는 취소되지 않고 계속 진행)
  const tk2 = tokenFor(sid, { now: Date.now() + 10 })
  const p2 = call(tk2) // 재시도
  const [r1, r2] = await Promise.all([p1, p2])
  return { responses: [r1, r2] }
}

const SCENARIOS = [
  ['first_visit', scenarioFirstVisit],
  ['refresh', scenarioRefresh],
  ['relogin', scenarioRelogin],
  ['double_click', scenarioDoubleClick],
  ['two_tabs', scenarioTwoTabs],
  ['two_devices_skew', scenarioTwoDevicesSkew],
  ['simultaneous_10', scenarioSimultaneous10],
  ['network_retry', scenarioNetworkRetry],
  ['slow_response', scenarioSlowResponse],
  ['timeout_retry', scenarioTimeoutRetry],
]

function assertExactlyOnce(label, sid, result) {
  const rows = ledgerRowsFor(sid)
  check(`${label}: dollar_ledger welcome 행 정확히 1개`, rows.length === 1)
  check(`${label}: dollars_delta 합계 정확히 20`, sumFor(sid) === 20)
  const grantedTrueCount = result.responses.filter((r) => r.body && r.body.granted === true).length
  check(`${label}: granted:true 응답 정확히 1회`, grantedTrueCount === 1)
  check(`${label}: 모든 응답 balanceAfter === 20`, result.responses.every((r) => r.body && r.body.balanceAfter === 20))
  check(`${label}: 모든 응답 ok === true`, result.responses.every((r) => r.body && r.body.ok === true))
}

// ============================================================================
console.log('\n1~10. 10가지 동시성/재시도 시나리오 — 학생 평생 정확히 1회 지급')
for (const [name, fn] of SCENARIOS) {
  reset()
  enableGate()
  const sid = uuidFor(1000 + SCENARIOS.findIndex(([n]) => n === name))
  seedStudent(sid)
  const result = await fn(sid)
  assertExactlyOnce(name, sid, result)
}

console.log('\n11. 두 디바이스(지연 스큐) — 더 빠른 회선이 지급받음(결정론적)')
{
  reset()
  enableGate()
  const sid = uuidFor(2001)
  seedStudent(sid)
  const result = await scenarioTwoDevicesSkew(sid)
  check('빠른(10ms) 디바이스 응답이 granted:true', result.responses[result.fastIndex].body?.granted === true)
  check('느린(200ms) 디바이스 응답이 granted:false', result.responses[result.slowIndex].body?.granted === false)
}

console.log('\n12. 느린 응답(800ms) 도중 도착한 두 번째 요청(5ms)이 먼저 지급받음')
{
  reset()
  enableGate()
  const sid = uuidFor(2002)
  seedStudent(sid)
  const result = await scenarioSlowResponse(sid)
  check('빠른(5ms) 응답이 granted:true', result.responses[result.fastIndex].body?.granted === true)
  check('느린(800ms) 응답이 granted:false(늦게 도착했지만 이미 지급됨을 확인)', result.responses[result.slowIndex].body?.granted === false)
}

console.log('\n13. 타임아웃 재시도 — 클라이언트가 포기한 첫 요청도 서버에서는 끝까지 완료됨')
{
  reset()
  enableGate()
  const sid = uuidFor(2003)
  seedStudent(sid)
  const result = await scenarioTimeoutRetry(sid)
  check('포기됐던 첫 요청도 결국 ok:true로 정상 완료(서버가 중도에 취소하지 않음)', result.responses[0].body?.ok === true)
  check('재시도 요청도 ok:true', result.responses[1].body?.ok === true)
}

console.log('\n14. 환경 스위치 OFF -> 0행, reason \'disabled\'')
{
  reset()
  const sid = uuidFor(3001)
  seedStudent(sid)
  delete process.env.TOWN_V1_WELCOME_ENABLED
  const r1 = await call(tokenFor(sid))
  check("스위치 미설정 -> ok false / reason 'disabled'", r1.body?.ok === false && r1.body?.reason === 'disabled')
  check('스위치 미설정 -> dollar_ledger 0행', ledgerRowsFor(sid).length === 0)
  check('스위치 미설정 -> RPC 호출 0회', rpcCallCount() === 0)

  process.env.TOWN_V1_WELCOME_ENABLED = '0'
  const r2 = await call(tokenFor(sid))
  check("스위치 '0'(문자열) -> 여전히 disabled", r2.body?.ok === false && r2.body?.reason === 'disabled')
  check("스위치 '0' -> dollar_ledger 여전히 0행", ledgerRowsFor(sid).length === 0)
}

console.log('\n15. table_missing 매핑 — 42P01/PGRST205/42883/PGRST202 전부')
{
  reset()
  enableGate()
  const sid = uuidFor(3002)
  seedStudent(sid)
  for (const code of ['42P01', 'PGRST205', '42883', 'PGRST202']) {
    fake.__fail.rpc = { code, message: 'missing' }
    const r = await call(tokenFor(sid))
    check(`${code} -> reason 'table_missing'`, r.body?.ok === false && r.body?.reason === 'table_missing')
  }
  fake.__fail.rpc = null
  check('table_missing 시나리오 동안 ledger 0행(지급 없음)', ledgerRowsFor(sid).length === 0)
}

console.log('\n16. 일반 RPC 실패 -> rpc_failed, ledger 0행')
{
  reset()
  enableGate()
  const sid = uuidFor(3003)
  seedStudent(sid)
  fake.__fail.rpc = { code: 'XX000', message: 'boom' }
  const r = await call(tokenFor(sid))
  check("reason 'rpc_failed'", r.body?.ok === false && r.body?.reason === 'rpc_failed')
  check('rpc_failed -> ledger 0행', ledgerRowsFor(sid).length === 0)
  fake.__fail.rpc = null
}

console.log('\n17. 인증 실패 경로 — 토큰 없음/위조/만료는 지급을 만들지 않는다')
{
  reset()
  enableGate()
  const sid = uuidFor(3004)
  seedStudent(sid)
  const baseline = rpcCallCount()

  const noToken = await callAction({ action: 'claim_town_welcome' })
  check("토큰 없음 -> relogin_required", noToken.body?.ok === false && noToken.body?.reason === 'relogin_required')

  const badSig = tokenFor(sid).split('.')[0] + '.AAAAAAAA'
  const r2 = await call(badSig)
  check("서명 위조 -> unauthorized(bad_signature)", r2.body?.reason === 'unauthorized' && r2.body?.detail === 'bad_signature')

  const expired = tokenFor(sid, { now: Date.now() - 1000 * 60 * 60 * 24 * 365 })
  const r3 = await call(expired)
  check("만료 토큰 -> unauthorized(expired)", r3.body?.reason === 'unauthorized' && r3.body?.detail === 'expired')

  check('인증 실패 3종 모두 RPC 미호출', rpcCallCount() === baseline)
  check('인증 실패 3종 모두 ledger 0행', ledgerRowsFor(sid).length === 0)
}

console.log('\n18. 학생 A/B 교차 오염 없음 — A의 청구가 B의 원장에 절대 나타나지 않음')
{
  reset()
  enableGate()
  const A = uuidFor(4001)
  const B = uuidFor(4002)
  seedStudent(A)
  seedStudent(B)
  await call(tokenFor(A))
  check('B의 idempotency_key로는 어떤 행도 없음', ledgerRowsFor(B).length === 0)
  check('A의 idempotency_key 문자열에 B의 UUID가 포함되지 않음', !keyFor(A).includes(B))
  check('전체 dollar_ledger에서 student_id===B인 행 0개', fake.__db.dollar_ledger.filter((e) => e.student_id === B).length === 0)
}

console.log('\n19. QA 스타일 동명이인(다른 UUID) — 각자 정확히 1행씩, 총 2행')
{
  reset()
  enableGate()
  const A = uuidFor(5001)
  const B = uuidFor(5002)
  seedStudent(A, '김민준')
  seedStudent(B, '김민준') // 이름 동일, UUID만 다름
  await Promise.all([call(tokenFor(A)), call(tokenFor(B))])
  check('A 정확히 1행', ledgerRowsFor(A).length === 1)
  check('B 정확히 1행', ledgerRowsFor(B).length === 1)
  const total = fake.__db.dollar_ledger.filter((e) => e.idempotency_key.endsWith(':welcome:town-v1')).length
  check('동명이인 두 명 합쳐 정확히 2행(전역 총합)', total === 2)
}

console.log('\n20. 45명 동시 매트릭스 — 10가지 시나리오를 45명에게 순환 배정, 총 45행')
{
  reset()
  enableGate()
  const students = Array.from({ length: 45 }, (_, i) => uuidFor(6000 + i))
  students.forEach((sid) => seedStudent(sid))
  await Promise.all(students.map((sid, i) => SCENARIOS[i % SCENARIOS.length][1](sid)))

  const allWelcomeRows = fake.__db.dollar_ledger.filter((e) => e.idempotency_key.endsWith(':welcome:town-v1'))
  check('45명 동시 매트릭스: 전역 welcome 행 총합 정확히 45개', allWelcomeRows.length === 45)
  const perStudentCounts = students.map((sid) => ledgerRowsFor(sid).length)
  check('45명 동시 매트릭스: 모든 학생이 정확히 1행씩(누락/중복 0)', perStudentCounts.every((c) => c === 1))
  const perStudentSums = students.map((sid) => sumFor(sid))
  check('45명 동시 매트릭스: 모든 학생 dollars_delta 합계 정확히 20', perStudentSums.every((s) => s === 20))
  const grandTotal = allWelcomeRows.reduce((a, e) => a + e.dollars_delta, 0)
  check('45명 동시 매트릭스: 전체 dollars_delta 총합 정확히 900(45x20)', grandTotal === 900)
  const foreignRows = fake.__db.dollar_ledger.filter((e) => !students.includes(e.student_id))
  check('45명 동시 매트릭스: 명단 밖 학생의 잔여 행 없음', foreignRows.length === 0)
}

console.log('\n21. 정적 검증 — useTownShop.claimWelcome에 학생별(마운트당) 재청구 가드 ref 존재')
{
  const src = fs.readFileSync(path.resolve('src/hooks/useTownShop.js'), 'utf8')
  check('welcomeClaimedRef(useRef(false)) 가드 변수 존재', /const\s+welcomeClaimedRef\s*=\s*useRef\(false\)/.test(src))
  check('claimWelcome 콜백 안에서 가드 확인 후 즉시 true로 설정(연속 호출 차단)',
    /claimWelcome\s*=\s*useCallback\(async[\s\S]{0,300}?welcomeClaimedRef\.current\)[\s\S]{0,80}?welcomeClaimedRef\.current\s*=\s*true/.test(src))
  check('studentId 변경 시 가드 ref 리셋(학생 전환 시에만 재청구 허용)', /welcomeClaimedRef\.current\s*=\s*false/.test(src))
}

console.log(`\n총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(failures === 0 ? '모든 단언 통과 — 환영 20PD exactly-once 검증 완료' : `${failures}개 단언 실패`)
process.exit(failures === 0 ? 0 : 1)
