// scripts/testCutoverClient.mjs
//
// 컷오버 레거시 별 서버 기준선 재조정(2026-09-06/07, src/hooks/useStudent.js
// reconcile effect + src/utils/wordLibrary.js의 holdRewardPosts/
// drainRewardPostQueueForStudent/rewardQueuePendingFor/
// postReconcileLegacyBaseline) 클라이언트 레이스 방지 검증.
//
// 2026-09-07 리뷰 2차 반영 — 1차 수정(hold 후 flush 대신 drain 프로토콜)
// 다음으로, "reconcile effect가 doSyncRef.current?.()를 직접 강제 호출"
// 하던 부분이 로그인당 sync 호출 횟수를 1→2로 늘려 기존 sync 횟수/타이밍
// 계약을 정밀 검증하는 회귀 테스트 3종(scripts/testStarDeltaOnEntry.mjs,
// scripts/testRestoreSyncRace.mjs, scripts/testMultiTabRace.mjs — 특히
// 마지막은 2026-07-18 P1 다중 탭 실사고 회귀 고정 테스트)을 깨뜨렸다.
// 코디네이터 결정: reconcile effect는 이제 새 sync를 만들지 않고, 이미
// 존재하던 자연스러운 ~2초 디바운스 sync(doSyncRef, 정상 진행도 업로드)가
// "방금 성공했다"는 사실을 syncSuccessSeqRef 카운터로 관찰(폴링, 250ms
// 간격·최대 15초 예산)만 한다 — 그래서 이 파일의 시나리오들은 이제 fake
// clock을 실제로 전진시켜(driveNaturalSync 헬퍼) "자연 sync"를 발생시켜야
// reconcile이 그 다음 단계(pending 재확인 → postReconcileLegacyBaseline)로
// 진행한다. 자연 sync가 예산 안에 성공하지 못하면(오프라인 등) reconcile은
// 포기하고 hold만 해제한다(시나리오 9, 신규).
//
// 구동 방식은 scripts/testLegacyGrantCoverage.mjs와 완전히 동일한
// 하네스(esbuild로 실제 src/hooks/useStudent.js를 그대로 번들 + fakeReact.mjs
// 최소 hooks 런타임 + FakeStorage/FakeDocument + settle/flush 헬퍼) — 새
// 테스트 프레임워크를 발명하지 않는다. 이 파일 전용 산출물(scripts/.tmp/
// useStudent.cutoverClient.bundle.mjs, scripts/.tmp/
// wordLibraryCutoverClientStub.mjs)을 독자적으로 생성해서 기존
// wordLibraryRaceStub.mjs(다른 여러 테스트가 공유하는 재대입 불가 export)
// 를 건드리지 않는다(CLAUDE.md 규칙 16, 파일당 소유권).
//
// 이 파일의 wordLibrary 스텁은 postReconcileLegacyBaseline/postRewardEvent/
// holdRewardPosts/drainRewardPostQueueForStudent/rewardQueuePendingFor/
// syncStudentProgress를 전부 "계측 가능하고 응답을 테스트가 스크립트할 수
// 있는" 가짜로 교체한다 — 이 함수들의 "네트워크 왕복 자체가 옳은가"는
// scripts/testRewardPostQueue.mjs(실제 wordLibrary.js 번들)가 이미
// 검증했으므로, 여기서는 오직 useStudent.js가 이 계약을 정확한 순서·
// 조건으로 호출하는가(레이스 방지 프로토콜 자체)만 검증한다. syncStudentProgress
// 자체는 이 스텁이 대체하지만, 그걸 성공시키면 실제 useStudent.js 코드
// 안의 markSyncSuccess/syncSuccessSeqRef는 그대로(스텁 아님) 실행되므로,
// 이 파일이 "자연 sync가 실제로 일어났다"고 주장하는 근거는 진짜다.
let expectedUnhandledRejections = 0
process.on('unhandledRejection', () => { expectedUnhandledRejections++ })

import esbuild from 'esbuild'
import path from 'node:path'
import fs from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createFakeClock, renderHook } from './fakeReact.mjs'

// ── 1) 자체 esbuild 번들(헤더 주석 참고) ────────────────────────────────
const TMP_DIR = path.resolve('scripts/.tmp')
fs.mkdirSync(TMP_DIR, { recursive: true })

const raceStubPath = path.resolve('scripts/wordLibraryRaceStub.mjs')
const raceStubUrl = pathToFileURL(raceStubPath).href
const reactStubPath = path.resolve('scripts/fakeReactModule.mjs')

const generatedStubPath = path.join(TMP_DIR, 'wordLibraryCutoverClientStub.mjs')
const generatedStubContent = `// AUTO-GENERATED by scripts/testCutoverClient.mjs — do not edit by hand.
export * from ${JSON.stringify(raceStubUrl)}
import { syncCalls as __syncCalls } from ${JSON.stringify(raceStubUrl)}

// ── 호출 순서 계측(레이스 방지 프로토콜 자체의 검증 포인트) ──────────────
export const __callOrder = []
export function __resetCallOrder() { __callOrder.length = 0 }

// ── 큐 모델(테스트 전용) — entry: { studentId, rewardType, sourceType, sourceId, key } ──
// 실제 wordLibrary.js의 localStorage 큐를 그대로 재구현하지 않는다(그건
// scripts/testRewardPostQueue.mjs가 실제 코드로 이미 검증) — 여기서는
// useStudent.js가 이 계약(enqueue/hold/drain/pendingFor)을 올바른 순서로
// 호출하는지만 관측 가능한 최소 모델로 재현한다.
let __queue = []
let __held = false
export function __isHeldForTest() { return __held }
export const __sentRewardCalls = [] // 실제로 "전송되어 ack된"(성공) 항목들

// sourceId별 전송 성공/실패를 스크립트 — 기본은 성공.
const __sendOutcomes = new Map()
export function __setSendOutcome(sourceId, outcome) { __sendOutcomes.set(sourceId, outcome) } // 'success' | 'fail'
export function __resetSendOutcomes() { __sendOutcomes.clear() }

function __entryKey(studentId, rewardType, sourceType, sourceId) {
  return studentId + ':' + rewardType + ':' + sourceType + ':' + sourceId
}
// 실제 네트워크 왕복(fetch)처럼 최소 1 microtask 경계를 만든다 — hold(false)
// 직후 release-flush가 동기적으로 "끝나버리지" 않게 해서(실제로도 fetch는
// 항상 비동기) 테스트가 순서(hold:false 다음에 post가 온다)를 의미있게
// 검증할 수 있게 한다.
async function __attemptSend(entry) {
  await Promise.resolve()
  return __sendOutcomes.get(entry.sourceId) !== 'fail'
}

export function __seedPendingQueue(studentId, rewardType, sourceType, sourceId) {
  const key = __entryKey(studentId, rewardType, sourceType, sourceId)
  if (!__queue.some((e) => e.key === key)) __queue.push({ studentId, rewardType, sourceType, sourceId, key })
}
export function __resetQueue() { __queue = [] }

export function rewardQueuePendingFor(studentId) {
  return __queue.filter((e) => e.studentId === studentId).length
}

export async function postRewardEvent(studentId, rewardType, sourceType, sourceId) {
  const key = __entryKey(studentId, rewardType, sourceType, sourceId)
  if (!__queue.some((e) => e.key === key)) __queue.push({ studentId, rewardType, sourceType, sourceId, key })
  if (__held) return // 보류 중 — 큐에만 남김(idempotent), 전송은 release/drain으로 미룸
  const entry = { studentId, rewardType, sourceType, sourceId, key }
  const ok = await __attemptSend(entry)
  if (ok) {
    __queue = __queue.filter((e) => e.key !== key)
    __sentRewardCalls.push(entry)
  }
}

// 컷오버 reconcile 프로토콜 전용 — hold를 의도적으로 무시하고 "이 학생"
// 몫만(호출 시점 스냅샷) 실제 전송+ack를 기다린다(실제 wordLibrary.js
// drainRewardPostQueueForStudent와 동일한 계약 — 헤더 주석 참고).
export async function drainRewardPostQueueForStudent(studentId) {
  __callOrder.push('drain')
  const batch = __queue.filter((e) => e.studentId === studentId)
  let sent = 0
  for (const entry of batch) {
    const ok = await __attemptSend(entry)
    if (ok) {
      __queue = __queue.filter((e) => e.key !== entry.key)
      __sentRewardCalls.push(entry)
      sent++
    }
  }
  return { sent, remaining: rewardQueuePendingFor(studentId) }
}

// release(holdRewardPosts(false)) 시점에 실제 wordLibrary.js가 하는
// flushRewardPostQueue() fire-and-forget 호출을 재현 — 전체 큐(모든 학생,
// 실제 flush와 동일)를 흘려보낸다. await하지 않는다(실제 코드와 동일한
// "fire-and-forget" 성격 — 호출부는 이 완료를 기다리지 않는다).
async function __releaseFlush() {
  const batch = __queue.slice()
  for (const entry of batch) {
    const ok = await __attemptSend(entry)
    if (ok) {
      __queue = __queue.filter((e) => e.key !== entry.key)
      __sentRewardCalls.push(entry)
      __callOrder.push('post:' + entry.sourceId)
    }
  }
}
export function holdRewardPosts(on) {
  __callOrder.push(on ? 'hold:true' : 'hold:false')
  const releasing = __held && !on
  __held = !!on
  if (releasing) __releaseFlush() // fire-and-forget — 실제 wordLibrary.js와 동일 패턴
}
export function __resetRewardCapture() {
  __held = false
  __queue = []
  __sentRewardCalls.length = 0
  __sendOutcomes.clear()
}

// ── syncStudentProgress 계측 — __callOrder에 'sync'를 남기고, raceStub의
//    원본 syncCalls 배열(참조 동일)에도 그대로 push해 기존 관례를 유지한다.
//    __setSyncShouldFail(true)면 throw해서 실제 useStudent.js의
//    doSyncRef.current 안 catch(markSyncFailure)를 타게 만든다 — 그러면
//    syncSuccessSeqRef가 절대 증가하지 않아 시나리오 9("자연 sync가 예산
//    안에 성공하지 못함")를 재현할 수 있다.
let __syncShouldFail = false
export function __setSyncShouldFail(v) { __syncShouldFail = !!v }
export async function syncStudentProgress(name, payload) {
  __callOrder.push('sync')
  __syncCalls.push({ name, ...payload })
  if (__syncShouldFail) throw new Error('simulated sync failure (testCutoverClient stub)')
}

// ── postReconcileLegacyBaseline — 호출 기록 + 스크립트된 응답 큐. 응답을
//    "미해결 상태로 붙잡아두는" 것도 지원(그 사이에 grant가 끼어드는
//    레이스를 재현하기 위함).
export const __reconcileCalls = []
let __reconcileResponses = []
let __reconcileDeferred = null
export function __queueReconcileResponse(res) { __reconcileResponses.push(res) }
export function __setReconcileDeferred() {
  let resolve
  const promise = new Promise((res) => { resolve = res })
  __reconcileDeferred = { promise, resolve }
  return __reconcileDeferred
}
export function __resetReconcile() { __reconcileCalls.length = 0; __reconcileResponses = []; __reconcileDeferred = null }
export async function postReconcileLegacyBaseline(snapshotTotal) {
  __callOrder.push('reconcile')
  __reconcileCalls.push({ snapshotTotal, at: __reconcileCalls.length })
  if (__reconcileDeferred) return __reconcileDeferred.promise
  if (__reconcileResponses.length > 0) return __reconcileResponses.shift()
  return { ok: false, reason: 'network_failed' }
}
`
fs.writeFileSync(generatedStubPath, generatedStubContent, 'utf8')
const generatedStubUrl = pathToFileURL(generatedStubPath).href

const outfile = path.join(TMP_DIR, 'useStudent.cutoverClient.bundle.mjs')
await esbuild.build({
  entryPoints: ['src/hooks/useStudent.js'],
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile,
  plugins: [{
    name: 'cutover-client-stubs',
    setup(build) {
      build.onResolve({ filter: /utils[\\/]wordLibrary$/ }, () => ({ path: generatedStubUrl, external: true }))
      build.onResolve({ filter: /^react$/ }, () => ({ path: pathToFileURL(reactStubPath).href, external: true }))
    },
  }],
})
console.log('bundled -> ' + outfile)

const stub = await import(generatedStubUrl)
const bundle = await import(pathToFileURL(outfile).href)
const { useStudent, todayStr } = bundle

// ── 2) 하네스 보일러플레이트(testLegacyGrantCoverage.mjs와 동일 패턴) ────
class FakeStorage {
  constructor() { this.map = new Map() }
  getItem(k) { return this.map.has(k) ? this.map.get(k) : null }
  setItem(k, v) { this.map.set(k, String(v)) }
  removeItem(k) { this.map.delete(k) }
}
class FakeDocument {
  constructor() { this.visibilityState = 'visible'; this.listeners = {} }
  addEventListener(type, fn) { (this.listeners[type] ||= []).push(fn) }
  removeEventListener(type, fn) { this.listeners[type] = (this.listeners[type] || []).filter(f => f !== fn) }
  dispatch(type) { (this.listeners[type] || []).forEach(fn => fn()) }
}

let failures = 0
let asserted = 0
const scenarioFailures = {}
let currentScenario = 0
function check(label, cond) {
  asserted++
  if (cond) console.log(`  PASS  ${label}`)
  else {
    console.log(`  FAIL  ${label}`)
    failures++
    scenarioFailures[currentScenario] = (scenarioFailures[currentScenario] || 0) + 1
  }
}
const flush = () => new Promise((r) => process.nextTick(r))
const flushMacro = () => new Promise((r) => setImmediate(r))
async function settleAsync(host, n = 6) {
  for (let i = 0; i < n; i++) { await flush() }
  await flushMacro()
  host.rerender()
  await flush(); await flush(); await flushMacro()
}

// 자연 sync 구동(2026-09-07 리뷰 2차) — reconcile effect는 더 이상 스스로
// sync를 만들지 않고, 이미 존재하던 ~2초 디바운스 useEffect(useStudent.js,
// doSyncRef)가 fake clock 위에서 실제로 발동하는 걸 이 헬퍼가 흉내낸다.
// reconcile의 폴링(setTimeout, 250ms 간격)도 이 effect 콜백의 동기 구간
// (커밋 단계)에서 캡처한 같은 fake clock을 타므로, 이 헬퍼가 clock을
// 250ms씩 여러 번 전진시키면 디바운스(2000ms)와 폴링 둘 다 자연스럽게
// 함께 발동한다 — 별도로 clock.advance(2000)을 따로 부를 필요가 없다
// (10사이클×250ms=2500ms로 디바운스 지점을 여유 있게 지나간다).
async function driveNaturalSync(host, clock, cycles = 10) {
  await flush(); await flush() // 이번 라운드의 drain이 먼저 정착되게(순서 계측 안정화)
  for (let i = 0; i < cycles; i++) {
    clock.advance(250)
    await flush(); await flush()
  }
  await flushMacro()
  host.rerender()
  await flush(); await flush()
}
// 시나리오 9 전용 — 자연 sync가 절대 성공하지 못하는 상황에서 reconcile의
// 폴링 예산(250ms×60회=15000ms)을 실제로 소진시킨다. 63사이클(15750ms)로
// 여유를 둔다.
async function exhaustPollBudget(host, clock, cycles = 63) {
  await flush(); await flush()
  for (let i = 0; i < cycles; i++) {
    clock.advance(250)
    await flush()
  }
  await flushMacro()
  host.rerender()
  await flush(); await flush()
}

function freshEnv() {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  stub.setStrictBackup(null)
  stub.setStrictBackupError(null)
  stub.__resetCallOrder()
  stub.__resetRewardCapture()
  stub.__resetQueue()
  stub.__resetSendOutcomes()
  stub.__resetReconcile()
  stub.__setSyncShouldFail(false)
  globalThis.localStorage = new FakeStorage()
  globalThis.document = new FakeDocument()
}
function mountOnCurrentEnv(id, name) {
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}
function mountFresh(id, name) {
  freshEnv()
  return mountOnCurrentEnv(id, name)
}
// beforeMount(선택) — freshEnv()+localStorage 시딩 "이후", 실제 hook 렌더
// (그리고 그 렌더가 동기적으로 시작시키는 reconcile effect) "이전"에 실행할
// 콜백. 큐 사전 시딩(__seedPendingQueue)/전송 결과 스크립팅
// (__setSendOutcome)은 반드시 여기서 해야 한다 — mountSeeded()가 리턴한
// "이후"에 하면, 이미 라운드1의 drainRewardPostQueueForStudent가 (renderHook
// 커밋 단계에서 동기적으로) 빈 큐를 스냅샷 떠버린 뒤라 그 시딩이 1라운드
// 늦게 반영돼(레이스) 호출 순서 단언이 어긋난다(2026-09-07 실측 — 아래
// 시나리오 2/2b가 이 콜백을 실제로 쓰는 이유).
function mountSeeded(id, name, seedRecord, beforeMount) {
  freshEnv()
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify({ [id]: seedRecord }))
  if (typeof beforeMount === 'function') beforeMount()
  return mountOnCurrentEnv(id, name)
}
// remount — freshEnv()를 부르지 않아 localStorage(=마커/진행도)가 그대로
// 유지된 채 새 마운트를 시뮬레이션한다(재로그인/새로고침 시나리오). 큐
// 모델(__queue)과 계측(__callOrder 등)도 이 프로세스 메모리에 그대로 남아
// 있다(실제 wordLibrary.js의 모듈 전역 상태가 재로그인에도 유지되는 것과
// 동일한 성격) — 호출부가 필요하면 길이 스냅샷(logSince류)으로 비교.
function remount(id, name) {
  stub.resetFetchFullProgressDeferred()
  stub.syncCalls.length = 0
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(id, name), clock)
  stub.fetchFullProgressDeferred.resolve(null)
  return { host, clock }
}
function freshRoundSeed() {
  return { date: todayStr(), wordsViewed: [], examplesHeard: 0, quizSolved: 0, pronunciationOk: 0, pronunciationOkWordIds: [], spellingWrongToday: [], spellingCombo: 0, starGrantLog: [], completedToday: [] }
}
function markerFor(id) {
  try { return JSON.parse(globalThis.localStorage.getItem(`paul_easy_legacy_reconciled:${id}`)) } catch { return null }
}
function orderOf(...names) {
  return stub.__callOrder.filter((e) => names.some((n) => e === n || e.startsWith(n)))
}

console.log('=== 컷오버 레거시 별 기준선 재조정 — 클라이언트 레이스 방지 ===')

// ── 시나리오 1 — 신선한 학생(레거시 300별), 큐 없음 → 정확히 1회, 순서 hold→drain→sync→reconcile→release, 마커 기록 ──
currentScenario = 1
console.log('\n시나리오 1 — 신선한 학생(totalStars=300), 큐 없음 → 정확히 1회, 순서 hold→drain→sync→reconcile→hold(false), 마커 기록')
{
  const ID = '44440000-0000-0000-0000-000000000001'
  const seed = { studentId: ID, totalStars: 300, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_Fresh', seed)
  // mountSeeded() 내부의 freshEnv()가 스텁 계측 상태를 리셋하므로, 응답
  // 스크립팅은 반드시 mountSeeded() 호출 "이후"에 해야 한다 — 아래 모든
  // 시나리오 동일.
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 300, earnedAfter: 0 })
  await driveNaturalSync(host, clock)

  check('reconcile 정확히 1회 호출됨', stub.__reconcileCalls.length === 1)
  check('snapshotTotal === 300(레거시 총합 그대로)', stub.__reconcileCalls[0] && stub.__reconcileCalls[0].snapshotTotal === 300)
  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false')
  check('호출 순서: hold(true) → drain → sync → reconcile → hold(false)', JSON.stringify(order) === JSON.stringify(['hold:true', 'drain', 'sync', 'reconcile', 'hold:false']))
  const marker = markerFor(ID)
  check("마커 기록됨(reason: 'reconciled')", marker && marker.reason === 'reconciled' && typeof marker.at === 'string')
}

// ── 시나리오 2 — 이 학생 몫 큐가 계속 실패(quiescent 불가) → 3라운드 drain 시도 후 포기 ──
currentScenario = 2
console.log('\n시나리오 2 — 이 학생 몫 큐 항목이 계속 전송 실패 → drain 3라운드 시도, reconcile 미호출, 마커 없음, hold 해제')
{
  const ID = '44440000-0000-0000-0000-000000000002'
  const seed = { studentId: ID, totalStars: 50, round: freshRoundSeed(), history: {} }
  const { host } = mountSeeded(ID, 'QA_Cutover_PendingFail', seed, () => {
    stub.__seedPendingQueue(ID, 'pronunciation', 'pronunciation', 'w-pending-fail')
    stub.__setSendOutcome('w-pending-fail', 'fail') // 이 항목은 절대 성공하지 않음(영구 네트워크 장애 재현)
  })
  await settleAsync(host)

  check('reconcile 호출 안 됨(quiescent 도달 실패)', stub.__reconcileCalls.length === 0)
  check('마커 없음', markerFor(ID) === null)
  check('hold는 해제된 상태로 마무리됨(released)', stub.__isHeldForTest() === false)
  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false')
  check('순서: hold(true) → drain×3(라운드 예산 전부 소진) → hold(false), sync/reconcile 없음',
    JSON.stringify(order) === JSON.stringify(['hold:true', 'drain', 'drain', 'drain', 'hold:false']))
  check('실패한 항목은 여전히 큐에 남음(포기하지 않고 다음 마운트에서 재시도 대상 유지)', stub.rewardQueuePendingFor(ID) === 1)
}

// ── 시나리오 2b — 이 학생 몫 큐 항목이 drain에서 성공 → reconcile 정상 진행 ──
currentScenario = 20 // "2b" — 결과 요약에서 구분되도록 별도 번호 사용
console.log('\n시나리오 2b — 이 학생 몫 큐 항목이 drain에서 성공 → reconcile 진행(스냅샷에 그 별 포함), 순서 drain(ack) → sync → reconcile')
{
  const ID = '44440000-0000-0000-0000-000000000003'
  // totalStars=50은 이미 그 대기 중이던 별(w-pending-ok)을 포함한 값 —
  // 로컬 지급은 네트워크 성공 여부와 무관하게 이미 반영돼 있었다는 전제
  // (postRewardEvent/grantReward의 기존 계약, 재구현 아님).
  const seed = { studentId: ID, totalStars: 50, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_PendingSucceeds', seed, () => {
    stub.__seedPendingQueue(ID, 'pronunciation', 'pronunciation', 'w-pending-ok')
  })
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 50, earnedAfter: 0 })
  await driveNaturalSync(host, clock)

  check('reconcile 정확히 1회 호출됨(drain 성공 후 진행)', stub.__reconcileCalls.length === 1)
  check('snapshotTotal === 50(대기 중이던 별 포함된 값 그대로)', stub.__reconcileCalls[0] && stub.__reconcileCalls[0].snapshotTotal === 50)
  check('대기 중이던 항목이 실제로 ack됨(전송 성공 로그에 존재)', stub.__sentRewardCalls.some((e) => e.sourceId === 'w-pending-ok'))
  check('큐에는 더 이상 남아있지 않음(drain으로 완전히 비워짐)', stub.rewardQueuePendingFor(ID) === 0)
  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false')
  check('호출 순서: hold(true) → drain(ack 성공) → sync → reconcile → hold(false)', JSON.stringify(order) === JSON.stringify(['hold:true', 'drain', 'sync', 'reconcile', 'hold:false']))
  check('마커 기록됨', markerFor(ID) && markerFor(ID).reason === 'reconciled')
}

// ── 시나리오 3 — 다른 학생 몫만 큐에 있음 → 이 학생은 quiescent, reconcile 진행 ──
currentScenario = 3
console.log('\n시나리오 3 — 다른 학생(stu-other) 몫 큐만 있음 → 이 학생은 quiescent, reconcile 진행, 다른 학생 큐는 안 건드림')
{
  const ID = '44440000-0000-0000-0000-000000000004'
  const seed = { studentId: ID, totalStars: 77, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_OtherPending', seed, () => {
    stub.__seedPendingQueue('some-other-student-id', 'pronunciation', 'pronunciation', 'w-other-1')
    stub.__setSendOutcome('w-other-1', 'fail') // 다른 학생 몫은 실패든 성공이든 이 학생과 무관해야 함
  })
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 77, earnedAfter: 0 })
  await driveNaturalSync(host, clock)

  check('reconcile 정확히 1회 호출됨(다른 학생 큐는 무관)', stub.__reconcileCalls.length === 1)
  check('snapshotTotal === 77', stub.__reconcileCalls[0] && stub.__reconcileCalls[0].snapshotTotal === 77)
  check('마커 기록됨', markerFor(ID) && markerFor(ID).reason === 'reconciled')
  check('다른 학생(some-other-student-id) 몫은 drain 대상이 아니라 그대로 남음', stub.rewardQueuePendingFor('some-other-student-id') === 1)
}

// ── 시나리오 4 — 보류 중 레거시 지급 발생 → 로컬은 즉시 반영, 전송은 release 후 1회만 ──
currentScenario = 4
console.log('\n시나리오 4 — reconcile 응답 대기 중 grant 발생 → 순서 hold→drain→sync→reconcile(snapshot에 N 미포함)→release→POST(N), 로컬은 즉시 +1')
{
  const ID = '44440000-0000-0000-0000-000000000005'
  const seed = { studentId: ID, totalStars: 300, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_GrantDuringHold', seed)
  const deferred = stub.__setReconcileDeferred() // reconcile 응답을 미해결로 붙잡아둠(mountSeeded 이후 — freshEnv 리셋 다음에)
  // reconcile 호출이 실제로 나갈 때까지(hold→drain→자연sync→reconcile 스텝 진행) fake clock을 전진시킨다.
  await driveNaturalSync(host, clock)

  check('reconcile가 이미 호출됨(응답 대기 중)', stub.__reconcileCalls.length === 1)
  check('아직 hold 상태(release 전)', stub.__isHeldForTest() === true)

  const before = host.result.stars
  host.result.markPronunciationOk('word-during-hold')
  check('로컬 totalStars 즉시 +1(보류와 무관하게 지급 자체는 지연되지 않음)', host.result.stars === before + 1)
  check('보류 중이라 아직 전송된 postRewardEvent 없음', stub.__sentRewardCalls.length === 0)

  deferred.resolve({ ok: true, reason: 'reconciled', baselineStars: 300, earnedAfter: 0 })
  await settleAsync(host)

  check('release 후 postRewardEvent가 정확히 1회 전송됨', stub.__sentRewardCalls.length === 1)
  check('전송된 항목이 방금 그 grant(pronunciation/word-during-hold)', stub.__sentRewardCalls[0] && stub.__sentRewardCalls[0].sourceType === 'pronunciation' && stub.__sentRewardCalls[0].sourceId.startsWith('word-during-hold:'))
  check('reconcile에 보낸 snapshotTotal은 grant 이전 값(300, +1 미포함)', stub.__reconcileCalls[0].snapshotTotal === 300)
  check('마커 기록됨(reconciled)', markerFor(ID) && markerFor(ID).reason === 'reconciled')

  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false', 'post:')
  const idxHold1 = order.indexOf('hold:true')
  const idxDrain = order.indexOf('drain')
  const idxSync = order.indexOf('sync')
  const idxReconcile = order.indexOf('reconcile')
  const idxHold2 = order.indexOf('hold:false')
  const idxPost = order.findIndex((e) => e.startsWith('post:'))
  check('순서: hold(true) < drain < sync < reconcile < hold(false) < post(N)',
    idxHold1 !== -1 && idxDrain !== -1 && idxSync !== -1 && idxReconcile !== -1 && idxHold2 !== -1 && idxPost !== -1 &&
    idxHold1 < idxDrain && idxDrain < idxSync && idxSync < idxReconcile && idxReconcile < idxHold2 && idxHold2 < idxPost)
}

// ── 시나리오 5 — 마커 있는 상태로 재마운트 → reconcile 재호출 없음 ──────
currentScenario = 5
console.log('\n시나리오 5 — 마커 존재 상태에서 재마운트(재로그인/새로고침) → reconcile 추가 호출 없음')
{
  const ID = '44440000-0000-0000-0000-000000000006'
  const seed = { studentId: ID, totalStars: 120, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_Remount', seed)
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 120, earnedAfter: 0 })
  await driveNaturalSync(host, clock)
  check('1차 마운트 — reconcile 1회', stub.__reconcileCalls.length === 1)
  check('마커 기록됨', markerFor(ID) !== null)

  const before = stub.__reconcileCalls.length
  const { host: host2 } = remount(ID, 'QA_Cutover_Remount')
  await settleAsync(host2)
  check('재마운트 후 reconcile 추가 호출 없음(마커가 이미 있음)', stub.__reconcileCalls.length === before)
}

// ── 시나리오 6 — 재시도 가능 사유(no marker) vs 확정 사유(review, marker) ──
currentScenario = 6
console.log("\n시나리오 6 — table_missing/network_failed → 마커 없음(재마운트 시 재시도), 'review' → 마커 기록(더 이상 재시도 안 함)")
{
  // 6-a) table_missing — 마커 없음, 재마운트 시 재호출.
  {
    const ID = '44440000-0000-0000-0000-000000000007'
    const seed = { studentId: ID, totalStars: 10, round: freshRoundSeed(), history: {} }
    const { host, clock } = mountSeeded(ID, 'QA_Cutover_TableMissing', seed)
    stub.__queueReconcileResponse({ ok: false, reason: 'table_missing' })
    await driveNaturalSync(host, clock)
    check('table_missing — 마커 없음', markerFor(ID) === null)

    stub.__queueReconcileResponse({ ok: false, reason: 'network_failed' })
    const before = stub.__reconcileCalls.length
    const { host: host2, clock: clock2 } = remount(ID, 'QA_Cutover_TableMissing')
    await driveNaturalSync(host2, clock2)
    check('마커 없음 상태 — 재마운트 시 reconcile 재호출됨', stub.__reconcileCalls.length === before + 1)
    check('network_failed도 마커 없음(재시도 대상 유지)', markerFor(ID) === null)
  }

  // 6-b) review — 확정 사유, 마커 기록, 이후 재마운트해도 더 이상 호출 안 함.
  {
    const ID = '44440000-0000-0000-0000-000000000008'
    const seed = { studentId: ID, totalStars: 999, round: freshRoundSeed(), history: {} }
    const { host, clock } = mountSeeded(ID, 'QA_Cutover_Review', seed)
    stub.__queueReconcileResponse({ ok: false, reason: 'review' })
    await driveNaturalSync(host, clock)
    check("'review' — 마커 기록됨(reason:'review')", markerFor(ID) && markerFor(ID).reason === 'review')

    const before = stub.__reconcileCalls.length
    const { host: host2 } = remount(ID, 'QA_Cutover_Review')
    await settleAsync(host2)
    check("'review' 마커 있음 — 재마운트해도 추가 호출 없음", stub.__reconcileCalls.length === before)
  }
}

// ── 시나리오 7 — 토큰 없음(relogin_required) → 마커 없음, 재시도 대상 ────
currentScenario = 7
console.log('\n시나리오 7 — relogin_required(토큰 없음) → 마커 없음, 재마운트 시 재시도')
{
  const ID = '44440000-0000-0000-0000-000000000009'
  const seed = { studentId: ID, totalStars: 5, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_Relogin', seed)
  stub.__queueReconcileResponse({ ok: false, reason: 'relogin_required' })
  await driveNaturalSync(host, clock)
  check('relogin_required — 마커 없음', markerFor(ID) === null)

  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 5, earnedAfter: 0 })
  const before = stub.__reconcileCalls.length
  const { host: host2, clock: clock2 } = remount(ID, 'QA_Cutover_Relogin')
  await driveNaturalSync(host2, clock2)
  check('재마운트(재로그인 이후) — reconcile 재호출됨', stub.__reconcileCalls.length === before + 1)
  check('이번엔 성공 응답 — 마커 기록됨', markerFor(ID) && markerFor(ID).reason === 'reconciled')
}

// ── 시나리오 8 — 회귀: grantReward dedup / V1 앵커 포스팅은 그대로 ───────
currentScenario = 8
console.log('\n시나리오 8 — 회귀 확인: 레거시 dedup(재진입 시 추가 전송 없음) + V1 앵커(grantLedgerReward) 포스팅 정상 동작')
{
  const ID = '44440000-0000-0000-0000-000000000010'
  // 큐/마커 모두 비어있는 신선한 학생 — reconcile이 먼저(정상적으로) 끝나
  // 마커가 기록된 뒤에 아래 지급 동작을 관찰(그래야 __sentRewardCalls가
  // reconcile 관련 hold/release가 아니라 순수 지급 동작만 반영).
  const seed = { studentId: ID, totalStars: 0, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_Regression', seed)
  stub.__queueReconcileResponse({ ok: true, reason: 'nothing_to_reconcile', baselineStars: 0, earnedAfter: 0 })
  await driveNaturalSync(host, clock)
  check('사전조건 — reconcile 완료(마커 기록)', markerFor(ID) !== null)

  const postBefore = stub.__sentRewardCalls.length
  const before = host.result.stars
  host.result.markPronunciationOk('reg-word-1')
  await flush(); await flush(); await flushMacro()
  check('레거시 pronunciation — totalStars +1', host.result.stars === before + 1)
  check('레거시 pronunciation — postRewardEvent 정확히 1회 전송', stub.__sentRewardCalls.length === postBefore + 1)

  // 재진입(dedup) — 추가 지급/전송 없음.
  host.result.markPronunciationOk('reg-word-1')
  await flush(); await flush(); await flushMacro()
  check('재진입(같은 wordId) — totalStars 변화 없음(dedup)', host.result.stars === before + 1)
  check('재진입 — 추가 전송 없음(dedup)', stub.__sentRewardCalls.length === postBefore + 1)

  // V1 앵커(grantLedgerReward 경로) — recordExamCompleted.
  const postBefore2 = stub.__sentRewardCalls.length
  const before2 = host.result.stars
  host.result.recordExamCompleted('reg-exam-1')
  await flush(); await flush(); await flushMacro()
  check('V1 앵커(exam-complete) — postRewardEvent 정확히 1회 전송', stub.__sentRewardCalls.length === postBefore2 + 1)
  check('V1 앵커 — totalStars 증가(REWARD_STARS[exam-complete] 그대로)', host.result.stars > before2)

  // 재진입(V1 dedup, hasRewardEntry) — 추가 전송 없음.
  host.result.recordExamCompleted('reg-exam-1')
  await flush(); await flush(); await flushMacro()
  check('V1 앵커 재진입 — 추가 전송 없음(hasRewardEntry dedup)', stub.__sentRewardCalls.length === postBefore2 + 1)
}

// ── 시나리오 9 — 자연 sync가 폴링 예산(15초) 안에 성공하지 못함 → reconcile 미호출, 마커 없음, hold 해제 ──
currentScenario = 9
console.log('\n시나리오 9 — 자연 sync가 계속 실패(오프라인 등)해 폴링 예산 안에 성공 신호가 안 옴 → reconcile 미호출, 마커 없음, hold 해제(다음 마운트에서 재시도)')
{
  const ID = '44440000-0000-0000-0000-000000000011'
  const seed = { studentId: ID, totalStars: 88, round: freshRoundSeed(), history: {} }
  const { host, clock } = mountSeeded(ID, 'QA_Cutover_SyncNeverSucceeds', seed, () => {
    stub.__setSyncShouldFail(true) // syncStudentProgress가 매번 throw — markSyncSuccess/syncSuccessSeqRef 증가가 전혀 일어나지 않음
  })
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 88, earnedAfter: 0 }) // 소비되면 안 됨(reconcile 자체가 호출되지 않아야 함)
  await exhaustPollBudget(host, clock)

  check('reconcile 호출 안 됨(자연 sync가 폴링 예산 안에 성공하지 못함)', stub.__reconcileCalls.length === 0)
  check('마커 없음(다음 마운트에서 재시도 대상)', markerFor(ID) === null)
  check('hold는 해제된 상태로 마무리됨(released)', stub.__isHeldForTest() === false)
  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false')
  check('순서: hold(true) → drain(1회, 큐가 비어있어 즉시 remaining=0) → sync 시도(들, 실패) → hold(false), reconcile 없음',
    order[0] === 'hold:true' && order.includes('drain') && !order.includes('reconcile') && order[order.length - 1] === 'hold:false')
  check('디바운스 sync 시도는 최소 1회 있었음(실패로 markSyncFailure만 탐, syncSuccessSeqRef는 증가 안 함)', order.filter((e) => e === 'sync').length >= 1)
}

// ── 시나리오 10 — 다기기 병합 특성화(characterization, 결함 단언 아님) ──
currentScenario = 10
console.log('\n시나리오 10 — 다기기 병합 특성화: 로컬 300 + 클라우드 340(다른 기기에서 +40) → 병합 후 스냅샷은 340(병합값) 그대로 신고됨')
{
  const ID = '44440000-0000-0000-0000-000000000012'
  const localSeed = { studentId: ID, totalStars: 300, round: freshRoundSeed(), history: {} }
  freshEnv()
  globalThis.localStorage.setItem('paul_easy_progress', JSON.stringify({ [ID]: localSeed }))
  const clock = createFakeClock()
  const host = renderHook(() => useStudent(ID, 'QA_Cutover_MultiDeviceMerge'), clock)
  // 클라우드 백업 — 다른 기기에서 이미 40별을 더 벌어(340) 서버에 백업된
  // 상태를 재현(local=300 < cloud=340, "다른 기기에서 40별 획득" 시나리오).
  const cloudBackup = {
    studentId: ID, totalStars: 340, stickers: [], diaryPlacements: [], missions: [], cleared: [],
    round: freshRoundSeed(), history: {}, milestoneStreak: 0, starBadgeThreshold: 0,
    lastGamePlayed: null, lastWordIndex: 0, wordStatus: {},
  }
  stub.fetchFullProgressDeferred.resolve(cloudBackup) // 로컬이 비어있지 않으므로 병합 복원 경로(fire-and-forget)로 들어감
  stub.__queueReconcileResponse({ ok: true, reason: 'reconciled', baselineStars: 340, earnedAfter: 0 })
  await driveNaturalSync(host, clock)

  check('병합 후 로컬 totalStars === 340(다른 기기 진행분 반영, max(300,340))', host.result.stars === 340)
  check('reconcile 정확히 1회 호출됨', stub.__reconcileCalls.length === 1)
  check('reconcile에 보낸 snapshotTotal === 340(병합값 그대로 — 다른 기기 몫도 포함)', stub.__reconcileCalls[0] && stub.__reconcileCalls[0].snapshotTotal === 340)
  const order = orderOf('hold:true', 'drain', 'sync', 'reconcile', 'hold:false')
  check('호출 순서: hold(true) → drain → sync → reconcile → hold(false)(다기기 병합과 무관하게 동일)', JSON.stringify(order) === JSON.stringify(['hold:true', 'drain', 'sync', 'reconcile', 'hold:false']))
  check('마커 기록됨', markerFor(ID) && markerFor(ID).reason === 'reconciled')

  // 특성화(문서화된 잔여, 결함 단언 아님) — student_progress.total_stars
  // 병합값(max(local, cloud))은 "그 별들이 서버 원장에 이미 ack됐는지,
  // 아니면 다른 기기의 로컬 포스트 큐에 여전히 미전송 상태로 남아있는지"
  // 를 구분할 수 있는 정보를 전혀 담지 않는다 — 그냥 두 기기 로컬
  // 카운터의 max일 뿐이다. 이 스냅샷(340)을 신고한 뒤에 그 다른 기기가
  // 뒤늦게(네트워크 재시도/재로그인 등으로) 그 40별 중 일부를 서버에
  // POST하면, 서버는 "그 이벤트가 이 reconcile 스냅샷보다 먼저 일어난
  // 것"이라고 신뢰할 근거가 없다(클라이언트가 보고하는 이벤트 발생
  // 시각은 클록 드리프트/재시도 지연/오프라인 큐잉 때문에 서버가 그대로
  // 믿을 수 없음) — 그 결과 이미 baseline(340)에 포함된 별 중 일부가
  // reward_ledger에 다시 반영되며 이중 계산될 수 있다. 이 레이스는 "같은
  // 기기, 단일 reconcile 시도" 범위 밖(다기기 동시 사용)이라 이번
  // 클라이언트 레이스 방지 프로토콜의 불변식 증명(위 useStudent.js
  // 헤더 주석 (1)~(4))이 커버하는 영역이 아니며, 서버가 이벤트 발생
  // 시각을 신뢰할 방법이 없는 한 구조적으로 제거할 수 없다 — 아래 단언은
  // "이걸 고쳤다"가 아니라 "이 한계가 실제로 존재함을 실행 가능한
  // 테스트로 특성화(기록)해둔다"는 뜻이다(항상 PASS, 결함 단언 아님).
  check('특성화(문서화된 잔여): 다른 기기의 미전송 POST가 있으면 이 40별 중 일부가 이후 이중 계산될 수 있음 — 서버가 이벤트 시각을 신뢰할 수 없어 구조적으로 제거 불가, handoff 115차 잔여 참고', true)
}

// ── 결과 요약 ────────────────────────────────────────────────────────
console.log('\n─── 결과 요약 ───')
for (const n of Object.keys(scenarioFailures)) console.log(`시나리오 ${n} 실패 수: ${scenarioFailures[n]}`)
console.log(`총 단언 ${asserted}개 중 실패 ${failures}개`)
console.log(`(참고) 의도된 unhandledRejection 흡수 횟수: ${expectedUnhandledRejections}`)
console.log(failures === 0
  ? '\n모든 단언 통과 — 컷오버 레거시 별 기준선 재조정 클라이언트 레이스 방지 확인 ✅'
  : `\n${failures}개 단언 실패 ❌`)
process.exit(failures > 0 ? 1 : 0)
